src/main/default/objects/Contact/fields/Available_for_Field_Work__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Field_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to indicate that the person is available to work in the field. This typically means that they can be assigned to a job or ticket.</description>
    <inlineHelpText>If selected, the user is selectable when adding a job or ticket in FieldFX Mobile. You must select this option if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Available for Field Work</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/AutoAddJobCreatorToCrew__c.field-meta.xml
<CustomField>
    <fullName>AutoAddJobCreatorToCrew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</description>
    <inlineHelpText>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</inlineHelpText>
    <label>AutoAddJobCreatorToCrew</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the job was added in FieldFX Mobile. This checkbox is selected automatically for all jobs added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for the job.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status_History__c/Status_History__c.object-meta.xml
<CustomObject>
    <label>Status History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who made the status change</inlineHelpText>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Changed_Date__c</fullName>
    <inlineHelpText>Date and time the status change was made.</inlineHelpText>
    <label>Changed Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job that had its status changed.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/New_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>New status of the job/ticket.</inlineHelpText>
    <label>New Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>StatusHistory_NewStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/JobBuilder.cls
public class JobBuilder
{
    public static void OnBeforeInsert(List<Job__c> jobs)
    {
        Initialize(jobs);
    }

    public static void OnAfterInsert(List<Job__c> jobs)
    {
        List<Job__c> syncJobs = new List<Job__c>();
        
        List<Status_History__c> shs = new List<Status_History__c>();

        Set<Id> userIds = new Set<Id>();

        for(Job__c j : jobs) 
        {
            if(j.Sync__c == true) syncJobs.add(j);  
            userIds.add(j.CreatedById);          
           
            if(j.Created_in_Mobile__c == false && j.Status__c != null)
            {          
                shs.add(new Status_History__c(Job__c = j.Id, New_Status__c = j.Status__c, Changed_Date__c = Datetime.now(), Changed_By__c = UserInfo.getUserId()));
            }             
        }
        insert shs;

        if(FX_Settings__c.getOrgDefaults().AutoAddJobCreatorToCrew__c == true)
        {
            List<Contact> contacts = [SELECT Id, User__c FROM Contact WHERE Available_for_Field_Work__c = true AND User__c IN :userIds];
            Map<Id, Id> userToContact = new Map<Id, Id>();
            for(Contact c : contacts)
            {
                userToContact.put(c.User__c, c.Id);
                
            }
            List<Crew_Planning__c> crews = new List<Crew_Planning__c>();
            for(Job__c j : jobs) 
            {
                if(!userToContact.containsKey(j.CreatedById)) continue;
                
                crews.add(new Crew_Planning__c(Job__c = j.Id, Crew_Member__c = userToContact.get(j.CreatedById)));
            }       
            insert crews;
        }

        if(!syncJobs.isEmpty()) SyncAssignmentManager.UpdateSyncAssignments(syncJobs);

    }

    public static void OnBeforeUpdate(List<Job__c> jobs, Map<Id, Job__c> oldMap)
    {
        List<Job__c> items = new List<Job__c>();
        for(Job__c j : jobs) 
        {
            if(oldMap.get(j.Id).Status__c != j.Status__c) items.add(j);         
        }
        if(!items.isEmpty()) SyncAssignmentManager.UpdateJobSyncFlag(items);
    }

    public static void OnAfterUpdate(List<Job__c> jobs, Map<Id, Job__c> oldMap)
    {
        List<Job__c> items = new List<Job__c>();
        for(Job__c j : jobs) 
        {
            Job__c jOld = oldMap.get(j.Id);
            if(jOld.Sync__c != j.Sync__c || jOld.Segment__c != j.Segment__c || jOld.CustomerAccount__c != j.CustomerAccount__c || jOld.Office__c != j.Office__c) 
            {
                items.add(j);     
            }
        }
        if(!items.isEmpty()) SyncAssignmentManager.UpdateSyncAssignments(items);

        RuleEngineConsole.OnJobUpdate(jobs, oldMap); //RuleEngineService.ApplyRuleActionsAsync(jobs, oldMap);


    }  

    public static void Initialize(List<Job__c> jobs)
    {
        Id initialConsoleStatus = null;
        Id initialMobileStatus = null;

        List<Status__c> statuses = [SELECT Id, Sync__c, SObject_Record_Type__c, Initial_Status_Console__c, Initial_Status_Mobile__c, RecordType.DeveloperName 
                                    FROM Status__c 
                                    WHERE SObject__c='Job__c'
                                    AND (Initial_Status_Console__c=true OR Initial_Status_Mobile__c=true)];

        Map<string, Status__c> defaultStatus = new Map<string, Status__c>();
        for (Status__c status: statuses)
        {
            if(status.Initial_Status_Console__c)
            {
                defaultStatus.put(string.valueOf(status.SObject_Record_Type__c)  + 'console', status);  
            }
            if(status.Initial_Status_Mobile__c)
            {
                defaultStatus.put(string.valueOf(status.SObject_Record_Type__c)  + 'mobile', status);  
            }

        }
        Map<Id, Status__c> mapStatuses = new Map<Id, Status__c>(statuses);

        Set<Id> recordTypeIDs = new Set<Id>();
        for(Job__c j: jobs)
        {
            recordTypeIDs.add(j.RecordTypeId);
        }
        Map<Id, RecordType> recordTypes = new Map<Id, RecordType>([SELECT Id, Developername FROM RecordType where IsActive=true AND  Id IN :recordTypeIDs]);

        for(Job__c j : jobs)
        {
            if(!StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, j.Tracking_Number__c))
            {        
                j.Tracking_Number__c = StringUtility.getTrackingNumber('J-');
            }

            if(j.SyncID__c == null)
            {
                j.SyncID__c = StringUtility.newGuid();
            }

            string key = null;
            if(j.Status__c == null && !string.isBlank(j.RecordTypeId) && recordTypes.containsKey(j.RecordTypeId))
            {                
                key = string.valueOf(recordTypes.get(j.RecordTypeId).DeveloperName) + (j.Created_in_Mobile__c ?  'mobile' : 'console');

                if(defaultStatus.containsKey(key))
                {
                    j.Status__c = defaultStatus.get(key).Id;                           
                }
            }

            if(j.Status__c == null)
            {                
                key = null + (j.Created_in_Mobile__c ?  'mobile' : 'console');

                if(defaultStatus.containsKey(key))
                {
                    j.Status__c = defaultStatus.get(key).Id;                           
                }
            }

            if(j.Status__c !=null && mapStatuses.containsKey(j.Status__c))
            {
                j.Sync__c = mapStatuses.get(j.Status__c).Sync__c;
            }
        } 
    }
}