src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/Sync_Configuration__c.object-meta.xml
<CustomObject>
    <description>This controls which data the mobile client users will receive when they sync.  Users will only get information related to the offices listed here.</description>
    <label>Sync Configuration</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by customer. If a customer is specified, the user only sees jobs with price books linked to that customer. If a customer is not specified, the user sees jobs for all accessible accounts.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations (Account)</relationshipLabel>
    <relationshipName>Sync_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>Contact record for the user granted access to jobs in FieldFX Mobile through the sync configuration.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job type. If a job type is specified, the user only sees jobs for that job type. If a job type is not specified, the user sees jobs for all job types.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Time &amp; Material</fullName>
            </value>
            <value>
                <fullName>Fixed Bid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by office. If an office is specified, the user only sees jobs for that office. If an office is not specified, the user sees jobs for all offices.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by business segment. If a segment is specified, the user only sees jobs for that segment. If a segment is not specified, the user sees jobs for all segments.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Sync_JobCrewOnly__c.field-meta.xml
<CustomField>
    <fullName>Sync_JobCrewOnly__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag Job for download only for Job Crew</description>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job crew assignment. If selected, the user only sees jobs if they are in the job crew. If not selected, the user sees any job matching the other criteria specified in the sync configuration.</inlineHelpText>
    <label>Sync - Job Crew Only</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/UniqueExternalId__c.field-meta.xml
<CustomField>
    <fullName>UniqueExternalId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the sync configuration.</inlineHelpText>
    <label>UniqueExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>Unique identifier for the sync configuration.</inlineHelpText>
    <label>UniqueId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/SyncConfigBatchable_UpdateExternalIds.cls
public  class SyncConfigBatchable_UpdateExternalIds extends FXBatchableBase implements Database.Stateful
{
	
	Set<String> uniqueExternalIds = new Set<String>();

	public  SyncConfigBatchable_UpdateExternalIds()
	{
		soqlQuery = String.format('SELECT Id, {0}Contact__c, {0}Office__c, {0}Account__c, {0}Segment__c, {0}Sync_JobCrewOnly__c, {0}UniqueId__c, {0}UniqueExternalId__c, {0}Job_Type__c FROM {0}Sync_Configuration__c WHERE IsDeleted=false AND {0}Contact__r.{0}User__c!=null AND {0}Contact__r.{0}User__r.IsActive=true',
			new String[]{StringUtility.FXNamespace()});
	}
	 
	public override void execute(Database.BatchableContext BC, List<SObject> scope)
	{
		List<Sync_Configuration__c> itemsToUpdate = new List<Sync_Configuration__c>();
        List<Sync_Configuration__c> itemsToDelete = new List<Sync_Configuration__c>();        
      
	    for(SObject item : scope)
	    {        
	    	Sync_Configuration__c sc = (Sync_Configuration__c)item;
	        String str = SyncConfigBuilderController.GetUniqueId(sc);
	        if(uniqueExternalIds.contains(str))
	        {
	            itemsToDelete.add(sc);
	        }
	        else
	        {
	            sc.UniqueExternalId__c = str;
	            sc.UniqueId__c = str;
	            itemsToUpdate.add(sc);
	            uniqueExternalIds.add(str);
	        }
	    }
	    if(!itemsToDelete.isEmpty())
	    {
	        Database.delete(itemsToDelete, false);
	    }
	    if(!itemsToUpdate.isEmpty())
	    {
	        Database.update(itemsToUpdate, false);
	    }      		
	} 
}