src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for the job.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>UTM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Quote__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Office)</relationshipLabel>
    <relationshipName>QuotesForOffice</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/Sync_Configuration__c.object-meta.xml
<CustomObject>
    <description>This controls which data the mobile client users will receive when they sync.  Users will only get information related to the offices listed here.</description>
    <label>Sync Configuration</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by customer. If a customer is specified, the user only sees jobs with price books linked to that customer. If a customer is not specified, the user sees jobs for all accessible accounts.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations (Account)</relationshipLabel>
    <relationshipName>Sync_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>Contact record for the user granted access to jobs in FieldFX Mobile through the sync configuration.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job type. If a job type is specified, the user only sees jobs for that job type. If a job type is not specified, the user sees jobs for all job types.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Time &amp; Material</fullName>
            </value>
            <value>
                <fullName>Fixed Bid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by office. If an office is specified, the user only sees jobs for that office. If an office is not specified, the user sees jobs for all offices.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by business segment. If a segment is specified, the user only sees jobs for that segment. If a segment is not specified, the user sees jobs for all segments.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Sync_JobCrewOnly__c.field-meta.xml
<CustomField>
    <fullName>Sync_JobCrewOnly__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag Job for download only for Job Crew</description>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job crew assignment. If selected, the user only sees jobs if they are in the job crew. If not selected, the user sees any job matching the other criteria specified in the sync configuration.</inlineHelpText>
    <label>Sync - Job Crew Only</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/SyncAssignmentBatchable.cls
public class SyncAssignmentBatchable extends FXBatchableBase 
{    
    Map<string, Id> JobTypePickListToRecordType { get; set;}
    Set<Id> Users { get; set;}
    Set<Id> JobIds { get; set;}

    Set<Id> JobAccounts { get; set;}
    Set<Id> JobRecordTypes { get; set;}
    Set<Id> JobOffices { get; set;}
    Set<string> JobSegments {get; set;}

    Boolean SyncJobCrewOnly;   
    List<Sync_Configuration__c> SyncConfigs;

    public SyncAssignmentBatchable()
    {
        List<Sync_Configuration__c> configs = [SELECT Id, Contact__c, Account__c, Office__c, Segment__c, Job_Type__c, Sync_JobCrewOnly__c, Contact__r.User__c FROM Sync_Configuration__c WHERE IsDeleted=false AND Contact__r.User__c!=null AND Contact__r.User__r.IsActive=true];
        Init(configs, SyncAssignmentManager.GetJobTypePickListToRecordType(), false);
    }

    public SyncAssignmentBatchable (List<Sync_Configuration__c> configs,  Map<string, Id> jobTypePickListToRecordType0, Boolean syncJobCrewOnly0)
    {
        Init(configs, jobTypePickListToRecordType0, syncJobCrewOnly0);
    }

    void Init(List<Sync_Configuration__c> configs,  Map<string, Id> jobTypePickListToRecordType0, Boolean syncJobCrewOnly0) 
    {
        SyncConfigs = configs;
        JobTypePickListToRecordType=jobTypePickListToRecordType0;
        SyncJobCrewOnly = syncJobCrewOnly0;

        Users = new Set<id>();
        JobAccounts = new Set<id>();
        JobRecordTypes = new Set<id>();
        JobOffices = new Set<id>();
        JobSegments = new Set<string>();

        for(Sync_Configuration__c sc : configs)
        {           
            Users.add(sc.Contact__c);
            if(!syncJobCrewOnly0)
            {
                if(sc.Account__c!=null) JobAccounts.add(sc.Account__c);
                if(sc.Office__c!=null) JobOffices.add(sc.Office__c);
                if(sc.Segment__c!=null) JobSegments.add(sc.Segment__c);
                if(sc.Job_Type__c!=null && sc.Job_Type__c!='' && jobTypePickListToRecordType0.containsKey(sc.Job_Type__c)) 
                    JobRecordTypes.add(jobTypePickListToRecordType0.get(sc.Job_Type__c));
            }
        }
     
        if(SyncJobCrewOnly)
        {   
            String quoteStr = (QuoteExtension.HasQuoteV1 == true)? String.format(',{0}Job__r.{0}Quote__c', new String[]{StringUtility.FXNamespace()}) : '';

            soqlQuery = String.format('SELECT Id, {0}Crew_Member__c, {0}Job__r.{0}CustomerAccount__c, {0}Job__r.RecordTypeId, {0}Job__r.{0}Office__c, {0}Job__r.{0}Segment__c {1} FROM {0}Crew_Planning__c WHERE {0}Job__r.{0}Sync__c=true AND {0}Crew_Member__c in :Users',
                    new String[]{StringUtility.FXNamespace(), quoteStr});
        }
        else
        { 

            String soql = 'SELECT Id, {0}CustomerAccount__c, RecordTypeId, {0}Office__c, {0}Segment__c {1} FROM {0}Job__c WHERE {0}Sync__c=true ';
            String whereClause = '';
            String sep='';
            if(!JobAccounts.isEmpty())
            {
                whereClause += sep + '{0}CustomerAccount__c IN :JobAccounts ';
                sep = ' OR ';
            }

            if(!JobRecordTypes.isEmpty())
            {
                whereClause += sep + 'RecordTypeId IN :JobRecordTypes ';
                sep = ' OR ';
            }


            if(!JobOffices.isEmpty())
            {
                whereClause += sep + '{0}Office__c IN :JobOffices ';
                sep = ' OR ';
            }

            if(!JobSegments.isEmpty())
            {
               // whereClause += sep + '{0}Segment__c IN :JobSegments ';
               // sep = ' OR ';
            }
            if(whereClause!='') soql += ' AND (' + whereClause + ')';
            
            String quoteField = (QuoteExtension.HasQuoteV1 == true)? ',' + QuoteExtension.QuoteV1FieldName : '';

            soqlQuery = String.format(soql, new String[]{StringUtility.FXNamespace(), quoteField});
        }
        System.debug('soql query: ' + soqlQuery);
    }
    
    public override Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(soqlQuery);
    }

    public override void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        if(SyncJobCrewOnly)
        {
            SyncAssignmentManager.UpdateJobCrewSyncAssignments(scope, SyncConfigs);
        }
        else
        {
            SyncAssignmentManager.UpdateSyncAssignments(scope, SyncConfigs);
        }       
    }
 
    public override void finish(Database.BatchableContext BC)
    {       
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        
        AsyncApexJob a = [SELECT Id, Status, ApexClass.Name, JobType, CompletedDate, ExtendedStatus, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
              FROM AsyncApexJob WHERE Id = :BC.getJobId()];
        if(a.NumberOfErrors>0)   
        {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            String[] toAddresses = new String[] {a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
            mail.setSubject('force.com System Error - ' + a.Status);
            mail.setPlainTextBody('Please forward this to your tech support team. '
                +' AsyncApexJob Id:' + a.Id 
                + ', ApexClass.Name:' + a.ApexClass.Name 
                + ', Status:' + a.Status
                + ', ExtendedStatus:' + a.ExtendedStatus
                + ', NumberOfErrors:' + a.NumberOfErrors
                + ', JobItemsProcessed:' + a.JobItemsProcessed
                + ', TotalJobItems:' + a.TotalJobItems
                + ', CreatedBy.Email:' + a.CreatedBy.Email);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }
}