src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/AutoFollowJobTicket__c.field-meta.xml
<CustomField>
    <fullName>AutoFollowJobTicket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically follow the Job and its Tickets on Chatter if the user has an entry in Job subscription (SyncAssignment). When the user is removed from SyncAssignment, stop following Job/Ticket.</description>
    <label>Auto Follow Job and Ticket</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for the job.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Sync_Assignment__c/Sync_Assignment__c.object-meta.xml
<CustomObject>
    <description>User's syncable Jobs</description>
    <label>Sync Assignment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>User granted access through the sync assignment.</inlineHelpText>
    <label>User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Sync Assignments</relationshipLabel>
    <relationshipName>Sync_Assignment_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Assignment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job to which the user is granted access in FieldFX Mobile through the sync assignment.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>User Sync Assignments</relationshipLabel>
    <relationshipName>Sync_Assignment_Job</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/Sync_Configuration__c.object-meta.xml
<CustomObject>
    <description>This controls which data the mobile client users will receive when they sync.  Users will only get information related to the offices listed here.</description>
    <label>Sync Configuration</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by customer. If a customer is specified, the user only sees jobs with price books linked to that customer. If a customer is not specified, the user sees jobs for all accessible accounts.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations (Account)</relationshipLabel>
    <relationshipName>Sync_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>Contact record for the user granted access to jobs in FieldFX Mobile through the sync configuration.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job type. If a job type is specified, the user only sees jobs for that job type. If a job type is not specified, the user sees jobs for all job types.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Time &amp; Material</fullName>
            </value>
            <value>
                <fullName>Fixed Bid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by office. If an office is specified, the user only sees jobs for that office. If an office is not specified, the user sees jobs for all offices.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by business segment. If a segment is specified, the user only sees jobs for that segment. If a segment is not specified, the user sees jobs for all segments.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Sync_JobCrewOnly__c.field-meta.xml
<CustomField>
    <fullName>Sync_JobCrewOnly__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag Job for download only for Job Crew</description>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job crew assignment. If selected, the user only sees jobs if they are in the job crew. If not selected, the user sees any job matching the other criteria specified in the sync configuration.</inlineHelpText>
    <label>Sync - Job Crew Only</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Job__r.Office__r.Name</formula>
    <inlineHelpText>Office responsible for performing the work listed on the ticket.</inlineHelpText>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/ChatterFeedManager_Test.cls
@isTest
private class ChatterFeedManager_Test
{

   static void turnOnAutoFollowJobTicket()
   {
      if(!Schema.SObjectType.User.isFeedEnabled())
      {
          throw new AlpineTestHelper.TesterException('Chatter is NOT on in the org');
      }
      if(!Schema.SObjectType.Job__c.isFeedEnabled())
      {
           throw new AlpineTestHelper.TesterException('Job__c Chatter Feed Tracking  is OFF on in the org');
      }     
      if(!Schema.SObjectType.Ticket__c.isFeedEnabled())
      {
           throw new AlpineTestHelper.TesterException('Job__c Chatter Feed Tracking  is OFF on in the org');
      }

      if(!FX_Settings__c.getOrgDefaults().AutoFollowJobTicket__c)
      {
        FX_Settings__c fs = new FX_Settings__c();
        fs.SetupOwnerId = UserInfo.getOrganizationId();
        fs.AutoFollowJobTicket__c = true;
        insert fs;
      }
   }

   
   static testMethod void FollowNewJob_NoTicket() 
   { 
       System.debug('FollowNewJob_NoTicket');

        Test.StartTest();
        turnOnAutoFollowJobTicket();
        Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
        Id userId = cp.User__c;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;
       
        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
       
        Test.StopTest();


        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :job.Id ];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assert(items.size() == 1);

   }
  

   static testMethod void FollowNewJob_WithTicket() 
   { 
     System.debug('FollowNewJob_WithTicket');

        Test.StartTest();
        turnOnAutoFollowJobTicket();
        Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
        Id userId = cp.User__c;

        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        System.debug('JobID=' + job.Id);
       
        Integer tktCount = 20;
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job, tktCount, true);     
       

        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
       
        Test.StopTest();

        List<Ticket__c> tkts2 = [SELECT Id, Sync__c FROM Ticket__c where Job__c = :job.Id AND Sync__c=true];
        System.assertEquals(tktCount, tkts2.size());

        Set<Id> tktIds = new Map<Id, Ticket__c>(tkts).keySet();

        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND (parentid = :job.Id OR parentid IN :tktIds)];
        
        Integer totalCount =0;
        if(Schema.SObjectType.Job__c.isFeedEnabled())
        {
           totalCount += 1;
        }
        if(Schema.SObjectType.Ticket__c.isFeedEnabled())
        {
           totalCount += tktCount;
        }

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assertEquals(totalCount,  items.size());
   }

   
    static testMethod void FollowNewTicket_UponInsert() 
    {  
     System.debug('FollowNewTicket_UponInsert');
    
        turnOnAutoFollowJobTicket(); 
         Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
         Id userId = cp.User__c;

        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);       
        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
      
        Test.StartTest();
        

        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :job.Id];

      if(ChatterFeedManager.AutoFollowJob(userId))  System.assert(items.size() ==1);
        
        Integer tktCount = 20;
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job, tktCount, true);     
            

        Set<Id> tktIds = new Map<Id, Ticket__c>(tkts).keySet();

        Test.StopTest();

         items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid IN :tktIds];


        Integer totalCount =0;       
        if(Schema.SObjectType.Ticket__c.isFeedEnabled())
        {
           totalCount += tktCount;
        }


        if(ChatterFeedManager.AutoFollowJob(userId))  System.assertEquals(totalCount,  items.size());
      
   }

   static testMethod void UnfollowNewJob_NoTicket() 
   { 
     System.debug('UnfollowNewJob_NoTicket');

         turnOnAutoFollowJobTicket();
        Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
        Id userId = cp.User__c;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;
       
        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
       
        Test.StartTest();
       

        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :job.Id ];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assert(items.size() == 1);

        Job__c dbJob = [SELECT Status__c, Status__r.RecordTypeId FROM Job__c WHERE Id = :job.Id LIMIT 1];

        string statusName = 'NoSyncJobStatus ' + dbJob.Status__c;

        Status__c st = new Status__c(Name = statusName, SObject__c='Job__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=dbJob.Status__r.RecordTypeId);
        insert st;

        dbjob.Status__c = st.Id;
        update dbJob;

        Test.StopTest();


    items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :job.Id ];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assert(items.size() == 0);

   }


   static testMethod void UnfollowNewJob_WithTicket() 
   { 
         System.debug('UnfollowNewJob_WithTicket');

         turnOnAutoFollowJobTicket();
        Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
        Id userId = cp.User__c;

        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
        Integer tktCount = 20;
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job, tktCount, true);     
       

        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
       
      

        Set<Id> tktIds = new Map<Id, Ticket__c>(tkts).keySet();     

        Test.StartTest();
       

        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND (parentid = :job.Id OR parentid IN :tktIds)];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assertEquals(tktCount + 1,  items.size());

        Job__c dbJob = [SELECT Status__c, Status__r.RecordTypeId FROM Job__c WHERE Id = :job.Id LIMIT 1];

        string statusName = 'NoSyncJobStatus ' + dbJob.Status__c;

        Status__c st = new Status__c(Name = statusName, SObject__c='Job__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=dbJob.Status__r.RecordTypeId);
        insert st;

        dbjob.Status__c = st.Id;
        update dbJob;

        Test.StopTest();

        items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND (parentid = :job.Id OR parentid IN :tktIds)];

        if(ChatterFeedManager.AutoFollowJob(userId))  System.assert(items.size() == 0);       
   }

   static testMethod void UnfollowTicket_UponTicketSyncOff() 
   { 
        System.debug('UnfollowTicket_UponTicketSyncOff');

        turnOnAutoFollowJobTicket();
        Contact cp = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Jane', true);
        Id userId = cp.User__c;

        Sync_Configuration__c sc = new Sync_Configuration__c(Contact__c = cp.Id, Sync_JobCrewOnly__c=true, Job_Type__c=null, Account__c = null, Office__c = null, Segment__c= null);

        insert sc;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        insert new Crew_Planning__c(Crew_Member__c = cp.Id, Job__c = job.Id);
       
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0); 

        Test.StartTest();
        

        List<EntitySubscription> items = [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :tkt.Id];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assertEquals(1,  items.size());

        Ticket__c dbTkt = [SELECT Id, Sync__c, Status__c, Status__r.RecordTypeId FROM Ticket__c WHERE Id = :tkt.Id LIMIT 1];

        System.debug('tkt=' + dbTkt);

        System.assert(dbTkt.Sync__c);

        string statusName = 'NoSyncJobStatus ' + dbTkt.Status__c;

        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=dbTkt.Status__r.RecordTypeId);
        insert st;

        dbTkt.Status__c = st.Id;
        update dbTkt;

        dbTkt = [SELECT Id, Sync__c, Status__c, Status__r.RecordTypeId FROM Ticket__c WHERE Id = :tkt.Id LIMIT 1];

        System.debug('after update, tkt=' + dbTkt);

        Test.StopTest();

        List<Sync_Assignment__c> jobSubs = [SELECT Contact__c, Contact__r.User__c, Job__c from Sync_Assignment__c WHERE Job__c =:job.Id AND Contact__r.User__c=:userId];
        System.assertEquals(1, jobSubs.size());
       

        Ticket__c dbTkt2 = [SELECT Sync__c, Status__c FROM Ticket__c WHERE Id = :tkt.Id LIMIT 1];
        System.assertEquals(st.Id, dbTkt2.Status__c);
        System.assert(!dbTkt2.Sync__c);


        items =  [select Id, parentid, subscriberid from EntitySubscription 
               where subscriberid = :userId AND parentid = :tkt.Id];

        if(ChatterFeedManager.AutoFollowJob(userId)) System.assertEquals(0, items.size());       
   }


}