src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/UserTriggerKeepInactiveUserSyncConfigs__c.field-meta.xml
<CustomField>
    <fullName>UserTriggerKeepInactiveUserSyncConfigs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UserTriggerKeepInactiveUserSyncConfigs</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/UserTriggerSkipPackageLicenseCleanup__c.field-meta.xml
<CustomField>
    <fullName>UserTriggerSkipPackageLicenseCleanup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, skip package license clean up for inactive users. The packages include 'FX5', 'FXTKT', 'FXEAM', 'FXT2', 'FXJSD', 'FXMAP'.</description>
    <label>UserTriggerSkipPackageLicenseCleanup</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/Sync_Configuration__c.object-meta.xml
<CustomObject>
    <description>This controls which data the mobile client users will receive when they sync.  Users will only get information related to the offices listed here.</description>
    <label>Sync Configuration</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>Contact record for the user granted access to jobs in FieldFX Mobile through the sync configuration.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/UserTriggerHandler.cls
public class UserTriggerHandler extends FXTriggerHandler
{
    public override void OnAfterUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    {
        List<User> users = (List<User>)items;
        Map<Id, User> m  = (Map<Id, User>)oldMap;

        Set<Id> inactiveUserIds = new Set<Id>();
        for(User u : users)
        {
            User prev = m.get(u.Id);
            if(u.IsActive == false && prev.IsActive)
            {
                inactiveUserIds.add(u.Id);
            }
        }
        RemovePackageLicenseForInactiveUsers(inactiveUserIds);
        DeleteSyncConfigs(inactiveUserIds);
    }

    public override void OnBeforeDelete(List<sObject> items)
    {
        Set<Id> userIds = new Map<Id, sObject>(items).keySet();
        DeleteSyncConfigs(userIds);
    }
    
    static void RemovePackageLicenseForInactiveUsers(Set<Id> inactiveUserIds)
    {
        if(inactiveUserIds==null || inactiveUserIds.isEmpty() || FX_Settings__c.getInstance(UserInfo.getUserId()).UserTriggerSkipPackageLicenseCleanup__c)
        {
            return;
        }       
        delete [SELECT Id FROM UserPackageLicense where UserId IN :inactiveUserIds AND PackageLicense.NamespacePrefix in ('FX5', 'FXTKT', 'FXEAM', 'FXT2', 'FXJSD', 'FXMAP', 'FXCPQ')];        
    }

    static void DeleteSyncConfigs(Set<Id> inactiveUserIds)
    {
        if(inactiveUserIds==null || inactiveUserIds.isEmpty() || FX_Settings__c.getInstance(UserInfo.getUserId()).UserTriggerKeepInactiveUserSyncConfigs__c) return;        
        Database.delete([SELECT Id FROM Sync_Configuration__c WHERE Contact__r.User__c IN :inactiveUserIds], false);
    }
}