src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/SyncV4Config__c.field-meta.xml
<CustomField>
    <fullName>SyncV4Config__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Sync Config option for Sync V4</description>
    <label>Sync v4 Config</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Sync_Assignment__c/Sync_Assignment__c.object-meta.xml
<CustomObject>
    <description>User's syncable Jobs</description>
    <label>Sync Assignment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>User granted access through the sync assignment.</inlineHelpText>
    <label>User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Sync Assignments</relationshipLabel>
    <relationshipName>Sync_Assignment_Contact</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Assignment__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job to which the user is granted access in FieldFX Mobile through the sync assignment.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>User Sync Assignments</relationshipLabel>
    <relationshipName>Sync_Assignment_Job</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/SObjectChecksum.cls
@RestResource(urlMapping='/SObjectChecksum/*')
global with sharing class SObjectChecksum {
   @HttpGet
   global static String getChecksum(){
      String sobjectName = RestContext.request.params.get('sobjectName');
      String lastSyncStr = RestContext.request.params.get('lastSync');
      Datetime lastSync = Datetime.valueOfGMT(lastSyncStr.replace('T',' '));
      return GetSObjectChecksum(sobjectName, lastSync);
    }

    @testVisible
    static String GetSObjectChecksum(String sObjectType, Datetime lastSync)
    {
        String ns = StringUtility.FXNamespace();
        //String ns = 'FX5__';
        String uid = UserInfo.getUserId();

        FX_Settings__c settings = FX_Settings__c.getInstance(uid);
        Map<String, Schema.SObjectField> fields = Schema.getGlobalDescribe().get(sObjectType).getDescribe().fields.getMap();

        String extraPredicates = '';
        String sep = ' AND ';
        if(fields.containsKey(ns + 'sync__c'))
        {
           extraPredicates = sep + ns + 'Sync__c = true ';
        }
        else if(fields.containsKey('sync__c'))
        {
           extraPredicates = sep + 'Sync__c = true ';
        }

        if(fields.containsKey('altsync__c'))
        {
            extraPredicates += sep + ' AltSync__c=true ';
        }

        if(settings.SyncV4Config__c) {
            String jobField = null;
            if (fields.containsKey(ns + 'Job__c'))
            {
                jobField = ns + 'Job__c';
            }
            else if(fields.containsKey('Job_Share__c'))
            {
                jobField = 'Job_Share__c';
            }
            if (sobjectType == ns + 'Job__c' ){
                jobField = 'Id';
            }

            if(jobField != null) {
                extraPredicates += sep + jobField + ' IN (SELECT [ns]Job__c FROM [ns]Sync_Assignment__c WHERE IsDeleted=false AND [ns]Contact__r.[ns]User__c=\''+uid+'\')';
                extraPredicates = extraPredicates.replace('[ns]', ns);
            }
        }
        String soql = String.format('SELECT Id FROM {0} WHERE CreatedDate <=:lastSync {1} AND (IsDeleted = false OR (IsDeleted = true AND SystemModstamp >:lastSync)) ORDER By Id ALL ROWS',
         new String[]{sObjectType, extraPredicates});

        Set<Id> ids = new Map<Id, sObject>(Database.query(soql)).keySet();
        return GetChecksum(new List<Id>(ids));

    }

    @testVisible
    static String GetChecksum(List<Id> ids)
    {
        Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(String.join(ids, '')));
        return EncodingUtil.convertToHex(hash);
    }
}