src/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Invoice_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the ticket was added in FieldFX Mobile. This checkbox is selected automatically for all tickets added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Auto_Added__c.field-meta.xml
<CustomField>
    <fullName>Auto_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This property indicates that the item was automatically added to the ticket.</description>
    <inlineHelpText>If selected, the item was added to the ticket automatically. An item gets added to a ticket automatically if the linked price book item has a default quantity or the linked price book item has a parent price book item.</inlineHelpText>
    <label>Auto Added</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the ticket item. The ticket item inherits this discount from the linked price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Item</label>
    <referenceTo>Invoice_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/On_Standby__c.field-meta.xml
<CustomField>
    <fullName>On_Standby__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the ticket item is on standby for a job and not in use. When a ticket item is on standby, the price charged for the item is the standby price inherited from the linked price book item.</inlineHelpText>
    <label>On Standby</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/PBI_Locked_Description__c.field-meta.xml
<CustomField>
    <fullName>PBI_Locked_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, the user cannot change the description when the price book item is used on a ticket.</description>
    <inlineHelpText>If selected, users cannot change the catalog description for the ticket item.</inlineHelpText>
    <label>PBI Locked Description</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/PBI_Locked_Discount__c.field-meta.xml
<CustomField>
    <fullName>PBI_Locked_Discount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users cannot change the discount granted on the ticket item.</inlineHelpText>
    <label>PBI Locked Discount</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/PBI_Locked_Price_Markup__c.field-meta.xml
<CustomField>
    <fullName>PBI_Locked_Price_Markup__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users cannot change the price charged for the ticket item.</inlineHelpText>
    <label>PBI Locked Price/Markup</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/PBI_Required_Item__c.field-meta.xml
<CustomField>
    <fullName>PBI_Required_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is checked, this item will automatically be added to all new Tickets.</description>
    <inlineHelpText>If selected, the item gets added automatically to all new tickets.</inlineHelpText>
    <label>PBI Required Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Rule_Required_Item__c.field-meta.xml
<CustomField>
    <fullName>Rule_Required_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will indicate that the item is required by the rule engine.</description>
    <inlineHelpText>This field will indicate that the item is required by the rule engine.</inlineHelpText>
    <label>Rule Required Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/CopyTicketItems.cls
@RestResource(urlMapping='/CopyTicketItems/*')
global with sharing class CopyTicketItems
{
    @HttpPost
    global static List<Ticket_Item__c> CopyTicketItems(Id newTicketId, List<Id> ticketItemIds, Boolean honorSequenceNumber, Decimal nextSequenceNumber)
    {

        RuleEngineCore.RuleEngineInProgress = true;

        String ns = UtilityGetNamespace.CurrentNamespace();

        Schema.DescribeSObjectResult rTktItem = Ticket_Item__c.sObjectType.getDescribe();
        if(!rTktItem.isAccessible() || !rTktItem.isCreateable()) {
            RuleEngineCore.RuleEngineInProgress = false;
            return null;
        }

        List<SObjectField> tktItemFields = rTktItem.fields.getMap().values();

        Set<String> tktItemFieldNames = new Set<String>();
        for(Schema.SObjectField f: Schema.sObjectType.Ticket_Item__c.fields.getMap().values())
        {
            Schema.DescribeFieldResult fd = f.getDescribe();

            //if (!fd.isAccessible() || !fd.isCreateable() || fd.isCalculated() || fd.isAutoNumber() || fd.isExternalId()|| fd.isUnique())
            //{
            //    continue;
            //}

            if (fd.getName().endsWith('Sequence_Number__c') && honorSequenceNumber) continue;

            tktItemFieldNames.add(fd.getName());
        }
        String fieldsStr = String.join(new List<String>(tktItemFieldNames), ',');

        String fields = '';
        String sep = '';
        for(SObjectField fTktItem: tktItemFields)
        {
            DescribeFieldResult dfrTktItem = fTktItem.getDescribe();
            //if(!dfrQuoteItem.isCreateable() || dfrQuoteItem.isUnique()) continue;
            if (dfrTktItem.getName().endsWith('Sequence_Number__c') && honorSequenceNumber) continue;

            fields += sep + dfrTktItem.getName();
            sep = ',';
        }

        String soql = 'SELECT ';
        soql += fields;
        soql += ' , (SELECT ';
        soql += fields;
        soql += ' FROM '+ns+'Ticket_Items__r) ';
        soql += ' FROM '+rTktItem.getName();
        soql += ' WHERE Id IN :ticketItemIds ';

        List<Ticket_Item__c> sourceTktItems = Database.query(soql);
        if(sourceTktItems == null) {
            RuleEngineCore.RuleEngineInProgress = false;
            return null;
        }

        Map<String, Ticket_Item__c> sourceTktItemsSyncIdLookup = new Map<String, Ticket_Item__c>();
        for(Ticket_Item__c ti : sourceTktItems)
        {
            sourceTktItemsSyncIdLookup.put(ti.SyncID__c, ti);
        }


        Map<Id, Ticket_Item__c> sourceTiLookup = new Map<Id, Ticket_Item__c>(sourceTktItems);

        List<Id> parentTktItemIds = new List<Id>();
        Map<String, Ticket_Item__c> parentTktItemIdsSyncIdLookup = new Map<String, Ticket_Item__c>();
        Map<String, Ticket_Item__c> childTktItemIdsSyncIdLookup = new Map<String, Ticket_Item__c>();

        List<Id> childTktItemIds = new List<Id>();
        for(Ticket_Item__c tktItem: sourceTktItems) {
            if (tktItem.Parent_Ticket_Item__c != null) {
                childTktItemIds.add(tktItem.Id);
                childTktItemIdsSyncIdLookup.put(tktItem.SyncID__c, tktItem);
            } else {
                parentTktItemIds.add(tktItem.Id);
                parentTktItemIdsSyncIdLookup.put(tktItem.SyncID__c, tktItem);
            }
        }

        List<Ticket_Item__c> newticketItems = new List<Ticket_Item__c>();
        List<Ticket_Item__c> parentTktItems = CreateTicketItemsUsingPriceBookItems(newTicketId, parentTktItemIds, sourceTiLookup, '');
        insert parentTktItems;

        Map<Integer, Id> newTiLookup = new Map<Integer, Id>();
        //need to preserve order so we can lookup matching quoteItem and ticketItem
        for(Integer i=0; i<parentTktItems.size(); i++)
        {
            newTiLookup.put(i, parentTktItems.get(i).Id);
        }

        List<Ticket_Item__c> dbItems = refreshTktItemsList(parentTktItems, fieldsStr);
        Map<Id, Ticket_Item__c> dbItemLookup = new Map<Id, Ticket_Item__c>(dbItems);

        parentTktItems = UpdateTicketItemsUsingTicketItems(dbItems, parentTktItemIds, sourceTiLookup,
                        honorSequenceNumber, nextSequenceNumber, tktItemFieldNames, tktItemFields,
                        parentTktItemIdsSyncIdLookup);

        newticketItems.addAll(parentTktItems);

        Integer i =0;
        for(Id tktItemId: parentTktItemIds) {
            Ticket_Item__c ti = sourceTiLookup.get(tktItemId);
            Ticket_Item__c paItem = dbItemLookup.get(newTiLookup.get(i)); //paItems[i];

            if (ti.Ticket_Items__r != null) {
                List<Ticket_Item__c> sourceChildTktItems = ti.Ticket_Items__r;

                Map<String, Ticket_Item__c> sourceChildTktItemsSyncIds = new Map<String, Ticket_Item__c>();
                Map<Id, Ticket_Item__c> tiChildLookup = new Map<Id, Ticket_Item__c>(sourceChildTktItems);
                List<Id> sourceChildTktItemsIds = new List<Id>();
                for(Ticket_Item__c ti2: sourceChildTktItems) {

                    if (sourceTiLookup.get(ti2.Id) != null) {
                        // if one of the current child tktItem.Ids was in the list of selected children,
                        // then remove it from the selected children list so it isn't processed twice
                        for (Integer j = childTktItemIds.size() - 1; j >= 0 ; --j) {
                            Id childTktItemId = childTktItemIds.get(j);
                            if (childTktItemId == ti2.Id) {
                                childTktItemIds.remove(j);
                            }
                        }

                        childTktItemIdsSyncIdLookup.remove(ti2.SyncID__c);
                    }

                    sourceChildTktItemsIds.add(ti2.Id);
                    sourceChildTktItemsSyncIds.put(ti2.SyncID__c, ti2);
                }


                List<Ticket_Item__c> childItems = CreateTicketItemsUsingPriceBookItems(newTicketId, sourceChildTktItemsIds, tiChildLookup, paItem.SyncID__c);
                insert childItems;

                dbItems = refreshTktItemsList(childItems, fieldsStr);

                dbItems = UpdateTicketItemsUsingTicketItems(dbItems, sourceChildTktItemsIds, tiChildLookup,
                                honorSequenceNumber, nextSequenceNumber, tktItemFieldNames, tktItemFields,
                                sourceChildTktItemsSyncIds);

                newticketItems.addAll(dbItems);
            }

            i++;
        }

        if (childTktItemIds.size() > 0) {
            List<Ticket_Item__c> childTktItems = CreateTicketItemsUsingPriceBookItems(newTicketId, childTktItemIds, sourceTiLookup, '');
            insert childTktItems;

            dbItems = refreshTktItemsList(childTktItems, fieldsStr);

            dbItems = UpdateTicketItemsUsingTicketItems(dbItems, childTktItemIds, sourceTiLookup,
                            honorSequenceNumber, nextSequenceNumber, tktItemFieldNames, tktItemFields,
                            childTktItemIdsSyncIdLookup);

            newticketItems.addAll(dbItems);

        }

        RuleEngineCore.RuleEngineInProgress = false;

        return newticketItems;
    }

    public static List<Ticket_Item__c> refreshTktItemsList(List<Ticket_Item__c> tktItems, String fieldsStr) {
        String ns = UtilityGetNamespace.CurrentNamespace();
        Set<Id> tktItemIds = new Map<Id, Ticket_Item__c>(tktItems).keySet();
        String tiSoql = String.format('SELECT {0} FROM {1} WHERE Id IN :tktItemIds', new String[]{fieldsStr, ns+'Ticket_Item__c'});
        return (List<Ticket_Item__c>)Database.query(tiSoql);
    }

    public static List<Ticket_Item__c> UpdateTicketItemsUsingTicketItems(
            List<Ticket_Item__c> ticketItems, List<Id> tktItemIds, Map<Id, Ticket_Item__c> sourceTiLookup,
            Boolean honorSequenceNumber, Decimal nextSequenceNumber,
            Set<String> tktItemFieldNames, List<SObjectField> tktItemFields,
            Map<String, Ticket_Item__c> sourceTiIdsSyncIdLookup
    ) {
        String ns = UtilityGetNamespace.CurrentNamespace();
        String ticketItemExcludeFieldSetName = 'FX_Ticket_Item_Copy_Exclusion';

        String ticketItemObjName = ns+'Ticket_Item__c';
        Schema.FieldSet fieldset = MetadataHelper.GetFieldSet(ticketItemObjName, ticketItemExcludeFieldSetName);
        List<Schema.FieldSetMember> excludeFields = new List<Schema.FieldSetMember>();

        if (fieldSet != null) excludeFields = fieldSet.getFields();

        Set<String> excludedFields = new Set<String>();
        for(Schema.FieldSetMember field: excludeFields) {
            excludedFields.add(field.getFieldPath());
        }

        Integer m = 0;
        Map<String, String> newSyncIdToOriginalSyncIdLookup = new Map<String, String>();
        for(String origSyncId : sourceTiIdsSyncIdLookup.keySet())
        {
            Ticket_Item__c newTi = ticketItems.get(m);
            newSyncIdToOriginalSyncIdLookup.put(origSyncId, newTi.SyncID__c);

            m++;
        }

        Map<String, Ticket_Item__c> targetTktItemIdsSyncIdLookup = new Map<String, Ticket_Item__c>();
        for(Ticket_Item__c dbti : ticketItems)
        {
            targetTktItemIdsSyncIdLookup.put(dbti.SyncID__c, dbti);
        }

        Map<Id, Ticket_Item__c> tiLookup = new Map<Id, Ticket_Item__c>(ticketItems);
        Map<String, Ticket_Item__c> tiToPbiLookup = new Map<String, Ticket_Item__c>();

        for(Id tktItemId: tktItemIds) {
            Ticket_Item__c sourceTktItem = sourceTiLookup.get(tktItemId);
            String targetSyncId = newSyncIdToOriginalSyncIdLookup.get(sourceTktItem.SyncID__c);
            Ticket_Item__c targetTktItem = targetTktItemIdsSyncIdLookup.get(targetSyncId);

            if (targetTktItem == null) continue;

            //copy fields
            for(SObjectField fTktItem: tktItemFields)
            {
                DescribeFieldResult dfrTktItem = fTktItem.getDescribe();
                String origf = dfrTktItem.getName();
                String f = ns + origf.replace(ns,''); //make sure fieldname has namespace
                String nf = origf.replace(ns,'');

                //skip system fields, and Sequence_Number__c.
                //PriceBook has a flag AddTktItemsByPBSeqNum__c to control how the sequence number should be assigned
                //and codes are down below to do that.
                if(!f.endsWith('__c') || f.endsWith('Sequence_Number__c') ||
                    f.endsWith('Description__c') ||
                    f.endsWith('Discount_Percent__c') ||
                    f.endsWith('Price__c') ||
                    f.endsWith('Parent_Ticket_Item__c') ||
                    f.endsWith('SyncId__c') ) continue;

                if (!dfrTktItem.isUpdateable() || !dfrTktItem.isAccessible() || !dfrTktItem.isCreateable() || dfrTktItem.isCalculated() ||
                    dfrTktItem.isAutoNumber() || dfrTktItem.isExternalId()|| dfrTktItem.isUnique())
                {
                    continue;
                }

                if (excludedFields.contains(f) || excludedFields.contains(nf)) continue;

                if(tktItemFieldNames.contains(f))
                {
                    targetTktItem.put(f, sourceTktItem.get(origf));
                } else if(tktItemFieldNames.contains(nf))
                {
                    targetTktItem.put(nf, sourceTktItem.get(origf));
                }
            }

            targetTktItem.Created_in_Mobile__c = false;

            if ((sourceTktItem.PBI_Locked_Description__c == false) && !excludedFields.contains(ns+'Description__c')) {
                targetTktItem.Description__c = sourceTktItem.Description__c;
            }

            if ((sourceTktItem.PBI_Locked_Discount__c == false) && !excludedFields.contains(ns+'Discount_Percent__c')) {
                targetTktItem.Discount_Percent__c = sourceTktItem.Discount_Percent__c;
            }

            if (!(targetTktItem.PBI_Locked_Price_Markup__c == true || targetTktItem.On_Standby__c == true) && !excludedFields.contains(ns+'Price__c')) {
                targetTktItem.Price__c = sourceTktItem.Price__c;
            }

            if (!honorSequenceNumber) {
                targetTktItem.Sequence_Number__c = nextSequenceNumber++;
            }

            targetTktItem.Invoice_Item__c = null; //#1062
            targetTktItem.PBI_Required_Item__c = false;
            targetTktItem.Rule_Required_Item__c = false;
            targetTktItem.Auto_Added__c = false;

            nextSequenceNumber++;
        }

        update ticketItems;

        return ticketItems;
    }

    public static List<Ticket_Item__c> CreateTicketItemsUsingPriceBookItems(Id newTicketId, List<Id> tktItemIds,
            Map<Id, Ticket_Item__c> tiLookup, String parentSyncId) {

        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();

        for(Id tktItemId: tktItemIds) {
            Ticket_Item__c ti = tiLookup.get(tktItemId);
            ID recId = ti.RecordTypeId;

            Ticket_Item__c tktItem  = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject(recId, true);
            tktItem.Ticket__c = newTicketId;
            tktItem.Price_Book_Item__c = ti.Price_Book_Item__c;
            tktItem.SyncID__c = StringUtility.newGuid();

            if (!String.isBlank(parentSyncId)) {
                tktItem.Parent_Ticket_Item__r = new Ticket_Item__c(SyncID__c = parentSyncId);
            } else {
                if (ti.Parent_Ticket_Item__c != null) {
                    tktItem.Parent_Ticket_Item__c = ti.Parent_Ticket_Item__c;
                }
            }

            tktItems.add(tktItem);
        }

        return tktItems;
    }
}