src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaStack__c.field-meta.xml
<CustomField>
    <fullName>CriteriaStack__c</fullName>
    <description>Preprocessed Criteria - DO NOT MODIFIED</description>
    <inlineHelpText>Preprocessed Criteria - DO NOT MODIFIED</inlineHelpText>
    <label>CriteriaStack</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>PriceBookRules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/Price_Book_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>These actions are triggered by the criteria on the Rule object for the CPQ module.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Rule Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule_Action__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule action is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>Price_Book_Rule__r.Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the rule action.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Price_Book_Rule_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Rule__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Rule__c</fullName>
    <inlineHelpText>Rule for which the rule action is used.</inlineHelpText>
    <label>Rule</label>
    <referenceTo>Price_Book_Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Indicates whether the linked price book item is required, recommended, or disallowed for a ticket.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
                <default>true</default>
                <label>Required</label>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Disallowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status__c/recordTypes/Ticket.recordType-meta.xml
<RecordType>
    <fullName>Ticket</fullName>
    <active>true</active>
    <description>This record type is for Ticket statuses and their related configurations.</description>
    <label>Ticket</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the ticket.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/RuleEngine_TicketItemRule_Test.cls
@isTest
private class RuleEngine_TicketItemRule_Test {
    
    static Price_Book_Rule__c CreateNullRule(String ruleName, Id pbId, String field, String op)
    {
        return CreateRule(ruleName, pbId, field, '', op, true);
    }

    static Price_Book_Rule__c CreateNullRule(String ruleName, Id pbId, String field, String op, Boolean saveNow)
    {
        return CreateRule(ruleName, pbId, field, '', op, saveNow);
    }
    static Price_Book_Rule__c CreateRule(String ruleName, Id pbId, String field, 
        String value, String op, Boolean saveNow)
    {
        String ns = UtilityGetNamespace.CurrentNamespace();

        field = field.replace('[ns]', ns);

        String criteria = String.isBlank(value)? field + ' ' + op + ' null ' : field + ' ' + op + '\'' + value + '\'';

        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"[op]\\",\\"left\\":{\\"type\\":\\"[expType]\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"[value]\\"}}"]';

        String valueStr = String.isBlank(value)? 'null' : value;

        criteriaStack = criteriaStack.replace('[fieldName]', field).replace('[value]', valueStr).replace('[op]', op);

        if(field.indexOf('.')>0)
        {
            criteriaStack = criteriaStack.replace('[expType]', 'MemberExpression');
        }
        else
        {
            criteriaStack = criteriaStack.replace('[expType]', 'Identifier');
        }

        Price_Book_Rule__c rule = new Price_Book_Rule__c(Price_Book__c = pbId, IsActive__c=true, 
            Criteria__c=criteria,
            CriteriaStack__c = criteriaStack);
        if(!String.isBlank(ruleName))
        {
            rule.Name = ruleName;
        }
        System.debug('Criteria: ' + rule.Criteria__c);
        System.debug('Stack: ' + rule.CriteriaStack__c);
        if(saveNow) insert rule;
        return rule;
    }

    
    static TestMethod void GetDisallowedPriceBookItemsForTicketItem_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId , 'Equipment', true);   
        Price_Book_Item__c rootItem = pbItems.get(0);
       
        Price_Book_Rule__c rule = CreateNullRule('Unit Test TicketItem child Disallowed Rule',
            pbId, '[ns]Ticket__r.[ns]Tracking_Number__c', '!=', false);
        rule.Price_Book_Item__c = rootItem.Id;
        insert rule;
     
        Price_Book_Item__c disallowedItem = pbItems.get(1);

        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
            Price_Book_Item__c = disallowedItem.Id, 
            IsActive__c = true, 
            Type__c='Disallowed');
       

        insert tktItemRuleAction;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);


        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        insert tkt;

        Ticket_Item__c ti = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject();
        ti.Ticket__c = tkt.Id;
        ti.Price_Book_Item__c = rootItem.Id;

        insert ti;       
      
        
        List<Id> disallowedItems = RuleEngineCore.GetDisallowedPriceBookItems(ti.Id);
        Test.StopTest();
        
        System.assert(disallowedItems.size()==1,  'Should have one disallowed item');
        System.assert(disallowedItems.get(0) == disallowedItem.Id,  'return ' + disallowedItems.get(0) + ' instead of ' + disallowedItem.Id);
    }
    
   
    static TestMethod void ManuallyAddDisallowedItem_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId , 'Equipment', true);   
        Price_Book_Item__c rootItem = pbItems.get(0);       

        Price_Book_Rule__c rule = CreateNullRule('Unit Test TicketItem child Disallowed Rule',
            pbId, '[ns]Ticket__r.[ns]Tracking_Number__c', '!=', false);
        rule.Price_Book_Item__c = rootItem.Id;
        insert rule;
     
    
     
        Price_Book_Item__c disallowedItem = pbItems.get(1);

        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
            Price_Book_Item__c = disallowedItem.Id, 
            IsActive__c = true, 
            Type__c='Disallowed');
       

        insert tktItemRuleAction;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);


        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        insert tkt;

        Ticket_Item__c ti = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject();
        ti.Ticket__c = tkt.Id;
        ti.Price_Book_Item__c = rootItem.Id;

        insert ti;
        
        Ticket_Item__c childItem = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject();
        childItem.Ticket__c = tkt.Id;
        childItem.Price_Book_Item__c = disallowedItem.Id;
        childItem.Parent_Ticket_Item__c = ti.Id;
        
        try
        {
            Database.SaveResult sr = Database.insert(childItem);
             System.assert(sr.isSuccess() == false,  'Manually adding disallowd item should fail');
        }
        catch(System.DmlException e)
        {
            String msg = '';
            for (Integer i = 0; i < e.getNumDml(); i++) 
            {
            
                msg += e.getDmlMessage(i); 
            }
            System.assert(msg.contains('Disallowed by Rule -'), 'Manually adding disallowd item should fail with DmlException');
        }     
    }
    
    static TestMethod void TwoRulesOnTheSameItem_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);

        Price_Book_Rule__c rule1 = CreateNullRule('',
            pbId, '[ns]Ticket__r.[ns]Tracking_Number__c', '!=', false);
        rule1.Price_Book_Item__c = requiredItem.Id;
        insert rule1;
        
        Price_Book_Rule__c rule2 = CreateNullRule('',
            pbId, '[ns]Ticket__r.[ns]SyncID__c', '!=', false);
        rule2.Price_Book_Item__c = requiredItem.Id;
        insert rule2;
     
        List<Price_Book_Rule_Action__c > ruleActions = new List<Price_Book_Rule_Action__c>();

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule1.Id, 
            Price_Book_Item__c = pbItems.get(1).Id, 
            IsActive__c = true, 
            Type__c='Required'));
            
        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule2.Id, 
            Price_Book_Item__c = pbItems.get(1).Id, 
            IsActive__c = true, 
            Type__c='Required'));       

        insert ruleActions;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);


        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        insert tkt;

        Ticket_Item__c ti = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject();
        ti.Ticket__c = tkt.Id;
        ti.Price_Book_Item__c = requiredItem.Id;

        insert ti;

        Test.stopTest();

        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Parent_Ticket_Item__c = :ti.Id];

        System.assert(tktItems.size() == 1, 'should have one child tkt items, but instead has ' + tktItems.size());


    }


   static TestMethod void InsertTicketItem_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);

        Price_Book_Rule__c tiRule = CreateNullRule('',
            pbId, '[ns]Ticket__r.[ns]Tracking_Number__c', '!=', false);
        tiRule.Price_Book_Item__c= requiredItem.Id;
        insert tiRule;

        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = tiRule.Id, 
            Price_Book_Item__c = pbItems.get(1).Id, 
            IsActive__c = true, 
            Type__c='Required');
       

        insert tktItemRuleAction;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);


        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        insert tkt;

        Ticket_Item__c ti = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject();
        ti.Ticket__c = tkt.Id;
        ti.Price_Book_Item__c = requiredItem.Id;

        insert ti;

        Test.stopTest();

        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Parent_Ticket_Item__c = :ti.Id];

        System.assert(tktItems.size() == 1, 'should have one child tkt items, but instead has ' + tktItems.size());


    }


    static TestMethod void InsertTicket_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(2, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);
        Price_Book_Item__c tktItemRuleChildItem = pbItems.get(1);
        
        Price_Book_Rule__c rule = CreateNullRule('', pbId, '[ns]Tracking_Number__c', '!=');

        Price_Book_Rule__c tiRule = CreateNullRule('',
            pbId, '[ns]Ticket__r.[ns]Tracking_Number__c', '!=', false);
        tiRule.Price_Book_Item__c= requiredItem.Id;
        insert tiRule;

        
        List<Price_Book_Rule_Action__c> actions = new List<Price_Book_Rule_Action__c>();
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        actions.add(action);



        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = tiRule.Id, 
            Price_Book_Item__c =tktItemRuleChildItem.Id, 
            IsActive__c = true, 
            Type__c='Required');
        actions.add(tktItemRuleAction);

        insert actions;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);

        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        insert tkt;


        Test.stopTest();

        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c = :tkt.Id];

        System.assert(tktItems.size() == 2, 'should have two tkt items, but instead has ' + tktItems.size());


    }


    static TestMethod void UpdateTicket_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(2, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);
        Price_Book_Item__c tktItemRuleChildItem = pbItems.get(1);

        String newGuid = StringUtility.newGuid();

      

        Price_Book_Rule__c rule = CreateNullRule('',
            pbId, '[ns]Tracking_Number__c', '!=');   


        Price_Book_Rule__c tiRule  = CreateRule('', pbId, '[ns]Ticket__r.[ns]Status__r.Name', 's2'+ newGuid, '==', false);
        tiRule.Price_Book_Item__c= requiredItem.Id;
        insert tiRule;

        
        List<Price_Book_Rule_Action__c> actions = new List<Price_Book_Rule_Action__c>();
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
            Price_Book_Item__c = requiredItem.Id, IsActive__c = true, 
            Type__c='Required');
        actions.add(action);



        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = tiRule.Id, 
            Price_Book_Item__c = tktItemRuleChildItem.Id, 
            IsActive__c = true, 
            Type__c='Required');
        actions.add(tktItemRuleAction);

        insert actions;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);

      
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        List<Status__c> tktStatus = new List<Status__c>();
        String statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        tktStatus.add(st);

        Status__c st2 = new Status__c(Name = 's2'+newGuid, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        tktStatus.add(st2);

        insert tktStatus;
        
        tkt.Status__c = st.Id;
        insert tkt;

        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c=:tkt.Id AND Price_Book_Item__c=:requiredItem.Id];
        System.assert(tktItems.size()==1, 'Ticket should have ONE tkt items');

        tkt.Customer_Survey_Satisfaction__c = 'Disappointed';
        update tkt;

        tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c=:tkt.Id];
        System.assert(tktItems.size()==1, 'Ticket should have not add child tkt items upon update on non-criteria field');

        tkt.Status__c = st2.Id;
        update tkt;

        Test.stopTest();

        tktItems = [SELECT Id, Price_Book_Item__c, Auto_Added__c, Rule_Required_Item__c FROM Ticket_Item__c 
            WHERE Ticket__c=:tkt.Id 
                AND Price_Book_Item__c =:tktItemRuleChildItem.Id
                AND Parent_Ticket_Item__r.Price_Book_Item__c =:requiredItem.Id];

        System.assert(tktItems.size()==1, 'Ticket should have ONE child tkt items upon update on criteria field');

        Ticket_Item__c ti = tktItems.get(0);

        System.assert(ti.Auto_Added__c ==true, 'Ticket Item should have  Auto_Added__c=true');
        System.assert(ti.Rule_Required_Item__c == true, 'Ticket Item should have  Rule_Required_Item__c=true');    


    }

    static TestMethod void UpdateJob_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(2, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);
        Price_Book_Item__c tktItemRuleChildItem = pbItems.get(1);

        String newGuid = StringUtility.newGuid();

      
        Price_Book_Rule__c rule = CreateNullRule('', pbId, '[ns]Tracking_Number__c', '!=');          


        Price_Book_Rule__c tiRule  = CreateRule('', pbId, '[ns]Ticket__r.[ns]Job__r.[ns]Status__r.Name', 's2'+ newGuid, '==', false);
        tiRule.Price_Book_Item__c= requiredItem.Id;
        insert tiRule;
        
        List<Price_Book_Rule_Action__c> actions = new List<Price_Book_Rule_Action__c>();
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
            Price_Book_Item__c = requiredItem.Id, IsActive__c = true, 
            Type__c='Required');
        actions.add(action);



        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = tiRule.Id, 
            Price_Book_Item__c = tktItemRuleChildItem.Id, 
            IsActive__c = true, 
            Type__c='Required');
        actions.add(tktItemRuleAction);

        insert actions;      


        Test.startTest();

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, false).get(0);

      
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        List<Status__c> statusItems = new List<Status__c>();
        Status__c tktStatus  = new Status__c(Name = 's1' + newGuid, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        statusItems.add(tktStatus);

        Status__c jobStatus = new Status__c(Name = 's2'+newGuid, SObject__c='Job__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        statusItems.add(jobStatus);

        insert statusItems;
        
        tkt.Status__c = tktStatus.Id;
        insert tkt;

        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c=:tkt.Id AND Price_Book_Item__c=:requiredItem.Id];
        System.assert(tktItems.size()==1, 'Ticket should have ONE tkt items');

        Job__c dbJob = [SELECT Id, Notes__c, Status__c FROM Job__c WHERE Id=:job.Id];
        dbJob.Notes__c ='Unit test updating Notes';
        update dbJob;

        tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c=:tkt.Id];
        System.assert(tktItems.size()==1, 'Should not add child tkt items upon update on non-criteria field');

        dbJob.Status__c = jobStatus.Id;
        update dbJob;

        Test.stopTest();

        tktItems = [SELECT Id, Price_Book_Item__c, Auto_Added__c, Rule_Required_Item__c FROM Ticket_Item__c 
            WHERE Ticket__c=:tkt.Id 
                AND Price_Book_Item__c =:tktItemRuleChildItem.Id
                AND Parent_Ticket_Item__r.Price_Book_Item__c =:requiredItem.Id];

        System.assert(tktItems.size()==1, 'Ticket should have ONE child tkt items upon update on criteria field');

        Ticket_Item__c ti = tktItems.get(0);

        System.assert(ti.Auto_Added__c ==true, 'Ticket Item should have  Auto_Added__c=true');
        System.assert(ti.Rule_Required_Item__c == true, 'Ticket Item should have  Rule_Required_Item__c=true');    


    }




    static void InitTest(Id pbId)
    {     
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);      
        Price_Book_Rule__c rule = CreateNullRule('', pbId, '[ns]Tracking_Number__c', '!=');          

        Price_Book_Rule__c tiRule  = CreateNullRule('', pbId, '[ns]Ticket__r..[ns]Tracking_Number__c', '!=');        
        List<Price_Book_Rule_Action__c> actions = new List<Price_Book_Rule_Action__c>();
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        actions.add(action);

        Price_Book_Rule_Action__c tktItemRuleAction = new Price_Book_Rule_Action__c(Price_Book_Rule__c = tiRule.Id, 
            Price_Book_Item__c = pbItems.get(1).Id, 
            IsActive__c = true, 
            Type__c='Required');
        actions.add(tktItemRuleAction);

        insert actions;      

    }


}