src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the ticket.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/ManagedPackageHelpersTest.cls
@isTest
private class ManagedPackageHelpersTest{

	static testmethod void GetCleanTypeName(){
		string typeName = ManagedPackageHelpers.CleanTypeName('job__c').toLowerCase();		
		system.assert(typeName.contains('job')); 
		string ns = UtilityGetNamespace.CurrentNamespace();
		if(ns != '') system.assert(typeName.contains(ns.toLowerCase())); 
		system.assertEquals(ManagedPackageHelpers.CleanTypeName('BogusType'), null);
		
	}
	
	static testmethod void GetCleanFieldName(){
		system.assertEquals(ManagedPackageHelpers.CleanFieldName('BogusType', 'tracking_number__c'), null);
		system.assertEquals(ManagedPackageHelpers.CleanFieldName('job__c', 'bogusField'), null);
		
		string result = ManagedPackageHelpers.CleanFieldName('job__c', 'tracking_number__c').toLowerCase();
		system.assert(result.contains('tracking_number__c')); 
		string ns = UtilityGetNamespace.CurrentNamespace();
		if(ns != '') system.assert(result.contains(ns.toLowerCase())); 
	}
	
	static testmethod void GetCleanFieldList(){
		string result = ManagedPackageHelpers.CleanFieldList('job__c', 'tracking_number__c,syncid__c').toLowerCase();
		string ns = UtilityGetNamespace.CurrentNamespace();
		if(ns==null) ns = '';
		ns = ns.toLowerCase();
		system.assertEquals(result, ns+'tracking_number__c' + ',' + ns + 'syncid__c');	
	}	
	
	static testmethod void GetCleanRelationship(){
		system.assertEquals(ManagedPackageHelpers.CleanRelationship('BogusType', 'Tickets__r'), null);
		system.assertEquals(ManagedPackageHelpers.CleanRelationship('job__c', 'bogusRelationship'), null);
		string result = ManagedPackageHelpers.CleanRelationship('job__c', 'Tickets__r').toLowerCase();
		string ns = UtilityGetNamespace.CurrentNamespace();
		if(ns==null) ns = '';
		ns = ns.toLowerCase();		
		system.assertEquals(result, ns+'tickets__r');
	}

}