src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/Ticket_Log__c.object-meta.xml
<CustomObject>
    <label>Ticket Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Ticket Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/JobPropagatorBatchable.cls
public without sharing class JobPropagatorBatchable extends FXBatchableBase
{
    public static void RunPostInstall()
    {
        String ns = StringUtility.FXNamespace();
        Database.executeBatch(new JobPropagatorBatchable(ns + 'Ticket_Item__c'));
        Database.executeBatch(new JobPropagatorBatchable(ns + 'Ticket_Log__c'));
        Database.executeBatch(new JobPropagatorBatchable(ns + 'Ticket_Checklist_Step__c'));
    }    

    public JobPropagatorBatchable(String objType)
    {
        Init(objType);
    }
    
    void Init(String objType)
    {
        RuleEngineIsActive = RuleEngineCore.IsActive();
        if(RuleEngineIsActive)
        {
            RuleEngineCore.Suspend();
        }
        String ns = StringUtility.FXNamespace();
        String jobField = 'Job_Share__c';
        if(!String.isBlank(ns) 
            || objType.equalsIgnorecase('Ticket_Item__c')
            || objType.equalsIgnorecase('Ticket_Log__c')
            || objType.equalsIgnorecase('Ticket_Checklist_Step__c'))
        {
            jobField = ns + 'Job__c';
        }
        soqlQuery = 'SELECT Id FROM ' + objType + ' WHERE IsDeleted=false AND ' + jobField + '=null'; 
    }
    Boolean RuleEngineIsActive {get;set;}


    public override void execute(Database.BatchableContext BC, List<sObject> scope)
    {   
        Database.update(scope, false);
    } 
    public override void finish(Database.BatchableContext BC)
    {       
        if(RuleEngineIsActive)
        {
            RuleEngineCore.Activate();
        } 
    }
}