src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/IsReadOnlyOnConsole__c.field-meta.xml
<CustomField>
    <fullName>IsReadOnlyOnConsole__c</fullName>
    <description>If the job status or ticket status is readonly for console, then the ticket is readonly</description>
    <formula>INCLUDES(Job__r.Status__r.Read_Only_Apps__c, "Console") ||  INCLUDES(Status__r.Read_Only_Apps__c, 'Console')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsReadOnlyOnConsole</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/AllowOverride__c.field-meta.xml
<CustomField>
    <fullName>AllowOverride__c</fullName>
    <formula>OR( NOT(ISBLANK( Price_Book_Item__r.Override_Price_Method__c )) , NOT(ISBLANK( Price_Book_Item__r.Override_Cost_Method__c )) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AllowOverride</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/OverrideBatcher.cls
public class OverrideBatcher extends FXBatchableBase 
{
    static Boolean ExcutedOnce = false;

    @testVisible
    static String TicketItemCountSoql_Tickets
    {
        get
        {
            return String.format('SELECT COUNT() FROM {0}Ticket_Item__c WHERE {0}Ticket__c IN :objIds AND {0}Ticket__r.{0}IsReadOnlyOnConsole__c=false AND {0}AllowOverride__c=true',
                    new String[]{StringUtility.FXNamespace()});
        }
    }

    @testVisible
    static String TicketItemCountSoql_Jobs
    {
        get
        {
            return String.format('SELECT COUNT() FROM {0}Ticket_Item__c WHERE {0}Ticket__r.{0}Job__c IN :objIds AND {0}Ticket__r.{0}IsReadOnlyOnConsole__c=false AND {0}AllowOverride__c=true',
                    new String[]{StringUtility.FXNamespace()});
        }
    }

    public static void RunOnJobs(Set<Id> objIds)
    {
    	if(ExcutedOnce == true) return;        
        Run(TicketItemCountSoql_Jobs, objIds);               
    }

    public static void RunOnTickets(Set<Id> objIds)
    {    	  
        if(ExcutedOnce == true) return;
        Run(TicketItemCountSoql_Tickets, objIds);  
         
    }

    static void Run(String countSoql, Set<Id> objIds)
    {
    	Integer count = Database.countQuery(countSoql);
        String soql = countSoql.replace('COUNT()', 'Id');
        Integer batchSize = (Integer)FXSettingHelper.OverrideBatchSize;
        Integer availableSoqls = Limits.getLimitQueries() - Limits.getQueries() - 5;

        if(availableSoqls>0 && availableSoqls<batchSize)
        {
            batchSize = availableSoqls;
        }
        if(count<=batchSize)
        {
        	ExcutedOnce = true;
        	Database.update(Database.query(soql));
        }
        else if(!System.isBatch() && !System.isFuture()) 
        {
        	RunBatch(soql, objIds, batchSize );
        }
    }
    
    @testVisible
    static void RunBatch(String soql, Set<Id> ids, Integer batchSize)
    {
    	OverrideBatcher b = new OverrideBatcher(soql, ids);
    	Database.executeBatch(b, batchSize);
    }
    
    Set<Id> objIds {get;set;}

    private OverrideBatcher(String soql, Set<Id> ids)
    {   
    	objIds = ids;
        soqlQuery = soql.replace('COUNT()', 'Id');
    }

    public override Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(soqlQuery);
    }

    public override void execute(Database.BatchableContext BC, List<sObject> scope)
    {   
    	ExcutedOnce = true;
        Database.update(scope, false);
    }     
}