src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/StatusBuilder_Test.cls
@isTest
private class StatusBuilder_Test 
{    
    static testmethod void OnlyOneInitialMobileStatus_BulkInsert()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   

        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');

        RecordType rtJob = AlpineTestHelper.GetRecordType('Job__c');
                
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE RecordTypeId=:rt.Id AND Initial_Status_Mobile__c =true];
        System.assertEquals(1, dbItems.size());
    }     

    static testmethod void OnlyOneInitialMobileStatus_Insert()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
        
        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');
        RecordType rtJob = AlpineTestHelper.GetRecordType('Job__c');
    
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Status__c s1 = new Status__c(Name = 'Final' + newGuid, SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);

        insert s1;

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE SObject__c = 'Job__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND Initial_Status_Mobile__c =true];
        System.assertEquals(1, dbItems.size());
        System.assertEquals('Final' + newGuid, dbItems.get(0).Name);
    } 

    static testmethod void OnlyOneInitialMobileStatus_Update()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
        
        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');

        RecordType rtJob = AlpineTestHelper.GetRecordType('Job__c');

    
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName,  Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Status__c s1 = new Status__c(Name = 'Final' + newGuid, SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);

        
        List<Status__c> itemsToUpdate = [SELECT Initial_Status_Mobile__c, Name, Id FROM Status__c WHERE RecordTypeId=:rt.Id AND (Name='s0' OR Name='s1')];
        for(Status__c s : itemsToUpdate)
        {
            s.Initial_Status_Mobile__c = true;
        }
        update itemsToUpdate;
      

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE RecordTypeId=:rt.Id AND Initial_Status_Mobile__c =true];
        System.assertEquals(1, dbItems.size());
        System.assert(dbItems.get(0).Name == 's0' || dbItems.get(0).Name == 's1');


    } 


    static testmethod void OnlyOneInitialConsoleStatus_Insert()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
        
        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');
        RecordType rtJob = AlpineTestHelper.GetRecordType('Job__c');


    
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Status__c s1 = new Status__c(Name = 'Final' + newGuid, SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName,  Initial_Status_Console__c =true, RecordTypeId=rt.Id);

        insert s1;

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE SObject__c= 'Job__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND Initial_Status_Console__c =true];
        System.assertEquals(1, dbItems.size());
        System.assertEquals('Final' + newGuid, dbItems.get(0).Name);
    } 


    static testmethod void OnlyOneInitialConsoleStatus_Update()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
       
         RecordType rt = AlpineTestHelper.GetRecordType('Status__c');
        RecordType rtJob = AlpineTestHelper.GetRecordType('Job__c');

    
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName,Initial_Status_Console__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Status__c s1 = new Status__c(Name = 'Final' + newGuid, SObject__c= 'Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =true, RecordTypeId=rt.Id);

        
        List<Status__c> itemsToUpdate = [SELECT Initial_Status_Console__c, Name, Id FROM Status__c WHERE RecordTypeId=:rt.Id AND (Name='s0' OR Name='s1')];
        for(Status__c s : itemsToUpdate)
        {
            s.Initial_Status_Console__c = true;
        }
        update itemsToUpdate;
      

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE SObject__c= 'Job__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND Initial_Status_Console__c =true];
        System.assertEquals(1, dbItems.size());
        System.assert(dbItems.get(0).Name == 's0' || dbItems.get(0).Name == 's1');
    } 


    static testmethod void OnlyOneInitialStatus_Insert()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
        
        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');
        RecordType rtJob = AlpineTestHelper.GetRecordType('Ticket__c');

        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Ticket__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =true, Initial_Status_Mobile__c=true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;       
      
        Status__c s1 = new Status__c(Name = 'Final' + newGuid, SObject__c= 'Ticket__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =true, 
        Initial_Status_Mobile__c=true, RecordTypeId=rt.Id);

        insert s1;

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE SObject__c= 'Ticket__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND Initial_Status_Console__c =true AND Initial_Status_Mobile__c=true];
        System.assertEquals(1, dbItems.size());
        System.assertEquals('Final' + newGuid, dbItems.get(0).Name);
    }

    static testmethod void OnlyOneInitialStatus_Update()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   
        
        RecordType rt = AlpineTestHelper.GetRecordType('Status__c');
        RecordType rtJob = AlpineTestHelper.GetRecordType('Ticket__c');

    
        List<Status__c> items = new List<Status__c>();
        Integer count = 100;
        for(Integer i = 0; i<count; i++)
        {
              Status__c s = new Status__c(Name = 's' + string.valueOf(i), SObject__c= 'Ticket__c', SObject_Record_Type__c = rtJob.DeveloperName,Initial_Status_Console__c =true, Initial_Status_Mobile__c =true, RecordTypeId=rt.Id);
              items.add(s);        
        }
        insert items;               
        
        List<Status__c> itemsToUpdate = [SELECT Initial_Status_Console__c, Initial_Status_Mobile__c, Name, Id FROM Status__c WHERE SObject__c= 'Ticket__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND (Name='s0' OR Name='s1')];
        for(Status__c s : itemsToUpdate)
        {
            s.Initial_Status_Console__c = true;
            s.Initial_Status_Mobile__c = true;
        }
        update itemsToUpdate;
      

        Test.StopTest();      

        List<Status__c> dbItems = [SELECT Id, Name FROM Status__c WHERE SObject__c= 'Ticket__c' AND SObject_Record_Type__c = :rtJob.DeveloperName AND Initial_Status_Console__c =true AND Initial_Status_Mobile__c=true];
        System.assertEquals(1, dbItems.size());
        System.assert(dbItems.get(0).Name == 's0' || dbItems.get(0).Name == 's1');
    } 
}