src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the job was added in FieldFX Mobile. This checkbox is selected automatically for all jobs added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Read_Only_Apps__c.field-meta.xml
<CustomField>
    <fullName>Read_Only_Apps__c</fullName>
    <inlineHelpText>Indicates whether jobs/tickets with this status are read-only in each application.</inlineHelpText>
    <label>Read Only Apps</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Console</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status__c/recordTypes/Ticket.recordType-meta.xml
<RecordType>
    <fullName>Ticket</fullName>
    <active>true</active>
    <description>This record type is for Ticket statuses and their related configurations.</description>
    <label>Ticket</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the ticket was added in FieldFX Mobile. This checkbox is selected automatically for all tickets added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/RuleEngineConsole.cls
public class RuleEngineConsole
{  
    public static void OnTicketItemBeforeInsert(List<Ticket_Item__c> tktItems)
    {
        if(RuleEngineCore.IsSuspended() || RuleEngineCore.RuleEngineInProgress == true) return;
        RuleEngineCore.ValdiateDisallowRules(tktItems);
        //Execute(new Map<Id, Ticket_Item__c>(tktItems).keySet(), false);
    }

    public static void OnTicketItemAfterInsert(List<Ticket_Item__c> tktItems)
    {
        //System.debug('***************** RuleEngineConsole.OnTicketItemAfterInsert');
        ExecuteOnTicketItems(new Map<Id, Ticket_Item__c>(tktItems).keySet(), false);
    }

    public static void OnTicketItemUpdate(List<Ticket_Item__c> tktItems)
    {   
        //System.debug('***************** RuleEngineConsole.OnTicketItemUpdate');
        ExecuteOnTicketItems(new Map<Id, Ticket_Item__c>(tktItems).keySet(), true);
    }


    public static void OnJobUpdate(List<Job__c> jobs, Map<Id, Job__c> oldMap)
    {
        if(RuleEngineCore.IsSuspended() || RuleEngineCore.RuleEngineInProgress == true) return;
        Set<Id> priceBookIds = new Set<Id>();
        for(Job__c j : jobs)
        {
            priceBookIds.add(j.Price_Book__c);
        }
        Map<String, Set<String>> criteriaFields = RuleEngineCore.GetPriceBookRuleCriteriaFields(priceBookIds);
        
        //System.debug('criteriaFields:'  + criteriaFields);

        Set<Id> jobIds = new Set<Id>();
        
        for(Job__c j : jobs)
        {
            Job__c prev = oldMap.get(j.Id);
            String fKey = 'job' + j.Price_Book__c;
            if(!criteriaFields.containsKey(fKey)) continue;
            for(String f : criteriaFields.get(fKey))
            {
                if(j.get(f) != prev.get(f))
                {
                    jobIds.add(j.Id);
                    break;
                }
            }
        }
        if(jobIds.isEmpty()) return;

        List<Ticket__c> tkts = [SELECT Id, Status__r.Read_Only_Apps__c FROM Ticket__c WHERE Job__c IN :jobIds AND Sync__c=false AND Status__c!=null];
        Set<Id> tktIds = new Set<Id>();
        for(Ticket__c t:tkts)
        {
            if(t.Status__c!=null && !String.isBlank(t.Status__r.Read_Only_Apps__c) && t.Status__r.Read_Only_Apps__c.contains('Console')) continue;
            tktIds.add(t.Id);            
        }
        //System.debug('run rule engine for tkts upon Job update:' + tktIds);
        Execute(tktIds, true);
    }
    public static void OnTicketInsert(List<Ticket__c> tickets)
    {
        if(RuleEngineCore.IsSuspended()) return;
        
        Set<Id> tktIds = new Set<Id>();
        
        for(Ticket__c t: tickets)
        {
            if(t.Created_in_Mobile__c == true) continue;
            tktIds.add(t.Id);
        }
        Execute(tktIds, false);
    }
    
    public static void OnTicketUpdate(List<Ticket__c> tickets, Map<Id, Ticket__c> oldMap)
    {
        if(RuleEngineCore.IsSuspended() || RuleEngineCore.RuleEngineInProgress == true) return;
        
        List<Ticket__c> tktsOfInterest = new List<Ticket__c>();
        
        Set<Id> tktIdsForRuleEngine = new Set<Id>();
        Set<Id> tktIds = new Set<Id>();
        Set<Id> jobIds = new Set<Id>();
        for(Ticket__c t: tickets)
        {
            if(t.Sync__c == true) continue;
            tktsOfInterest.add(t);
            jobIds.add(t.Job__c);
        }
        if(tktsOfInterest.isEmpty()) return;

        Map<Id, Id> jobPriceBookLookup = new Map<Id, Id>();
        List<Job__c> jobs = [SELECT Id, Price_Book__c FROM Job__c WHERE Id IN :jobIds];
        Set<Id> priceBookIds = new Set<Id>();
        for(Job__c j : jobs)
        {
            priceBookIds.add(j.Price_Book__c);
            jobPriceBookLookup.put(j.Id, j.Price_Book__c);
        }
        Map<String, Set<String>> criteriaFields = RuleEngineCore.GetPriceBookRuleCriteriaFields(priceBookIds);
        // System.debug('criteriaFields:'  + criteriaFields);

        for(Ticket__c t: tktsOfInterest)
        {
            Ticket__c prev = oldMap.get(t.Id);
            if(t.Sync__c != prev.Sync__c && t.Sync__c==false) 
            {
                tktIds.add(t.Id);
                continue;
            }
            
            String fKey = 'tkt' + jobPriceBookLookup.get(t.Job__c);
            if(!criteriaFields.containsKey(fKey)) continue;
            for(String f : criteriaFields.get(fKey))
            {
                if(t.get(f) != prev.get(f))
                {
                    tktIds.add(t.Id);
                    break;
                }
            }
        }  

        //System.debug('run rule engine for tkts upon Ticket update:' + tktIds);
        if(!tktIds.isEmpty())
        {
           Execute(tktIds, true);           
        }
    }
    
    static void Execute(Set<Id> objIds, Boolean skipRecommendedItems)
    {

        if(objIds==null || objIds.isEmpty()) return;

        //System.debug('Execute on objIds:' + objIds);

        if(objIds.size()==1)
        {
            RuleEngineCore.Execute(objIds, skipRecommendedItems);
        }
        else
        {
            System.enqueueJob(new RuleEngineQueueable(objIds, skipRecommendedItems));
        }
    }

    static void ExecuteOnTicketItems(Set<Id> objIds, Boolean skipRecommendedItems)
    {
        if(objIds==null || objIds.isEmpty()) return;
        
        //System.debug('objIds.size()=' + objIds.size());

        if(RuleEngineCore.IsSuspended() || RuleEngineCore.RuleEngineInProgress == true) return;       

        if(objIds.size()==1)
        {
            RuleEngineCore.ExecuteOnTicketItems(objIds, skipRecommendedItems);
        }
        else
        {
            System.enqueueJob(new RuleEngineQueueable(objIds, skipRecommendedItems));
        }
    }
}