src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status__c/recordTypes/Ticket.recordType-meta.xml
<RecordType>
    <fullName>Ticket</fullName>
    <active>true</active>
    <description>This record type is for Ticket statuses and their related configurations.</description>
    <label>Ticket</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/StatusTriggerTests.cls
@isTest
private class StatusTriggerTests
{
   static testmethod void SetJobInitialStatus()
   {
   		String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rtStatus = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

  		objType = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        RecordType rtJob = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

		Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);

		Status__c s = new Status__c(Name='New Job', SObject__c='Job__c', SObject_Record_Type__c = rtJob.DeveloperName, RecordTypeId=rtStatus.Id, Initial_Status_Console__c=true);
		insert s;
        
        string jobName = 'Job' + StringUtility.newGuid();
       
        j.RecordTypeId = rtJob.Id;
        j.Name = jobName;
        j.Status__c = null;

        Insert j;
		
		Job__c dbJob = [SELECT Status__c FROM Job__c where Name =:jobName LIMIT 1];	
		System.assertEquals(s.Id, dbJob.Status__c);		
	}
	
	static testmethod void SetTicketInitialStatus(){
     	String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rtStatus = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

        objType = UtilityGetNamespace.CurrentNamespace()  + 'Ticket__c';
        RecordType rtTkt = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

		
		Status__c s = new Status__c(Name='New Ticket', SObject__c='Ticket__c', SObject_Record_Type__c = rtTkt.DeveloperName, RecordTypeId=rtStatus.Id, Initial_Status_Console__c=true);
		insert s;

		Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);		  
		Ticket__c t= new Ticket__c(Job__c = job.Id, RecordTypeId= rtTkt.Id);
        insert t;
		
		Ticket__c tkt =  [SELECT Id, Status__c FROM Ticket__c WHERE Job__c= :job.Id LIMIT 1];  
		System.assertEquals(s.Id, tkt.Status__c);
	}
	
	static testmethod void StatusOnlyOneInitialStatusForConsole(){	
		TestOnlyOneInitialStatus(true);
	}
	
	static testmethod void StatusOnlyOneInitialStatusForMobile(){
	
		TestOnlyOneInitialStatus(false);
	}
	
	static void TestOnlyOneInitialStatus(Boolean trueForConsole_FalseForMobile){
		Boolean isInitial_Status_Console = false;
		Boolean isInitial_Status_Mobile = false; 	
		if(trueForConsole_FalseForMobile)
		{
			isInitial_Status_Console = true;
		}
		else
		{
			isInitial_Status_Mobile = true;
		}
		String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rt = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

        objType = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        RecordType rtJob = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

	
		String statusName = StringUtility.newGuid();
		Status__c s1 = new Status__c(Name=statusName, SObject__c='Job__c', SObject_Record_Type__c=rtJob.DeveloperName, RecordTypeId=rt.Id, Initial_Status_Console__c =isInitial_Status_Console, Initial_Status_Mobile__c=isInitial_Status_Mobile);
		insert s1;
		List<Status__c> statusItems = [select Id, Name from Status__c where Initial_Status_Console__c =:isInitial_Status_Console AND Initial_Status_Mobile__c=:isInitial_Status_Mobile AND SObject__c = 'Job__c'];
		System.assertEquals(statusItems.size(), 1);
		System.assertEquals(statusItems[0].Name, statusName);
		
		statusName = StringUtility.newGuid();
		Status__c s2 = new Status__c(Name=statusName, SObject__c='Job__c', SObject_Record_Type__c=rtJob.DeveloperName, RecordTypeId=rt.Id, Initial_Status_Console__c =isInitial_Status_Console, Initial_Status_Mobile__c=isInitial_Status_Mobile);
		insert s2;
		statusItems =[select Id, Name from Status__c where Initial_Status_Console__c =:isInitial_Status_Console AND Initial_Status_Mobile__c=:isInitial_Status_Mobile AND SObject__c = 'Job__c'];
		System.assertEquals(statusItems.size(), 1);
		System.assertEquals(statusItems[0].Name, statusName);
		
		statusName = StringUtility.newGuid();
		Status__c s3 = new Status__c(Name=statusName, SObject__c='Job__c', SObject_Record_Type__c=rtJob.DeveloperName, RecordTypeId=rt.Id, Initial_Status_Console__c =isInitial_Status_Console, Initial_Status_Mobile__c=isInitial_Status_Mobile);
		insert s3;
		statusItems = [select Id, Name from Status__c where Initial_Status_Console__c =:isInitial_Status_Console AND Initial_Status_Mobile__c=:isInitial_Status_Mobile AND SObject__c = 'Job__c'];
		System.assertEquals(statusItems.size(), 1);
		System.assertEquals(statusItems[0].Name, statusName);
		
		
		s2.Initial_Status_Console__c = isInitial_Status_Console;
		s2.Initial_Status_Mobile__c = isInitial_Status_Mobile;
		update s2;
		
		statusItems =[select Id, Name from Status__c where Initial_Status_Console__c =:isInitial_Status_Console AND Initial_Status_Mobile__c=:isInitial_Status_Mobile AND SObject__c = 'Job__c'];
		System.assertEquals(statusItems.size(), 1);
		System.assertEquals(statusItems[0].Name, s2.Name);
	}
}