src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaStack__c.field-meta.xml
<CustomField>
    <fullName>CriteriaStack__c</fullName>
    <description>Preprocessed Criteria - DO NOT MODIFIED</description>
    <inlineHelpText>Preprocessed Criteria - DO NOT MODIFIED</inlineHelpText>
    <label>CriteriaStack</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>PriceBookRules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/Price_Book_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>These actions are triggered by the criteria on the Rule object for the CPQ module.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Rule Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule_Action__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule action is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>Price_Book_Rule__r.Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the rule action.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Price_Book_Rule_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Rule__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Rule__c</fullName>
    <inlineHelpText>Rule for which the rule action is used.</inlineHelpText>
    <label>Rule</label>
    <referenceTo>Price_Book_Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Indicates whether the linked price book item is required, recommended, or disallowed for a ticket.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
                <default>true</default>
                <label>Required</label>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Disallowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status__c/recordTypes/Ticket.recordType-meta.xml
<RecordType>
    <fullName>Ticket</fullName>
    <active>true</active>
    <description>This record type is for Ticket statuses and their related configurations.</description>
    <label>Ticket</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/RuleEngine_Test.cls
@isTest
private class RuleEngine_Test
{
    static Price_Book_Rule__c GetRule(Id pbId, String criteria, String criteriaStack)
    {
        Price_Book_Rule__c rule = new Price_Book_Rule__c(Price_Book__c = pbId, IsActive__c=true, 
            Criteria__c=criteria,
            CriteriaStack__c = criteriaStack);
        insert rule;
        return rule;
    }

    static Price_Book_Rule__c GetRule(Id pbId, String field, 
        String value, String op)
    {
        return GetRule(pbId, field, value, op, true);
    }


    static Price_Book_Rule__c GetRule(Id pbId, String field, 
        String value, String op, Boolean saveNow)
    {
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        field = field.replace('[ns]', ns);

        String criteria = field + op + '\'' + value + '\'';
        System.debug('criteria: ' + criteria);

         
        String criteriaStack =  '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"[op]\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        
        System.debug('criteriaStack: ' + criteriaStack);
        criteriaStack = criteriaStack.replace('[fieldName]', field).replace('[op]', op).replace('[value]', value);
        Price_Book_Rule__c rule = new Price_Book_Rule__c(Price_Book__c = pbId, IsActive__c=true, 
            Criteria__c=criteria,
            CriteriaStack__c = criteriaStack);
        if(saveNow) insert rule;
        return rule;

    }

    static Integer groupSize = 6;
    static void setupTicketItemRules()
    {
        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = j.Price_Book__c;

        String newGuid = StringUtility.newGuid();
      
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');       
        RecordType qtRecordType = AlpineTestHelper.GetRecordType('Job__c');   

        string statusName = 'JobNoSyncStatus ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Job__c', 
            SObject_Record_Type__c=qtRecordType.DeveloperName, 
            Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);

        insert st;


        String ns = StringUtility.FXNamespace();


        

        List<Price_Book_Item__c> priceBookItems = AlpineTestHelper.CreatePriceBookItems(4* groupSize, priceBookId, 'Equipment');

        String criteria = ns + 'Status__c!=null';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"!=\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"null\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Status__c');
        Price_Book_Rule__c rule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true, Criteria__c=criteria, Applies_To__c='Ticket__c',
            CriteriaQueryFields__c = ns + 'Status__c',
            CriteriaStack__c=criteriaStack);        
        insert rule;

        List<Price_Book_Rule_Action__c> ruleActions = new List<Price_Book_Rule_Action__c>();

        for(Integer i=0; i<groupSize; i++)
        {
            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i).Id, 
                IsActive__c = true, 
                Type__c='Required'));

            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i+groupSize).Id, 
                IsActive__c = true, 
                Type__c='Recommended'));

            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i+2*groupSize).Id, 
                IsActive__c = true, 
                Type__c='Disallowed'));
        }
       


        Price_Book_Item__c rootItem = priceBookItems.get(0);

        Integer index = groupSize * 3 + 1;

        criteria = String.format('{0}Ticket__r.{0}Status__c!=null', new String[]{ns});
        criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"!=\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"null\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Ticket__r.' + ns + 'Status__c');

        Price_Book_Rule__c quoteItemRule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true, Criteria__c=criteria, 
            CriteriaStack__c = criteriaStack,
            Applies_To__c='Ticket__c', 
            Price_Book_Item__c=rootItem.Id);     

        insert quoteItemRule;


        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index).Id, 
                IsActive__c = true, 
                Type__c='Required'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index+1).Id, 
                IsActive__c = true, 
                Type__c='Recommended'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index+2).Id, 
                IsActive__c = true, 
                Type__c='Disallowed'));

        insert ruleActions;

    }

    static testmethod void Ticket_AndRuleTrueTest()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        insert pbItems;

        String ns = StringUtility.FXNamespace();

        String criteria = 'Job__r.Sync__c == true && Sync__c == true';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"Job__r.Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"true\\"}}","{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"true\\"}}","&&"]';
        criteriaStack = criteriaStack.replace('Job__r', ns + 'Job__r').replace('Sync__c', ns+ 'Sync__c');

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);

        Price_Book_Item__c pbItem = pbItems.get(0);

        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItem.Id, 
                IsActive__c = true, 
                Type__c='Recommended');
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbItem.Id];
        System.assertEquals(1, tktItems.size());
    }

    static testmethod void Ticket_AndRuleFalseTest()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        insert pbItems;

        String ns = StringUtility.FXNamespace();

        String criteria = 'Job__r.Sync__c == false && Sync__c == true';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"Job__r.Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"false\\"}}","{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"true\\"}}","&&"]';
        criteriaStack = criteriaStack.replace('Job__r', ns + 'Job__r').replace('Sync__c', ns+ 'Sync__c');

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);

        Price_Book_Item__c pbItem = pbItems.get(0);

        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItem.Id, 
                IsActive__c = true, 
                Type__c='Recommended');
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbItem.Id];
        System.assertEquals(0, tktItems.size());
    }


    static testmethod void Ticket_OrRuleTrueTest()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        insert pbItems;

        String ns = StringUtility.FXNamespace();
        String criteria = 'Job__r.Sync__c == true || Sync__c == true';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"Job__r.Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"true\\"}}","{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"false\\"}}","||"]';
        criteriaStack = criteriaStack.replace('Job__r', ns + 'Job__r').replace('Sync__c', ns+ 'Sync__c');

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);

        Price_Book_Item__c pbItem = pbItems.get(0);

        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItem.Id, 
                IsActive__c = true, 
                Type__c='Recommended');
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbItem.Id];
        System.assertEquals(1, tktItems.size());
    }

    static testmethod void Ticket_OrRuleFalseTest()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        insert pbItems;

        String ns = StringUtility.FXNamespace();
        String criteria = 'Job__r.Sync__c == true || Sync__c == true';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"Job__r.Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"false\\"}}","{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"Sync__c\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"false\\"}}","||"]';
        criteriaStack = criteriaStack.replace('Job__r', ns + 'Job__r').replace('Sync__c', ns+ 'Sync__c');

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);

        Price_Book_Item__c pbItem = pbItems.get(0);

        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItem.Id, 
                IsActive__c = true, 
                Type__c='Recommended');
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbItem.Id];
        System.assertEquals(0, tktItems.size());
    }

    static testmethod void TicketItemRule_Test()
    {
        setupTicketItemRules();
        Test.startTest();
        Job__c j = [SELECT Id, Price_Book__c, Price_Book__r.Name FROM Job__c LIMIT 1];        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);

        Status__c noSyncStatus = [SELECT Id FROM Status__c WHERE Sync__c=false AND SObject__c='Ticket__c' LIMIT 1];

        tkt.Status__c = noSyncStatus.Id;
        insert tkt;
        Test.stopTest();


        List<Ticket_Item__c> childItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c = :tkt.Id AND Parent_Ticket_Item__c!=null];
        System.assert(childItems.size()==2, 'should have ' + 2 + ' child items, instead have ' + childItems.size());
        
        List<Ticket_Item__c> items = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c = :tkt.Id];

        Integer expectedResult = groupSize * 2 + 2; //required + recommended + ItemRule child items

        System.assert(items.size()==expectedResult, 'should have ' + expectedResult + ' auto added items, instead have ' + items.size());

    }
    static testmethod void TicketRulesOnly_JobUpdate_RequiredItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job,5,true);
          
        Ticket__c syncTkt = tkts[0];
        Ticket__c noSyncTkt = tkts[1];
        
        String newGuid = 'E9E05272-5AD1-BD9A-D351-9194DCC7AB27';
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  
        
        string jobStatusName = 'Job Status ' + newGuid;
        Status__c jobStatus = new Status__c(Name = jobStatusName , SObject__c='Job__c', Sync__c=true, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert jobStatus ;
        

        string syncStatusName = 'Status Sync ' + newGuid;
        Status__c syncStatus = new Status__c(Name = syncStatusName , SObject__c='Ticket__c', Sync__c=true, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert syncStatus ;
        
        string noSyncStatusName = 'Status NOT Sync ' + newGuid;
        Status__c noSyncStatus = new Status__c(Name = noSyncStatusName , SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert noSyncStatus ;
        
        syncTkt.Status__c = syncStatus.Id;
        noSyncTkt.Status__c = noSyncStatus.Id;
        
        update syncTkt;
        update noSyncTkt;        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);

        Price_Book_Item__c quoteRequiredItem = pbItems.get(1);
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        //String criteria = ns + 'Job__r.' + ns + 'Status__r.Name ==\'' + jobStatusName  + '\'';    
      

       
        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Job__r.[ns]Status__r.Name', jobStatusName, '==');
      

       
        //Price_Book_Rule__c rule2 = new Price_Book_Rule__c(Price_Book__c = priceBookId, IsActive__c=true, Criteria__c=criteria, Applies_To__c='Quote__c');
        //insert rule2;

        Price_Book_Rule__c dbRule = [SELECT Id, Applies_To__c FROM Price_Book_Rule__c WHERE Id=:rule.Id];
        System.assert(dbRule.Applies_To__c == 'Ticket__c', 'Applies_To__c should be Ticket__c');
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        //Price_Book_Rule_Action__c action2 = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule2.Id, Price_Book_Item__c = quoteRequiredItem.Id, IsActive__c = true, Type__c='Required');
        //insert action2;

        job.Status__c = jobStatus.Id;
        update job;
        Test.stopTest();        
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:noSyncTkt.Id AND Rule_Required_Item__c=true];
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktItem = tktItems.get(0);        
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');        
        
        
    }

    static testmethod void JobUpdate_RequiredItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job,5,true);
          
        Ticket__c syncTkt = tkts[0];
        Ticket__c noSyncTkt = tkts[1];
        
        String newGuid = 'E9E05272-5AD1-BD9A-D351-9194DCC7AB27';
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  
        
        string jobStatusName = 'Job Status E9E05272-5AD1-BD9A-D351-9194DCC7AB27';
        Status__c jobStatus = new Status__c(Name = jobStatusName , SObject__c='Job__c', Sync__c=true, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert jobStatus ;
        

        string syncStatusName = 'Status Sync E9E05272-5AD1-BD9A-D351-9194DCC7AB27';
        Status__c syncStatus = new Status__c(Name = syncStatusName , SObject__c='Ticket__c', Sync__c=true, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert syncStatus ;
        
        string noSyncStatusName = 'Status NOT Sync E9E05272-5AD1-BD9A-D351-9194DCC7AB27';
        Status__c noSyncStatus = new Status__c(Name = noSyncStatusName , SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert noSyncStatus ;
        
        syncTkt.Status__c = syncStatus.Id;
        noSyncTkt.Status__c = noSyncStatus.Id;
        
        update syncTkt;
        update noSyncTkt;        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();       
       
        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Job__r.[ns]Status__r.Name', jobStatusName, '==');
      


        Price_Book_Rule__c dbRule = [SELECT Id, Applies_To__c FROM Price_Book_Rule__c WHERE Id=:rule.Id];
        System.assert(dbRule.Applies_To__c == 'Ticket__c', 'Applies_To__c should be Ticket__c');
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        job.Status__c = jobStatus.Id;
        update job;
        Test.stopTest();  
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:noSyncTkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktItem = tktItems.get(0);        
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');        
        
        
    }
    
    static testmethod void TicketUpdate_RequiredItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
       // String criteria = ns + 'Status__r.Name ==\'' + statusName  + '\'';      

        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');
      


        Price_Book_Rule__c dbRule = [SELECT CriteriaQueryFields__c FROM Price_Book_Rule__c WHERE Id=:rule.Id];
        System.assert(dbRule.CriteriaQueryFields__c == ns + 'Status__r.Name', 
            'CriteriaQueryFields should be ' + ns + 'Status__r.Name, instead of ' + dbRule.CriteriaQueryFields__c);
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        tkt.Status__c = st.Id;
        update tkt;
        Test.stopTest();  
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktItem = tktItems.get(0);
        
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');
        
        
    }
    
    
    static testmethod void TicketUpdate_NewRuleOnRequiredItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
         
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(3, priceBookId , 'Equipment', true);  

        List<Price_Book_Item__c> dbItems = [SELECT Id, Parent_Price_Book_Item__c FROM Price_Book_Item__c WHERE Price_Book__c=:priceBookId];
        
        Price_Book_Item__c parent = dbItems.get(0);
        parent.Required_Item__c = true;
        dbItems.get(1).Parent_Price_Book_Item__c = parent.Id;
        Price_Book_Item__c child1 = dbItems.get(1);

        dbItems.get(2).Parent_Price_Book_Item__c = parent.Id;
        Price_Book_Item__c child2 = dbItems.get(2);

        update dbItems;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0); 

        
       
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        //String criteria = ns + 'Status__r.Name ==\'' + statusName  + '\'';
        
        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');      

        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = child1.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        tkt.Status__c = st.Id;
        update tkt;

        Test.stopTest();  
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:child1.Id];
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktItem = tktItems.get(0);
        
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');
        
        
    }

    static testmethod void GetDisallowedPriceBookItems_Test()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        tkt.Status__c = st.Id;
        update tkt;
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
       
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        //String criteria = ns + 'Status__r.Name ==\'' + statusName  + '\'';     
        
        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');
      

        Price_Book_Rule_Action__c action1 = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbItems.get(0).Id, IsActive__c = true, Type__c='Disallowed');
        insert action1;
        Price_Book_Rule_Action__c action2 = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbItems.get(1).Id, IsActive__c = true, Type__c='Disallowed');
        insert action2;
        Price_Book_Rule_Action__c action3= new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbItems.get(2).Id, IsActive__c = true, Type__c='Disallowed');
        insert action3;        
      
        
        
        Set<Id> tktIds = new Set<Id>();
        tktIds.add(tkt.Id);
        List<Id> pbIds =  RuleEngineCore.GetDisallowedPriceBookItems(tkt.Id);

        Test.stopTest();  

        Set<Id> disallowedItems = new Set<Id>();
        disallowedItems.addAll(pbIds);
        System.debug('*********************************pbIds ='+ pbIds );
        System.debug('*********************************item 1 ='+ pbItems.get(0).Id );
          System.assert(disallowedItems.size()==3, 'Should have three disallowed items.' + disallowedItems.size());
        
        System.assert(disallowedItems.contains(pbItems.get(0).Id) || disallowedItems.contains(String.valueOf(pbItems.get(0).Id)));
        System.assert(disallowedItems.contains(pbItems.get(1).Id)|| disallowedItems.contains(String.valueOf(pbItems.get(1).Id)));
        System.assert(disallowedItems.contains(pbItems.get(2).Id)|| disallowedItems.contains(String.valueOf(pbItems.get(2).Id)));
        
        
    }
    
    static testmethod void TicketUpdate_ApplyRequiredRuleActionForExistingTicketItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
        Price_Book_Item__c requiredItem = pbItems.get(0);

        Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = requiredItem.Id);
        insert ti;
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
       

        Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');
      

        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        tkt.Status__c = st.Id;
        update tkt;
        Test.stopTest();  
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktItem = tktItems.get(0);
        
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true anytime RuleAction is applied');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true anytime Required RuleActon is applied');
        
        
    }
    
    static testmethod void TicketUpdate_SkipRecommendedItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);   
        
        Price_Book_Item__c pbi = pbItems.get(0);
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
          Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');
      
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbi.Id, IsActive__c = true, Type__c='Recommended');
        insert action;
        
        tkt.Status__c = st.Id;
        update tkt;
        Test.stopTest();  
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbi.Id];
        System.assert(0==tktItems.size(), 'Ticket Update should skip Recommended (optional) item(s).');
        
        
        
        //System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        //System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');
        
        
    }
    
    static testmethod void TicketUpdate_DisallowedItems()
    {
        Test.startTest();  
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c; 
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);           
        Price_Book_Item__c pbi = pbItems.get(0);
        pbi.Required_Item__c = true;
        insert pbItems;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbi.Id];
        System.assert(1==tktItems.size(), 'Should have one PBRequired Item.');
        Ticket_Item__c tktItem = tktItems.get(0);
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');
        
        Ticket__c dbTkt = [SELECT Id, Status__r.Name FROM Ticket__c WHERE Id=:tkt.Id];
        
        
        String newGuid = StringUtility.newGuid();
         
        RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');  

        string statusName = 'Status ' + newGuid;
        Status__c st = new Status__c(Name = statusName, SObject__c='Ticket__c', Sync__c=false, Initial_Status_Console__c =false,  RecordTypeId=statusRecordType.Id);
        insert st;
        
        
           
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
         Price_Book_Rule__c rule = GetRule(priceBookId, '[ns]Status__r.Name', statusName, '==');
      
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbi.Id, IsActive__c = true, Type__c='Disallowed');
        insert action;
        
        tkt.Status__c = st.Id;
        update tkt;
        Test.stopTest();  
        
        tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c  FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbi.Id];
        System.assert(0==tktItems.size(), 'Ticket Update should remove Item disalloed by ruleAction.');    
        

        
    }
    
    
    static testmethod void GetPriceBookRuleCriteriaFields_Test()
    {
        Test.startTest();  
        Set<Id> pricebookIds = new Set<Id>();
        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id pbId = job.Price_Book__c;
        
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, pbId, 'Equipment');


        pricebookIds.add(pbId);
        
        List<Price_Book_Rule__c> rules = new List<Price_Book_Rule__c>();
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        //Ticket field - Status__c
        String criteria = ns + 'Status__r.Name==\'In Progress\'';  
        Price_Book_Rule__c rule = GetRule(pbId, '[ns]Status__r.Name', 'In Progress', '==', true);
        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItems.get(0).Id, 
                IsActive__c = true, 
                Type__c='Required');



        
        criteria =  ns+ 'Customer_Survey_Satisfaction__c==\'OK\'';  
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"OK\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns+ 'Customer_Survey_Satisfaction__c');
        //rules.add(GetRule(pbId, criteria, criteriaStack));
        rule = GetRule(pbId, criteria, criteriaStack);
        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItems.get(1).Id, 
                IsActive__c = true, 
                Type__c='Required');
        
        criteria =  ns+ 'Customer_Survey_Performance__c==\'Excellent\'';                
        criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"Excellent\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns+ 'Customer_Survey_Performance__c');        
        rule = GetRule(pbId, criteria, criteriaStack);
        rule.IsActive__c = false;
        update rule;
        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItems.get(2).Id, 
                IsActive__c = true, 
                Type__c='Required');

        criteria =  ns+ 'Job__r.' + ns + 'Office__r.Name==\'RuleEngineTestOffice\'';                
        rule = GetRule(pbId, '[ns]Job__r.[ns]Office__r.Name', 'RuleEngineTestOffice', '==', true);
        
        insert new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = pbItems.get(3).Id, 
                IsActive__c = true, 
                Type__c='Required');

        
        Test.stopTest();
                
        Map<String, Set<String>> fields = RuleEngineCore.GetPriceBookRuleCriteriaFields(priceBookIds);
        System.debug('all fields: ' + fields);
        Set<String> tktFields = fields.get('tkt' + pbId);
        System.assert(tktFields.contains(ns + 'Status__c'), 'Ticket relation field should have format __c instead of __r');
        System.assert(tktFields.contains(ns + 'Customer_Survey_Satisfaction__c'), 'Ticket field Customer_Survey_Satisfaction__c is missing');
        System.assert(!tktFields.contains(ns+ 'Customer_Survey_Performance__c'), 'Inactive rule for Customer_Survey_Performance__c should be excluded');
        
        Set<String> jobFields = fields.get('job' + pbId);
        
        System.assert(jobFields!=null && jobFields.contains(ns + 'Office__c'), 'Office__c misssing for Job__r.Office__r.Name');
        
    }

    
    static testmethod void InsertDisallowedTicketItem()
    {
        Test.startTest();    
        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
       
        
        Price_Book_Item__c disallowedItem = pbItems.get(0);
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        String criteria = ns + 'Job__c==\'' + job.Id + '\'';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns+ 'Job__c').replace('[value]', job.Id);
      

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);    
      
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = disallowedItem.Id, IsActive__c = true, Type__c='Disallowed');
        insert action;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);   
        
        Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = disallowedItem.Id);
        try
        {
            insert ti;
            System.assert(false, 'Insert should fail by the disallowed rule');
        }
        catch(DMLException e)
        {
            String msg = '';
            String sep ='';
            for (Integer i = 0; i < e.getNumDml(); i++) 
            {
                System.debug(e.getDmlMessage(i)); 
                msg += sep + e.getDmlMessage(i);
                sep =  ' | ';
            }            
            
            System.debug(msg);
            System.assert(msg.contains('Item is disallowed by Rule'), msg);
        }
          
        Test.stopTest();
      
    }
    
    
    static testmethod void RuleEngine_Activate_Test()
    {
        Test.startTest();
        RuleEngineCore.Suspend();
        System.assert(RuleEngineCore.IsSuspended());
        
        RuleEngineCore.Activate();
        System.assert(RuleEngineCore.IsActive());
        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        pbItems.get(0).Required_Item__c  = true;
        insert pbItems;
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
    }
    
    static testmethod void RuleEngine_Suspend_Test()
    {
        Test.startTest();
        RuleEngineCore.Suspend();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        pbItems.get(0).Required_Item__c  = true;
        insert pbItems;
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(0, tktItems.size());
    }
    
    static testmethod void CreateOneTicket_TestPriceBookRequiredItem()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        pbItems.get(0).Required_Item__c  = true;
        insert pbItems;
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
    }
    



    static testmethod void PriceBookRequired_NoChildItemAlone()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);


        Price_Book_Item__c parent = pbItems.get(0);
        Price_Book_Item__c child = pbItems.get(1);
        child.Required_Item__c = true;
        child.Parent_Price_Book_Item__c = parent.Id;
        update child;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c, Rule_Required_Item__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:child.Id];
        System.assert(0 == tktItems.size(), 'Child PriceBookItem could not be added to Ticket without the parent item');     

    }

    static testmethod void RuleAction_ChildItemAloneNotAllow()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
        Price_Book_Item__c parent = pbItems.get(0);
        Price_Book_Item__c child = pbItems.get(1);
        child.Parent_Price_Book_Item__c = parent.Id;
        update child;     

        String ns = UtilityGetNamespace.CurrentNamespace();
        String criteria = ns + 'Job__c==\'' + job.Id + '\''; 
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns+ 'Job__c').replace('[value]', job.Id);
      

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);  
        
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = child.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:child.Id];
        
        System.assert(0==tktItems.size(), 'RuleAction on child item should not be added to ticket if its parent is not on the ticket');       
      
    }


    static testmethod void CreateTickets_TestPriceBookRequiredItem()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', false);
        pbItems.get(0).Required_Item__c  = true;
        insert pbItems;
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,5,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        System.assertEquals(1, tktItems.size());
    }
    
    static testmethod void CreateTicket_TestRequiredRules()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
       
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        String criteria = ns + 'Job__c==\'' + job.Id + '\'';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Job__c').replace('[value]', job.Id);

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c tktitem = tktItems.get(0);
        System.assert(tktItem.Auto_Added__c == true, 'Auto_Added should be true');
        System.assert(tktItem.Rule_Required_Item__c == true, 'Rule_Required_Item__c should be true');
          
        
        System.debug(tktItems.get(0));
        
    }
    
    static testmethod void CreateTicket_ParentChildPriceBookItems()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
       
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        for(Integer i=1; i<pbItems.size(); i++)
        {
            pbItems.get(i).Parent_Price_Book_Item__c = requiredItem.Id;
        }
        update pbItems;
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        String criteria = ns + 'Job__c==\'' + job.Id + '\'';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Job__c').replace('[value]', job.Id);

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);
        
      
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c parent = tktItems.get(0);
        
        
         List<Ticket_Item__c> childItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Parent_Ticket_Item__c =:parent.Id AND Rule_Required_Item__c=false AND Auto_Added__c=false];
        
        System.assertEquals(4, childItems.size());       
        
      
    }
    
    static testmethod void CreateTicket_ChildPriceBookItemDisallowed()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
       
        
        Price_Book_Item__c requiredItem = pbItems.get(0);
        for(Integer i=1; i<pbItems.size(); i++)
        {
            pbItems.get(i).Parent_Price_Book_Item__c = requiredItem.Id;
        }
        update pbItems;
        
        
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        String criteria = ns + 'Job__c==\'' + job.Id + '\'';
        
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Job__c').replace('[value]', job.Id);

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);
        
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        Id disallowedItemId = pbItems.get(1).Id;
        Price_Book_Rule_Action__c disallowed = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = disallowedItemId , IsActive__c = true, Type__c='Disallowed');
        insert disallowed;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:requiredItem.Id];
        
        System.assertEquals(1, tktItems.size());
        
        Ticket_Item__c parent = tktItems.get(0);
        
        
         List<Ticket_Item__c> allItems= [SELECT Id, Price_Book_Item__c, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id];
         Set<Id> pbiOnTkt = new Set<Id>();
         for(Ticket_Item__c ti : allItems)
         {
             pbiOnTkt.add(ti.Price_Book_Item__c);
         }       
        
        System.assert(!pbiOnTkt.contains(disallowedItemId ), 'Disallowed child item(s) should not be on ticket');       
        
      
    }

    static testmethod void CreateTicket_ChildPriceBookItemRequired()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Id priceBookId = job.Price_Book__c;
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(3, priceBookId , 'Equipment', true);
       
        
         Price_Book_Item__c requiredItem = pbItems.get(0);
        for(Integer i=1; i<pbItems.size(); i++)
        {
            pbItems.get(i).Parent_Price_Book_Item__c = requiredItem.Id;
            pbItems.get(i).Description_Override__c = 'Child item ' + i;
        }
        update pbItems;
        String ns = UtilityGetNamespace.CurrentNamespace();
        
        String criteria = ns + 'Job__c=\'' + job.Id + '\'';
        
       String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Literal\\",\\"value\\":\\"[value]\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Job__c').replace('[value]', job.Id);

        Price_Book_Rule__c rule = GetRule(priceBookId, criteria, criteriaStack);
        
        Price_Book_Rule_Action__c action = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = requiredItem.Id, IsActive__c = true, Type__c='Required');
        insert action;
        
        Id pbiChildRequired = pbItems.get(1).Id;
        Price_Book_Rule_Action__c childRequired = new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, Price_Book_Item__c = pbiChildRequired , IsActive__c = true, Type__c='Required');
        insert childRequired;
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job,1,true).get(0);        
        Test.stopTest();
        List<Ticket_Item__c> tktItems = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:pbiChildRequired];
        
        System.assertEquals(1, tktItems.size());    
        System.debug('tktItems.get(0).Auto_Added__c=' + tktItems.get(0).Auto_Added__c);
        System.assert(tktItems.get(0).Auto_Added__c == true, 'RuleAction on Child item should set Auto_Added__c=true');      
        System.assert(tktItems.get(0).Rule_Required_Item__c == true, 'RuleAction on Child item should set Rule_Required_Item__c=true');   

        Id childItemId = pbItems.get(2).Id;
        List<Ticket_Item__c> tktItems2 = [SELECT Id, Rule_Required_Item__c, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Price_Book_Item__c =:childItemId];
        
        System.assertEquals(1, tktItems2.size());   
        System.assert(tktItems2.get(0).Auto_Added__c == false, 'Child item with no RuleAction should have Auto_Added__c=false');       
        System.assert(tktItems2.get(0).Rule_Required_Item__c == false, 'Child item with no RuleAction should have Rule_Required_Item__c=false');       
    }
    
}