src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Applies_To__c.field-meta.xml
<CustomField>
    <fullName>Applies_To__c</fullName>
    <label>Applies To</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket__c</fullName>
                <default>true</default>
                <label>Ticket__c</label>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaQueryFields__c.field-meta.xml
<CustomField>
    <fullName>CriteriaQueryFields__c</fullName>
    <description>DO NOT CHANGED</description>
    <label>CriteriaQueryFields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaStack__c.field-meta.xml
<CustomField>
    <fullName>CriteriaStack__c</fullName>
    <description>Preprocessed Criteria - DO NOT MODIFIED</description>
    <inlineHelpText>Preprocessed Criteria - DO NOT MODIFIED</inlineHelpText>
    <label>CriteriaStack</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/PriceBookRuleHandler.cls
public class PriceBookRuleHandler 
{
    public static void RefreshQueryFields(List<Price_Book_Rule__c> rules)
    {
        String ns = StringUtility.FXNamespace().replace('__', '.');
        for(Price_Book_Rule__c r : rules)
        {
            if(String.isBlank(r.CriteriaStack__c)) continue;
            Set<String> fields = new Set<String>();
            
            List<String> exps = (List<String>)JSON.deserialize(r.CriteriaStack__c, Type.forName('List<String>'));
            for(String s : exps)
            {
                if(s == '&&' || s=='||') continue;
                RuleExpression re = (RuleExpression)JSON.deserialize(s, Type.forName(ns + 'RuleExpression'));
                fields.addAll(re.GetQueryFields());
            }
            r.CriteriaQueryFields__c = String.join(new List<String>(fields), ',');
        }   
    }
    
    public static void ValidatePriceBookRules(List<Price_Book_Rule__c> rules)
    {
        for(Price_Book_Rule__c r: rules)
        {
            IsRuleValid(r);
        }
    }
    public static Boolean IsRuleValid(Price_Book_Rule__c r)
    {        
        String targetStr = r.Applies_To__c; 
        String[] targets = String.isBlank(targetStr)? (new String[]{'Ticket__c'}) : targetStr.split(';');
        String msg = '';
        String sep = '';
        for(String target : targets)
        {
            String contextStr = String.isBlank(r.Price_Book_Item__c)? target : target.replace('__c', '_Item__c');
            String errorMsg = IsRuleCriteriaValid(r.Criteria__c, contextStr);
            if(!String.isBlank(errorMsg))
            {
                 msg += sep + errorMsg;
                 sep = '; ';
            }           
        }

       if(!String.isBlank(msg))
       {
           r.addError(msg);
           return false;
       }
       return true;
    }
    
    public static String IsRuleCriteriaValid(String criteria, String objContext)
    {
        //String whereClause = ParseRuleCriterion(criteria);

        String whereClause = criteria.trim(); //criteria.replace('||', '&&').split()

        if(whereClause.containsIgnoreCase('contains') 
            || whereClause.containsIgnoreCase('includes')
            || whereClause.containsIgnoreCase('excludes'))
        {
            /*
            String str = 'contains(Job__r.Ticket__r.multiTest__c, \'testStr\')';
            String funcreg = '(?i)(contains|includes|excludes)[ \t]*[(][ \t]*(([\\w]+__r[\\.])*([\\w]+))[ \t]*,[ \t]*[\']((.)*)[\'][ \t]*[)][ \t]*';
            Pattern funcPattern = Pattern.compile(funcreg);
            Matcher fm = funcPattern.matcher(str);
            if(fm.matches())
            {
                System.debug(fm.groupCount());
                for(Integer i=0; i<fm.groupCount(); i++)
                System.debug('group ' + i + ' : ' + fm.group(i));
            }

            // contains(Job__r.Ticket__r.multiTest__c, \'testStr\')
            //group 0 : contains(Job__r.Ticket__r.multiTest__c, 'testStr')
            //group 1 : contains
            //group 2 : Job__r.Ticket__r.multiTest__c
            //group 3 : Ticket__r.
            //group 4 : multiTest__c
            //group 5 : testStr


            */

            String funcreg = '(?i)(contains|includes|excludes)[ \t]*[(][ \t]*(([\\w]+__r[\\.])*([\\w]+))[ \t]*,[ \t]*[\']((.)*)[\'][ \t]*[)][ \t]*';
          
            Pattern funcPattern = Pattern.compile(funcreg);

            String[] items = whereClause.replace('||', '&&').split('&&');
            Map<String, String> matches = new Map<String, String>();

            for(String fStr : items)
            {
                if(!fStr.containsIgnoreCase('contains')  
                    && !fStr.containsIgnoreCase('includes')
                    && !fStr.containsIgnoreCase('excludes')) continue;
                
                Matcher fm = funcPattern.matcher(fStr);
                
                while(fm.find())
                {
                    String funcStr = fm.group(0);
                    String func = fm.group(1).toLowercase();
                    String fName = fm.group(2);
                    String vStr = fm.group(5);
                    String soqlStr = '';
                    if(func == 'contains')
                    {
                        soqlStr = ' ' + fName + ' LIKE \'%' + vStr + '%\' ';
                    }
                    else if(func == 'includes')
                    {
                        soqlStr = ' ' + fName + ' includes (\'' + vStr + '\') ';
                    }
                    else if(func == 'excludes')
                    {
                        soqlStr = ' ' + fName + ' excludes (\'' + vStr + '\') ';
                    }
                    matches.put(funcStr, soqlStr);               
                }    
            }
            System.debug(JSON.serializePretty(matches));
            for(String k: matches.keySet())
            {
                 whereClause = whereClause.replace(k, matches.get(k));
            }

        }
                   
            //====START============================================================
            //soql doesn't allow Date/Datetime in quote ('' or ""), but formulaForce js requires them in quote
            //this hack is to remove quotes for criteria validation using soql

        String s = '\'[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z)?\'';
        Pattern p= Pattern.compile(s);
        Matcher m = p.matcher(whereClause);
        List<String> dateTimeStrs = new List<String>();
        while(m.find())
        {  
            dateTimeStrs.add(m.group()); 
        }
        for(String dt : dateTimeStrs)
        {
            whereClause = whereClause.replace(dt, dt.subString(1, dt.length() - 1));
        }
        
        //====END ==============================================================

        whereClause = whereClause.replace('==', '=').replace('<>', '!=').replace('&&', ' AND ').replace('||', ' OR ').trim();


        String fakeId = StringUtility.newGuid();
        
        String ns = StringUtility.FXNamespace();
        if(!String.isBlank(ns) && !objContext.startsWithIgnoreCase(ns))
        {
            objContext = ns + objContext;
        }

        String soql = String.format('SELECT Id FROM {0} WHERE Id=:fakeId AND ({1}) LIMIT 1', new String[]{objContext,  whereClause});
        System.debug('soql=' + soql);
        try
        {
            Database.query(soql);
            return null;
        }
        catch(Exception ex)
        {
            return ex.getMessage();
        }
    }
    
    public static String ParseRuleCriterion(String criterion)
    {   
        String str = criterion.trim().replace('==', '=').replace('<>', '!=').replace('&&', ' AND ').replace('||', ' OR ');
        if(str.startsWith('ISPICKVAL'))
        {
            //Pattern p = Pattern.compile('(?i)^ISPICKVAL\\s*[(]\\s*(\\w+)\\s*,\\s*[\'\"](.*?)[\'\\"]\\s*[)]');            
           
            Pattern p = Pattern.compile('(?i)^ISPICKVAL\\s*[(]\\s*(\\w+([.]\\w+)*)+\\s*,\\s*[\'\"](.*?)[\'\\"]\\s*[)]');
            
            Matcher pm = p.matcher(str);
            if(pm.matches())
            {      
               str = pm.group(1) + '=\'' + pm.group(3) + '\'';
            }
                   
        }

        return str;
    }
    
    public static String SetDefaultValueForAppliesTo()
    {
        List<Price_Book_Rule__c> rulesToUpdate = new List<Price_Book_Rule__c>();
        for(List<Price_Book_Rule__c> rules : [SELECT Id, Applies_To__c FROM Price_Book_Rule__c WHERE IsDeleted=false AND Applies_To__c=null])
        {
            for(Price_Book_Rule__c r: rules)
            {
                r.Applies_To__c = 'Ticket__c';
                rulesToUpdate.add(r);
            }
        }
        
        Database.SaveResult[] res = Database.update(rulesToUpdate, false);

        Integer successCount=0;
        Set<String> errors = new Set<String>();
        for(Database.SaveResult sr : res) 
        {          
            if (sr.isSuccess())
            {
                ++successCount;
            }
            else
            {               
                for(Database.Error err : sr.getErrors()) 
                {
                    errors.add(err.getMessage());
                }
            }
        }
        String errorMsg = errors.isEmpty()? '': 'ERROR:<br/> ' + String.join(new List<String>(errors), '<br/>');

        String msg = String.format('{0} out of {1} Price_Book_Rule__c updated (setting Applies_To__c to Ticket__c). {2}', 
            new String[]{String.valueOf(successCount), String.valueOf(res.size()), errorMsg});
        return msg; 
    }
}