src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Category used to classify the job.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job</fullName>
                <default>true</default>
                <label>Job</label>
            </value>
            <value>
                <fullName>Deal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the job was added in FieldFX Mobile. This checkbox is selected automatically for all jobs added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <inlineHelpText>Identifying number assigned to the job.</inlineHelpText>
    <label>Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Quote__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/objects/Status__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Category used to classify the ticket.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket</fullName>
                <default>true</default>
                <label>Ticket</label>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Ticket__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the ticket was added in FieldFX Mobile. This checkbox is selected automatically for all tickets added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the ticket.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/QuoteExtension.cls
public with sharing class QuoteExtension 
{
    private ApexPages.StandardController controller;
    private final string prefix;
    private final string typeName;
    public sObject srecord { get; set; } 
    
    Map<String, String> JobRecordTypes {get;set;}   
    public static Boolean HasQuoteV1
    {
        get
        {
            InitQuoteV1Info();
            return HasQuoteV1Internal;
        }
    }
    public static String QuoteV1FieldName
    {
        get
        {    
            InitQuoteV1Info();      
            return QuoteV1FieldNameInternal;
        }
    }
    static String QuoteV1FieldNameInternal = null;
    static Boolean HasQuoteV1Internal = null;
    static void InitQuoteV1Info()
    {
        if(String.isBlank(QuoteV1FieldNameInternal))
        { 
            QuoteV1FieldNameInternal = StringUtility.FXNamespace().toLowercase() + 'quote__c';
            HasQuoteV1Internal = Job__c.sObjectType.getDescribe().fields.getMap().keySet().contains('quote__c'); 
        }
    }
  
    public QuoteExtension(ApexPages.StandardController controller) 
    {     
       this(controller.getId());
       this.controller = controller;
       srecord = controller.getRecord();
       Init();
    }
    
    void Init()
    {
          Ticket__c t= (Ticket__c)srecord;
          TktEntity  = [SELECT Job__c, Category__c FROM Ticket__c WHERE Id =: t.Id LIMIT 1];
          isQuote  = TktEntity.Category__c == 'Quote';
          
          JobRecordTypes = new Map<String, String>();

            List<RecordTypeInfo> infos = Job__c.sObjectType.getDescribe().getRecordTypeInfos();
            for(RecordTypeInfo i : infos)
            {
                //// Ignore the Master Record Type, whose Id is always '012000000000000AAA'. We check the Id because Name can change depending on the user's language.
                if(!i.isAvailable() || String.valueOf(i.getRecordTypeId()) == '012000000000000AAA') continue;
                JobRecordTypes.put(i.RecordTypeId, i.Name);
            }            
            
    }
    // for test purposes
    public QuoteExtension(Id controllerId, sobject record)
    {
        this(controllerId);
        srecord = record;
        Init();
    }
    
    public QuoteExtension(Id controllerId) 
    {
       this.typeName = UtilityGetTypeNameFromId.CurrentTypeName(controllerId);
       this.prefix = UtilityGetNamespace.CurrentNamespace();
    }
    
    Ticket__c TktEntity { get; set; }


    List<String> GetJobFields() {
        List<String> fields = new List<String>();

        Map<string, SObjectField> fieldMap = Schema.sObjectType.Job__c.fields.getMap();
        for(String f: fieldMap.keySet())
        {       
            DescribeFieldResult res = fieldMap.get(f).getDescribe();
            if(!res.isAccessible() || !res.isUpdateable()) continue;
            fields.add(f);
        }

        return fields;
    }

    String GetJobFieldsAsString() {
        String sep = '';
        String soql = '';
        List<String> fields = GetJobFields();
        for(String f: fields)
        {          
            soql += sep + f;
            sep = ',';
        }

        return soql;
    }

    Job__c JobEntity
    {
        get
        {
            if(jobEntityLocal == null && TktEntity != null)
            {              
                String soql = 'SELECT ' + GetJobFieldsAsString() + ' FROM Job__c where Id = \'' + TktEntity.Job__c + '\'   LIMIT 1';
                jobEntityLocal = (Job__c)Database.query(soql);
            }
            return jobEntityLocal;
        }
    }
    Job__c jobEntityLocal=null;

    public PageReference convertToJob() 
    {      
        if(!string.isBlank(HiddenTextValue))
        {
            string namespace = UtilityGetNamespace.CurrentNamespace();

            Job__c s = JobEntity;          

            Job__c job = s.clone(false, false, false, false);
            job.RecordTypeId = HiddenTextValue;
            if(QuoteExtension.HasQuoteV1 == true)
            {                
                job.put(QuoteExtension.QuoteV1FieldName, TktEntity.Id);
            }
            job.SyncID__c = StringUtility.newGuid();
            job.Tracking_Number__c = null;
            job.Created_in_Mobile__c = false;
            job.Category__c = 'Job';
            job.Status__c = null;
            job.Job_Number__c = null;
            
            insert job;

            redirectUrl = '/' + job.Id;

            shouldRedirect = true;                     
            return null;
        }
       
        return ApexPages.currentPage();       
    }
  
    public Component.Apex.Form getForm() 
    {   
        if(TktEntity == null || TktEntity.Category__c != 'Quote')
        {
            return null;
        } 
            
        Component.Apex.Form form = new Component.Apex.Form();

        form.id = 'quoteToJobForm';  

        Component.Apex.PageBlock pageBlock = new Component.Apex.PageBlock();
        pageBlock.id = 'pageBlock';
        pageBlock.title='';
        pageBlock.mode = 'maindetail';
        form.ChildComponents.Add(pageBlock);      
         
        
        string jobObjectType = this.prefix  + 'Job__c';

        
        if(JobRecordTypes.isEmpty())
        {
            return form;
        }

        Component.Apex.PageBlockButtons cmdButtons = new Component.Apex.PageBlockButtons();
        cmdButtons.location = 'top';

        Id objRecordTypeID = (Id)srecord.get('RecordTypeId');       
        
        
        for(String recordTypeId : JobRecordTypes.keySet())
        {        
          
            if(recordTypeId == JobEntity.RecordTypeId)  continue;
            Component.Apex.CommandButton command = new Component.Apex.CommandButton();

            command.onclick = 'jsSetNewJobRecordType("' + recordTypeId  + '");';

            command.oncomplete='refreshPage();';

            command.id = 'rt' + recordTypeId;
            command.value = JobRecordTypes.get(recordTypeId);
            command.title = 'Create ' + JobRecordTypes.get(recordTypeId);
            command.expressions.action = '{!convertToJob}';
            command.rendered = true;  
            Set<string> ops = new Set<string>();
            ops.add('redirectPanel');
            command.rerender = ops;

            cmdButtons.ChildComponents.Add(command); 

        }         

        pageBlock.ChildComponents.Add(cmdButtons);      

        Component.Apex.InputHidden hidden = new Component.Apex.InputHidden();
        hidden.id = 'recordTypeForNewJob';
        hidden.expressions.value = '{!HiddenTextValue}';
        form.ChildComponents.Add(hidden); 

        return form;
    }   
  

    public string HiddenTextValue { get; set; }

    public Boolean shouldRedirect {public get; private set;}
    public String redirectUrl {public get; private set;}
    public Boolean isQuote {public get; private set;}
    
}