src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the job was added in FieldFX Mobile. This checkbox is selected automatically for all jobs added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment used on the job is stored. When you select a warehouse, the ticket items added to tickets for the job will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Ticket.recordType-meta.xml
<RecordType>
    <fullName>Ticket</fullName>
    <active>true</active>
    <description>This record type is for Ticket statuses and their related configurations.</description>
    <label>Ticket</label>
</RecordType>

src/main/default/objects/Status_History__c/Status_History__c.object-meta.xml
<CustomObject>
    <label>Status History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status_History__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>User who made the status change</inlineHelpText>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Changed_Date__c</fullName>
    <inlineHelpText>Date and time the status change was made.</inlineHelpText>
    <label>Changed Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job that had its status changed.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/New_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>New status of the job/ticket.</inlineHelpText>
    <label>New Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>StatusHistory_NewStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Status_History__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Ticket that had its status changed.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Status History</relationshipLabel>
    <relationshipName>Status_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the ticket was added in FieldFX Mobile. This checkbox is selected automatically for all tickets added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the ticket.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment included on the ticket is stored. When you select a warehouse, ticket items will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will insert a UUID only if it is not already there</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/TicketBuilder.cls
public class TicketBuilder
{
    public static void OnBeforeInsert(List<Ticket__c> tkts)
    {
        Initialize(tkts);
    }

    public static void OnAfterInsert(List<Ticket__c> tkts)
    {
        List<Id> tktIds = new List<Id>(new Map<Id, Ticket__c>(tkts).keySet());
        TicketBuilder.CreateChecklistSteps(tktIds);        

        ChatterFeedManager.ProcessTicketFeedsOnTicketInsert(tkts);
        List<Status_History__c> shs = new List<Status_History__c>();
        List<Ticket__c> tktsForRuleEngine = new List<Ticket__c>();
        for(Ticket__c t : tkts) 
        {           
            if(t.Created_in_Mobile__c == true || t.Status__c == null) continue;
          
            Status_History__c sh = new Status_History__c();
            sh.Ticket__c = t.Id;
            sh.New_Status__c = t.Status__c;
            sh.Changed_Date__c = Datetime.now();
            sh.Changed_By__c = UserInfo.getUserId();
            shs.add(sh);            
        }
        if(!shs.isEmpty())
        {
            insert shs;
        }
     
        if(SObjectClonerUtility.CloningInProgress !=true)
        {
           RuleEngineConsole.OnTicketInsert(tkts);
        }
    }

    public static void OnBeforeUpdate(List<Ticket__c> tkts, Map<Id, Ticket__c> oldMap)
    {
        List<Ticket__c> items = new List<Ticket__c>();
        for(Ticket__c  t : tkts) 
        {
            if(oldMap.get(t.Id).Status__c != t.Status__c) items.add(t);     
        }
        if(!items.isEmpty()) 
        {
            SyncAssignmentManager.UpdateTicketSyncFlag(items);
        }
    }
    public static void OnTicketUpdate(List<Ticket__c> tkts, Map<Id, Ticket__c> oldMap, Boolean isBefore)
    {
        List<Ticket__c> items = new List<Ticket__c>();
        if(isBefore)
        {
            for(Ticket__c  t : tkts) 
            {
                if(oldMap.get(t.Id).Status__c != t.Status__c) items.add(t);     
            }
            if(!items.isEmpty()) 
            {
                SyncAssignmentManager.UpdateTicketSyncFlag(items);
            }
        }
        else
        {
            for(Ticket__c  t : tkts) 
            {
                if(oldMap.get(t.Id).Sync__c != t.Sync__c) items.add(t);     
            }
            if(!items.isEmpty()) 
            {
                ChatterFeedManager.ProcessTicketFeedsOnTicketUpdate(items);
            }
            RuleEngineConsole.OnTicketUpdate(tkts, oldMap);
        }
    }

    public static void Initialize(List<Ticket__c> tkts)
    {   

        PopulateTicketWarehouse(tkts);
        List<Status__c> statuses = [SELECT Id, SObject_Record_Type__c, Sync__c, Initial_Status_Console__c, Initial_Status_Mobile__c 
                                  FROM Status__c 
                                  WHERE SObject__c='Ticket__c'
                                  AND (Initial_Status_Console__c=true OR Initial_Status_Mobile__c=true)];

        Map<string, Status__c> defaultStatus = new Map<string, Status__c>();
        for (Status__c status: statuses)
        {
        if(status.Initial_Status_Console__c)
        {
          defaultStatus.put(string.valueOf(status.SObject_Record_Type__c)  + 'console', status);  
        }
        if(status.Initial_Status_Mobile__c)
        {
          defaultStatus.put(string.valueOf(status.SObject_Record_Type__c)  + 'mobile', status);  
        }
        }
        Map<Id, Status__c> mapStatuses = new Map<Id, Status__c>(statuses);

        Set<Id> recordTypeIDs = new Set<Id>();
        for(Ticket__c t: tkts)
        {
            recordTypeIDs.add(t.RecordTypeId);
        }
        Map<Id, RecordType> recordTypes = new Map<Id, RecordType>([SELECT Id, Developername FROM RecordType where IsActive=true AND  Id IN :recordTypeIDs]);

        for(Ticket__c t: tkts)
        {
            if(!StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, t.Tracking_Number__c))
        {        
            t.Tracking_Number__c = StringUtility.getTrackingNumber('T-');
        }
        if(t.SyncID__c == null)
        {
            t.SyncID__c = StringUtility.newGuid();
        }

        string key = null;
            if(t.Status__c==null && !string.isBlank(t.RecordTypeId) && recordTypes.containsKey(t.RecordTypeId))
            {      
                key = string.valueOf(recordTypes.get(t.RecordTypeId).DeveloperName) + (t.Created_in_Mobile__c?  'mobile' : 'console');

                if(defaultStatus.containsKey(key))
                {
                t.Status__c = defaultStatus.get(key).Id;                           
              }
            }

          if(t.Status__c == null)
          {
            key = null + (t.Created_in_Mobile__c ?  'mobile' : 'console');

            if(defaultStatus.containsKey(key))
            {
              t.Status__c = defaultStatus.get(key).Id;                           
            }
          }

            if(t.Status__c!=null && mapStatuses.containsKey(t.Status__c))
            {
                t.Sync__c = mapStatuses.get(t.Status__c).Sync__c;
            }           
        }    
    }   

    public static void PopulateTicketWarehouse(List<Ticket__c> tkts)
    {
        Set<Id> jobIds = new Set<Id>();
        for(Ticket__c t : tkts)
        {
            jobIds.add(t.Job__c);
        }
        Map<Id, Job__c> jobs = new Map<Id, Job__c>([SELECT Id, Warehouse__c FROM Job__c where Id IN :jobIds AND Warehouse__c!=null]);
        for(Ticket__c t : tkts)
        {
            if(String.isBlank(t.Warehouse__c) && jobs.containsKey(t.Job__c))
            {
                t.Warehouse__c = jobs.get(t.Job__c).Warehouse__c;
            }
        }
    }

    public static void CreateChecklistSteps(List<Id> tktIds) 
    {
        List<Ticket__c> tickets = [SELECT Id, RecordType.DeveloperName, RecordType.Name, Checklist_Name__c, 
            job__r.CustomerAccount__c, Job__r.Office__c,  Job__r.Segment__c, Job__r.RecordType.DeveloperName FROM Ticket__c WHERE Id IN :tktIds AND Created_in_Mobile__c=false AND Checklist_Name__c=null];

        if(tickets.isEmpty()) return;

        List<Checklist__c> checkLists = [SELECT Id, 
            Account__r.Id, 
            Name,
            Ticket_Type__c,
            Office__c, 
            Segment__c, 
            Job_Type__c 
           FROM Checklist__c
           ORDER BY WeightingFactor__c DESC];

        if(checkLists.isEmpty()) return;
                                                  
        List<Ticket_Checklist_Step__c> newItems = new List<Ticket_Checklist_Step__c>();

        Map<string, Checklist__c> mapChecklist = new Map<string, Checklist__c>();

        Map<Id, List<Checklist_Step__c>> checklistSteps = new Map<Id, List<Checklist_Step__c>>();

        List<Ticket__c>  tktsWithChange = new List<Ticket__c>();

        for(Ticket__c t : tickets) 
        {   
            Checklist__c cResult = null; 
            for(Checklist__c c: checkLists)
            {
                if((c.Account__c == NULL || c.Account__c == t.Job__r.CustomerAccount__c)
                    && (c.Office__c == NULL || c.Office__c == t.Job__r.Office__c)
                    && (c.Segment__c == NULL || c.Segment__c == t.Job__r.Segment__c)
                    && (c.Job_Type__c == NULL || c.Job_Type__c == t.Job__r.RecordType.DeveloperName)
                    && (c.Ticket_Type__c == NULL || c.Ticket_Type__c == t.RecordType.DeveloperName))
                {
                    cResult = c;
                    break;
                } 
            }   
            if(cResult == null) continue;

            if(!checklistSteps.containsKey(cResult.Id))
            {
                
                checklistSteps.put(cResult.Id, [SELECT Id, Name, Description__c, Required_Step__c, Screen__c, Sequence_Number__c
                                                    FROM Checklist_Step__c
                                                    WHERE Checklist__c = :cResult.Id]);
            }

            List<Checklist_Step__c> steps =  checklistSteps.get(cResult.Id);
            if(steps!=null && !steps.isEmpty()) 
            {
                for(Checklist_Step__c item: steps) 
                {
                    newItems.add(new Ticket_Checklist_Step__c(Ticket__c = t.Id, Name = item.Name, Description__c = item.Description__c, 
                            Screen__c = item.Screen__c, Sequence_Number__c = item.Sequence_Number__c, 
                            Required_Step__c = item.Required_Step__c));
                }                        

                t.Checklist_Name__c = cResult.Name;
                tktsWithChange.add(t);        
            }           
        }    
        if(!newItems.isEmpty())  insert newItems;
        if(!tktsWithChange.isEmpty())  update tktsWithChange;
    }
}