src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Log__c/Ticket_Log__c.object-meta.xml
<CustomObject>
    <label>Ticket Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Ticket Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Log__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Date and time the activity started.</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket for which the log entry was recorded.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/StringUtilityTest.cls
@isTest
private class StringUtilityTest{
    
    static testmethod void ValidIdTest()
    { 
      Account office = AlpineTestHelper.CreateOffice(StringUtility.newGuid());
      System.assert(StringUtility.IsValidId(office.Id));           
    }  

    static testmethod void InvalidIdTest()
    {     
      String s = StringUtility.newGuid();      
      System.assert(!StringUtility.IsValidId(s));      

      s = null;      
      System.assert(!StringUtility.IsValidId(s));

      s = '';      
      System.assert(!StringUtility.IsValidId(s));  

      s = 'InvalidString';      
      System.assert(!StringUtility.IsValidId(s)); 

      s = '2014 Price Book'; //15 characters     
      System.assert(!StringUtility.IsValidId(s));

      s = '2014 Price Book123'; //18 characters
      System.assert(!StringUtility.IsValidId(s));
    } 

    static testmethod void newGuidTest(){
     
       String guid = StringUtility.newGuid();
       System.debug('new Guid: ' + guid);  
       System.assert(StringUtility.isValidGuid(guid));      
    }  

     static testmethod void newJobTrackingNumberTest(){
            
        string trackingNumber = StringUtility.GetTrackingNumber('J-');  
        System.assert(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, trackingNumber)); 
    }
    
    static testmethod void newTicketTrackingNumberTest(){
            
        string trackingNumber = StringUtility.GetTrackingNumber('T-');        
        System.assert(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, trackingNumber));
    }
    
    static testmethod void uniqueTest(){
        Set<string> items = new Set<string>();
        for(Integer i=0; i<1000; i++){
            string tn =  StringUtility.GetTrackingNumber('T-');
            if(!items.isEmpty())
            {
                system.assertEquals(items.contains(tn), false);          
            }
            items.add(tn);
        }        
    }  

    static testmethod void SetSyncIdTest()
    {
      Test.startTest();
      Ticket__c tkt = AlpineTestHelper.CreateTickets(1, true).get(0);       
      Ticket_Log__c tktLog = new Ticket_Log__c(Ticket__c = tkt.Id, Start_Time__c = System.now());
      List<Ticket_Log__c> items = new List<Ticket_Log__c>();
      items.add(tktLog);
      StringUtility.setSyncId(items, StringUtility.FXNamespace() + 'SyncID__c');
      Test.stopTest();
      System.assert(StringUtility.isValidGuid(items.get(0).SyncID__c), 'Sync ID should have a valid guid value, instead of [' + items.get(0).SyncID__c + ']');
    }    
    
    static testmethod void validateTrackingNumberTest(){
          
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, 'J-A80-E99-1234'), true); 
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, 'J-A80-E99-12345'), true); 
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, 'J-A80-E99-123456'), false);           
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, 'T-A80-E99-1234'), false); 
          
          
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, 'T-995-47C-1234'), true); 
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, 'T-995-47C-12345'), true); 
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, 'T-995-47C-123456'), false);           
          System.assertEquals(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, 'J-995-47C-1234'), false); 
          
    }      
}