src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/eForm_Config__c/eForm_Config__c.object-meta.xml
<CustomObject>
    <label>eForm Config</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>eForm Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eForm Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/eForm_Config__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer for which the FX Form is available. If no customer is specified, the FX Form is available for every customer.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eForm Configs</relationshipLabel>
    <relationshipName>eForm_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/eForm_SObject__c.field-meta.xml
<CustomField>
    <fullName>eForm_SObject__c</fullName>
    <inlineHelpText>API name of the FX Form object. You must make an entry in this field.</inlineHelpText>
    <label>eForm SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/eForm_SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>eForm_SObject_Record_Type__c</fullName>
    <inlineHelpText>FX Form record type for which the FX Form is available. If no record type is specified, the FX Form is available for every record type.</inlineHelpText>
    <label>eForm SObject Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/eForm_SObject_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>eForm_SObject_Record_Type_Id__c</fullName>
    <inlineHelpText>Unique identifier for the record type specified in the "eForm SObject Record Type" field.</inlineHelpText>
    <label>eForm SObject Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Key_SObject__c.field-meta.xml
<CustomField>
    <fullName>Key_SObject__c</fullName>
    <inlineHelpText>API name of the object for which the FX Form is available. You must make an entry in this field.</inlineHelpText>
    <label>Key SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FX5__Job__c</fullName>
            </value>
            <value>
                <fullName>FX5__Ticket__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Key_SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Key_SObject_Record_Type__c</fullName>
    <inlineHelpText>Record type for which the FX Form is available. If no record type is specified, the FX Form is available for every record type.</inlineHelpText>
    <label>Key SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Key_SObject_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Key_SObject_Record_Type_Id__c</fullName>
    <inlineHelpText>Unique identifier for the record type specified in the "Key SObject Record Type" field.</inlineHelpText>
    <label>Key SObject Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office for which the FX Form is available. If no office is specified, the FX Form is available for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eForm Configs (Office)</relationshipLabel>
    <relationshipName>eForm_Configs1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Report_Template__c/Report_Template__c.object-meta.xml
<CustomObject>
    <description>This object describes a template for various reports, primarily for Mobile users.</description>
    <label>Report Template</label>
    <nameField>
        <label>Report Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Report_Template__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer for which the attached report is available. If no customer is specified, the report is available for every customer.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Report Templates</relationshipLabel>
    <relationshipName>Report_Templates2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Report_Template__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>Job type for which the attached report is available. If no job type is specified, the report is available for every job type.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Report_Template__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office for which the attached report is available. If no office is specified, the report is available for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Report Templates (Office)</relationshipLabel>
    <relationshipName>Report_Templates3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Report_Template__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <inlineHelpText>API name of the object for which the attached report is available. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Report_Template__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <inlineHelpText>Record type for which the attached report is available. If no record type is specified, the report is available for every record type.</inlineHelpText>
    <label>SObject Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Report_Template__c/fields/SObject_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type_Id__c</fullName>
    <inlineHelpText>Unique identifier for the record type specified in the "SObject Record Type" field.</inlineHelpText>
    <label>SObject Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Job__r.Office__r.Name</formula>
    <inlineHelpText>Office responsible for performing the work listed on the ticket.</inlineHelpText>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/RecordTypeIdMangler_Test.cls
@isTest
private class RecordTypeIdMangler_Test
{
   static testMethod void ReportTemplate_Test() 
   { 
     
       String namespace = UtilityGetNamespace.CurrentNamespace();

       Account acct = AlpineTestHelper.CreateAccount(StringUtility.newGuid());
       Account office = AlpineTestHelper.CreateOffice(StringUtility.newGuid());
       RecordType jobRecordType = AlpineTestHelper.GetRecordType(namespace + 'Job__c');
       RecordType tktRecordType = AlpineTestHelper.GetRecordType(namespace + 'Ticket__c');

       Report_Template__c rt = new Report_Template__c(Account__c=acct.Id, 
         	Job_Type__c=jobRecordType.DeveloperName, 
         	Office__c = office.Id, 
         	SObject__c = namespace + 'Ticket__c',
         	SObject_Record_Type__c = tktRecordType.DeveloperName);

        List<Report_Template__c> items = new List<Report_Template__c>();
        items.add(rt);

       RecordTypeIdMangler.PopulateRecordTypeId(items,  'SObject__c', 'SObject_Record_Type__c', 'SObject_Record_Type_Id__c');

       System.assertEquals(rt.SObject_Record_Type_Id__c, tktRecordType.Id);  

       rt.SObject_Record_Type_Id__c = null;
       insert rt;

       Report_Template__c dbItem = [SELECT SObject_Record_Type_Id__c FROM Report_Template__c WHERE Office__c = : office.Id LIMIT 1];
        System.assertEquals(dbItem.SObject_Record_Type_Id__c, tktRecordType.Id);  
   }


   static testmethod void eFormConfig_Test()
    {
       
        Test.StartTest();
        
        eForm_Config__c newItem = new eForm_Config__c();

        newItem.Account__c = AlpineTestHelper.CreateAccount(StringUtility.newGuid()).Id;
        newItem.Office__c =  AlpineTestHelper.CreateOffice(StringUtility.newGuid()).Id;
       
        RecordType rtFormObject = AlpineTestHelper.GetRecordType(UtilityGetNamespace.CurrentNamespace()  + 'Job__c');
    
        RecordType rtKeyObject = AlpineTestHelper.GetRecordType(UtilityGetNamespace.CurrentNamespace()  + 'Ticket__c');

        newItem.eForm_SObject__c = 'Job__c';
        //newItem.eForm_SObject__c = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        
        newItem.eForm_SObject_Record_Type__c = rtFormObject.DeveloperName;

        newItem.Key_SObject__c = UtilityGetNamespace.CurrentNamespace()  + 'Ticket__c';
        newItem.Key_SObject_Record_Type__c = rtKeyObject.DeveloperName;

        insert newItem;
      
      
        Test.StopTest();
 
        eForm_Config__c dbItem = [SELECT Id, eForm_SObject__c, eForm_SObject_Record_Type__c, eForm_SObject_Record_Type_Id__c, Key_SObject__c, Key_SObject_Record_Type__c,  Key_SObject_Record_Type_Id__c FROM eForm_Config__c WHERE Id =:newItem.Id];   

        System.assertEquals(rtFormObject.DeveloperName, dbItem.eForm_SObject_Record_Type__c);  
        System.assertEquals(rtFormObject.Id, dbItem.eForm_SObject_Record_Type_Id__c);  


        System.assertEquals(rtKeyObject.DeveloperName, dbItem.Key_SObject_Record_Type__c);  
        System.assertEquals(rtKeyObject.Id, dbItem.Key_SObject_Record_Type_Id__c);  
    }
}