src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/CustomFieldInfo__c/CustomFieldInfo__c.object-meta.xml
<CustomObject>
    <label>CustomFieldInfo</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomFieldInfo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/CustomFieldInfo__c/fields/CustomObjectInfo__c.field-meta.xml
<CustomField>
    <fullName>CustomObjectInfo__c</fullName>
    <label>CustomObjectInfo</label>
    <referenceTo>CustomObjectInfo__c</referenceTo>
    <relationshipLabel>CustomFieldInfo</relationshipLabel>
    <relationshipName>CustomFieldInfo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/CustomFieldInfo__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/CustomFieldInfo__c/fields/FieldDefinitionId__c.field-meta.xml
<CustomField>
    <fullName>FieldDefinitionId__c</fullName>
    <externalId>true</externalId>
    <label>FieldDefinitionId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/CustomFieldInfo__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>CustomField.FullName</inlineHelpText>
    <label>FullName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/CustomObjectInfo__c/CustomObjectInfo__c.object-meta.xml
<CustomObject>
    <label>CustomObjectInfo</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomObjectInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/CustomObjectInfo__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <externalId>true</externalId>
    <label>DeveloperName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/CustomObjectInfo__c/fields/EntityDefinitionId__c.field-meta.xml
<CustomField>
    <fullName>EntityDefinitionId__c</fullName>
    <externalId>true</externalId>
    <label>EntityDefinitionId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer that uses the price book. If a customer is not selected, the price book is available for every customer.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/LookupFilterHandler_Test.cls
@isTest
private class LookupFilterHandler_Test
{
    static void SetupData()
    {
        String contents = 'window.FX_Mobile_Filters = {' + 
               '"Account": {       ' +
               '"Job__c.CustomerAccount__c": {' +
               '    "predicate": "Account.RecordType.DeveloperName != \'Office\' && (ISNULL($Source.Price_Book__c) || ISNULL($Source.Price_Book__r.Account__c) || $Source.Price_Book__r.Account__c==Account.Id)",' +
               '    "sortFormula": {' +
               '        "formula": "Account.Name",' +
               '        "limit": "10",' +
               '        "sort": "asc"' +
               '    }' +
               '}}}';
        
        StaticResourceHandler.UpsertFile('FX_Mobile_Filters', contents); 
        CustomObjectInfo__c objInfo = new CustomObjectInfo__c();
        objInfo.DeveloperName__c = 'Job__c';
        objInfo.EntityDefinitionId__c = '01I36000001VBPgEAO';
        insert objInfo;

        CustomFieldInfo__c fInfo = new CustomFieldInfo__c(CustomObjectInfo__c = objInfo.Id, 
            FullName__c = 'Job__c.TestField__c',
            DeveloperName__c ='TestField__c',
            FieldDefinitionId__c ='00N3600000E0xm1EAB');
        insert fInfo;


    }

    static testmethod void RunTest()
    {
        SetupData();
        Test.startTest();
        
        List<StaticResource> items = [SELECT Id, Body FROM StaticResource WHERE Name='FX_Mobile_Filters'];
        LookupFilterHandler.Run();
        Test.stopTest();
    }

    static testmethod void BatchTest()
    {
        SetupData();
        Test.startTest();
        Database.executeBatch(new LookupFilterHandler());
        Test.stopTest();
    }

    static testmethod void BatchTest2()
    {
        SetupData();
        Test.startTest();
        Database.executeBatch(new LookupFilterHandler(UserInfo.getSessionID()));
        Test.stopTest();
    }


    static testmethod void BatchTest3()
    {
        SetupData();
        Test.startTest();
        List<LookupFilterHandler.LookupFilterRecord> filters = new List<LookupFilterHandler.LookupFilterRecord>();

        Database.executeBatch(new LookupFilterHandler(UserInfo.getSessionID(), filters,
             LookupFilterHandler.GetLookupFieldDefinitionIds()));
        Test.stopTest();
    }


    static testmethod void BatchTest4()
    {
        SetupData();
        Test.startTest();

        Database.executeBatch(new LookupFilterHandler(UserInfo.getSessionID(), 
             LookupFilterHandler.GetLookupFieldDefinitionIds()));
        Test.stopTest();
    }


    static testmethod void SchedulerTest()
    {
        SetupData();
        Test.startTest();
        String ns = StringUtility.FXNamespace().replace('__', '.');
        FXScheduleDispatcher.ScheduleJobNow( ns+ 'LookupFilterHandler');
        Test.stopTest();
    }


    static testmethod void FXWorkerLauncherTest()
    {
        SetupData();
        Test.startTest();
        String ns = StringUtility.FXNamespace().replace('__', '.');
        FXWorkerLauncher.DoWork(ns + 'LookupFilterHandler', null);
        Test.stopTest();
    }
    
    static testmethod void CodeCoverage()
    {
        SetupData();
        Test.startTest();
        LookupFilterHandler.RefreshLookupFilters();
        LookupFilterHandler h = new LookupFilterHandler();
        h.DoWork(null);
        Test.stopTest();
    }


    static testmethod void PredidateTest()
    {
        String rawStr = '{'
  + '"size" : 1,'
  + '"totalSize" : 1,'
  + '"done" : true,'
  + '"queryLocator" : null,'
  + '"entityTypeName" : "CustomField",'
  + '"records" : [ {'
  + '  "attributes" : {'
  + '    "type" : "CustomField",'
  + '    "url" : "/services/data/v31.0/tooling/sobjects/CustomField/00N4A00000FcsKTUAZ"'
  + '  },'
  + '  "Id" : "00N4A00000FcsKTUAZ",'
  + '  "TableEnumOrId" : "01IG0000002ELX4MAO",'
  + '  "DeveloperName" : "FilterTest",'
  + '  "FullName" : "FX5__Crew_Planning__c.FilterTest__c",'
  + '  "Metadata" : {'
  + '    "caseSensitive" : null,'
  + '    "customDataType" : null,'
  + '    "defaultValue" : null,'
  + '    "deleteConstraint" : "SetNull",'
  + '    "deprecated" : null,'
  + '    "description" : null,'
  + '    "displayFormat" : null,'
  + '    "displayLocationInDecimal" : null,'
  + '    "encrypted" : null,'
  + '    "escapeMarkup" : null,'
  + '    "externalDeveloperName" : null,'
  + '    "externalId" : false,'
  + '    "formula" : null,'
  + '    "formulaTreatBlanksAs" : null,'
  + '    "inlineHelpText" : null,'
  + '    "isFilteringDisabled" : null,'
  + '    "isNameField" : null,'
  + '    "isSortingDisabled" : null,'
  + '    "label" : "Price Book Item",'
  + '    "length" : null,'
  + '    "lookupFilter" : {'
  + '      "booleanFilter" : "(1 AND 2 AND 3 AND 4) OR 5",'
  + '      "filterItems" : [ {'
  + '        "field" : "FX5__Price_Book_Item__c.FX5__Price__c",'
  + '        "operation" : "greaterThan",'
  + '        "value" : "1956",'
  + '        "valueField" : null'
  + '      }, {'
  + '        "field" : "FX5__Price_Book_Item__c.Max_Temp__c",'
  + '        "operation" : "greaterOrEqual",'
  + '        "value" : "25.3",'
  + '        "valueField" : null'
  + '      }, {'
  + '        "field" : "FX5__Price_Book_Item__c.FX5__Catalog_Description__c",'
  + '        "operation" : "notContain",'
  + '        "value" : "Equipment",'
  + '        "valueField" : null'
  + '      }, {'
  + '        "field" : "FX5__Price_Book_Item__c.FX5__Catalog_Cost__c",'
  + '        "operation" : "notEqual",'
  + '        "value" : "0",'
  + '        "valueField" : null'
  + '      }, {'
  + '        "field" : "FX5__Price_Book_Item__c.FX5__Catalog_UOM__c",'
  + '        "operation" : "notEqual",'
  + '        "value" : "EA",'
  + '        "valueField" : null'
  + '      } ],'
  + '      "active" : true,'
  + '      "description" : null,'
  + '      "errorMessage" : null,'
  + '      "infoMessage" : null,'
  + '      "isOptional" : false'
  + '    },'
  + '    "maskChar" : null,'
  + '    "maskType" : null,'
  + '    "picklist" : null,'
  + '    "populateExistingRows" : null,'
  + '    "precision" : null,'
  + '    "readOnlyProxy" : null,'
  + '    "referenceTargetField" : null,'
  + '    "referenceTo" : "FX5__Price_Book_Item__c",'
  + '    "relationshipLabel" : "Crew Planning (Price Book Item)",'
  + '    "relationshipName" : "Crew_Planning",'
  + '    "relationshipOrder" : null,'
  + '    "reparentableMasterDetail" : null,'
  + '    "required" : false,'
  + '    "restrictedAdminField" : null,'
  + '    "scale" : null,'
  + '    "startingNumber" : null,'
  + '    "stripMarkup" : null,'
  + '    "summarizedField" : null,'
  + '    "summaryFilterItems" : null,'
  + '    "summaryForeignKey" : null,'
  + '    "summaryOperation" : null,'
  + '    "trackFeedHistory" : null,'
  + '    "trackHistory" : false,'
  + '    "trackTrending" : false,'
  + '    "type" : "Lookup",'
  + '    "unique" : null,'
  + '    "urls" : null,'
  + '    "visibleLines" : null,'
  + '    "writeRequiresMasterRead" : null'
  + '  }'
  + '} ]'
  + '}';
        Test.startTest();
        
        LookupFilterHandler.LookupFilterRawResponse result = (LookupFilterHandler.LookupFilterRawResponse)JSON.deserialize(rawStr, 
                        LookupFilterHandler.LookupFilterRawResponse.class);

        System.assert(result.HasActiveFilter(), 'should have active filter');

        LookupFilterHandler.LookupFilterRecord filter =  result.LookupFilter;
        String predicate = filter.predicate;
        System.debug(predicate);

        Test.stopTest();
    }
}