src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/Contact/fields/Available_for_Field_Work__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Field_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to indicate that the person is available to work in the field. This typically means that they can be assigned to a job or ticket.</description>
    <inlineHelpText>If selected, the user is selectable when adding a job or ticket in FieldFX Mobile. You must select this option if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Available for Field Work</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/Sync_Configuration__c.object-meta.xml
<CustomObject>
    <description>This controls which data the mobile client users will receive when they sync.  Users will only get information related to the offices listed here.</description>
    <label>Sync Configuration</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Sync Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Sync_Configuration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by customer. If a customer is specified, the user only sees jobs with price books linked to that customer. If a customer is not specified, the user sees jobs for all accessible accounts.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations (Account)</relationshipLabel>
    <relationshipName>Sync_Configurations1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <inlineHelpText>Contact record for the user granted access to jobs in FieldFX Mobile through the sync configuration.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job type. If a job type is specified, the user only sees jobs for that job type. If a job type is not specified, the user sees jobs for all job types.</inlineHelpText>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Time &amp; Material</fullName>
            </value>
            <value>
                <fullName>Fixed Bid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by office. If an office is specified, the user only sees jobs for that office. If an office is not specified, the user sees jobs for all offices.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Configurations</relationshipLabel>
    <relationshipName>Sync_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by business segment. If a segment is specified, the user only sees jobs for that segment. If a segment is not specified, the user sees jobs for all segments.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/Sync_JobCrewOnly__c.field-meta.xml
<CustomField>
    <fullName>Sync_JobCrewOnly__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag Job for download only for Job Crew</description>
    <inlineHelpText>Controls the jobs that the user sees in FieldFX Mobile by job crew assignment. If selected, the user only sees jobs if they are in the job crew. If not selected, the user sees any job matching the other criteria specified in the sync configuration.</inlineHelpText>
    <label>Sync - Job Crew Only</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Sync_Configuration__c/fields/UniqueId__c.field-meta.xml
<CustomField>
    <fullName>UniqueId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>Unique identifier for the sync configuration.</inlineHelpText>
    <label>UniqueId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/SyncConfigBuilderController_Test.cls
@isTest
private class SyncConfigBuilderController_Test
{
   static testMethod void runTestForCodeCoverage() 
   { 
       SyncConfigBuilderController ctrl = new SyncConfigBuilderController();

       List<Contact> contacts = CreateContacts(20);
       System.debug('contacts count = ' + contacts.size());
       ctrl.SyncConfigContacts = contacts.get(0).Id + ':' + contacts.get(0).Name;
       //ctrl.FilterSyncConfigs();
       ctrl.save();
       ctrl.resetSearcher();

       ctrl.contactObj.Office__c = contacts.get(0).Office__c;
       ctrl.keyword = 'Doe';
       ctrl.SearchContacts();

       ctrl.SaveGridEdit();
       ctrl.CancelGridEdit();

       ctrl.ResetSyncConfigFilter();

       Sync_Configuration__c sc = CreateSyncConfig();
       ctrl.SelectedSyncConfigIds = sc.Id;

       ctrl.DeleteSyncConfigs();
   }

   static testMethod void GetUniqueId_Test() 
   { 
   		Test.startTest();
   		Contact c = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Joe', false);
   		c.Available_for_Field_Work__c = true;
   		insert c;

       	Sync_Configuration__c sc = new Sync_Configuration__c();

       	sc.Contact__c = c.Id;
       	sc.Sync_JobCrewOnly__c = true;

       	Account a = AlpineTestHelper.CreateAccount('UnitTest Account');
       	Account office = AlpineTestHelper.CreateOffice('Unit Test Office');

       	sc.Account__c = a.Id;
       	sc.Office__c = office.Id;

       	sc.Job_Type__c = 'UnitTestJobType';
       	sc.Segment__c = 'UnitTestSegment';

       	String uniqueId = SyncConfigBuilderController.GetUniqueId(sc);
       	insert sc;

       	Test.stopTest();

       	Sync_Configuration__c dbItem = [SELECT Id, UniqueId__c FROM Sync_Configuration__c WHERE Id=:sc.Id LIMIT 1];
       	System.assertEquals(dbItem.UniqueId__c, uniqueId);
   }

   static List<Contact> CreateContacts(Integer count)
   {
   		List<Contact> items = new List<Contact>();
   		for(Integer i=0; i<count; i++)
   		{
   			Contact c = AlpineTestHelper.CreateContactWithTestUser('Doe ' + i, 'Joe ' + i, false);
   			c.Available_for_Field_Work__c = true;
   			items.add(c);
   		}
   		insert items;
   		return [SELECT Id, Name, Office__c FROM Contact where User__c !=null AND  Available_for_Field_Work__c=true];
   }

   static Sync_Configuration__c CreateSyncConfig()
   {
      Contact c = AlpineTestHelper.CreateContactWithTestUser('Doe', 'Joe', false);
      c.Available_for_Field_Work__c = true;
      insert c;

        Sync_Configuration__c sc = new Sync_Configuration__c();

        sc.Contact__c = c.Id;
        sc.Sync_JobCrewOnly__c = true;

        Account a = AlpineTestHelper.CreateAccount('UnitTest Account');
        Account office = AlpineTestHelper.CreateOffice('Unit Test Office');

        sc.Account__c = a.Id;
        sc.Office__c = office.Id;

        sc.Job_Type__c = 'UnitTestJobType';
        sc.Segment__c = 'UnitTestSegment';

        String uniqueId = SyncConfigBuilderController.GetUniqueId(sc);
        insert sc;

        return sc;

   }
}