src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/Contact/fields/Available_for_Field_Work__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Field_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to indicate that the person is available to work in the field. This typically means that they can be assigned to a job or ticket.</description>
    <inlineHelpText>If selected, the user is selectable when adding a job or ticket in FieldFX Mobile. You must select this option if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Available for Field Work</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Contact/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office where the user works. You must select an office if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>FieldFX-Force.com user record for the contact.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Contact/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/AutoAddJobCreatorToCrew__c.field-meta.xml
<CustomField>
    <fullName>AutoAddJobCreatorToCrew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</description>
    <inlineHelpText>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</inlineHelpText>
    <label>AutoAddJobCreatorToCrew</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the job was added in FieldFX Mobile. This checkbox is selected automatically for all jobs added in FieldFX Mobile.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for the job.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office that uses the price book. If an office is not selected, the price book is available for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books (Office)</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment that uses the price book. If a business segment is not selected, the price book is available for every segment.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Job.recordType-meta.xml
<RecordType>
    <fullName>Job</fullName>
    <active>true</active>
    <description>This record type is for Job statuses and their related configurations.</description>
    <label>Job</label>
</RecordType>

src/main/default/classes/JobBuilder_Test.cls
@isTest
private class JobBuilder_Test 
{    

    static testmethod void Initialize_Test()
    {
        Test.StartTest();
        string newGuid = StringUtility.newGuid();

        RecordType officeRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType = 'Account' and DeveloperName = 'office' ];

        Account office = new Account(name= 'Office ' + StringUtility.newGuid(), RecordTypeId = officeRecordType.Id);

        insert office;
    
        Account a = new Account(Name = 'Acct ' + newGuid);
        string priceListName = 'Price List ' + newGuid;
        Price_Book__c pl = new Price_Book__c(Name = priceListName);
        insert a;
        insert pl;
        
      
        Price_Book__c priceBook = [SELECT Id FROM Price_Book__c WHERE Name =:priceListName LIMIT 1]; 
              

        String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rtStatus = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

        String jobObjType = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        RecordType rtJob = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :jobObjType LIMIT 1];


        string statusName = 'JobStatus ' + newGuid;
        Status__c consoleStatus = new Status__c(Name = 'console' + statusName, SObject__c='Job__c', SObject_Record_Type__c= rtJob.DeveloperName, Sync__c=true, Initial_Status_Console__c =true,  RecordTypeId=rtStatus.Id);
        insert consoleStatus;

        Status__c mobileStatus = new Status__c(Name = 'mobile' + statusName, SObject__c='Job__c', SObject_Record_Type__c= rtJob.DeveloperName, Sync__c=true, Initial_Status_Mobile__c =true,  RecordTypeId=rtStatus.Id);
        insert mobileStatus;       
               
           
          
        string consoleJobName = StringUtility.newGuid();
        string mobileJobName = StringUtility.newGuid();

        Job__c j1 = new Job__c(Name= consoleJobName, CustomerAccount__c = a.Id, Office__c = office.Id, Price_Book__c = priceBook.Id, Segment__c='Default', RecordTypeId= rtJob.Id); 

        Job__c j2 = new Job__c(Name= mobileJobName, Created_in_Mobile__c = true, CustomerAccount__c = a.Id, Office__c = office.Id, Price_Book__c = priceBook.Id, Segment__c='Default', RecordTypeId= rtJob.Id); 

        insert j1;
        insert j2;
        Test.StopTest();

        Job__c consoleJob = [SELECT Tracking_Number__c, SyncID__c, Status__c FROM Job__c where Name = :consoleJobName LIMIT 1];
        
        System.assert(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, consoleJob.Tracking_Number__c));

        System.assert(consoleJob.SyncID__c != null);

        System.assert(consoleJob.Status__c == consoleStatus.Id);


        Job__c mobileJob = [SELECT Tracking_Number__c, SyncID__c, Status__c FROM Job__c where Name = :mobileJobName LIMIT 1];
        
        System.assert(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Job, mobileJob.Tracking_Number__c));

        System.assert(mobileJob.SyncID__c != null);

        System.assert(mobileJob.Status__c == mobileStatus.Id);
    }
    

    static testmethod void UpdateJob_SyncStatus_Test()
    {
       
        Test.StartTest();
        
        Integer jobCount = 200;
        List<Job__c> newJobs = AlpineTestHelper.CreateJobs(jobCount, false);

        String newGuid = StringUtility.newGuid();   

        String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rt = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :objType LIMIT 1];

        String jobObjType = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        RecordType rtJob = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :jobObjType LIMIT 1];

    
        Status__c noSyncStatus = new Status__c(Name = 'noSync' + newGuid, SObject__c='Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =false, Sync__c = false, Initial_Status_Mobile__c=false, RecordTypeId=rt.Id);

        Status__c syncStatus = new Status__c(Name = 'Sync' + newGuid, SObject__c='Job__c', SObject_Record_Type__c = rtJob.DeveloperName, Initial_Status_Console__c =false, Sync__c = true, Initial_Status_Mobile__c=false, RecordTypeId=rt.Id);

        insert syncStatus;
        insert noSyncStatus;

        for(Job__c j : newJobs)
        {
            j.Name = newGuid;
            j.RecordTypeId = rtJob.Id;
            j.Status__c = noSyncStatus.Id;
        }
        insert newJobs;

      
        
        List<Job__c> dbJobs = [SELECT Id, Sync__c, Status__c FROM Job__c WHERE Status__c = :noSyncStatus.Id AND Sync__c=false];  

        System.assertEquals(jobCount, dbJobs.size());

        for(Job__c j:dbJobs)
        {
            j.Status__c = syncStatus.Id;            
        }
        update dbJobs;  
      
       
        Test.StopTest();

        List<Job__c> results = [SELECT Id, Sync__c, Status__c FROM Job__c WHERE Sync__c=true AND Status__c = :syncStatus.Id];   

        System.assertEquals(jobCount, results.size());        
    }


    static testmethod void UpdateJob_NoSyncStatus_Test()
    {
       
        Test.StartTest();
        Integer jobCount = 200;

        List<Job__c> newJobs = AlpineTestHelper.CreateJobs(jobCount, false);

        String newGuid = StringUtility.newGuid();  

        String objType = UtilityGetNamespace.CurrentNamespace()  + 'Status__c';
        RecordType rt = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType=:objType LIMIT 1];
    
        String jobObjType = UtilityGetNamespace.CurrentNamespace()  + 'Job__c';
        RecordType rtJob = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SObjectType = :jobObjType LIMIT 1];


        Status__c noSyncStatus = new Status__c(Name = 'noSync' + newGuid, SObject__c='Job__c', SObject_Record_Type__c=rtJob.DeveloperName, Initial_Status_Console__c=true, Sync__c=false, Initial_Status_Mobile__c=false, RecordTypeId=rt.Id);

        Status__c syncStatus = new Status__c(Name = 'Sync' + newGuid, SObject__c='Job__c', SObject_Record_Type__c=rtJob.DeveloperName, Initial_Status_Console__c=false, Sync__c=true, Initial_Status_Mobile__c=true, RecordTypeId=rt.Id);

        insert syncStatus;
        insert noSyncStatus;

        for(Job__c j : newJobs)
        {
            j.RecordTypeId = rtJob.Id;
            j.Status__c = syncStatus.Id;
        }
        insert newJobs;

        List<Job__c> dbJobs = [SELECT Id, Sync__c, Status__c FROM Job__c WHERE Status__c =:syncStatus.Id AND Sync__c=true];       
        System.assertEquals(jobCount, dbJobs.size());

        for(Job__c j:dbJobs)
        {
            j.Status__c = noSyncStatus.Id;            
        }
        update dbJobs;  
      
        Test.StopTest();
 
        List<Job__c> results = [SELECT Id, Sync__c, Status__c FROM Job__c WHERE Sync__c=false AND Status__c = :noSyncStatus.Id];   

        System.assertEquals(jobCount, results.size());        
    }

    static testmethod void AutoAddJobCreatorToCrew_Test()
    {       
        Test.StartTest();
        FX_Settings__c fs = FX_Settings__c.getOrgDefaults();
        fs.SetupOwnerId = UserInfo.getOrganizationId();
        fs.AutoAddJobCreatorToCrew__c = true;
        insert fs;

        Id userId = UserInfo.getUserId();
        Contact c= null;

        List<Contact> contacts = [SELECT Id FROM Contact WHERE User__c = :userId];
        if(contacts.isEmpty())
        {
            c = AlpineTestHelper.CreateContactWithNoUser('Jane', 'Joe', false);
            c.User__c = userId;
            c.Available_for_Field_Work__c = true;
            insert c;
        }
        else
        {
            c = contacts.get(0);
        }

        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        Test.StopTest();

        List<Crew_Planning__c> cps = [SELECT Id FROM Crew_Planning__c WHERE Job__c = :j.Id AND Crew_Member__c = :c.Id];
        System.assert(cps.size()==1);
    }

    static testmethod void AutoAddJobCreatorToCrew_Negative_Test()
    {       
        Test.StartTest();
        FX_Settings__c fs = FX_Settings__c.getOrgDefaults();
        fs.SetupOwnerId = UserInfo.getOrganizationId();
        fs.AutoAddJobCreatorToCrew__c = false;
        insert fs;
        
        Id userId = UserInfo.getUserId();
        Contact c= null;

        List<Contact> contacts = [SELECT Id FROM Contact WHERE User__c = :userId];
        if(contacts.isEmpty())
        {
            c = AlpineTestHelper.CreateContactWithNoUser('Jane', 'Joe', false);
            c.User__c = userId;
            c.Available_for_Field_Work__c = true;
            insert c;
        }
        else
        {
            c = contacts.get(0);
        }

        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        Test.StopTest();

        List<Crew_Planning__c> cps = [SELECT Id FROM Crew_Planning__c WHERE Job__c = :j.Id AND Crew_Member__c = :c.Id];
        System.assert(cps.isEmpty());
    }

    //contact with Available_for_Field_Work__c = false
    static testmethod void AutoAddJobCreatorToCrew_Negative_Test2()
    {       
        Test.StartTest();
        FX_Settings__c fs = FX_Settings__c.getOrgDefaults();
        fs.SetupOwnerId = UserInfo.getOrganizationId();
        fs.AutoAddJobCreatorToCrew__c = true;
        insert fs;
        
        Id userId = UserInfo.getUserId();
        Contact c= null;

        List<Contact> contacts = [SELECT Id FROM Contact WHERE User__c = :userId];
        if(contacts.isEmpty())
        {
            c = AlpineTestHelper.CreateContactWithNoUser('Jane', 'Joe', false);
            c.User__c = userId;
            c.Available_for_Field_Work__c = false;
            insert c;
        }
        else
        {
            c = contacts.get(0);
        }

        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        Test.StopTest();

        List<Crew_Planning__c> cps = [SELECT Id FROM Crew_Planning__c WHERE Job__c = :j.Id AND Crew_Member__c = :c.Id];
        System.assert(cps.isEmpty());
    }
    
}