src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Contact/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the person to a specific catalog item so that this person can be added to a field ticket and the app will automatically lookup the person's catalog item in the ticket's job's price book in order to automatically select the correct price book item to add to the ticket.</description>
    <inlineHelpText>Labor catalog item for the user's job title.</inlineHelpText>
    <label>Job Title from Catalog</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Role_on_Job__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Labor catalog item for the employee's role on the job.</inlineHelpText>
    <label>Role on Job</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning_Role</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Description__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Description__c</fullName>
    <formula>Catalog_Item__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog description for the price book item. The price book item inherits this description from the linked catalog item by default. If the price book item has a description override, the price book item uses that description.</inlineHelpText>
    <label>Catalog Description</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item_Code__c</fullName>
    <formula>Catalog_Item__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog item code for the price book item. The price book item inherits this item code from the linked catalog item.</inlineHelpText>
    <label>Catalog Item Code</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Included_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Included_Quantity__c</fullName>
    <inlineHelpText>Quantity of the price book item given to the customer at no charge.</inlineHelpText>
    <label>Included Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/FXEditor_Test.cls
@isTest
private class FXEditor_Test
{
    static testMethod void RunThrough() 
    {
        Test.startTest();
         Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);   
        List<Price_Book_Item__c> pliItems = CreatePriceBookItems(5, job.Price_Book__c, 'Labor');

        RecordType officeRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType = 'Account' and DeveloperName != 'office' LIMIT 1];
        Account acct = new Account(name='Account123', RecordTypeId = officeRecordType.Id);
        insert acct;

        Contact p1 = new Contact(FirstName='Jane', LastName='Doe', Account = acct);
        insert p1;


        Crew_Planning__c cp = new Crew_Planning__c(Job__c = job.Id, Role_on_Job__c = pliItems.get(0).Id, Crew_Member__c = p1.Id);
        insert cp;

        PageReference page = new PageReference('CrewPlanningEditor');
        page.getParameters().put('id', cp.Id);
        Test.setCurrentPage(page);        
      
        FXEditorController ctrl = new FXEditorController(new ApexPages.StandardController(cp));  
        List<LayoutField> fields = ctrl.LayoutFields;
        List<LayoutSection> sects = ctrl.LayoutSections;
          
        Test.stopTest();

    }
    static testMethod void newCrewPlaningTest() 
    {

        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);       
        PageReference page = new PageReference('CrewPlanningEditor');
        page.getParameters().put('retURL', '/' + job.Id);
        page.getParameters().put('entityType', String.valueOf(Crew_Planning__c.class));
        Test.setCurrentPage(page);        
      
        FXEditorController ext = new FXEditorController(new ApexPages.StandardController(new Crew_Planning__c()));   
     
        PageReference p2 = ext.doCancel();   
        Test.stopTest();
    }  

    static testMethod void editCrewPlaningTest() 
    {

        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);   
        List<Price_Book_Item__c> pliItems = CreatePriceBookItems(5, job.Price_Book__c, 'Labor');

        RecordType officeRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType = 'Account' and DeveloperName != 'office' LIMIT 1];
        Account acct = new Account(name='Account123', RecordTypeId = officeRecordType.Id);
        insert acct;

        Contact p1 = new Contact(FirstName='Jane', LastName='Doe', Account = acct);
        insert p1;


        Crew_Planning__c cp = new Crew_Planning__c(Job__c = job.Id, Role_on_Job__c = pliItems.get(0).Id, Crew_Member__c = p1.Id);
        insert cp;

        PageReference page = new PageReference('CrewPlanningEditor');
        page.getParameters().put('id', cp.Id);
        Test.setCurrentPage(page);        
      
        FXEditorController ext = new FXEditorController(new ApexPages.StandardController(cp));   
     
        PageReference p2 = ext.save();   
        Test.stopTest();
    }  

    static testMethod void saveAndNewTest() 
    {

        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);   
        List<Price_Book_Item__c> pliItems = CreatePriceBookItems(5, job.Price_Book__c, 'Labor');

        RecordType officeRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType = 'Account' and DeveloperName != 'office' LIMIT 1];
        Account acct = new Account(name='Account123', RecordTypeId = officeRecordType.Id);
        insert acct;

        Contact p1 = new Contact(FirstName='Jane', LastName='Doe', Account = acct);
        insert p1;


        Crew_Planning__c cp = new Crew_Planning__c(Job__c = job.Id, Role_on_Job__c = pliItems.get(0).Id, Crew_Member__c = p1.Id);
        insert cp;

        PageReference page = new PageReference('CrewPlanningEditor');
        page.getParameters().put('id', cp.Id);
        Test.setCurrentPage(page);        
      
        FXEditorController ext = new FXEditorController(new ApexPages.StandardController(cp));      
        PageReference p2 = ext.saveAndNew();   
        Test.stopTest();
    }  

    static testMethod void SeachRoleOnJob()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);   
        List<Price_Book_Item__c> pliItems = CreatePriceBookItems(5, job.Price_Book__c, 'Labor');
        String ns = StringUtility.FXNamespace();

        String searchAttrs = '{"[ns]Role_on_Job__c" : {';
        searchAttrs += '"QueryFilter" : "IsDeleted=false",';
        searchAttrs += '"QueryFields" : "Id,Name,[ns]Catalog_Item_Code__c,[ns]Catalog_Description__c",';
        searchAttrs += '"KeywordSearchFields" : "[ns]Catalog_Description__c,[ns]Catalog_Item_Code__c",';
        searchAttrs += '"OrderBy" : "[ns]Catalog_Item_Code__c"}}';
        searchAttrs = searchAttrs.replace('[ns]', ns);


        PageReference page = new PageReference('FXEditorSearcher');
        page.getParameters().put('originatorId', job.Id);
        page.getParameters().put('subjectType', ns + 'Crew_Planning__c');
        page.getParameters().put('lknm', ns + 'Role_on_Job__c');
        page.getParameters().put('searchAttrs', searchAttrs);


        Test.setCurrentPage(page);      

        FXEditorSearchController ctrl = new FXEditorSearchController();
        ctrl.search();
        Test.stopTest();
    }

    static testMethod void LayoutDescribe_Test()
    {
        String str = '{"editLayoutSections" : [ {"columns" : 2,"heading" : "Information","layoutRows" : [ {"layoutItems" : [ {"editableForNew" : false,';
        str += '"editableForUpdate" : false, "label" : "Audit Log ID", ';
        str += '    "layoutComponents" : [ {';
        str += '  "details" : { "autoNumber" : true,"createable" : false, "custom" : false, "idLookup" : true, "inlineHelpText" : null,"label" : "Audit Log ID",';
        str += '    "name" : "Name",';
        str += '    "nameField" : true,';
        str += '    "namePointing" : false,';
        str += '    "nillable" : false,';
        str += '    "permissionable" : false,    ';        
        str += '    "updateable" : false';
        str += '  },';
        str += '  "displayLines" : 1,';
        str += '  "tabOrder" : 4,';
        str += '  "type" : "Field",';
        str += '  "value" : "Name"';
        str += '} ],';
        str += '"placeholder" : false,';
        str += '"required" : false';
        str += '}, {';
        str += '"editableForNew" : false,';
        str += '"editableForUpdate" : false,';
        str += '"label" : "Owner",';
        str += '"layoutComponents" : [ {';
        str += '  "details" : {';
        str += '  "autoNumber" : false,"byteLength" : 18,"createable" : true,"custom" : false, "defaultValue" : null,';
        str += '    "defaultValueFormula" : null, "idLookup" : false, "inlineHelpText" : null, "label" : "Owner ID","length" : 18,           ';
        str += '    "name" : "OwnerId",  "nameField" : false, "namePointing" : true,  "updateable" : true },';
        str += '  "displayLines" : 1,';
        str += '  "tabOrder" : 6,';
        str += '  "type" : "Field",';
        str += '  "value" : "OwnerId"';
        str += '} ],';
        str += '"placeholder" : false,';
        str += '"required" : false';
        str += '} ],';
        str += '"numItems" : 2';
        str += '}, {';
        str += '"layoutItems" : [ {';
        str += '"editableForNew" : true,';
        str += '"editableForUpdate" : true,';
        str += '"label" : "Event Date",';
        str += '"layoutComponents" : [ {';
        str += '  "details" : {';
        str += '    "autoNumber" : false,';
        str += '    "byteLength" : 0,';
        str += '    "calculated" : false,';
        str += '    "calculatedFormula" : null,';
        str += '    "cascadeDelete" : false,';
        str += '    "caseSensitive" : false,';
        str += '    "controllerName" : null,';
        str += '    "createable" : true,';
        str += '    "custom" : true,';
        str += '    "defaultValue" : null,';
        str += '    "defaultValueFormula" : "NOW()",';
        str += '    "defaultedOnCreate" : true,';
        str += '    "dependentPicklist" : false,';
        str += '    "deprecatedAndHidden" : false,';
        str += '    "digits" : 0,';
        str += '    "displayLocationInDecimal" : false,  ';          
        str += '    "idLookup" : false,';
        str += '    "inlineHelpText" : "Date and time",';
        str += '    "label" : "Event Date",';
        str += '    "length" : 0,';
       
        str += '    "name" : "LF50__Event_Date__c",';
        str += '    "nameField" : false,';
        str += '    "namePointing" : false,';
        str += '    "nillable" : false,';
        str += '    "updateable" : true,';
        str += '    "writeRequiresMasterRead" : false';
        str += '  },';
        str += '  "displayLines" : 1,';
        str += '  "tabOrder" : 5,';
        str += '  "type" : "Field",';
        str += '  "value" : "LF50__Event_Date__c"';
        str += '} ],';
        str += '"placeholder" : false,';
        str += '"required" : true';
        str += '}, {';
        str += '"editableForNew" : false,';
        str += '"editableForUpdate" : false,';
        str += '"label" : "",';
        str += '"layoutComponents" : [ ],';
        str += '"placeholder" : true,';
        str += '"required" : false';
        str += '} ],';
        str += '"numItems" : 2';
        str += '} ],';
        str += '"rows" : 2,';
        str += '"tabOrder" : "TopToBottom",';
        str += '"useCollapsibleSection" : false,';
        str += '"useHeading" : true';
        str += '} ]';
        str += '}';
        String ns = StringUtility.FXNamespace().replace('__', '.');

        LayoutDescribe.RecordTypeLayout rs = (LayoutDescribe.RecordTypeLayout)JSON.deserialize(str, Type.forName(ns + 'LayoutDescribe.RecordTypeLayout'));
        System.debug(rs.editLayoutSections.size());
        System.debug(rs.getFieldInfo().size());


    }

   
    static List<Price_Book_Item__c> CreatePriceBookItems(Integer itemsCount, Id priceBookId, string itemType)
    {
        List<Catalog_Item__c> catalogItems = new List<Catalog_Item__c>();
        for(Integer i=0; i<itemsCount; i++)
        {
            catalogItems.add(new Catalog_Item__c(Name= 'CI' + i , Description__c = 'Test Catalog Item' + i, UOM__c='Gal', Sequence_Number__c=i,  Ticket_Item_Record_Type__c = itemType));
        }
        insert catalogItems;

        List<Price_Book_Item__c> pliItems = new List<Price_Book_Item__c>();
        for(Integer i=0; i<itemsCount; i++)
        {
            pliItems.add(new Price_Book_Item__c(Price_Book__c = priceBookId, Price__c=i+3, Sequence_Number__c =i, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItems.get(i).Id));
        }
        insert pliItems;
        return pliItems;
    }
}