src/main/default/objects/Account/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <label>Office</label>
</RecordType>

src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Catalog item for the equipment. You must link an equipment record to a catalog item. Equipment records inherit the catalog description and ticket item record type for their linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description used to help identify the equipment.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office that owns the equipment.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipment (Office)</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <inlineHelpText>Unit number for the equipment.</inlineHelpText>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the equipment is scheduled for use.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Job_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Planned_Start__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start__c</fullName>
    <description>The planned start date/time for this equipment.</description>
    <inlineHelpText>Date and time the equipment is due to start being used on the job.</inlineHelpText>
    <label>Planned Start</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/EquipmentPlanningPlaceHolder_Test.cls
@isTest
private class EquipmentPlanningPlaceHolder_Test
{
    @testSetup
    static void Setup()
    {
        List<Catalog_Item__c> catalogItems = new List<Catalog_Item__c>();
        for(Integer i=0; i<100; i++)
        {
            String guidStr = StringUtility.newGuid();
            catalogItems.add(new Catalog_Item__c(Name= 'CI' + guidStr   , Description__c = 'Test Catalog Item' + guidStr , UOM__c='Gal', Sequence_Number__c=i,  Ticket_Item_Record_Type__c = 'Equipment'));
        }
       
        insert catalogItems;       
        
        RecordType officeRecordType = [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType = 'Account' and DeveloperName = 'office'];

        Account office = new Account(Name= 'Office ' + StringUtility.newGuid(), RecordTypeId = officeRecordType.Id);
        insert office;  
        
        String ns = StringUtility.FXNamespace();
        Boolean hasEquipField = Equipment_Planning__c.sObjectType.getDescribe().fields.getMap().containsKey(ns + 'Equipment__c');
        
        List<Equipment__c> equip = new List<Equipment__c>();
        
        for(Integer i=0; i<100; i++)
        {    
            String uniqueStr = StringUtility.newGuid();       
            equip.add(new Equipment__c(Name= 'Equip ' + uniqueStr , Catalog_Item__c = catalogItems.get(i).Id, Unit_Number__c = uniqueStr, Office__c = office.Id));
        } 
        insert equip ;
        
        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        
        List<Equipment_Planning__c> eps = new List<Equipment_Planning__c>();
        for(Integer i=0; i<100; i++)
        {
            Equipment_Planning__c ep = new Equipment_Planning__c(Planned_Start__c = Datetime.now(), Job__c = j.Id);
            if(hasEquipField)
            {
                ep.put(ns + 'Equipment__c', equip.get(i).Id);
            }
            eps.add(ep);
        } 
        
        insert eps;
    }
    static testmethod void runTest()
    {
        Test.startTest();
        String ns = StringUtility.FXNamespace();
        if(!String.isBlank(ns))
        {
            ns = ns.replace('__', '.');
        }        
         
        FXResult r = FXBatchableLauncher.Run(ns + 'EquipmentPlanningPlaceHolderBatchable');        
        Test.stopTest();
        
        System.assert(r.isSuccess, 'should succeed');
        
    }
}