src/main/default/objects/eForm_Config__c/eForm_Config__c.object-meta.xml
<CustomObject>
    <label>eForm Config</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>eForm Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eForm Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/eForm_Config__c/fields/eForm_SObject__c.field-meta.xml
<CustomField>
    <fullName>eForm_SObject__c</fullName>
    <inlineHelpText>API name of the FX Form object. You must make an entry in this field.</inlineHelpText>
    <label>eForm SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Key_SObject__c.field-meta.xml
<CustomField>
    <fullName>Key_SObject__c</fullName>
    <inlineHelpText>API name of the object for which the FX Form is available. You must make an entry in this field.</inlineHelpText>
    <label>Key SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FX5__Job__c</fullName>
            </value>
            <value>
                <fullName>FX5__Ticket__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/Ticket_Log__c.object-meta.xml
<CustomObject>
    <label>Ticket Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Ticket Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket for which the log entry was recorded.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/JobPropagator.cls
public class JobPropagator
{   
    public static Boolean IsActive()
    {
        return !FXSettingHelper.TurnOffJobPropagator;
    }
    
    Static Boolean JobPropagatorRunning {get;set;}

    public static void SetJobId(List<Ticket_Item__c> objs)
    {
         if(!JobPropagator.IsActive() 
            || objs == null 
            || objs.isEmpty()) return;

        Set<Id> ids = new Set<Id>();
        for(Ticket_Item__c o : objs)
        {
            ids.add(o.Ticket__c);
        }
        Map<Id, Id> jobLookup = new Map<Id, Id>();
        for(Ticket__c o: [SELECT Id, Job__c FROM Ticket__c WHERE IsDeleted=false AND Id IN :ids])
        {
            jobLookup.put(o.Id, o.Job__c);
        }
        for(Ticket_Item__c o : objs)
        {
            if(!jobLookup.containsKey(o.Ticket__c)) continue;
            o.Job__c = jobLookup.get(o.Ticket__c);
        }
    }

    public static void SetJobId(List<Ticket_Log__c> objs)
    {
         if(!JobPropagator.IsActive() 
            || objs == null 
            || objs.isEmpty()) return;
         
        Set<Id> ids = new Set<Id>();
        for(Ticket_Log__c o : objs)
        {
            ids.add(o.Ticket__c);
        }
        Map<Id, Id> jobLookup = new Map<Id, Id>();
        for(Ticket__c o: [SELECT Id, Job__c FROM Ticket__c WHERE IsDeleted=false AND Id IN :ids])
        {
            jobLookup.put(o.Id, o.Job__c);
        }
        for(Ticket_Log__c o : objs)
        {
            if(!jobLookup.containsKey(o.Ticket__c)) continue;
            o.Job__c = jobLookup.get(o.Ticket__c);
        }
    }

    public static void SetJobId(List<Ticket_Checklist_Step__c> objs)
    {
        if(!JobPropagator.IsActive() 
            || objs == null 
            || objs.isEmpty()) return;

        Set<Id> ids = new Set<Id>();
        for(Ticket_Checklist_Step__c o : objs)
        {
            ids.add(o.Ticket__c);
        }
        Map<Id, Id> jobLookup = new Map<Id, Id>();
        for(Ticket__c o: [SELECT Id, Job__c FROM Ticket__c WHERE IsDeleted=false AND Id IN :ids])
        {
            jobLookup.put(o.Id, o.Job__c);
        }
        for(Ticket_Checklist_Step__c o : objs)
        {
            if(!jobLookup.containsKey(o.Ticket__c)) continue;
            o.Job__c = jobLookup.get(o.Ticket__c);
        }
    } 


    public static void SetJobId(List<sObject> items)
    {
        if(!JobPropagator.IsActive() 
            || items == null 
            || items.isEmpty()) return;

        //this will run on after insert and after update trigger, 
        //to prevent recursive infinite loop, check JobPropagatorRunning to only run the code once
        if(JobPropagatorRunning == true) return;
        JobPropagatorRunning = true;

        Set<Id> objIds = new Map<Id, sObject>(items).keySet();

        Schema.DescribeSObjectResult r = items.get(0).getSObjectType().getDescribe();
        if(!r.fields.getMap().containsKey('Job_Share__c')) return;

        String objType = r.getName();
        String jobField = GetPathsToJob(r);
       
        String soql = String.format('SELECT Id, {0} FROM {1} WHERE Id IN :objIds FOR UPDATE',
            new String[]{jobField, objType });

        soql = soql.replace('__c.', '__r.');

        //System.debug(soql);
        List<sObject> objs = Database.query(soql);
        for(sObject o : objs)
        {
            Object v = GetJobId(o, jobField);

            if(v!=null)
            {
                o.put('Job_Share__c', v);
            }
        }
        Database.update(objs, false);
    }

    @testVisible
    static Object GetJobID(sObject obj, String path)
    {
        path = path.replace('__c.', '__r.');
        
        String[] entries = path.split('\\.');
        if(entries.size()==1)
        {
            return (Id)obj.get(path);
        }
        sObject source = obj;
        while(entries.size()>1)
        {
            String fk = entries.remove(0);        

            source = source.getsObject(fk);
            if(source==null) return null;
        }
        return source.get(entries.remove(0));           
    }          

    @testVisible
    static String GetKeySObject(String form)
    {
        if(formKeySObjs == null)
        {
            formKeySObjs = new Map<String,String>();
            for(eForm_Config__c c: [SELECT Id, eForm_SObject__c, Key_SObject__c FROM eForm_Config__c WHERE IsDeleted=false])
            {
                formKeySObjs.put(c.eForm_SObject__c, c.Key_SObject__c);
            }
        }
        return formKeySObjs.containsKey(form)? formKeySObjs.get(form) : null;
    }

    @testVisible
    Static Map<String, String> formKeySObjs {get;set;}

    @testVisible
    static String GetPathsToJob(Schema.DescribeSObjectResult r)
    {
        String ns = StringUtility.FXNamespace();

        String objType = r.getName();

        String root = '';

        String keySObj = GetKeySObject(objType);

        Schema.DescribeSObjectResult dsrWithJobPath = r;

        //while keySObj is blank, this might be a child eForm or one not properly configured
        if(String.isBlank(keySObj))
        {
            dsrWithJobPath = null;
            for(Schema.SObjectField f: r.fields.getMap().values())
            {
                Schema.DescribeFieldResult fd = f.getDescribe();
                if(!fd.isCustom()) continue;
                String fieldName = fd.getName();
                if(fieldName == 'Job_Share__c') continue;
                System.debug(fieldName + ':' + fd.getRelationshipOrder());
                if(fd.getRelationshipOrder()>=0)
                {
                    List<Schema.sObjectType> fks = fd.getReferenceTo();
                    if(fks.isEmpty()) continue; 
                    Schema.DescribeSObjectResult fkDsr = fks.get(0).getDescribe();
                    if(!fkDsr.isCustom()) continue;

                    String fkKeySobj = GetKeySObject(fkDsr.getName());
                    if(!String.isBlank(fkKeySobj))
                    {
                        dsrWithJobPath = fkDsr;
                        root = fieldName;
                        keySObj = fkKeySobj;
                        break;
                    }
                }           
            }
        }
        if(String.isBlank(keySObj) || dsrWithJobPath == null) return null;

        keySObj = keySObj.replace('FX5__', ns);

        String path = '';

        for(Schema.SObjectField f: dsrWithJobPath.fields.getMap().values())
        {
            Schema.DescribeFieldResult fd = f.getDescribe();
            if(!fd.isCustom()) continue;

            String fieldName = fd.getName();
            if(fieldName == 'Job_Share__c') continue;

            List<Schema.sObjectType> fks = fd.getReferenceTo();
            if(fks.isEmpty()) continue; 

            Schema.DescribeSObjectResult fkDsr = fks.get(0).getDescribe();
            if(!fkDsr.isCustom()) continue;

            if(fkDsr.getName() == keySObj)
            {
                if(keySObj == ns + 'Job__c')
                {
                    path = fieldName;
                    break;
                }
                if(keySObj == ns + 'Ticket__c')
                {
                    path = fieldName.removeEndIgnorecase('__c') + '__r.' + ns + 'Job__c';
                    break;
                }
            }
        }
        if(String.isBlank(path)) return null;

        if(!String.isBlank(root))
        {
            path = root.removeEndIgnorecase('__c') + '__r.' + path;
        }
        return path;
    }
    
}