src/main/default/objects/eForm_Config__c/eForm_Config__c.object-meta.xml
<CustomObject>
    <label>eForm Config</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>eForm Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eForm Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/eForm_Config__c/fields/eForm_SObject__c.field-meta.xml
<CustomField>
    <fullName>eForm_SObject__c</fullName>
    <inlineHelpText>API name of the FX Form object. You must make an entry in this field.</inlineHelpText>
    <label>eForm SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/eForm_Config__c/fields/Key_SObject__c.field-meta.xml
<CustomField>
    <fullName>Key_SObject__c</fullName>
    <inlineHelpText>API name of the object for which the FX Form is available. You must make an entry in this field.</inlineHelpText>
    <label>Key SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FX5__Job__c</fullName>
            </value>
            <value>
                <fullName>FX5__Ticket__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/classes/eFormHandler_Test.cls
@isTest
private class eFormHandler_Test
{
    static testmethod void Run()
    {
        Test.startTest();
        Set<String> forms = new Set<String>();
        String ns = StringUtility.FXNamespace();
        String form = ns + 'Ticket__c';
        forms.add(form);
        eFormHandler.InitForms(forms);    
        eFormHandler.CreateSyncIDField();   
        
        eForm_Config__c c = new eForm_Config__c(eForm_SObject__c = form, Key_SObject__c = 'FX5__Job__c');
        
        List<eForm_Config__c> configs = new List<eForm_Config__c>();
        configs.add(c);
        eFormHandler.Validate(configs, true);
        
        Test.stopTest();
    }
    
    static testmethod void eFormConfig_Test()
    {
        Test.startTest();
        String ns = StringUtility.FXNamespace();
        eForm_Config__c c = new eForm_Config__c(eForm_SObject__c = 'Ticket__c', Key_SObject__c = 'FX5__Job__c');
        
        insert c;
        
        Test.stopTest();
    }
}