src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Equipment2__c.field-meta.xml
<CustomField>
    <fullName>Equipment2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Equipment Planning (Equipment)</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/EquipmentPlanningTriggerHandler.cls
public class EquipmentPlanningTriggerHandler extends FXTriggerHandler
{
    public override void OnBeforeInsert(List<sObject> items)
    {
    	EquipmentPlanningHandler.ValidateSourcePriceBook((List<Equipment_Planning__c>)items, null);    	
    	JobQualificationHandler.ValidateQualifications((List<Equipment_Planning__c>)items);
        JobResourcePlanning.ApplyEquipmentPriceBookItem((List<Equipment_Planning__c>)items);
    }
    
    public override void OnBeforeUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    { 
    	EquipmentPlanningHandler.ValidateSourcePriceBook((List<Equipment_Planning__c>)items, (Map<Id, Equipment_Planning__c>)oldMap);    	
    	JobQualificationHandler.ValidateQualifications((List<Equipment_Planning__c>)items);

        List<Equipment_Planning__c> itemsOfInterest = new List<Equipment_Planning__c>();
        for(sObject obj: items)
        {        
            Equipment_Planning__c equipPlanning = (Equipment_Planning__c)obj;
            Equipment_Planning__c old = (Equipment_Planning__c)oldMap.get(obj.Id);    
            if(old.Equipment2__c != equipPlanning.Equipment2__c)
            {
                itemsOfInterest.add(equipPlanning);
            }
        }
        if(!itemsOfInterest.isEmpty())
        {            
            JobResourcePlanning.ApplyEquipmentPriceBookItem(itemsOfInterest);
        }

    }    
}