src/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Status</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/Credit_Memo_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Item</label>
    <nameField>
        <displayFormat>CMI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo_Item__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <label>Credit Memo</label>
    <referenceTo>Credit_Memo__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Status</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Status record must have a record type of Invoice.</errorMessage>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/CreditMemoItemHandler_Update_Test.cls
@isTest
public class CreditMemoItemHandler_Update_Test
{
  @testSetup
  static void setup()
  {
    Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);

    Account acc = AlpineTestHelper.CreateAccount('a1');

    RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');
    string newGuid = StringUtility.newGuid();

    string statusName = 'InvoiceStatus ' + newGuid;
    Status__c stI = new Status__c(Name = statusName, SObject__c='Invoice__c', Sync__c=true, Initial_Status_Console__c =true);

    insert stI;

    statusName = 'CMInitialStatus ' + newGuid;
    Status__c st = new Status__c(Name = statusName, SObject__c='Credit_Memo__c', Sync__c=true, Initial_Status_Console__c =true,  RecordTypeId=statusRecordType.Id);

    insert st;

    Credit_Memo__c cm = new Credit_Memo__c(CustomerAccount__c = acc.Id, Status__c = st.Id);
    insert cm;

    Credit_Memo_Item__c cmi = new Credit_Memo_Item__c();
    cmi.Credit_Memo__c = cm.Id;
    cmi.Description__c = 'cmi1';
    insert cmi;
  }

  static testMethod void CreditMemoItemUpdate() {
    Test.startTest();

    List<Credit_Memo_Item__c> cmis = [SELECT Id, Description__c FROM Credit_Memo_Item__c LIMIT 1];
    cmis[0].Description__c = 'updated';

    CreditMemoItemHandler_Update.UpdateCreditMemoItemRequest request = new CreditMemoItemHandler_Update.UpdateCreditMemoItemRequest();
    request.cmItem = cmis[0];
    request.typeStr = 'Credit_Memo_Item__c';
    request.cmFields = 'Id, Name';
    request.cmiFields = 'Id, Name';

    CreditMemoItemHandler_Update.UpdateCreditMemoItemResult res = CreditMemoItemHandler_Update.CreditMemoItemUpdate(request);

    List<Credit_Memo_Item__c> cmis2 = [SELECT Id, Description__c FROM Credit_Memo_Item__c LIMIT 1];

    System.assert(cmis2[0].Description__c=='updated', 'should have updated cmis');

    Test.stopTest();
  }

  static testMethod void CreditMemoItemsUpdate() {
    Test.startTest();

    List<Credit_Memo_Item__c> cmis = [SELECT Id, Description__c FROM Credit_Memo_Item__c LIMIT 1];
    cmis[0].Description__c = 'updated again';

    CreditMemoItemHandler_Update.UpdateCreditMemoItemsRequest request = new CreditMemoItemHandler_Update.UpdateCreditMemoItemsRequest();
    request.typeStr = 'Credit_Memo_Item__c';
    request.cmFields = 'Id, Name';
    request.cmiFields = 'Id, Name';
    request.cmiList = cmis;

    CreditMemoItemHandler_Update.CreditMemoItemsUpdateResult res = CreditMemoItemHandler_Update.CreditMemoItemsUpdate(request);

    List<Credit_Memo_Item__c> cmis2 = [SELECT Id, Description__c FROM Credit_Memo_Item__c LIMIT 1];

    System.assert(cmis2[0].Description__c=='updated again', 'should have updated cmis');

    Test.stopTest();
  }

  static testMethod void CreditMemoItemsUpdateOver200() {
    Test.startTest();

    List<Credit_Memo__c> cms = [SELECT Id FROM Credit_Memo__c LIMIT 1];

    List<Credit_Memo_Item__c> newcmis = new List<Credit_Memo_Item__c>();
    for(integer i = 0; i<201 ; i++){
        Credit_Memo_Item__c cmi = new Credit_Memo_Item__c();
        cmi.Credit_Memo__c = cms[0].Id;
        cmi.Description__c = 'cmi '+i;
        newcmis.add(cmi);
    }
    insert newcmis;


    List<Credit_Memo_Item__c> cmis = [SELECT Id, Description__c FROM Credit_Memo_Item__c LIMIT 201];
    for(integer i = 0; i<201 ; i++){
      cmis[i].Description__c = 'updated again '+i;
    }

    CreditMemoItemHandler_Update.UpdateCreditMemoItemsRequest request = new CreditMemoItemHandler_Update.UpdateCreditMemoItemsRequest();
    request.typeStr = 'Credit_Memo_Item__c';
    request.cmFields = 'Id, Name';
    request.cmiFields = 'Id, Name';
    request.cmiList = cmis;

    CreditMemoItemHandler_Update.CreditMemoItemsUpdateResult res = CreditMemoItemHandler_Update.CreditMemoItemsUpdate(request);

    List<Credit_Memo_Item__c> cmis2 = [SELECT Id, Description__c FROM Credit_Memo_Item__c WHERE Description__c='updated again 50' LIMIT 1];

    System.assert(cmis2.size() > 0, 'should have updated cmis');

    Test.stopTest();
  }

}