src/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/Credit_Memo_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Item</label>
    <nameField>
        <displayFormat>CMI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo_Item__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <label>Credit Memo</label>
    <referenceTo>Credit_Memo__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Description__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Description__c</fullName>
    <formula>Catalog_Item__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog description for the price book item. The price book item inherits this description from the linked catalog item by default. If the price book item has a description override, the price book item uses that description.</inlineHelpText>
    <label>Catalog Description</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item_Code__c</fullName>
    <formula>Catalog_Item__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog item code for the price book item. The price book item inherits this item code from the linked catalog item.</inlineHelpText>
    <label>Catalog Item Code</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Description_Override__c.field-meta.xml
<CustomField>
    <fullName>Description_Override__c</fullName>
    <description>Complete this field to override the catalog item description within this price book</description>
    <inlineHelpText>Catalog description for the price book item. This description overrides the catalog description inherited from the linked catalog item.</inlineHelpText>
    <label>Description Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Requires_Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Requires_Parent_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item and its parent price book item get added automatically to all new tickets.</inlineHelpText>
    <label>Requires Parent Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/CreditMemoItemHandler_PBISearch.cls
public class CreditMemoItemHandler_PBISearch
{

  public static String GetAvailablePBIsForCreditMemo(String processStr) {
      JSONParser parser = JSON.createParser(processStr);
      Type resultType = Type.forName('CreditMemoItemHandler_PBISearch.GetAvailablePBIsForCreditMemoRequest');
      CreditMemoItemHandler_PBISearch.GetAvailablePBIsForCreditMemoRequest readValueAsResults = (CreditMemoItemHandler_PBISearch.GetAvailablePBIsForCreditMemoRequest)parser.readValueAs(resultType);

      GetAvailablePBIsForCreditMemoResult result = GetAvailablePBIsForCreditMemo(readValueAsResults);

      return JSON.serializePretty(result, false);
  }

  public static GetAvailablePBIsForCreditMemoResult GetAvailablePBIsForCreditMemo(GetAvailablePBIsForCreditMemoRequest request) {
      String creditMemoId = request.creditMemoId;
      String showItemsAlreadyOnTheCreditMemo = request.showItemsAlreadyOnTheCreditMemo;
      String itemLimit = request.itemLimit;
      String itemOffset = request.itemOffset;
      String sortby = request.sortby;
      String sortdir = request.sortdir;
      String pbiFields = request.pbiFields;
      String creditMemoItemParentPBIId = request.creditMemoItemParentPBIId;

      String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
      GetAvailablePBIsForCreditMemoResult result = new GetAvailablePBIsForCreditMemoResult();

      if(!pbiFields.contains('Price_Book__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Price_Book__c';
      }
      if(!pbiFields.contains('Parent_Price_Book_Item__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Parent_Price_Book_Item__c';
      }
      if(!pbiFields.contains('Name')) {
        pbiFields += ', '+'Name';
      }
      if(!pbiFields.contains('Catalog_Item_Code__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Catalog_Item_Code__c';
      }
      if(!pbiFields.contains('Description_Override__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Description_Override__c';
      }
      if(!pbiFields.contains('Catalog_Description__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Catalog_Description__c';
      }
      if(!pbiFields.contains('PBI_Requires_Parent_Item__c')) {
        pbiFields += ', '+fxNamespacePrefix+'Requires_Parent_Item__c';
      }

      Set<Id> creditMemodPBIIds = new Set<Id>();

      for(Credit_Memo_Item__c cmi : [SELECT Id, Price_Book_Item__c FROM Credit_Memo_Item__c WHERE Credit_Memo__c=:creditMemoId]) {
        if (!creditMemodPBIIds.contains(cmi.Price_Book_Item__c)) {
            creditMemodPBIIds.add(cmi.Price_Book_Item__c);
        }
      }

      String commandText = 'SELECT ' + pbiFields + ' FROM ' + fxNamespacePrefix + 'Price_Book_Item__c ';
      commandText += ' WHERE IsDeleted=false ';
      commandText += ' AND Id IN :creditMemodPBIIds ';

      result.selectedPBIs = Database.query(commandText);

      commandText = 'SELECT ' + pbiFields + ' FROM ' + fxNamespacePrefix + 'Price_Book_Item__c ';
      commandText += ' WHERE IsDeleted=false ';
      commandText += ' AND ' + fxNamespacePrefix + 'Parent_Price_Book_Item__c = NULL ';

      if (showItemsAlreadyOnTheCreditMemo == 'false') {
          if (creditMemodPBIIds.size() > 0) {
              commandText += ' AND Id not in :creditMemodPBIIds ';
          }
      }

      if (creditMemoItemParentPBIId != null && creditMemoItemParentPBIId != '') {
          commandText += ' AND Id != :creditMemoItemParentPBIId ';
      }

      commandText += ItemBuilderHelper.GetFilterSoql(request.availablePBIfilters, '');

      String sb = (sortby != '') ? ' ORDER BY ' + sortby : '';
      String sd = (sb != '') ? (sortdir != null) ? sortdir : '' : '';
      String nullsLast = (sb != '') ? 'NULLS LAST' : '';
      commandText += sb + ' ' + sd + ' ' + nullsLast;

      String lim = (itemLimit != '' ) ? (Integer.valueOf(itemLimit) > 2000) ? '2000' : itemLimit : '2000';
      String off = (itemOffset != '' ) ? (Integer.valueOf(itemOffset) > 2000) ? '2000' : itemOffset : '0';
      commandText += ' LIMIT ' + lim + ' OFFSET ' + off + ' ';

      result.soql = commandText;

      result.availablePBIs = Database.query(commandText);

      Set<Id> availablePBIIds = new Map<Id, Price_Book_Item__c>(result.availablePBIs).keySet();

      commandText = 'SELECT '+pbiFields+' FROM ' + fxNamespacePrefix + 'Price_Book_Item__c WHERE ' + fxNamespacePrefix + 'Parent_Price_Book_Item__c IN :availablePBIIds';

      if (creditMemoItemParentPBIId != null && creditMemoItemParentPBIId != '') {
          commandText += ' AND Id != :creditMemoItemParentPBIId ';
      }

      result.childPBIs = Database.query(commandText);

      return result;
  }

  public static String GetCreditMemoAvailablePBISearchFilter() {
    String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
    String objName = fxNamespacePrefix+'Price_Book_Item__c';
    String searchFieldSetName = fxNamespacePrefix+'CMBSearchFields';
    List<ItemBuilderHelper.SearchFieldResult> pbiSearchFields = new List<ItemBuilderHelper.SearchFieldResult>();
    List<Schema.FieldSetMember> fields = new List<Schema.FieldSetMember>();

    Schema.FieldSet fieldSet = MetadataHelper.GetFieldSet(objName, searchFieldSetName);
  System.Debug(fieldSet);
    if (fieldSet != null) fields = fieldSet.getFields();

    SObjectType objType = Schema.getGlobalDescribe().get(objName);
    Schema.DescribeSObjectResult obj = objType.getDescribe();
    Map<String,Schema.SObjectField> fieldsMap = obj.fields.getMap();
    Schema.DescribeFieldResult priceBookFieldInfo = fieldsMap.get(fxNamespacePrefix+'Price_Book__c').getDescribe();

    Boolean found = false;
    if (fields != null) {
      pbiSearchFields = ItemBuilderHelper.ProcessSearchFieldSet(objName, searchFieldSetName);

      //look for pricebook in the filter fieldSet. If not there is needs to be added.

      String priceBookFieldInfoName = priceBookFieldInfo.getName();
      for(Schema.FieldSetMember field: fields) {
        if (field.getFieldPath() == priceBookFieldInfoName) {
          found = true;
          break;
        }
      }
    }
    if (!found) {
      ItemBuilderHelper.SearchFieldResult searchField = new ItemBuilderHelper.SearchFieldResult();
      if(priceBookFieldInfo.getReferenceTo().size()>0) {
        Schema.SObjectType reference = priceBookFieldInfo.getReferenceTo()[0];
        Schema.DescribeSObjectResult fieldObjDescribe = reference.getDescribe();
        searchField.keyPrefix = fieldObjDescribe.getKeyPrefix();
        searchField.ApiName = fieldObjDescribe.getName();
        searchField.label = fieldObjDescribe.getLabel();
        searchField.type = Schema.DisplayType.Reference;
      }

      pbiSearchFields.add(searchField);
    }

    GetCreditMemoAvailablePBISearchFilterResult result = new GetCreditMemoAvailablePBISearchFilterResult();
    result.pbiSearchFields = pbiSearchFields;
    result.keyPrefixesForObjects = ItemBuilderHelper.getKeyPrefixesForObjects();

    return JSON.serializePretty(result, false);
  }

  public class GetAvailablePBIsForCreditMemoRequest {
      public String creditMemoId;
      public String showItemsAlreadyOnTheCreditMemo;
      public String itemLimit;
      public String itemOffset;
      public String sortby;
      public String sortdir;
      public String pbiFields;
      public String creditMemoItemParentPBIId;
      public List<ItemBuilderHelper.SearchFieldRequest> availablePBIfilters;
  }

  public class GetAvailablePBIsForCreditMemoResult {
      public List<Price_Book_Item__c> selectedPBIs;
      public List<Price_Book_Item__c> availablePBIs;
      public List<Price_Book_Item__c> childPBIs;
      public string soql;
  }

  public class GetCreditMemoAvailablePBISearchFilterResult {
    public List<ItemBuilderHelper.SearchFieldResult> pbiSearchFields;
    public Map<String, String> keyPrefixesForObjects;
  }

}