src/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Status</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/Credit_Memo_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Item</label>
    <nameField>
        <displayFormat>CMI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo_Item__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <label>Credit Memo</label>
    <referenceTo>Credit_Memo__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Item</label>
    <referenceTo>Invoice_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Invoice__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Status</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Status record must have a record type of Invoice.</errorMessage>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Invoice_Item__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <formula>Invoice__r.CustomerAccount__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/AddTktItemsByPBSeqNum__c.field-meta.xml
<CustomField>
    <fullName>AddTktItemsByPBSeqNum__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, price book items, when added to a ticket, should honor the sequence number.  Otherwise they will be inserted at the end of the ticket.</description>
    <inlineHelpText>Controls whether users can change sequence numbers for price book items to adjust the order of item lists. If selected, users cannot change sequence numbers. If deselected, users can change sequence numbers and new items get added at the end of a list.</inlineHelpText>
    <label>Honor Sequence Number</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/CreditMemoItemHandler_InvoiceSearch_Test.cls
@isTest
public class CreditMemoItemHandler_InvoiceSearch_Test
{
  @testSetup
  static void setup()
  {
    Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);

    Account acc = AlpineTestHelper.CreateAccount('a1');

    RecordType statusRecordType = AlpineTestHelper.GetRecordType('Status__c');
    string newGuid = StringUtility.newGuid();

    string statusName = 'InvoiceStatus ' + newGuid;
    Status__c stI = new Status__c(Name = statusName, SObject__c='Invoice__c', Sync__c=true, Initial_Status_Console__c =true);

    insert stI;

    statusName = 'CMInitialStatus ' + newGuid;
    Status__c st = new Status__c(Name = statusName, SObject__c='Credit_Memo__c', Sync__c=true, Initial_Status_Console__c =true,  RecordTypeId=statusRecordType.Id);

    insert st;

    Credit_Memo__c cm = new Credit_Memo__c(CustomerAccount__c = acc.Id, Status__c = st.Id);
    insert cm;

    Credit_Memo_Item__c cmi = new Credit_Memo_Item__c();
    cmi.Credit_Memo__c = cm.Id;
    cmi.Description__c = 'cmi1';
    insert cmi;

    Invoice__c inv = new Invoice__c(CustomerAccount__c = j.CustomerAccount__c , Price_Book__c = j.Price_Book__c, Status__c = stI.Id );
    insert inv;

    Price_Book__c pb = [SELECT Id, AddTktItemsByPBSeqNum__c FROM Price_Book__c WHERE Id=:j.Price_Book__c ];
    pb.AddTktItemsByPBSeqNum__c = false;
    update pb;

    List<Price_Book_Item__c> pbiEquip = AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Equipment', true);
    List<Price_Book_Item__c> pbiLabor = AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Labor', true);

    List<Price_book_Item__c> sources  = [SELECT Id FROM Price_book_Item__c];
    List<Id> sourceIds = new List<Id>(new Map<Id, Price_book_Item__c>(sources).keySet());

    Decimal nextSeqNumber = 200;
    List<Invoice_Item__c> invItems = InvoiceItemHandler.CreateInvoiceItems(inv.Id, sourceIds, nextSeqNumber, null);


  }

  static testMethod void GetCreditMemoAvailableInvoiceSearchFilterTest()
  {
      Test.startTest();

      String res = CreditMemoItemHandler_InvoiceSearch.GetCreditMemoAvailableInvoiceSearchFilter();

      System.assert(!String.IsEmpty(res), 'should have a search filter');

      Test.stopTest();
  }

  static testMethod void GetAvailableInvoicesForCreditMemoTest()
  {
      Test.startTest();

      List<Credit_Memo__c> cms = [SELECT Id FROM Credit_Memo__c LIMIT 1];
System.debug(cms.size());


      CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoRequest request = new CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoRequest();
      request.creditMemoId = cms[0].Id;
      request.itemLimit = '2000';
      request.itemOffset = '0';
      request.sortby = 'Name';
      request.sortdir = 'ASC';
      request.invoiceFields = 'Id, Name';
      request.invoiceItemFields = 'Id, Name';
      request.creditMemoItemParentInvoiceItemId = null;
      request.invoicefilters = new List<ItemBuilderHelper.SearchFieldRequest>();
      request.invoiceItemfilters = new List<ItemBuilderHelper.SearchFieldRequest>();

      CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoResult res = CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemo(request);

      System.assert(res.availableInvoices.size() > 0, 'should have some invoices');

      Test.stopTest();
  }



}