src/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/Credit_Memo_Item__c.object-meta.xml
<CustomObject>
    <label>Credit Memo Item</label>
    <nameField>
        <displayFormat>CMI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memo Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Credit_Memo_Item__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <label>Credit Memo</label>
    <referenceTo>Credit_Memo__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Item</label>
    <referenceTo>Invoice_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Parent_Credit_Memo_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Credit_Memo_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Credit Memo Item.</description>
    <label>Parent Credit Memo Item</label>
    <referenceTo>Credit_Memo_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Credit_Memo_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Credit Memo Items</relationshipLabel>
    <relationshipName>Credit_Memo_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Invoice__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Parent_Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Invoice Item</label>
    <referenceTo>Invoice_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/CreditMemoItemHandler_InvoiceSearch.cls
public class CreditMemoItemHandler_InvoiceSearch
{

  public static String GetAvailableInvoicesForCreditMemo(String processStr) {
      JSONParser parser = JSON.createParser(processStr);
      Type resultType = Type.forName('CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoRequest');
      CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoRequest readValueAsResults = (CreditMemoItemHandler_InvoiceSearch.GetAvailableInvoicesForCreditMemoRequest)parser.readValueAs(resultType);

      GetAvailableInvoicesForCreditMemoResult result = GetAvailableInvoicesForCreditMemo(readValueAsResults);

      return JSON.serializePretty(result, false);
  }

  public static GetAvailableInvoicesForCreditMemoResult GetAvailableInvoicesForCreditMemo(GetAvailableInvoicesForCreditMemoRequest request) {
      String creditMemoId = request.creditMemoId;
      String itemLimit = request.itemLimit;
      String itemOffset = request.itemOffset;
      String sortby = request.sortby;
      String sortdir = request.sortdir;
      String invoiceFields = request.invoiceFields;
      String invoiceItemFields = request.invoiceItemFields;
      String creditMemoItemParentInvoiceItemId = request.creditMemoItemParentInvoiceItemId;

      String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
      GetAvailableInvoicesForCreditMemoResult result = new GetAvailableInvoicesForCreditMemoResult();

      if(!invoiceItemFields.contains('Invoice__c')) {
        invoiceItemFields += ', '+fxNamespacePrefix+'Invoice__c';
      }
      if(!invoiceItemFields.contains('Parent_Invoice_Item__c')) {
        invoiceItemFields += ', '+fxNamespacePrefix+'Parent_Invoice_Item__c';
      }
      if(!invoiceItemFields.contains('Name')) {
        invoiceItemFields += ', '+'Name';
      }
      if(!invoiceItemFields.contains('Item_Code__c')) {
        invoiceItemFields += ', '+fxNamespacePrefix+'Item_Code__c';
      }
      if(!invoiceItemFields.contains('Price_Book_Item__r.Name')) {
        invoiceItemFields += ', '+fxNamespacePrefix+'Price_Book_Item__r.Name';
      }
      if(!invoiceItemFields.contains('Description__c')) {
        invoiceItemFields += ', '+fxNamespacePrefix+'Description__c';
      }

      Credit_Memo__c creditMemo = [SELECT Id, Price_Book__c FROM Credit_Memo__c WHERE Id=:creditMemoId LIMIT 1];

      Set<Id> creditMemoedInvoiceIds = new Set<Id>();
      Set<Id> creditMemoedInvoiceItemIds = new Set<Id>();

      for(Credit_Memo_Item__c cmi : [SELECT Id, Invoice_Item__c, Invoice_Item__r.Invoice__c FROM Credit_Memo_Item__c WHERE Credit_Memo__c=:creditMemoId]) {
        if (!creditMemoedInvoiceIds.contains(cmi.Invoice_Item__r.Invoice__c)) {
            creditMemoedInvoiceIds.add(cmi.Invoice_Item__r.Invoice__c);
        }
        if (!creditMemoedInvoiceItemIds.contains(cmi.Invoice_Item__c)) {
            creditMemoedInvoiceItemIds.add(cmi.Invoice_Item__c);
        }
      }

      String commandText = 'SELECT ' + invoiceFields + ' FROM ' + fxNamespacePrefix + 'Invoice__c ';
      commandText += ' WHERE IsDeleted=false ';
      commandText += ' AND Id IN :creditMemoedInvoiceIds ';

      result.selectedInvoices = Database.query(commandText);

      commandText = 'SELECT ' + invoiceItemFields + ' FROM ' + fxNamespacePrefix + 'Invoice_Item__c ';
      commandText += ' WHERE IsDeleted=false ';
      commandText += ' AND Id IN :creditMemoedInvoiceItemIds ';

      result.selectedInvoiceItems = Database.query(commandText);

      String invoiceItemFilterSoql = ItemBuilderHelper.GetFilterSoql(request.invoiceItemfilters, '');
      String invoiceFilterSoql = ItemBuilderHelper.GetFilterSoql(request.invoicefilters, 'Invoice__r.');

      commandText = 'SELECT '+invoiceItemFields+', (SELECT Id FROM Credit_Memo_Items__r) FROM ' + fxNamespacePrefix + 'Invoice_Item__c WHERE ' + fxNamespacePrefix + 'Parent_Invoice_Item__c = NULL';
      commandText += invoiceFilterSoql;
      commandText += invoiceItemFilterSoql;

      if (creditMemoItemParentInvoiceItemId != null && creditMemoItemParentInvoiceItemId != '') {
          commandText += ' AND Id != :creditMemoItemParentInvoiceItemId ';
      }

      result.parentInvoiceItems = Database.query(commandText);

      commandText = 'SELECT '+invoiceItemFields+', (SELECT Id FROM Credit_Memo_Items__r) FROM ' + fxNamespacePrefix + 'Invoice_Item__c WHERE ' + fxNamespacePrefix + 'Parent_Invoice_Item__c != NULL';
      commandText += invoiceFilterSoql;
      commandText += invoiceItemFilterSoql;

      if (creditMemoItemParentInvoiceItemId != null && creditMemoItemParentInvoiceItemId != '') {
          commandText += ' AND Id != :creditMemoItemParentInvoiceItemId ';
      }

      result.childInvoiceItems = Database.query(commandText);

      Set<Id> availableInvIds = new Set<Id>();
      for (Invoice_Item__c ii : result.parentInvoiceItems) {
        if (!availableInvIds.contains(ii.Invoice__c))
        availableInvIds.add(ii.Invoice__c);
      }

      commandText = 'SELECT ' + invoiceFields + ' FROM ' + fxNamespacePrefix + 'Invoice__c ';
      commandText += ' WHERE IsDeleted=false ';
      commandText += ' AND Id IN :availableInvIds ';

      String sb = (sortby != '') ? ' ORDER BY ' + sortby : '';
      String sd = (sb != '') ? (sortdir != null) ? sortdir : '' : '';
      String nullsLast = (sb != '') ? 'NULLS LAST' : '';
      commandText += sb + ' ' + sd + ' ' + nullsLast;

      String lim = (itemLimit != '' ) ? (Integer.valueOf(itemLimit) > 2000) ? '2000' : itemLimit : '2000';
      String off = (itemOffset != '' ) ? (Integer.valueOf(itemOffset) > 2000) ? '2000' : itemOffset : '0';
      commandText += ' LIMIT ' + lim + ' OFFSET ' + off + ' ';

      result.availableInvoices = Database.query(commandText);


      return result;
  }

  public static String GetCreditMemoAvailableInvoiceSearchFilter() {
    String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
    String searchFieldSetName = fxNamespacePrefix+'CMBSearchFields';

    GetCreditMemoAvailableInvoiceSearchFilterResult result = new GetCreditMemoAvailableInvoiceSearchFilterResult();
    result.invoiceSearchFields = ItemBuilderHelper.ProcessSearchFieldSet(fxNamespacePrefix+'Invoice__c', searchFieldSetName);
    result.invoiceItemSearchFields = ItemBuilderHelper.ProcessSearchFieldSet(fxNamespacePrefix+'Invoice_Item__c', searchFieldSetName);
    result.keyPrefixesForObjects = ItemBuilderHelper.getKeyPrefixesForObjects();

    return JSON.serializePretty(result, false);
  }

  public class GetAvailableInvoicesForCreditMemoRequest {
      public String creditMemoId;
      public String itemLimit;
      public String itemOffset;
      public String sortby;
      public String sortdir;
      public String invoiceFields;
      public String invoiceItemFields;
      public String creditMemoItemParentInvoiceItemId;
      public List<ItemBuilderHelper.SearchFieldRequest> invoicefilters;
      public List<ItemBuilderHelper.SearchFieldRequest> invoiceItemfilters;
  }

  public class GetAvailableInvoicesForCreditMemoResult {
      public List<Invoice__c> selectedInvoices;
      public List<Invoice_Item__c> selectedInvoiceItems;
      public List<Invoice__c> availableInvoices;
      public List<Invoice_Item__c> childInvoiceItems;
      public List<Invoice_Item__c> parentInvoiceItems;
      public string soql;
  }

  public class GetCreditMemoAvailableInvoiceSearchFilterResult {
    public List<ItemBuilderHelper.SearchFieldResult> invoiceSearchFields;
    public List<ItemBuilderHelper.SearchFieldResult> invoiceItemSearchFields;
    public Map<String, String> keyPrefixesForObjects;
  }

}