src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>The work order is a representation of planned and actual work done to satisfy a need related to equipment such as a preventative maintenance action, a corrective maintenance action or an inspection.</description>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ij0000000wVH4EAM_00Nj0000008Hwq7EAC</fullName>
        <active>true</active>
        <field>Preventative_Maintenance_Schedule__c.Template_Work_Order__c</field>
        <filterItems>
            <field>Work_Order__c.IsTemplate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Preventative Maintenance Schedule_Templa</name>
    </namedFilters>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemplate</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the work order</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/EquipmentWorkOrderTemplatesController.cls
public with sharing class EquipmentWorkOrderTemplatesController
{
    Equipment__c EquipEntity {get;set;}
    public List<Work_Order__c> woTemplates {get;set;}
    public String TemplateWorkOrderId {get;set;}
    
    public EquipmentWorkOrderTemplatesController(ApexPages.StandardController ctrl)
    {
        Map<String, String> params = ApexPages.CurrentPage().getParameters();
        String idStr = params.get('Id');
        EquipEntity = [SELECT Id, Name FROM Equipment__c WHERE Id=:idStr];
        woTemplates = [SELECT Id, Name FROM Work_Order__c WHERE IsDeleted=false AND IsTemplate__c = true];
        
        if(params.containsKey('templateid'))
        {
            TemplateWorkOrderId = params.get('templateid');           
        }
    }    
   
    
    public PageReference CreateWorkOrder()
    {
        if(String.isBlank(TemplateWorkOrderId)) return null;        
        
        Schema.DescribeSObjectResult dsrServiceHistory = Service_History__c.sObjectType.getDescribe();
        if(!Equipment__c.sObjectType.getDescribe().isUpdateable() 
            || !Work_Order__c.sObjectType.getDescribe().isCreateable()
            || !dsrServiceHistory.isQueryable()
            || !dsrServiceHistory.isUpdateable())
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'User does NOT have permission(s) to update Equipment, create Work Order or update Service History. Please contact Administrator.'));
            return null;
        }
        Datetime dtNow = Datetime.now();
        
        EquipEntity.Out_of_Service__c = true;
        update EquipEntity;  
        
        String soql = MetadataHelper.GetSelectQuery(Work_Order__c.sObjectType.getDescribe());
        soql += ' WHERE Id=:TemplateWorkOrderId';
        
        Work_Order__c w = (Work_Order__c) Database.query(soql);
        Work_Order__c newWorkOrder = w.clone(false, false,false, false);
        newWorkOrder.Tracking_Number__c = null;
        newWorkOrder.SyncID__c = null;
        newWorkOrder.IsTemplate__c = false;
        newWorkOrder.Equipment__c = EquipEntity.Id;
        insert newWorkOrder;
        
        List<Service_History__c> shs = [SELECT Id FROM Service_History__c WHERE Equipment__c = :EquipEntity.Id AND Work_Order__c=null AND CreatedDate>= :dtNow ORDER BY CreatedDate desc];
        if(!shs.isEmpty())
        {
            Service_History__c sh = shs.get(0);
            sh.Work_Order__c = newWorkOrder.Id;
            update sh;
        }
        
        
        String pageUrl = URL.getSalesforceBaseUrl().toExternalForm() + '/' + EquipEntity.Id;
        PageReference p = new PageReference(pageUrl);
        p.setRedirect(true);
        return p;
    }
    
}