src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Equipment2__c.field-meta.xml
<CustomField>
    <fullName>Equipment2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Equipment Planning (Equipment)</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/EquipmentPlanningPlaceHolderBatchable.cls
public class EquipmentPlanningPlaceHolderBatchable extends FXBatchableBase
{    
    Boolean hasEquipField {get;set;}
    String ns {get;set;}
    
    public EquipmentPlanningPlaceHolderBatchable()
    {
        ns = StringUtility.FXNamespace();
        hasEquipField = Equipment_Planning__c.sObjectType.getDescribe().fields.getMap().containsKey(ns + 'Equipment__c');
        
        soqlQuery = hasEquipField? String.format('SELECT Id, {0}Equipment__c, {0}Equipment2__c FROM {0}Equipment_Planning__c WHERE {0}Equipment2__c=null', new String[]{ns})
            : String.format('SELECT Id FROM {0}Equipment_Planning__c LIMIT 1', new String[]{ns});
    }
   
    public override void execute(Database.BatchableContext BC, List<sObject> scope)
    {   
        if(!hasEquipField) return;
        
        List<Equipment_Planning__c> objs = (List<Equipment_Planning__c>)scope;
        for(Equipment_Planning__c o : objs)
        {
            o.put(ns + 'Equipment2__c', o.get(ns + 'Equipment__c'));
        }
        update objs;
    }    
}