src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Meter__c.field-meta.xml
<CustomField>
    <fullName>Meter__c</fullName>
    <label>Meter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Criterion__c/Preventative_Maintenance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Preventative Maintenance Criterion</label>
    <nameField>
        <displayFormat>PMC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preventative Maintenance Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Preventative_Maintenance_Criterion__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Criterion__c/fields/Last_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Last_Meter_Value__c</fullName>
    <label>Last Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Criterion__c/fields/Preventative_Maintenance_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Preventative_Maintenance_Schedule__c</fullName>
    <label>Preventative Maintenance Schedule</label>
    <referenceTo>Preventative_Maintenance_Schedule__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Criteria</relationshipLabel>
    <relationshipName>Preventative_Maintenance_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Criterion__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/Preventative_Maintenance_Schedule__c.object-meta.xml
<CustomObject>
    <label>Preventative Maintenance Schedule</label>
    <nameField>
        <displayFormat>PMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preventative Maintenance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Schedules</relationshipLabel>
    <relationshipName>Preventative_Maintenance_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Last_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Last_Meter_Value__c</fullName>
    <label>Last Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Previous_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Previous_Meter_Value__c</fullName>
    <label>Previous Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Returned_to_Service__c.field-meta.xml
<CustomField>
    <fullName>Returned_to_Service__c</fullName>
    <label>Returned to Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/classes/EquipmentHandler.cls
public class EquipmentHandler
{  
    public static void ApplyPMS(List<Equipment__c> items, Map<Id, Equipment__c> oldmap)
    {
        Set<Id> equipIds = oldMap.keySet();
        Datetime now = Datetime.now();

        Map<Id, Equipment__c> newmap = new Map<Id, Equipment__c>(items);

        Set<Id> equipWithChange = new Set<Id>();

        for(Preventative_Maintenance_Criterion__c c : [SELECT Id, Target_Field__c, Preventative_Maintenance_Schedule__r.Equipment__c FROM Preventative_Maintenance_Criterion__c WHERE IsDeleted=false AND Preventative_Maintenance_Schedule__r.IsActive__c=true AND  Preventative_Maintenance_Schedule__r.Equipment__c IN :equipIds AND Target_Field__c!=null AND Effective_Date__c<=:now AND (Expiration_Date__c=null OR Expiration_Date__c>:now)])
        {
            Id equipId = c.Preventative_Maintenance_Schedule__r.Equipment__c;
            Equipment__c newValues = newmap.get(equipId);
            Equipment__c oldValues = oldmap.get(equipId);

            if(newValues.get(c.Target_Field__c) != oldValues.get(c.Target_Field__c))
            {
                equipWithChange.add(equipId);
            }            
        }

        if(!equipWithChange.isEmpty())
        {
            System.enqueueJob(new WorkOrderSchedulerQueueable(equipWithChange)); 
        }
    }
    public static void ProcessOutOfServiceChanged(List<Equipment__c> items, Map<Id, Equipment__c> oldmap)
    {
        Set<Id> outOfService = new Set<Id>();
        Set<Id> backInService = new Set<Id>();
        
        for(Equipment__c e : items)
        {
            if(e.Out_of_Service__c == oldmap.get(e.Id).Out_of_Service__c) continue;
            if(e.Out_of_Service__c == true)
            {
                outOfService.add(e.Id);
            }            
            else if(e.Out_of_Service__c == false)
            {
                backInService.add(e.Id);
            }           
        }
        if(!outOfService.isEmpty())
        {
            CreateServiceHistory(outOfService);
        }
        if(!backInService.isEmpty())
        {
            UpdateServiceHistoryReturnToService(backInService );
        }
    }
    static void CreateServiceHistory(Set<Id> equipIds)
    {
        if(equipIds.isEmpty()) return;        
        List<Service_History__c> shs = new List<Service_History__c>();
        Map<Id, Service_History__c> equipSerHistory = new Map<Id, Service_History__c>();
       
        for(Id e : equipIds)
        {
            Service_History__c sh = new Service_History__c(Equipment__c = e, Out_of_Service__c = Datetime.now());
            equipSerHistory.put(e, sh);
        }        
        List<Equipment__c> equipItems = [SELECT Id, Meter__c, (SELECT Last_Meter_Value__c FROM Service_History__r ORDER BY CreatedDate DESC LIMIT 1) FROM Equipment__c WHERE Id IN :equipIds];
        for(Equipment__c e : equipItems)
        {
             Service_History__c sh = equipSerHistory.get(e.Id);
             sh.Last_Meter_Value__c = e.Meter__c;
             
             if(!e.Service_History__r.isEmpty())
             {
                 sh.Previous_Meter_Value__c = e.Service_History__r.get(0).Last_Meter_Value__c;
             }            
        }
        insert equipSerHistory.values();
    }
    
    static void UpdateServiceHistoryReturnToService(Set<Id> equipIds)
    {                   
        if(equipIds.isEmpty()) return;
        
        List<Equipment__c> equipItems = [SELECT Id, Meter__c, (SELECT Id, Returned_to_Service__c FROM Service_History__r ORDER BY CreatedDate DESC LIMIT 1) FROM Equipment__c WHERE Id IN :equipIds];
        
        List<Service_History__c> shsToUpdate = new List<Service_History__c>();
        
        Datetime dt = Datetime.now();        
        for(Equipment__c e : equipItems)
        {
             if(e.Service_History__r.isEmpty()) continue;  
             Service_History__c sh = e.Service_History__r.get(0);
             if(sh.Returned_to_Service__c != null) continue;
             sh.Returned_to_Service__c = dt; 
             shsToUpdate.add(sh);
        }      
        update shsToUpdate;
    }  
}