src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Meter__c.field-meta.xml
<CustomField>
    <fullName>Meter__c</fullName>
    <label>Meter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/Preventative_Maintenance_Schedule__c.object-meta.xml
<CustomObject>
    <label>Preventative Maintenance Schedule</label>
    <nameField>
        <displayFormat>PMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preventative Maintenance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Schedules</relationshipLabel>
    <relationshipName>Preventative_Maintenance_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/HasOpenWorkOrder__c.field-meta.xml
<CustomField>
    <fullName>HasOpenWorkOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>One or more WorkOrder with IsCompleted false value</description>
    <label>HasOpenWorkOrder</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/Last_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Last_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Schedules (Last Work Order)</relationshipLabel>
    <relationshipName>PMS</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Last_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Last_Meter_Value__c</fullName>
    <label>Last Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>The work order is a representation of planned and actual work done to satisfy a need related to equipment such as a preventative maintenance action, a corrective maintenance action or an inspection.</description>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ij0000000wVH4EAM_00Nj0000008Hwq7EAC</fullName>
        <active>true</active>
        <field>Preventative_Maintenance_Schedule__c.Template_Work_Order__c</field>
        <filterItems>
            <field>Work_Order__c.IsTemplate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Preventative Maintenance Schedule_Templa</name>
    </namedFilters>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCompleted</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemplate</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the work order</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Work_Order_Item__c/Work_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Work Order Item</label>
    <nameField>
        <displayFormat>WOI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Work_Order_Task__c/Work_Order_Task__c.object-meta.xml
<CustomObject>
    <label>Work Order Task</label>
    <nameField>
        <displayFormat>WT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order_Task__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Work_Order_Task__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Work_Order_Task__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Tasks</relationshipLabel>
    <relationshipName>Work_Order_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/WorkOrder_Test.cls
@isTest
private class WorkOrder_Test
{
    static testmethod void SetTrackingNumberSyncId_Test()
    {
        List<Work_Order__c> workOrders = AlpineTestHelper.CreateWorkOrders(null, 5, true);
        Set<Id> ids = new Map<Id, Work_Order__c>(workOrders).keySet();
        List<Work_Order__c> dbItems = [SELECT Id, Tracking_Number__c, SyncId__c FROM Work_Order__c WHERE Id IN :ids];
        for(Work_Order__c wo : dbItems )
        {
            System.assert(!String.isBlank(wo.Tracking_Number__c), 'TrackingNumber should have been set by insert trigger.');
            System.assert(!String.isBlank(wo.SyncId__c ), 'SyncId__c  should have been set by insert trigger.');            
        }
    }
    
    
    static testmethod void SetLastWorkOrderForPMS_Test()
    {   
        Test.startTest();     
        
        Work_Order__c workOrderTemplate = AlpineTestHelper.CreateWorkOrders(null, 1, false).get(0);
        workOrderTemplate.IsTemplate__c =true;
        insert workOrderTemplate;
        
        Preventative_Maintenance_Schedule__c pms = AlpineTestHelper.CreatePMS(workOrderTemplate, true);
        
        Preventative_Maintenance_Schedule__c  dbPMS = [SELECT Id, Last_Work_Order__c FROM Preventative_Maintenance_Schedule__c WHERE Id =:pms.Id];
        
        System.assert(String.isBlank(dbPMS.Last_Work_Order__c), 'Last_Work_Order__c should be null');        
        
        List<Work_Order__c> workOrders = AlpineTestHelper.CreateWorkOrders(pms, 1, true);
        
        Test.stopTest();
        
        dbPMS = [SELECT Id, Last_Work_Order__c FROM Preventative_Maintenance_Schedule__c WHERE Id =:pms.Id];
         
        System.assert(!String.isBlank(dbPMS.Last_Work_Order__c), 'Last_Work_Order__c should not be null after workOrder insertion.');  
        System.assertEquals(workOrders.get(0).Id, dbPMS.Last_Work_Order__c );      
    
        
    }


    static testmethod void FlagHasOpenOrderOnPMS_DeleteWorkOrder_Test()
    {   
           
        
        Work_Order__c workOrderTemplate = AlpineTestHelper.CreateWorkOrders(null, 1, false).get(0);
        workOrderTemplate.IsTemplate__c =true;
        insert workOrderTemplate;
        
        Preventative_Maintenance_Schedule__c pms = AlpineTestHelper.CreatePMS(workOrderTemplate, true);
        
        Preventative_Maintenance_Schedule__c  dbPMS = [SELECT Id, Last_Work_Order__c FROM Preventative_Maintenance_Schedule__c WHERE Id =:pms.Id];
        
        System.assert(String.isBlank(dbPMS.Last_Work_Order__c), 'Last_Work_Order__c should be null');        
        
        List<Work_Order__c> workOrders = AlpineTestHelper.CreateWorkOrders(pms, 1, true);
       
        Id workOrderId = workOrders.get(0).Id;


        Test.startTest();
        
        dbPMS = [SELECT Id, Last_Work_Order__c, HasOpenWorkOrder__c FROM Preventative_Maintenance_Schedule__c WHERE Id =:pms.Id];

        System.assert(!String.isBlank(dbPMS.Last_Work_Order__c), 'Last_Work_Order__c should not be null after workOrder insertion.');  
        System.assert(dbPMS.HasOpenWorkOrder__c==true, 'should have one open WorkOrder');

        delete [SELECT Id FROM Work_Order__c WHERE Id=:workOrderId];

        Test.stopTest();
         
        dbPMS = [SELECT Id, Last_Work_Order__c, HasOpenWorkOrder__c FROM Preventative_Maintenance_Schedule__c WHERE Id =:pms.Id];

        System.assert(String.isBlank(dbPMS.Last_Work_Order__c), 'Last_Work_Order__c should be null after workOrder deletion.');  
        System.assert(dbPMS.HasOpenWorkOrder__c==false, 'should have no open WorkOrder after workorder deletion');  
    
        
    }

    

    static testmethod void AssignWorkOrderToServiceHistory_Test()
    {
        Equipment__c e = AlpineTestHelper.CreateEquipment(false);
        String meterValue = '5900';
        e.Meter__c = meterValue;
        insert e;

        Datetime outDate= Datetime.now().addDays(-5);

        Service_History__c sh = new Service_History__c(Equipment__c = e.Id, Last_Meter_Value__c = meterValue, Out_of_Service__c = outDate);
        insert sh;

        Work_Order__c wo = AlpineTestHelper.CreateWorkOrders(null, 1, false).get(0);
        wo.Equipment__c = e.Id;
        wo.IsTemplate__c = false;
        insert wo;

        Test.startTest();
        Work_Order__c dbItem  = [SELECT Id, IsCompleted__c FROM Work_Order__c WHERE Id=:wo.Id];
        dbItem.IsCompleted__c = true;
        update dbItem;
        Test.stopTest();

        Service_History__c shResult = [SELECT Id, Work_Order__c FROM Service_History__c WHERE Id=:sh.Id];

        
        System.assert(shResult.Work_Order__c == wo.Id, 'Completing a WorkOrder should assign the WorkOrder ID to a ServiceHistory entry');        
    }

    static testmethod void SyncID_Test()
    {
        Test.startTest();
        Work_Order__c wo = AlpineTestHelper.CreateWorkOrders(null, 1, false).get(0);
        System.assert(String.isBlank(wo.SyncID__c), 'Before insert SyncID has null default value');

        insert wo;

        Work_Order__c dbwo = [SELECT Id, SyncID__c FROM Work_Order__c WHERE id=:wo.Id];
        System.assert(!String.isBlank(dbwo.SyncID__c), 'Insert Trigger should set SyncID');        
       

        Work_Order_Task__c task1 = new Work_Order_Task__c(Work_Order__c = dbwo.Id, Sequence_Number__c = 10) ;
        insert task1;

        Work_Order_Task__c task2 = [SELECT Id, SyncID__c FROM Work_Order_Task__c WHERE id=:task1.Id];
        System.assert(!String.isBlank(task2.SyncID__c), 'Insert Trigger should set Work_Order_Task__c SyncID');
        
        

        Work_Order_Item__c wi = new Work_Order_Item__c(Work_Order__c = dbwo.Id) ;
        insert wi;
        Work_Order_Item__c workItem  = [SELECT Id, SyncID__c FROM Work_Order_Item__c WHERE id=:wi.Id];
        System.assert(!String.isBlank(workItem.SyncID__c), 'Insert Trigger should set Work_Order_Item__c SyncID');        
       
    }

}