src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>The work order is a representation of planned and actual work done to satisfy a need related to equipment such as a preventative maintenance action, a corrective maintenance action or an inspection.</description>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ij0000000wVH4EAM_00Nj0000008Hwq7EAC</fullName>
        <active>true</active>
        <field>Preventative_Maintenance_Schedule__c.Template_Work_Order__c</field>
        <filterItems>
            <field>Work_Order__c.IsTemplate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Preventative Maintenance Schedule_Templa</name>
    </namedFilters>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemplate</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/EquipmentWorkOrderTemplatesCtrl_Test.cls
@isTest
private class EquipmentWorkOrderTemplatesCtrl_Test
{
    static testmethod void RunTest()
    {
        Test.startTest();
        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);
        
        List<Work_Order__c> workOrders = AlpineTestHelper.CreateWorkOrders(null, 5, false);
        for(Work_Order__c wo: workOrders)
        {
            wo.IsTemplate__c = true;
        }
        insert workOrders;      
        
        PageReference p = Page.EquipmentWorkOrderTemplates;
        p.getParameters().put('templateid', workOrders.get(0).Id);
        p.getParameters().put('id', equip.Id);        

        Test.setCurrentPage(p);
        
        EquipmentWorkOrderTemplatesController ctrl = new EquipmentWorkOrderTemplatesController(new ApexPages.StandardController(equip));

        ctrl.CreateWorkOrder();        
        Test.stopTest();
        
        Integer workOrderCount = [SELECT Count() FROM Work_Order__c WHERE Equipment__c = :equip.Id];
        System.assert(workOrderCount == 1, 'Should have a workOrder created');
        
        Integer shCount = [SELECT Count() FROM Service_History__c WHERE Equipment__c = :equip.Id];
        System.assert(workOrderCount == 1, 'Should have a Service_History__c created');
        
        Equipment__c e = [SELECT Out_of_Service__c FROM Equipment__c WHERE Id=:equip.Id];
        System.assert(e.Out_of_Service__c ==true, 'Equipment should have Out_of_Service__c =true'); 
        
    }
    
    
    
    
}