src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Meter__c.field-meta.xml
<CustomField>
    <fullName>Meter__c</fullName>
    <label>Meter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Last_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Last_Meter_Value__c</fullName>
    <label>Last Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Previous_Meter_Value__c.field-meta.xml
<CustomField>
    <fullName>Previous_Meter_Value__c</fullName>
    <label>Previous Meter Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Returned_to_Service__c.field-meta.xml
<CustomField>
    <fullName>Returned_to_Service__c</fullName>
    <label>Returned to Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/classes/EquipmentHandler_Test.cls
@isTest
private class EquipmentHandler_Test
{
    static testmethod void SetEquipOutOfService_Test()
    {
        Equipment__c e = AlpineTestHelper.CreateEquipment(false);
        String meterValue = '5000';
        e.Meter__c = meterValue;
        insert e;
        Test.startTest();
        e.Out_of_Service__c = true;
        update e;
        Test.stopTest();
        
        List<Service_History__c> shs = [SELECT Id, Last_Meter_Value__c, Previous_Meter_Value__c, Equipment__c FROM Service_History__c WHERE Equipment__c =:e.Id];
        
        System.assert(shs.size()==1, 'set Equipment out of service should create a ServiceHistory');
        System.assert(shs.get(0).Last_Meter_Value__c == meterValue , 'ServiceHistory should have Equipment meter value: ' + meterValue  + ', but instead having ' + shs.get(0).Last_Meter_Value__c);
    }
    
    static testmethod void ReturnEquipToService_Test()
    {
        Equipment__c e = AlpineTestHelper.CreateEquipment(false);
        String meterValue = '5000';
        e.Meter__c = meterValue;
        e.Out_of_Service__c = true;
        insert e;
      
        Datetime outDate= Datetime.now().addDays(-5);
        
        Service_History__c sh = new Service_History__c(Equipment__c = e.Id, Last_Meter_Value__c = meterValue, Out_of_Service__c = outDate);
        insert sh;
        
        Test.startTest();        
        e.Out_of_Service__c = false;
        update e;        
        Test.stopTest();
        
        
        Datetime dtNow = Datetime.now();
        
        List<Service_History__c> shs = [SELECT Id, Last_Meter_Value__c, Previous_Meter_Value__c, Equipment__c, Returned_to_Service__c FROM Service_History__c WHERE Equipment__c =:e.Id];        
        
         
        System.assert(shs.get(0).Returned_to_Service__c !=null, 'Return Equipment to service should update Datetime Returned_to_Service__c');
        
    }
    
    
    static testmethod void UpdateServiceHistoryPreviousMeterValue_Test()
    {
        Equipment__c e = AlpineTestHelper.CreateEquipment(false);
        String meterValue = '5000';
        e.Meter__c = meterValue;
        insert e;
        
        Datetime outDate= Datetime.now().addDays(-5);
        Service_History__c sh = new Service_History__c(Equipment__c = e.Id, Last_Meter_Value__c = meterValue, Out_of_Service__c = outDate);
        insert sh;
        
      
        
        Test.startTest();
        
        String newMeterValue = '9500';
        Equipment__c dbItem = [SELECT Id, Meter__c, Out_of_Service__c  FROM Equipment__c where Id=:e.Id];
        dbItem.Meter__c = newMeterValue;
        dbItem.Out_of_Service__c = true;
        update dbItem;       
        
          
       
        Test.stopTest();
        
        List<Service_History__c> shs = [SELECT Id, Last_Meter_Value__c, Previous_Meter_Value__c, Equipment__c FROM Service_History__c WHERE Equipment__c =:e.Id AND Id != :sh.Id];    
      
        
        System.assert(shs.size()==1, 'Every time setting Equipment out of service should create a ServiceHistory');
        
        System.assert(shs.get(0).Last_Meter_Value__c == newMeterValue, 'ServiceHistory should have Equipment meter value: ' + newMeterValue+ ', but instead having ' + shs.get(0).Last_Meter_Value__c);
        
        System.assert(shs.get(0).Previous_Meter_Value__c == meterValue, 'ServiceHistory should have Previous_Meter_Value__c value: ' + meterValue+ ', but instead having ' + shs.get(0).Previous_Meter_Value__c );
        
    }
    
    
}