src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out of Service</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/Preventative_Maintenance_Schedule__c.object-meta.xml
<CustomObject>
    <label>Preventative Maintenance Schedule</label>
    <nameField>
        <displayFormat>PMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preventative Maintenance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Schedules</relationshipLabel>
    <relationshipName>Preventative_Maintenance_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/HasOpenWorkOrder__c.field-meta.xml
<CustomField>
    <fullName>HasOpenWorkOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>One or more WorkOrder with IsCompleted false value</description>
    <label>HasOpenWorkOrder</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/Last_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Last_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Preventative Maintenance Schedules (Last Work Order)</relationshipLabel>
    <relationshipName>PMS</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Service_History__c/Service_History__c.object-meta.xml
<CustomObject>
    <label>Service History</label>
    <nameField>
        <displayFormat>ESH-{0000}</displayFormat>
        <label>Service History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Service_History__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Out_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Service__c</fullName>
    <label>Out of Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Returned_to_Service__c.field-meta.xml
<CustomField>
    <fullName>Returned_to_Service__c</fullName>
    <label>Returned to Service</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Service_History__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Service History</relationshipLabel>
    <relationshipName>Service_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>The work order is a representation of planned and actual work done to satisfy a need related to equipment such as a preventative maintenance action, a corrective maintenance action or an inspection.</description>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ij0000000wVH4EAM_00Nj0000008Hwq7EAC</fullName>
        <active>true</active>
        <field>Preventative_Maintenance_Schedule__c.Template_Work_Order__c</field>
        <filterItems>
            <field>Work_Order__c.IsTemplate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Preventative Maintenance Schedule_Templa</name>
    </namedFilters>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Work_Order__c/fields/Actual_Finish_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Finish_Date__c</fullName>
    <label>Actual Finish Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCompleted</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemplate</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/Source_PMS__c.field-meta.xml
<CustomField>
    <fullName>Source_PMS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Source PMS</label>
    <referenceTo>Preventative_Maintenance_Schedule__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Work_Order__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the work order</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/WorkOrderHandler.cls
public class WorkOrderHandler
{
    public static void SetTrackingNumberSyncId(List<Work_Order__c> workOrders)
    {        
        for(Work_Order__c w : workOrders)
        {
            if(String.isBlank(w.Tracking_Number__c))
            {
              w.Tracking_Number__c = StringUtility.getTrackingNumber('W-');
            }
            if(String.isBlank(w.SyncID__c))
            {
                w.SyncID__c =  StringUtility.newGuid();
            }
        }
    }
    
    
    public static void SetActualFinishDate(List<Work_Order__c> workOrders)
    {        
        for(Work_Order__c w : workOrders)
        {
            if(w.IsCompleted__c == true && w.Actual_Finish_Date__c == null )
            {
              w.Actual_Finish_Date__c = Datetime.now();
            }           
        }
    }
    
    public static void ProcessWorkOrderCompleted(List<Work_Order__c> workOrders, Map<Id, Work_Order__c> oldMap)
    {
        Map<Id, Id> equipWorkOrder = new Map<Id, Id>();
        for(Work_Order__c wo: workOrders)
        {
            if(wo.IsCompleted__c == true && (oldMap == null || oldMap.get(wo.Id).IsCompleted__c !=true))
            {
                if(!String.isBlank(wo.Equipment__c)) 
                {  
                    equipWorkOrder.put(wo.Equipment__c, wo.Id);
                }
            }
        }
        Datetime dt = Datetime.now();
        Set<Id> equipIds = equipWorkOrder.keySet();
        List<Id> woIds = equipWorkOrder.values();
        
        List<Service_History__c> shs = [SELECT Id, Equipment__c, Returned_to_Service__c FROM Service_History__c WHERE Work_Order__c IN :woIds AND Returned_to_Service__c=null];
        for(Service_History__c sh: shs)
        {
            sh.Returned_to_Service__c = dt;
            equipWorkOrder.remove(sh.Equipment__c);
        }
        update shs;
        
        Map<Id, Equipment__c> equipItems = new Map<Id, Equipment__c>([SELECT Id, Out_of_Service__c, (SELECT Id FROM Service_History__r WHERE Work_Order__c=null AND Returned_to_Service__c=null ORDER BY CreatedDate LIMIT 1) FROM Equipment__c WHERE Id IN :equipIds]);
           
           
        if(!equipWorkOrder.isEmpty())
        {
            Set<Id> equipWithNoServiceHistory = equipWorkOrder.keySet();
            List<Service_History__c> shToUpdate = new List<Service_History__c>();
           
            for(Id equipId : equipWithNoServiceHistory)                
            {
                Equipment__c e = equipItems.get(equipId);
                if(e.Service_History__r.isEmpty()) continue;
                Service_History__c sh = e.Service_History__r.get(0);
                sh.Work_Order__c = equipWorkOrder.get(e.Id);
                sh.Returned_to_Service__c = dt;
                shToUpdate.add(sh);                
            }
            update shToUpdate;
        }
        
        List<Equipment__c> equipToUpdate = new List<Equipment__c >();
        for(Equipment__c e: equipItems.values())
        {
            if(e.Out_of_Service__c == false) continue;
            e.Out_of_Service__c = true;
            equipToUpdate.add(e);
        }
        update equipToUpdate;
        
    }
    
    public static List<Preventative_Maintenance_Schedule__c> SetLastWorkOrderForPMS(List<Work_Order__c> workOrders, Boolean autoSave)
    {     
        List<Preventative_Maintenance_Schedule__c> pmsItems = new List<Preventative_Maintenance_Schedule__c>();
           
        Set<Id> pmsIds = new Set<Id>();
        
        Map<Id, Id> pmsLastWorkOrder = new Map<Id, Id>();
        for(Work_Order__c w : workOrders)
        {            
            if(String.isBlank(w.Source_PMS__c)) continue;
            pmsIds.add(w.Source_PMS__c);   
            pmsLastWorkOrder.put(w.Source_PMS__c, w.Id);
                             
        }
         
        
        if(pmsIds.isEmpty()) return pmsItems;
        
        for(Preventative_Maintenance_Schedule__c pms : [SELECT Id, Last_Work_Order__c FROM Preventative_Maintenance_Schedule__c WHERE Id IN :pmsIds])
        {         
            pms.Last_Work_Order__c = pmsLastWorkOrder.get(pms.Id);
            pmsItems.add(pms);
        }
        if(autoSave==true) Database.update(pmsItems , false);
        return pmsItems;
    }
    
    public static List<Preventative_Maintenance_Schedule__c> FlagHasOpenOrderOnPMS(List<Work_Order__c> workOrders, Boolean autoSave)
    {   
      
        Set<Id> pmsIds = new Set<Id>();
        for(Work_Order__c w : workOrders)
        {            
            if(String.isBlank(w.Source_PMS__c)) continue;
            pmsIds.add(w.Source_PMS__c);                             
        }
        
        List<Preventative_Maintenance_Schedule__c> pms = [SELECT Id, HasOpenWorkOrder__c, (SELECT Id FROM Work_Orders__r WHERE IsCompleted__c=false AND IsTemplate__c=false) FROM Preventative_Maintenance_Schedule__c WHERE Id IN :pmsIds];
        
        List<Preventative_Maintenance_Schedule__c> pmsToUpdate = new List<Preventative_Maintenance_Schedule__c>();
        
        for(Preventative_Maintenance_Schedule__c p : pms)
        {
            if(p.HasOpenWorkOrder__c == !p.Work_Orders__r.isEmpty()) continue;            
            p.HasOpenWorkOrder__c = !p.Work_Orders__r.isEmpty();
            pmsToUpdate.add(p);            
        }
        if(autoSave==true) Database.update(pmsToUpdate, false);
        return pmsToUpdate;
    } 
}