src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the equipment is scheduled for use.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Job_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Price book item for the equipment.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the job syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office that uses the price book. If an office is not selected, the price book is available for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books (Office)</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>PriceBookRules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/Price_Book_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>These actions are triggered by the criteria on the Rule object for the CPQ module.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Rule Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule_Action__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule action is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>Price_Book_Rule__r.Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the rule action.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Price_Book_Rule_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Rule__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Rule__c</fullName>
    <inlineHelpText>Rule for which the rule action is used.</inlineHelpText>
    <label>Rule</label>
    <referenceTo>Price_Book_Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Indicates whether the linked price book item is required, recommended, or disallowed for a ticket.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
                <default>true</default>
                <label>Required</label>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Disallowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Job__r.Office__r.Name</formula>
    <inlineHelpText>Office responsible for performing the work listed on the ticket.</inlineHelpText>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sync bit to flag on/off item for download</description>
    <inlineHelpText>If selected, the ticket syncs to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Ticket__r.Job__r.Office__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/SObjectCloner_Test.cls
@isTest
private class SObjectCloner_Test
{

    static testMethod void ClonerWithFilter_Test()
    {
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(job, 2, true);

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(2, job.Price_Book__c, 'Equipment', true);

        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();

        List<Ticket__c> dbTkts = [SELECT Id FROM Ticket__c WHERE Job__c =:job.Id];
        Ticket__c tkt1 = dbTkts.get(0);
        Ticket__c tkt2 = dbTkts.get(1);
        tkt1.Sync__c = true;
        tkt2.Sync__c = false;
        update dbTkts;


        tktItems.add(new Ticket_Item__c(Ticket__c = tkt1.Id, Price_Book_Item__c = pbItems.get(0).Id));
        tktItems.add(new Ticket_Item__c(Ticket__c = tkt2.Id, Price_Book_Item__c = pbItems.get(1).Id));
        
        insert tktItems;

        Test.startTest();

        Integer count = [SELECT COUNT() FROM Ticket_Item__c WHERE Ticket__c =:tkt2.Id];
        System.assert(count == 1, 'BEFORE: should have 1 ticket item instead of ' + count);

        
        String ns = StringUtility.FXNamespace();

        String sources = job.Id;

        

        String cloningtypes = 'ns__Ticket__c{ns__Sync__c=true},ns__Ticket_Item__c';
        cloningtypes = cloningtypes.replace('ns__', ns); 
        
        System.debug(SObjectCloner.DeepCopy(job.Id, cloningtypes));

        Test.stopTest();
        count = [SELECT COUNT() FROM Ticket_Item__c];
        System.assert(count == 3, 'AFTER: should have total 3 ticket item, instead of ' + count);
        
        count = [SELECT COUNT() FROM Ticket_Item__c WHERE Ticket__c =:tkt1.Id];
        System.assert(count == 1, 'AFTER: should have 1 ticket item on tkt1, instead of ' + count);
        
        count = [SELECT COUNT() FROM Ticket_Item__c WHERE Ticket__c =:tkt2.Id];
        System.assert(count == 1, 'AFTER: should have 1 ticket item on tkt2, instead of ' + count);
    }

    static testMethod void CommandCloner_DryRun_Test()
    {

        List<Job__c> jobs = AlpineTestHelper.CreateJobs(2, true);
        AlpineTestHelper.CreateTickets(jobs.get(0), 20, true);
        Test.startTest();
        Set<Id> jobIds = new Map<Id, Job__c>(jobs).keySet();
        String ns = StringUtility.FXNamespace();

        String sources = StringUtility.GetJoinedString(jobIds);

        Map<String, Object> params = new Map<String, Object>();
        params.put('sources', sources);
        params.put('cloningtypes', String.format('{0}Crew_Planning__c,{0}Equipment_Planning__c,{0}Ticket__c,{0}Ticket_Item__c', new String[]{ns})); 
       

        System.debug(FXBatchableLauncher.Run(ns + 'SObjectClonerBatchable', params, true));

        Test.stopTest();
    }
    
    static testMethod void CommandCloner_Test()
    {
        List<Job__c> jobs = AlpineTestHelper.CreateJobs(2, true);
        AlpineTestHelper.CreateTickets(jobs.get(0), 20, true);
        Test.startTest();
        Set<Id> jobIds = new Map<Id, Job__c>(jobs).keySet();
        String ns = StringUtility.FXNamespace();

        String sources = StringUtility.GetJoinedString(jobIds);

        Map<String, Object> params = new Map<String, Object>();
        params.put('sources', sources);
        params.put('cloningtypes', String.format('{0}Crew_Planning__c,{0}Equipment_Planning__c,{0}Ticket__c,{0}Ticket_Item__c', new String[]{ns}));
 
        FXBatchableLauncher.Run(ns + 'SObjectClonerBatchable', params);

        Test.stopTest();
    }

    static testMethod void SObjectCloner_Test() 
    {
        Test.startTest();

        Integer level1Count = 20;
        Integer level2Count = 20;

        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Integer sourceCount = [SELECT COUNT() FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id];
        System.assert(sourceCount == level1Count + level2Count, 'should have ' + (level1Count + level2Count) + ' source items, instead of ' + sourceCount);
        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;

    
        String cloneTypes = '[ns]Price_Book_Item__c,[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        String newId = SObjectCloner.DeepCopy(pb.Id, cloneTypes, SObjectCloner.ExecMode.Sync);       
        sObject copyItem = SObjectDescribeInfo.GetSObject(Id.valueOf(newId));
       
        Test.stopTest();

        System.debug('copy=' + copyItem);

        
        Price_Book__c pbNew =  (Price_Book__c)copyItem;

        List<Price_Book_Item__c> allItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(level1Count + level2Count, allItems.size());


        List<Price_Book_Item__c> level2Items = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id AND Parent_Price_Book_Item__c!=null];
        System.assertEquals(level2Count, level2Items.size());

        List<Price_Book_Rule__c> newRules = [SELECT Id FROM Price_Book_Rule__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(1, newRules.size());

        List<Price_Book_Rule_Action__c> newRuleActions = [SELECT Id FROM Price_Book_Rule_Action__c WHERE Price_Book_Rule__r.Price_Book__c=:pbNew.Id AND Price_Book_Item__r.Price_Book__c =:pbNew.Id];
        System.assertEquals(1, newRuleActions.size());


    }


    static testMethod void SObjectCloner_DryRun_Test() 
    {
        Test.startTest();

        Integer level1Count = 100;
        Integer level2Count = 20;

        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;

    
        String cloneTypes = '[ns]Price_Book__c,[ns]Price_Book_Item__c,[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        String str = SObjectCloner.DryRun(pb.Id, cloneTypes);       
       
        Test.stopTest();
    }


    static testMethod void SObjectCloner_DeepCopyAsync_Test() 
    {
        Test.startTest();

        Integer level1Count = 100;
        Integer level2Count = 20;

        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;
   
        String cloneTypes = '[ns]Price_Book__c,[ns]Price_Book_Item__c,[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        String str = SObjectCloner.DeepCopy(pb.Id, cloneTypes, SObjectCloner.ExecMode.Async);       
       
        Test.stopTest();
    }

    static Price_Book_Rule__c CreateRule(Id pbId)
    {
        String ns = StringUtility.FXNamespace();
        String fieldName = ns + 'Job__r.' + ns + 'Office__r.Name';

        String criteria = fieldName + '!=\'Houston\'';

        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"!=\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"Houston\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', fieldName);
        Price_Book_Rule__c r = new Price_Book_Rule__c(Price_Book__c = pbId, 
            IsActive__c=true, Criteria__c=criteria, Applies_To__c='Ticket__c',
            CriteriaQueryFields__c = fieldName,
            CriteriaStack__c = criteriaStack);

        if (AlpineTestHelper.HasCurrencyIso()) {
            r.put('CurrencyIsoCode', 'USD');
        }
        insert r;
        return r;
    }
    static testMethod void DeepCopyPriceBook_VF_Test() 
    {
        Test.startTest();

        Integer level1Count = 40;
        Integer level2Count = 40;

        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;

        PageReference p = Page.sObjectEntityCloner;
        String ns = StringUtility.FXNamespace();
        String cloneTypes = '[ns]Price_Book__c,[ns]Price_Book_Item__c,[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', ns);

        p.getParameters().put('id', pb.Id);
        p.getParameters().put('cloningtypes', cloneTypes);
        p.getParameters().put('sync', '');
        Test.setCurrentPage(p);        
        sObjectCloningController ctrl = new sObjectCloningController();  
        ctrl.redirect();
       
        Test.stopTest();

        System.debug('copy=' + ctrl.EntityCopy);

        
        Price_Book__c pbNew =  (Price_Book__c)ctrl.EntityCopy;

        List<Price_Book_Item__c> allItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(level1Count + level2Count, allItems.size());


        List<Price_Book_Item__c> level2Items = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id AND Parent_Price_Book_Item__c!=null];
        System.assertEquals(level2Count, level2Items.size());

        List<Price_Book_Rule__c> newRules = [SELECT Id FROM Price_Book_Rule__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(1, newRules.size());

        List<Price_Book_Rule_Action__c> newRuleActions = [SELECT Id FROM Price_Book_Rule_Action__c WHERE Price_Book_Rule__r.Price_Book__c=:pbNew.Id AND Price_Book_Item__r.Price_Book__c =:pbNew.Id];
        System.assertEquals(1, newRuleActions.size());
 

    }

    static testMethod void DeepCopyPriceBook_VF_WithCustomFilter_Test() 
    {
        Test.startTest();

        Integer level1Count = 5;
        Integer level2Count = 5;

        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;

        PageReference p = Page.sObjectEntityCloner;
        String cloneTypes = '[ns]Price_Book__c,[ns]Price_Book_Item__c{[ns]Parent_Price_Book_Item__c=null},[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        p.getParameters().put('id', pb.Id);
        p.getParameters().put('cloningtypes', cloneTypes);
        p.getParameters().put('sync', cloneTypes);
        Test.setCurrentPage(p);        
        sObjectCloningController ctrl = new sObjectCloningController();         
        ctrl.redirect();
       
        Test.stopTest();

        System.debug('copy=' + ctrl.EntityCopy);

        
        Price_Book__c pbNew =  (Price_Book__c)ctrl.EntityCopy;

        List<Price_Book_Item__c> allItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(level1Count, allItems.size());
    

        List<Price_Book_Rule__c> newRules = [SELECT Id FROM Price_Book_Rule__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(1, newRules.size());

        List<Price_Book_Rule_Action__c> newRuleActions = [SELECT Id FROM Price_Book_Rule_Action__c WHERE Price_Book_Rule__r.Price_Book__c=:pbNew.Id AND Price_Book_Item__r.Price_Book__c =:pbNew.Id];
        System.assertEquals(1, newRuleActions.size());
 

    }

    static testMethod void DeepCopyPriceBook_VF_WithCustomStringFilter_Test() 
    {
        Test.startTest();

        Integer level1Count = 5;
        Integer level2Count = 5;
        Integer supplyCount = 5;


        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(level1Count, pb.Id, 'Equipment', true);
        List<Price_Book_Item__c> supplyItems = AlpineTestHelper.CreatePriceBookItems(supplyCount, pb.Id, 'Supply', true);

        List<Price_Book_Item__c> childPbItems = AlpineTestHelper.CreatePriceBookItems(level2Count, pb.Id, 'Equipment', false);
        Integer i = 0;
        for(Price_Book_Item__c c : childPbItems)
        {
            Price_Book_Item__c parent = pbItems.get(i);
            c.Parent_Price_Book_Item__c = parent.Id;
            i++;
        }
        insert childPbItems;

        Price_Book_Rule__c r = CreateRule(pb.Id);

        Price_Book_Rule_Action__c ra = new Price_Book_Rule_Action__c(Price_Book_Rule__c = r.Id, Price_Book_Item__c = pbItems.get(0).Id, Type__c = 'Required');
        insert ra;

        PageReference p = Page.sObjectEntityCloner;
        String cloneTypes = '[ns]Price_Book__c,[ns]Price_Book_Item__c{[ns]Parent_Price_Book_Item__c=null AND [ns]Ticket_Item_Record_Type__c=\'Equipment\'},[ns]Price_Book_Rule__c,[ns]Price_Book_Rule_Action__c'.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        p.getParameters().put('id', pb.Id);
        p.getParameters().put('cloningtypes', cloneTypes);
         p.getParameters().put('sync', '');
        Test.setCurrentPage(p);        
        sObjectCloningController ctrl = new sObjectCloningController();         
        ctrl.redirect();
       
        Test.stopTest();

        System.debug('copy=' + ctrl.EntityCopy);

        
        Price_Book__c pbNew =  (Price_Book__c)ctrl.EntityCopy;

        List<Price_Book_Item__c> allItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c=:pbNew.Id];
        System.assertEquals(level1Count, allItems.size());      
 

    }

}