src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/CrewPlanningTriggerHandler.cls
public class CrewPlanningTriggerHandler extends FXTriggerHandler
{
    public override void OnBeforeInsert(List<sObject> items)
    {
    	JobQualificationHandler.ValidateQualifications((List<Crew_Planning__c>)items);
        JobResourcePlanning.ApplyContactPriceBookItem((List<Crew_Planning__c>)items);
    }
    
    public override void OnBeforeUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    { 
    	JobQualificationHandler.ValidateQualifications((List<Crew_Planning__c>)items);

    	List<Crew_Planning__c> itemsForSyncAssign = new List<Crew_Planning__c>();
        List<Crew_Planning__c> itemsForResourcePlanning = new List<Crew_Planning__c>();

    	List<Crew_Planning__c> cps = (List<Crew_Planning__c>)items;

        for(Crew_Planning__c cp: cps)
        {        
            Crew_Planning__c old = (Crew_Planning__c)oldMap.get(cp.Id);    
            if(old.Crew_Member__c != cp.Crew_Member__c)
            {
                itemsForSyncAssign.add(old);
                itemsForResourcePlanning.add(cp);
            }
        }
        if(!itemsForSyncAssign.isEmpty())
        {
            SyncAssignmentManager.UpdateSyncAssignmentsOnCrewDelete(itemsForSyncAssign);
            JobResourcePlanning.ApplyContactPriceBookItem(itemsForResourcePlanning);
        }
    }    

    public override void OnBeforeDelete(List<sObject> items)
    {
    	SyncAssignmentManager.UpdateSyncAssignmentsOnCrewDelete((List<Crew_Planning__c>)items);
    }

    public override void OnAfterInsert(List<sObject> items)
    {
    	SyncAssignmentManager.UpdateSyncAssignmentsOnCrewAdd((List<Crew_Planning__c>)items);
    }

    public override void OnAfterUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    {
    	SyncAssignmentManager.UpdateSyncAssignmentsOnCrewAdd((List<Crew_Planning__c>)items);
    }
}