src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/RuleEngineQueueable.cls
public class RuleEngineQueueable implements Queueable
{
    Set<Id> itemIds {get;set;}
    Boolean skipRecommendedItems {get;set;}
    Boolean isOnTicket {get;set;}
       
    public RuleEngineQueueable(Set<Id> paramItemIds, Boolean skipRecommendedItems0)
    {
        itemIds = paramItemIds;
        skipRecommendedItems = skipRecommendedItems0;
       

    }

    public void execute(QueueableContext context) 
    {
        if(itemIds == null || itemIds.isEmpty()) return;
        String idStr = String.valueOf(new List<Id>(itemIds).get(0));
        if(idStr.startsWith(Ticket__c.sObjectType.getDescribe().getKeyPrefix()))
        {
          RuleEngineCore.Execute(itemIds, skipRecommendedItems);
        }
        else if(idStr.startsWith(Ticket_Item__c.sObjectType.getDescribe().getKeyPrefix()))
        {
           RuleEngineCore.ExecuteOnTicketItems(itemIds, skipRecommendedItems);
        }
        else if(idStr.startsWith(Quote__c.sObjectType.getDescribe().getKeyPrefix()))
        {
          RuleEngineForQuote.Execute(itemIds, skipRecommendedItems);
        }
        else if(idStr.startsWith(Quote_Item__c.sObjectType.getDescribe().getKeyPrefix()))
        {
           RuleEngineForQuote.ExecuteOnQuoteItems(itemIds, skipRecommendedItems);
        }

    }
}