src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/IsReadOnlyOnConsole__c.field-meta.xml
<CustomField>
    <fullName>IsReadOnlyOnConsole__c</fullName>
    <description>If the job status or ticket status is readonly for console, then the ticket is readonly</description>
    <formula>INCLUDES(Job__r.Status__r.Read_Only_Apps__c, "Console") ||  INCLUDES(Status__r.Read_Only_Apps__c, 'Console')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsReadOnlyOnConsole</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/TicketTriggerHandler.cls
public class TicketTriggerHandler extends FXTriggerHandler
{ 
    public override void OnAfterUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    {
        super.OnAfterUpdate(items, oldMap);
        List<Ticket__c> tkts = (List<Ticket__c>)items;
        Set<Id> tktIds = new Set<Id>();
        Set<String> rollupSummaryFields =MetadataHelper.GetRollupSummaryFields(Ticket__c.sObjectType); 
        for(Ticket__c t : tkts)
        {
        	if(t.IsReadOnlyOnConsole__c == true) continue;
            //tktIds.add(t.Id);
            
            Boolean isRollupUpdate = false;
            Ticket__c prev = (Ticket__c)oldMap.get(t.Id);
            for(String f : rollupSummaryFields)
            {
                if(t.get(f) != prev.get(f))
                {
                    isRollupUpdate=true;
                    break;
                }
            }
            if(!isRollupUpdate)
            {
        	   tktIds.add(t.Id);
            }
            
        }
        if(!tktIds.isEmpty()) 
        {
            OverrideBatcher.RunOnTickets(tktIds);
        }
    }
}