src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Log__c/Ticket_Log__c.object-meta.xml
<CustomObject>
    <label>Ticket Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Ticket Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Log__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Date and time the activity started.</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket for which the log entry was recorded.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/TicketLogTest.cls
@isTest
private class TicketLogTest{

    
    static testmethod void addSyncIDToTicketLog(){
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(1, true).get(0);       
        Ticket_Log__c tktLog = new Ticket_Log__c(Ticket__c = tkt.Id, Start_Time__c = System.now());
        insert tktLog;
       
        Ticket_Log__c dbTktLog=  [SELECT SyncID__c FROM Ticket_Log__c WHERE Ticket__c = :tkt.Id LIMIT 1];

        system.assert(StringUtility.isValidGuid(dbTktLog.SyncID__c));       
    }
    
    
}