src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/Initial_Status_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Mobile. You can only select "Initial Status Mobile" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/StatusBuilder.cls
public class StatusBuilder
{
	static void EnforceSingleInitialStatus(List<Status__c> items, Boolean isBeforeTrigger)
	{	
		Map<string, Status__c> mapInitStatus = new Map<string, Status__c>();
		for(Status__c s : items)
		{			
			if(s.Initial_Status_Console__c)
			{
				string key = s.SObject__c + s.SObject_Record_Type__c + 'c';
				if(mapInitStatus.containsKey(key) && isBeforeTrigger)
				{
					mapInitStatus.get(key).Initial_Status_Console__c = false;
					mapInitStatus.remove(key);
				}
				mapInitStatus.put(key, s);
			}
			if(s.Initial_Status_Mobile__c)
			{
				string key = s.SObject__c + s.SObject_Record_Type__c + 'm';
				if(mapInitStatus.containsKey(key) && isBeforeTrigger)
				{
					mapInitStatus.get(key).Initial_Status_Mobile__c = false;
					mapInitStatus.remove(key);
				}
				mapInitStatus.put(key, s);
			}

		}
		if(isBeforeTrigger) return;

		List<Status__c> statuses = [SELECT Id, SObject__c, SObject_Record_Type__c, Initial_Status_Console__c, Initial_Status_Mobile__c FROM Status__c WHERE (Initial_Status_Console__c=true OR Initial_Status_Mobile__c=true)];

		List<Status__c> itemsToUpdate = new List<Status__c>();
    	for(Status__c s: statuses)
    	{
    		Boolean hasChange = false;
    		if(s.Initial_Status_Console__c)
    		{
    			string key = s.SObject__c + s.SObject_Record_Type__c + 'c';
    			if(mapInitStatus.containsKey(key) && mapInitStatus.get(key).Id != s.Id)
    			{
    				s.Initial_Status_Console__c = false;
    				hasChange = true;
    			}    			
    		}
    		if(s.Initial_Status_Mobile__c)
    		{
    			string key = s.SObject__c + s.SObject_Record_Type__c + 'm';
    			if(mapInitStatus.containsKey(key) && mapInitStatus.get(key).Id != s.Id)
    			{
    				s.Initial_Status_Mobile__c = false;
    				hasChange = true;
    			}    
    		}
    		if(hasChange)
    		{
    			itemsToUpdate.add(s);
    		}
    	}

    	if(!itemsToUpdate.isEmpty())	           
	    {
	    	 update itemsToUpdate;	
	    }
	}	

	public static void OnBeforeInsert(List<Status__c> items)
	{
		List<Status__c> actionItems = new List<Status__c>();		
		for (Status__c s: items)
    	{
    		if (s.Initial_Status_Console__c || s.Initial_Status_Mobile__c) 
	        {	        	
    			actionItems.add(s);
	        }
	    }
	    if(!actionItems.isEmpty())	           
	    {
	    	EnforceSingleInitialStatus(actionItems, true);
	    }	   
	}	
	public static void OnAfterInsert(List<Status__c> items)
	{
		List<Status__c> actionItems = new List<Status__c>();		
		for (Status__c s: items)
    	{
    		if (s.Initial_Status_Console__c || s.Initial_Status_Mobile__c) 
	        {	        	
    			actionItems.add(s);
	        }
	    }
	    if(!actionItems.isEmpty())	           
	    {
	    	EnforceSingleInitialStatus(actionItems, false);
	    }	   
	}	


	public static void OnBeforeUpdate(List<Status__c> items, Map<Id, Status__c> oldMap)
	{
		List<Status__c> actionItems = new List<Status__c>();

		for (Status__c s: items)
    	{	       
	        if (s.Initial_Status_Console__c == true && s.Initial_Status_Console__c != oldMap.get(s.Id).Initial_Status_Console__c 
	        	|| s.Initial_Status_Mobile__c == true && s.Initial_Status_Mobile__c != oldMap.get(s.Id).Initial_Status_Mobile__c)
	        {
	        	actionItems.add(s);
	        }	       
    	}
    	if(!actionItems.isEmpty()) 
    	{
    		EnforceSingleInitialStatus(actionItems, true);
    	}    	
	}

	public static void OnAfterUpdate(List<Status__c> items, Map<Id, Status__c> oldMap)
	{	

		EnforceSingleInitialStatus(items, false);
		List<Status__c> actionItems = new List<Status__c>();
		for(Status__c s : items) 
		{
			if(oldMap.get(s.Id).Sync__c != s.Sync__c) 
			{
                actionItems.add(s);
            }			
	    }
	    if(!actionItems.isEmpty()) 
	    {	    	
	        SyncAssignmentManager.UpdateJobTicketSyncFlag(actionItems);            
	    }
	}
	
}