src/main/default/objects/Preventative_Maintenance_Schedule__c/Preventative_Maintenance_Schedule__c.object-meta.xml
<CustomObject>
    <label>Preventative Maintenance Schedule</label>
    <nameField>
        <displayFormat>PMS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preventative Maintenance Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Preventative_Maintenance_Schedule__c/fields/HasOpenWorkOrder__c.field-meta.xml
<CustomField>
    <fullName>HasOpenWorkOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>One or more WorkOrder with IsCompleted false value</description>
    <label>HasOpenWorkOrder</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>The work order is a representation of planned and actual work done to satisfy a need related to equipment such as a preventative maintenance action, a corrective maintenance action or an inspection.</description>
    <label>Work Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ij0000000wVH4EAM_00Nj0000008Hwq7EAC</fullName>
        <active>true</active>
        <field>Preventative_Maintenance_Schedule__c.Template_Work_Order__c</field>
        <filterItems>
            <field>Work_Order__c.IsTemplate__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Preventative Maintenance Schedule_Templa</name>
    </namedFilters>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/WorkOrderTriggerHandler.cls
public class WorkOrderTriggerHandler extends FXTriggerHandler
{
    public override void OnBeforeInsert(List<sObject> workOrders)
    {
        FXLicenseController.EnforceEAMLicense();
        WorkOrderHandler.SetTrackingNumberSyncId((List<Work_Order__c>)workOrders);
        WorkOrderHandler.SetActualFinishDate(workOrders);
    }
    
    public override void OnAfterInsert(List<sObject> workOrders)
    {        
        List<Preventative_Maintenance_Schedule__c> pms = WorkOrderHandler.SetLastWorkOrderForPMS((List<Work_Order__c>)workOrders, false);
        
        Map<Id, Preventative_Maintenance_Schedule__c> pmsMap = pms.isEmpty()? new Map<Id, Preventative_Maintenance_Schedule__c>() : new Map<Id, Preventative_Maintenance_Schedule__c>(pms);
        
        List<Preventative_Maintenance_Schedule__c> pms2 = WorkOrderHandler.FlagHasOpenOrderOnPMS((List<Work_Order__c>)workOrders, false);
        for(Preventative_Maintenance_Schedule__c p : pms2)
        {
            if(pmsMap.containsKey(p.Id))
            {
                pmsMap.get(p.Id).HasOpenWorkOrder__c = p.HasOpenWorkOrder__c;
            }
            else            
            {
                pmsMap.put(p.Id, p);                
            }
        }
        Database.update(pmsMap.values(), false);        
    }
    
    
    public override void OnBeforeUpdate(List<sObject> workOrders, Map<Id, sObject> oldMap)
    {
        FXLicenseController.EnforceEAMLicense();
        WorkOrderHandler.SetActualFinishDate((List<Work_Order__c>)workOrders);
    }
    
    public override void OnAfterUpdate(List<sObject> workOrders, Map<Id, sObject> oldMap)
    {
        WorkOrderHandler.FlagHasOpenOrderOnPMS((List<Work_Order__c>)workOrders, true);
        WorkOrderHandler.ProcessWorkOrderCompleted((List<Work_Order__c>)workOrders, (Map<Id, Work_Order__c>)oldMap);
    }  
    
    public override void OnBeforeDelete(List<sObject> workOrders)
    {
        FXLicenseController.EnforceEAMLicense();
    }
    public override void OnAfterDelete(List<sObject> workOrders)
    {
         WorkOrderHandler.FlagHasOpenOrderOnPMS((List<Work_Order__c>)workOrders, true);
    }
}