src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the price book is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Parent_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book for the price book. When a price book has a parent, you can select items from its parent price book when building tickets.</inlineHelpText>
    <label>Parent Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/classes/ParentPricebookUtilities_Test.cls
@isTest
private class ParentPricebookUtilities_Test{

    static testmethod void GetParentPricebooks() {
        Test.startTest();

        Price_Book__c pb1 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');
        Price_Book__c pb2 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');

        pb2.Parent_Price_Book__c = pb1.Id;
        update pb2;

        List<Price_Book__c> parents = ParentPricebookUtilities.GetParentPricebooks(pb2.Id);

        System.assertEquals(1, parents.Size());

        Test.stopTest();
    }


    static testmethod void GetParentPricebooks_ArchivedParent() {
        Test.startTest();

        Price_Book__c pb1 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');
        Price_Book__c pb2 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');

        List<Price_Book__c> pbs = [SELECT Id, Parent_Price_Book__c, IsArchived__c FROM Price_Book__c];
        Map<Id, Price_Book__c> pbMap = new Map<Id, Price_Book__c>(pbs);

        pbMap.get(pb1.Id).IsArchived__c = true;
        pbMap.get(pb2.Id).Parent_Price_Book__c = pb1.Id;
       
        update pbs;

        List<Price_Book__c> parents = ParentPricebookUtilities.GetParentPricebooks(pb2.Id);

        System.assertEquals(0, parents.Size());

        Test.stopTest();
    }

    static testmethod void GetPricebookItems() {
        Test.startTest();

        Price_Book__c pb1 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');
        Price_Book__c pb2 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');

        pb2.Parent_Price_Book__c = pb1.Id;
        update pb2;

        AlpineTestHelper.CreatePriceBookItems(3, pb1.Id, 'Supplies', true);
        AlpineTestHelper.CreatePriceBookItems(3, pb2.Id, 'Supplies', true);

        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(1, true);

        String ticketId = tkts[0].Id;
        ParentPricebookUtilities.Result res = ParentPricebookUtilities.GetPriceBookItems(pb1.Id, ticketId, 'false', 'not found', '', 'supplies2', '2000', '0', 'Name', 'ASC', 'Name');

        System.assertNotEquals(null, res.items);

        Test.stopTest();
    }

    static testmethod void GetPricebookItemsFromParentPricebook() {
        Test.startTest();

        Price_Book__c pb1 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');
        Price_Book__c pb2 = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'EUR');

        pb2.Parent_Price_Book__c = pb1.Id;
        update pb2;

        AlpineTestHelper.CreatePriceBookItems(3, pb1.Id, 'Supplies', true);
        AlpineTestHelper.CreatePriceBookItems(3, pb2.Id, 'Supplies', true);

        List<Ticket__c> tkts = AlpineTestHelper.CreateTickets(1, true);

        String ticketId = tkts[0].Id;
        ParentPricebookUtilities.Result res = ParentPricebookUtilities.GetPricebookItemsFromParentPricebook(pb2.Id, ticketId, 'false', 'not found', '', 'supplies4', '2000', '0', 'Name', 'ASC', 'Name');

        System.assertNotEquals(null, res.items);

        Test.stopTest();
    }

}