src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Global_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Global_Price_Book__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this Price Book is global. Global price books will sync to all Mobile users.</description>
    <inlineHelpText>If selected, the price book is available for every customer, office, and business segment. This setting overrides any selection made in the "Account", "Office", and "Segment" fields.</inlineHelpText>
    <label>Global Price Book</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(!IsArchived__c &amp;&amp; Effective_Date__c &lt;=TODAY() &amp;&amp; (ISNULL(Expiration_Date__c) || (Expiration_Date__c >=TODAY())) &amp;&amp; (ISBLANK(Account__c) || !Account__r.IsArchived__c), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether users can select the price book for a job. Users cannot select a price book for a job if the current date is before the "Effective Date", the current date is after the "Expiration Date", or "Archived" is selected.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Parent_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book for the price book. When a price book has a parent, you can select items from its parent price book when building tickets.</inlineHelpText>
    <label>Parent Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/PriceBookHandler.cls
public class PriceBookHandler
{
    public static void ResetGlobalPriceBooks(List<Price_Book__c> pbs)
    { 
        for(Price_Book__c pb: pbs)
        {               
            if(pb.Global_Price_Book__c ==true && pb.Is_Active__c == false) 
            {
               pb.Global_Price_Book__c = false;
            }            
        }
    }
    
    public static void EnforceCPQLicense(List<Price_Book__c> pbs)
    {
        if(Test.isRunningTest() || FXLicenseController.isCurrentUserLicensed('FXCPQ')) return;
       
        for(Price_Book__c pb : pbs)
        {
            if(String.isBlank(pb.Parent_Price_Book__c)) continue;            
            pb.addError('FXCPQ license is required to edit Price Book with Parent Price Book. The user does not have FXCPQ license. You may clear out Parent Price Book or contact the administrator.');            
        }
    }   
    
}