src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment that uses the price book. If a business segment is not selected, the price book is available for every segment.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Applies_To__c.field-meta.xml
<CustomField>
    <fullName>Applies_To__c</fullName>
    <label>Applies To</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket__c</fullName>
                <default>true</default>
                <label>Ticket__c</label>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaQueryFields__c.field-meta.xml
<CustomField>
    <fullName>CriteriaQueryFields__c</fullName>
    <description>DO NOT CHANGED</description>
    <label>CriteriaQueryFields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaStack__c.field-meta.xml
<CustomField>
    <fullName>CriteriaStack__c</fullName>
    <description>Preprocessed Criteria - DO NOT MODIFIED</description>
    <inlineHelpText>Preprocessed Criteria - DO NOT MODIFIED</inlineHelpText>
    <label>CriteriaStack</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>PriceBookRules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/Price_Book_Rule_Action__c.object-meta.xml
<CustomObject>
    <description>These actions are triggered by the criteria on the Rule object for the CPQ module.</description>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>ACT-{0000}</displayFormat>
        <label>Rule Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule_Action__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates whether the rule action is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <formula>Price_Book_Rule__r.Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the rule action.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipName>Price_Book_Rule_Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Price_Book_Rule__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Rule__c</fullName>
    <inlineHelpText>Rule for which the rule action is used.</inlineHelpText>
    <label>Rule</label>
    <referenceTo>Price_Book_Rule__c</referenceTo>
    <relationshipLabel>Rule Actions</relationshipLabel>
    <relationshipName>Rule_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Rule_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Indicates whether the linked price book item is required, recommended, or disallowed for a ticket.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
                <default>true</default>
                <label>Required</label>
            </value>
            <value>
                <fullName>Recommended</fullName>
            </value>
            <value>
                <fullName>Disallowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Auto_Added__c.field-meta.xml
<CustomField>
    <fullName>Auto_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item was added to the quote automatically. An item gets added to a quote automatically if the linked price book item has a default quantity or the linked price book item has a parent price book item.</inlineHelpText>
    <label>Auto Added</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <inlineHelpText>Catalog item code for the quote item. The quote item inherits this code from the linked catalog item.</inlineHelpText>
    <label>Item Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Parent_Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent item for the quote item. When you add a parent item to a quote, any designated child items also get added. You cannot add child items to quotes individually without adding their parent first.</inlineHelpText>
    <label>Parent Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Status__c/Status__c.object-meta.xml
<CustomObject>
    <description>This object stores the master list of statuses for all entities using record types.  Note that not all status attributes are applicable to all entity types</description>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01I36000001VBQ4EAO_00N3600000E0xoPEAR</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a quote status.</errorMessage>
        <field>Quote__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Quote__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Quote_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nC2eEAE_00N3600000Rjhw3EAB</fullName>
        <active>true</active>
        <field>Invoice__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Invoice__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Invoice_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01I36000002nYqkEAE_00N3600000S7xL1EAJ</fullName>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <field>Credit_Memo__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Credit_Memo__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Credit_Memo_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Ytj2EAC</fullName>
        <active>true</active>
        <errorMessage>The selected status was not a Job Status</errorMessage>
        <field>Job__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Job__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z9AEAU_00Ni0000001YuNREA0</fullName>
        <active>true</active>
        <errorMessage>The selected status must be a ticket status.</errorMessage>
        <field>Ticket__c.Status__c</field>
        <filterItems>
            <field>Status__c.SObject__c</field>
            <operation>equals</operation>
            <value>Ticket__c</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Status</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbwEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.New_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_New Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000zFhnEAE_00Ni00000099NbxEAE</fullName>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (1 AND 3)</booleanFilter>
        <field>Status_Workflow__c.Old_Status__c</field>
        <filterItems>
            <field>$Source.SObject__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <valueField>Status__c.SObject_Record_Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>Status__c.SObject_Record_Type__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Status Workflow_Old Status</name>
        <sourceObject>Status_Workflow__c</sourceObject>
    </namedFilters>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Status__c/fields/Initial_Status_Console__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status_Console__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, this status is the first status for new jobs/tickets in FieldFX Console. You can only select "Initial Status Console" for one status in a workflow.</inlineHelpText>
    <label>Initial Status Console</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Select the sobject for this status.</description>
    <inlineHelpText>Object for which the status is used. You must make an entry in this field.</inlineHelpText>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Job__c</fullName>
            </value>
            <value>
                <fullName>Ticket__c</fullName>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Credit_Memo__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/SObject_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>SObject_Record_Type__c</fullName>
    <description>Select the record type for the target sobject. This should be the developer name of the record type.</description>
    <inlineHelpText>Record type for which the status is used.</inlineHelpText>
    <label>SObject Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Field_Ticket</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit_Memo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Status__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If selected, jobs/tickets with this status sync to FieldFX Mobile.</inlineHelpText>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Status__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/classes/RuleEngineForQuote_Test.cls
@isTest
private class RuleEngineForQuote_Test
{
    static Integer groupSize = 6;

    @testSetup
     static void setup()
    {
        Quote__c q = AlpineTestHelper.CreateQuotes(1, false).get(0);

        Status__c s = [SELECT Id FROM Status__c WHERE Sync__c=false AND SObject__c='Quote__c' LIMIT 1];
        q.Status__c = s.Id;
        insert q;


        Id priceBookId = q.Price_Book__c;

        String ns = StringUtility.FXNamespace();        

        List<Price_Book_Item__c> priceBookItems = AlpineTestHelper.CreatePriceBookItems(6* groupSize, priceBookId, 'Equipment');

        String criteria = ns + 'Status__c!=null';
        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"!=\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"null\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Status__c');
        
        Price_Book_Rule__c rule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true, Criteria__c=criteria, Applies_To__c='Quote__c',
            CriteriaQueryFields__c = ns + 'Status__c',
            CriteriaStack__c=criteriaStack);        
        insert rule;
        
        String segmentCriteria = ns + 'Segment__c==\'UnitTestSegment\'';
        criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"==\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"UnitTestSegment\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Segment__c');
        
        Price_Book_Rule__c segmentRule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true, Criteria__c=segmentCriteria,
            Applies_To__c='Quote__c',
            CriteriaQueryFields__c = ns + 'Segment__c',
            CriteriaStack__c=criteriaStack);        
        insert segmentRule ;

        List<Price_Book_Rule_Action__c> ruleActions = new List<Price_Book_Rule_Action__c>();

        for(Integer i=0; i<groupSize; i++)
        {
            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i).Id, 
                IsActive__c = true, 
                Type__c='Required'));

            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i+groupSize).Id, 
                IsActive__c = true, 
                Type__c='Recommended'));

            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = rule.Id, 
                Price_Book_Item__c = priceBookItems.get(i+2*groupSize).Id, 
                IsActive__c = true, 
                Type__c='Disallowed'));
        }

        Price_Book_Item__c rootItem = priceBookItems.get(0);

        Integer index = groupSize * 3 + 1;

        String itemRuleCriteria = String.format('{0}Quote__r.{0}Status__c!=null', new String[]{ns});

        criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\"!=\\",\\"left\\":{\\"type\\":\\"MemberExpression\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"null\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Quote__r.' + ns + 'Status__c');

        Price_Book_Rule__c quoteItemRule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true, Criteria__c= itemRuleCriteria , 
            CriteriaStack__c = criteriaStack,
            Applies_To__c='Quote__c',
            CriteriaQueryFields__c = ns + 'Quote__r.' +  ns + 'Status__c', 
            Price_Book_Item__c=rootItem.Id);  

         insert quoteItemRule;


        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index).Id, 
                IsActive__c = true, 
                Type__c='Required'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index+1).Id, 
                IsActive__c = true, 
                Type__c='Recommended'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index+2).Id, 
                IsActive__c = true, 
                Type__c='Disallowed'));
                
        
        //6 segment rule action items
        index = groupSize * 4 + 1;
        for(Integer i=0; i<groupSize; i++)
        {
            ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = segmentRule.Id, 
                Price_Book_Item__c = priceBookItems.get(index + i).Id, 
                IsActive__c = true, 
                Type__c='Required'));           
        }

        insert ruleActions;

    } 

    static testmethod void OnQuoteCreate_Test()
    {       
        Test.startTest();

        System.debug('OnQuoteCreate_Test ');
        Quote__c q = [SELECT Id, Price_Book__c, Price_Book__r.Name, Status__r.RecordTypeId, RecordType.DeveloperName FROM Quote__c LIMIT 1];
        List<Quote_Item__c> items = [SELECT Id, Price_Book_Item__c, Parent_Quote_Item__c, Item_Code__c FROM Quote_Item__c];
        System.assert(items.isEmpty(), 'should have no quoteItem in the system');

        Quote__c newQuote = AlpineTestHelper.CreateQuotes(q.Price_Book__r, 1, false).get(0);
        String statusName = 'Status' + StringUtility.newGuid();
        Status__c st = new Status__c(Name = statusName, SObject__c='Quote__c', 
            SObject_Record_Type__c= q.RecordType.DeveloperName, 
            Sync__c=false, Initial_Status_Console__c =false,
            RecordTypeId=q.Status__r.RecordTypeId);

        insert st;
        newQuote.Status__c = st.Id;
        insert newQuote;

        Test.stopTest();


        List<Quote_Item__c> childItems = [SELECT Id, Price_Book_Item__c, Parent_Quote_Item__c, Item_Code__c FROM Quote_Item__c WHERE Quote__c = :newQuote.Id AND Parent_Quote_Item__c!=null ORDER BY Item_Code__c];

        System.debug('childItems count = ' + childItems.size());
        items = [SELECT Id, Price_Book_Item__c, Parent_Quote_Item__c, Item_Code__c FROM Quote_Item__c WHERE Quote__c = :newQuote.Id ORDER BY Item_Code__c];

        Integer expectedResult = groupSize * 2 + 2; //required + recommended + ItemRule child items

        System.assert(items.size()==expectedResult, 'should have ' + expectedResult + ' auto added items, instead have ' + items.size());
    }




    static testmethod void OnQuoteUpdate_Test()
    {
        
        Test.startTest();

        Quote__c q = [SELECT Id, Status__c FROM Quote__c LIMIT 1];  
        Integer count = [SELECT COUNT() FROM Quote_Item__c WHERE Auto_Added__c = true AND Quote__c = :q.Id];
        System.assert(count==0, 'should have no auto added item before Quote update');

        Status__c s = [SELECT Id FROM Status__c WHERE Sync__c=true AND SObject__c='Quote__c' LIMIT 1];
        q.Status__c = s.Id;
        update q;

        s = [SELECT Id FROM Status__c WHERE Sync__c=false AND SObject__c='Quote__c' LIMIT 1];
        q.Status__c = s.Id;
        update q;

        Test.stopTest();
        Integer expectedResult = groupSize + 1; // required + 1 child item (require), recommended items skipped on update
        count = [SELECT COUNT() FROM Quote_Item__c WHERE Auto_Added__c = true AND Quote__c = :q.Id];
        System.assert(count== expectedResult, 'should have ' + expectedResult + ' auto added required items after update (Recommended items skipped on update), instead have ' + count);
        
    }   

    static testmethod void QuoteItemRule_Test()
    {
        
       
        String ns = StringUtility.FXNamespace();

        Quote__c q = [SELECT Id, Price_Book__c, Price_Book__r.Name FROM Quote__c LIMIT 1];  
        List<Price_Book_Item__c> priceBookItems = AlpineTestHelper.CreatePriceBookItems(5, q.Price_Book__c, 'Equipment');

        Integer count = [SELECT COUNT() FROM Quote_Item__c WHERE Auto_Added__c = true AND Quote__c = :q.Id];
        System.assert(count==0, 'should have no auto added item before Quote update');

        Status__c s = [SELECT Id FROM Status__c WHERE Sync__c=false AND SObject__c='Quote__c' LIMIT 1];
        Quote__c newQuote = AlpineTestHelper.CreateQuotes(q.Price_Book__r, 1, false).get(0);
        newQuote.Status__c = s.Id;
        insert newQuote;

        Id priceBookId = q.Price_Book__c;

        String itemRuleCriteria = String.format('{0}Qty__c>100', new String[]{ns});

        String criteriaStack = '["{\\"type\\":\\"BinaryExpression\\",\\"operator\\":\\">\\",\\"left\\":{\\"type\\":\\"Identifier\\",\\"value\\":\\"[fieldName]\\"},\\"right\\":{\\"type\\":\\"Constant\\",\\"value\\":\\"100\\"}}"]';
        criteriaStack = criteriaStack.replace('[fieldName]', ns + 'Qty__c');

        Price_Book_Item__c rootItem = priceBookItems.get(0);
        Price_Book_Rule__c quoteItemRule = new Price_Book_Rule__c(Price_Book__c = priceBookId, 
            IsActive__c=true,
            Criteria__c=itemRuleCriteria, 
            CriteriaQueryFields__c = ns + 'Qty__c',
            CriteriaStack__c=criteriaStack,
            Applies_To__c='Quote__c', Price_Book_Item__c=rootItem.Id);
        insert quoteItemRule;

        List<Price_Book_Rule_Action__c> ruleActions = new List<Price_Book_Rule_Action__c>();


        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(1).Id, 
                IsActive__c = true, 
                Type__c='Required'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(2).Id, 
                IsActive__c = true, 
                Type__c='Recommended'));

        ruleActions.add(new Price_Book_Rule_Action__c(Price_Book_Rule__c = quoteItemRule.Id, 
                Price_Book_Item__c = priceBookItems.get(3).Id, 
                IsActive__c = true, 
                Type__c='Disallowed'));

        insert ruleActions;

        Test.startTest();

        Quote_Item__c qi = new Quote_Item__c(Quote__c = newQuote.Id, Price_Book_Item__c = rootItem.Id, Qty__c=200);
        insert qi;
        Test.stopTest();

        Integer expectedResult = 2; //one required + one recommended
        List<Quote_Item__c> childItems = [SELECT Id FROM Quote_Item__c WHERE Parent_Quote_Item__c = :qi.Id];

        System.assert(childItems.size()== 2, 'should have ' + expectedResult + ' child items from RuleActions, instead have ' + childItems.size());
        
    }   

    static testmethod void DisallowedItem_Test()
    {
        Test.startTest();  

        Price_Book_Rule_Action__c disallowedItem = [SELECT Id, Price_Book_Item__c FROM Price_Book_Rule_Action__c WHERE Type__c='Disallowed' AND Price_Book_Rule__r.Price_Book_Item__c=null LIMIT 1];
       
        Quote__c q = [SELECT Id FROM Quote__c LIMIT 1];
        Quote_Item__c qi = new Quote_Item__c(Quote__c = q.Id, Price_Book_Item__c = disallowedItem.Price_Book_Item__c);
        try {
            insert qi;
        }
        catch ( System.DmlException ex) {

            System.assert(ex.getMessage().contains('Item is disallowed by Rule'), 'error should contains "Item is disallowed", instead of :' + ex);
        }
        finally {
           Test.stopTest(); 
        }          
    }

    static testmethod void GetDisallowedPriceBookItems_OnQuote_Test()
    {
        Test.startTest();
        Quote__c q = [SELECT Id, Status__c, Price_Book__c FROM Quote__c WHERE Status__r.Sync__c = false LIMIT 1];
        Quote__c newQuote = q.clone(false, false, false, false);
        insert newQuote;
        List<Id> items = RuleEngineForQuote.GetDisallowedPriceBookItems(newQuote.Id);       
        Test.stopTest();

        System.assert(items.size() == groupSize, 'should have ' + groupSize + ' disallowed items, instead of have ' + items.size());
    }

    

    static testmethod void GetDisallowedPriceBookItems_OnQuoteItem_Test()
    {
        Test.startTest();
        Quote__c q = [SELECT Id, Status__c, Price_Book__c FROM Quote__c WHERE Status__r.Sync__c = false LIMIT 1];
        Quote__c newQuote = q.clone(false, false, false, false);
        insert newQuote;

        List<Quote_Item__c> quoteItems = [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE Quote__c =:newQuote.Id];
        Map<Id, Id> pbiToQuoteItem = new Map<Id, Id>();
        for(Quote_Item__c qi:quoteItems)
        {
            pbiToQuoteItem.put(qi.Price_Book_Item__c, qi.Id);
        }
        Set<Id> priceBookItemIds = pbiToQuoteItem.keySet();
        
        List<Price_Book_Rule__c> rules = [SELECT Id, Price_Book_Item__c, (SELECT Id, Price_Book_Item__c FROM Rule_Actions__r WHERE Type__c='Disallowed') FROM Price_Book_Rule__c WHERE Price_Book_Item__c IN :priceBookItemIds];
        Map<Id, Set<Id>> disallowedChildItems = new  Map<Id, Set<Id>>();
        for(Price_Book_Rule__c r : rules)
        {
            if(r.Rule_Actions__r.isEmpty()) continue;
            if(!disallowedChildItems.containsKey(r.Price_Book_Item__c))
            {
                disallowedChildItems.put(r.Price_Book_Item__c, new Set<Id>());
            }
            for(Price_Book_Rule_Action__c a : r.Rule_Actions__r)
            {
                disallowedChildItems.get(r.Price_Book_Item__c).add(a.Price_Book_Item__c);
            }
        }
        for(Id pbi : disallowedChildItems.keySet())
        {
            List<Id> items = RuleEngineForQuote.GetDisallowedPriceBookItems(pbiToQuoteItem.get(pbi));
            Set<Id> disallowedItems = disallowedChildItems.get(pbi);
            System.assert(items.size() == disallowedItems.size(), 'should have ' + disallowedItems.size() + ' disallowed items, instead have ' + items.size());
            for(Id itemId : items)
            {
                System.assert(disallowedItems.contains(itemId), 'returnging extra (wrong) item');
            }
        }       
        Test.stopTest();    
    }    

    static testmethod void AddDisallowedChildItem_Test()
    {
        Test.startTest();
        Quote__c q = [SELECT Id, Status__c, Price_Book__c FROM Quote__c WHERE Status__r.Sync__c = false LIMIT 1];
        Quote__c newQuote = q.clone(false, false, false, false);
        insert newQuote;

        List<Quote_Item__c> quoteItems = [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE Quote__c =:newQuote.Id];
        Map<Id, Id> pbiToQuoteItem = new Map<Id, Id>();
        for(Quote_Item__c qi:quoteItems)
        {
            pbiToQuoteItem.put(qi.Price_Book_Item__c, qi.Id);
        }
        Set<Id> priceBookItemIds = pbiToQuoteItem.keySet();
        
        List<Price_Book_Rule__c> rules = [SELECT Id, Price_Book_Item__c, (SELECT Id, Price_Book_Item__c FROM Rule_Actions__r WHERE Type__c='Disallowed') FROM Price_Book_Rule__c WHERE Price_Book_Item__c IN :priceBookItemIds];
        Map<Id, Set<Id>> disallowedChildItems = new  Map<Id, Set<Id>>();
        for(Price_Book_Rule__c r : rules)
        {
            if(r.Rule_Actions__r.isEmpty()) continue;
            if(!disallowedChildItems.containsKey(r.Price_Book_Item__c))
            {
                disallowedChildItems.put(r.Price_Book_Item__c, new Set<Id>());
            }
            for(Price_Book_Rule_Action__c a : r.Rule_Actions__r)
            {
                disallowedChildItems.get(r.Price_Book_Item__c).add(a.Price_Book_Item__c);
            }
        }
        List<Quote_Item__c> newItems = new List<Quote_Item__c>();

        for(Id pbi : disallowedChildItems.keySet())
        {
            Id parentQuoteItem = pbiToQuoteItem.get(pbi);

            for(Id pbiChild : disallowedChildItems.get(pbi))
            {
                Quote_Item__c qi = new Quote_Item__c(Quote__c = newQuote.Id, Parent_Quote_Item__c = parentQuoteItem, Price_Book_Item__c=pbiChild);
                newItems.add(qi);
            }
        }       
        Database.SaveResult[] results = Database.insert(newItems, false);
        Test.stopTest();    
        
        Integer errorCount = 0;
        for (Database.SaveResult sr : results) {
            if(sr.isSuccess()) continue;
            ++errorCount;
        }
        System.assert(newItems.size() == errorCount, 'all save should fail, instead ' + errorCount + ' out of ' + newItems.size() + ' failed.');

        
    }    
    static testmethod void SegmentRule_RemoveRuleAddedItemUponUpdate_Test()
    {
        Quote__c q = [SELECT Id, Status__c, Price_Book__c FROM Quote__c WHERE Status__r.Sync__c = false LIMIT 1];
        Quote__c newQuote = q.clone(false, false, false, false);
        newQuote.Segment__c = 'UnitTestSegment';
        insert newQuote;
        Test.startTest();

        
        List<Quote_Item__c> items = [SELECT Id FROM Quote_Item__c where Quote__c = :newQuote.Id];
        
        Integer expectedResult = groupSize * 3 + 2; //required + recommended + segmentRuleItems + ItemRule child items 
        System.assert(items.size() == expectedResult , 'should ' + expectedResult + 'quote items, instead have ' + items.size());
        
        Quote__c dbQuote = [SELECT Id, Segment__c FROM Quote__c WHERE Id=:newQuote.Id];
        dbQuote.Segment__c = null;
        update dbQuote ;
        Test.stopTest();
        
        items = [SELECT Id FROM Quote_Item__c where Quote__c = :newQuote.Id];
        expectedResult = groupSize * 2 + 2; //required + recommended + ItemRule child items //segment rule now is false
        System.assert(items.size() == expectedResult , 'should ' + expectedResult + 'quote items, instead have ' + items.size());
        
        
    }
    
}