src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the price book is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Classification__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Classification__c</fullName>
    <formula>CASESAFEID(Catalog_Item__r.Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog classification for the price book item. The price book item inherits this classification from the linked catalog item.</inlineHelpText>
    <label>Catalog Classification</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Description__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Description__c</fullName>
    <formula>Catalog_Item__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog description for the price book item. The price book item inherits this description from the linked catalog item by default. If the price book item has a description override, the price book item uses that description.</inlineHelpText>
    <label>Catalog Description</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item_Code__c</fullName>
    <formula>Catalog_Item__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog item code for the price book item. The price book item inherits this item code from the linked catalog item.</inlineHelpText>
    <label>Catalog Item Code</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Description_Override__c.field-meta.xml
<CustomField>
    <fullName>Description_Override__c</fullName>
    <description>Complete this field to override the catalog item description within this price book</description>
    <inlineHelpText>Catalog description for the price book item. This description overrides the catalog description inherited from the linked catalog item.</inlineHelpText>
    <label>Description Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the price book item is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/PricebookItemsForQuoteSvc.cls
@RestResource(urlMapping = '/getPricebookItemsForQuote/*')
global with sharing class PricebookItemsForQuoteSvc{

    //
    @HttpGet
    global static Result getPricebookItemsForQuote() {

        String quoteId = RestContext.request.params.get('quoteId');
        String showItemsAlreadyOnTheQuote = RestContext.request.params.get('showItemsAlreadyOnTheQuote');
        String keyword = RestContext.request.params.get('keyword');
        String classification = RestContext.request.params.get('classification');
        String itemType = RestContext.request.params.get('itemType');
        String itemLimit = RestContext.request.params.get('limit');
        String itemOffset = RestContext.request.params.get('offset');
        String sortby = RestContext.request.params.get('sortby');
        String sortdir = RestContext.request.params.get('sortdir');
        String fields = RestContext.request.params.get('fields');

        return searchPricebookItemsForQuote(quoteId, showItemsAlreadyOnTheQuote, keyword, classification,
                    itemType, itemLimit, itemOffset, sortby, sortdir, fields);
    }

    public static Result searchPricebookItemsForQuote(String quoteId, String showItemsAlreadyOnTheQuote, String keyword, String classification,
        String itemType, String itemLimit, String itemOffset, String sortby, String sortdir, String fields) {

        String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();

        Result result = new Result();
        result.disallowedIds = new List<Id>(); // RuleEngineCore.GetDisallowedPriceBookItems(quoteId);

        String commandText = 'SELECT ' + fields + ' FROM ' + fxNamespacePrefix + 'Price_Book_Item__c ';
        commandText += ' WHERE Id != null ';
        commandText += ' AND ' + fxNamespacePrefix + 'IsArchived__c = false ';
        commandText += ' AND ' + fxNamespacePrefix + 'Parent_Price_Book_Item__c = null ';

        commandText += ' AND ' + fxNamespacePrefix + 'Price_Book__c in (SELECT ' + fxNamespacePrefix + 'Price_Book__c from ' + fxNamespacePrefix + 'Quote__c where Id = \'' + quoteId + '\') ';

        if (showItemsAlreadyOnTheQuote == 'false') {
            commandText += ' AND Id not in (SELECT ' + fxNamespacePrefix + 'Price_Book_Item__c FROM ' + fxNamespacePrefix + 'Quote_Item__c WHERE ' + fxNamespacePrefix + 'Quote__c = \'' + quoteId + '\' ) ';
        }

        if (keyword != null && keyword != '') {
          String keywordSoql = ' AND ( ';
          List<String> keywords = keyword.split(' ');

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += 'Name LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Catalog_Description__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Description_Override__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Catalog_Item_Code__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') ';

          keywordSoql += ' ) ';
          commandText += keywordSoql;
        }

        if (classification != null && classification != '') {
            commandText += ' AND Catalog_Classification__c in (' + classification + ') ';
        }

        if (itemType != null && itemType != '') {
            commandText += ' AND ' + fxNamespacePrefix + 'Ticket_Item_Record_Type__c = \'' + itemType + '\' ';
        }

        if (result.disallowedIds.size() > 0) {
            commandText += ' AND Id NOT IN (' + GetIDsAsString(result.disallowedIds) + ')';
        }

        String sb = (sortby != '') ? ' ORDER BY ' + sortby : '';
        String sd = (sb != '') ? (sortdir != null) ? sortdir : '' : '';
        String nullsLast = (sb != '') ? 'NULLS LAST' : '';
        commandText += sb + ' ' + sd + ' ' + nullsLast;

        String lim = (itemLimit != '' ) ? (Integer.valueOf(itemLimit) > 2000) ? '2000' : itemLimit : '2000';
        String off = (itemOffset != '' ) ? (Integer.valueOf(itemOffset) > 2000) ? '2000' : itemOffset : '0';
        commandText += ' LIMIT ' + lim + ' OFFSET ' + off + ' ';

        result.soql = commandText;

        result.items = Database.query(commandText);

        return result;
    }

    global class Result {
        public List<Price_Book_Item__c> items;
        public string soql;
        public List<Id> disallowedIds;
    }

    static String GetIDsAsString(List<Id> ids) {
        String sep = '';
        String soql = '';
        for(Id id: ids)
        {
            soql += sep + '\'' + id + '\'';
            sep = ',';
        }

        return soql;
    }

}