src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/Price_Book_Rule__c.object-meta.xml
<CustomObject>
    <description>This object contains the criteria used to apply actions in the CPQ module.</description>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Rule__c/fields/Applies_To__c.field-meta.xml
<CustomField>
    <fullName>Applies_To__c</fullName>
    <label>Applies To</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket__c</fullName>
                <default>true</default>
                <label>Ticket__c</label>
            </value>
            <value>
                <fullName>Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>This criteria should be a valid Salesforce formula and will be used to determine if actions should be applied in the CPQ module.</description>
    <inlineHelpText>Formula that specifies when any linked rule actions apply.</inlineHelpText>
    <label>Criteria</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/CriteriaStack__c.field-meta.xml
<CustomField>
    <fullName>CriteriaStack__c</fullName>
    <description>Preprocessed Criteria - DO NOT MODIFIED</description>
    <inlineHelpText>Preprocessed Criteria - DO NOT MODIFIED</inlineHelpText>
    <label>CriteriaStack</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/IsCriteriaDirty__c.field-meta.xml
<CustomField>
    <fullName>IsCriteriaDirty__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True - criteria have change
False - no change</description>
    <label>IsCriteriaDirty</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Rule__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Rules</relationshipLabel>
    <relationshipName>PriceBookRules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/RuleCriteriaStackBuilderController.cls
public class RuleCriteriaStackBuilderController
{
    public RuleCriteriaStackBuilderController()
    {        
       QueryDirtyRules();
       if(Rules.isEmpty())
       {               
           ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, allProcessedMsg));
       }
      
    }   
    public List<Price_Book_Rule__c> Rules {get;set;}

    String allProcessedMsg = 'All Rules have been preprocessed, i.e. no entry has IsCriteriaDirty = true.';   
    
    public String getNamespaceWithoutUnderscores () { return UtilityGetNamespace.CurrentNamespaceWithoutUnderscores(); }

    
    public PageReference Save()
    {
        for(Price_Book_Rule__c r:Rules)
        {
            r.IsCriteriaDirty__c = false;
        }
        Integer successCount = 0;
        Integer failCount = 0;
        String msg = '';
        Integer index = 0;
        String sep = '<br />';
        for(Database.SaveResult r : Database.update(Rules, false))
        {
            if(r.isSuccess())
            {
                successCount++;
            }
            else
            {
                failCount++;
                Price_Book_Rule__c rule =  Rules.get(index);
                msg += sep + 'Failed: ' + rule.Name + ' ( ' + rule.Id + ')';
                for(Database.Error err : r.getErrors()) {
                    msg += ', ' + err.getMessage();              
                }

            }
            index++;
        }
        msg = successCount + ' items updated, ' + failCount + ' failed. ' + msg;       

        QueryDirtyRules();
        if(Rules.isEmpty())
        {
           msg += allProcessedMsg;  
        }

        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, msg));
        return null;
    }

    void QueryDirtyRules()
    {
        Rules = [SELECT Name, Applies_To__c, Price_Book__r.Name, Criteria__c, CriteriaStack__c, IsCriteriaDirty__c FROM Price_Book_Rule__c WHERE IsDeleted=false AND IsCriteriaDirty__c=true LIMIT 1000];
    }


    public PageReference TaintAllRules()
    {
        Integer batchCount = 5000;
        TaintingResult r = TaintRules(batchCount);
        String msg = r.successCount + ' items flagged for processing. ';
        if(r.failCount>0)
        {
            msg += '<br />' + r.failCount + ' failed, ' + r.msg;
        }
        if(r.hasMore == true)
        {
            msg += '<br />A batch job is enqueued to flag more Rules. ';           
        }
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, msg));
        QueryDirtyRules();
        return null;
    }

    TaintingResult TaintRules(Integer itemCount)
    {
        TaintingResult result = new TaintingResult();

        List<Price_Book_Rule__c> rulesToUpdate = new List<Price_Book_Rule__c>();
        for(Price_Book_Rule__c r:[SELECT Id FROM Price_Book_Rule__c WHERE IsDeleted=false AND IsCriteriaDirty__c=false LIMIT :itemCount])
        {
            r.IsCriteriaDirty__c = true;
            rulesToUpdate.add(r);
        }
        Integer successCount = 0;
        Integer failCount = 0;
        String msg = '';
        Integer index = 0;

        for(Database.SaveResult r : Database.update(rulesToUpdate, false))
        {
            if(r.isSuccess())
            {
                successCount++;
            }
            else
            {
                failCount++;
                Price_Book_Rule__c rule = rules.get(index);
                msg += '<br />Failed: ' + rule.Name + ' (' + rule.Id + ')';
                for(Database.Error err : r.getErrors()) {
                    msg += ', ' + err.getMessage();              
                }
            }
            index++;
        }
        if(successCount == itemCount)
        {
            result.hasMore = true;
            System.enqueueJob(new PriceBookRuleTaintingCriteriaBatchable());
        }
        result.successCount = successCount;
        result.failCount = failCount;
        result.msg = msg;
        return result;
    }
    
    class TaintingResult 
    {
        public Integer successCount {get;set;}
        public Integer failCount {get;set;}
        public String msg {get;set;}
        public Boolean hasMore {get;set;}
    }
}