src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Auto_Added__c.field-meta.xml
<CustomField>
    <fullName>Auto_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item was added to the quote automatically. An item gets added to a quote automatically if the linked price book item has a default quantity or the linked price book item has a parent price book item.</inlineHelpText>
    <label>Auto Added</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item was added to the quote in FieldFX Mobile. If unselected, the item was added to the quote in FieldFX Back office.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Rule_Required_Item__c.field-meta.xml
<CustomField>
    <fullName>Rule_Required_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item is required on the quote by the Rule Engine.</inlineHelpText>
    <label>Rule Required Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/QuoteItemTriggerHandler.cls
public class QuoteItemTriggerHandler extends FXTriggerHandler
{
	public override void OnBeforeInsert(List<sObject> items)
	{
		super.OnBeforeInsert(items);
		List<Quote_Item__c> quoteItems = (List<Quote_Item__c>)items;

		if(SObjectClonerUtility.CloningInProgress !=true) 
        {
            List<Quote_Item__c> itemsOfInterest = new List<Quote_Item__c>();
            for(Quote_Item__c item: quoteItems)
            {
                if(item.Created_in_Mobile__c ==true) continue;
                itemsOfInterest.add(item);
            }
            if(!itemsOfInterest.isEmpty())
            {
            	QuoteItemHandler.InitQuoteItems(itemsOfInterest);   
                RuleEngineDispatcher.RunDisallowedRules(itemsOfInterest);      
            }
        }
        for(Quote_Item__c item: quoteItems)
        {  
            if(!String.isBlank(item.SyncID__c))  continue;
            item.SyncID__c = StringUtility.newGuid();            
        }
        OverrideHandler.ApplyOverride(items);

	}

	public override void OnAfterInsert(List<sObject> items)
    {         
        super.OnAfterInsert(items);
        if(SObjectClonerUtility.CloningInProgress != true && RuleEngineCore.RuleEngineInProgress != true) 
        {
            List<Quote_Item__c> quoteItems = (List<Quote_Item__c>)items;
            List<Quote_Item__c> itemsOfInterest = new List<Quote_Item__c>();
            for(Quote_Item__c item: quoteItems)
            {
                if(item.Created_in_Mobile__c ==true) continue;
                itemsOfInterest.add(item);
            }
            if(!itemsOfInterest.isEmpty())
            {
                QuoteItemHandler.AddChildren(itemsOfInterest);
                RuleEngineDispatcher.Run(itemsOfInterest, false);
            }
        }    
    }   

    public override void OnBeforeUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    {            
        super.OnBeforeUpdate(items, oldMap);
        OverrideHandler.ApplyOverride(items);
    }  

	public override void OnBeforeDelete(List<sObject> items)
	{
        super.OnBeforeDelete(items);
		List<Quote_Item__c> quoteItems = (List<Quote_Item__c>)items;
		List<Quote_Item__c> itemsOfInterest = new List<Quote_Item__c>();

		for(Quote_Item__c o: quoteItems)
        {  
            if (RuleEngineCore.RuleEngineInProgress!=true && o.Auto_Added__c == true 
                && o.Rule_Required_Item__c ==true) 
            {                
                o.addError('Cannot delete a required Quote Item.');
                continue;
            } 
            itemsOfInterest.add(o);
        }

		QuoteItemHandler.DeleteChildItems(itemsOfInterest);
	}

	public override void OnAfterUpdate(List<sObject> items, Map<Id, sObject> oldMap)
    {     
        super.OnAfterUpdate(items, oldMap);   
        if(SObjectClonerUtility.CloningInProgress != true && RuleEngineCore.RuleEngineInProgress != true) 
        {
           RuleEngineDispatcher.Run((List<Quote_Item__c>)items, true);
        }
    }
}