src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/CDN_CMB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_CMB_Resource_URL__c</fullName>
    <defaultValue>"cmb/LATEST"</defaultValue>
    <label>CDN CMB Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_IIB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_IIB_Resource_URL__c</fullName>
    <defaultValue>"iib/LATEST"</defaultValue>
    <label>CDN Invoice Item Builder Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_JSD_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_JSD_Resource_URL__c</fullName>
    <defaultValue>"prod/jsd/LATEST"</defaultValue>
    <label>CDN JSD Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_JWB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_JWB_Resource_URL__c</fullName>
    <defaultValue>"prod/jwb/LATEST"</defaultValue>
    <label>CDN Job Whiteboard Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_PacketViewer_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_PacketViewer_Resource_URL__c</fullName>
    <defaultValue>"prod/pv/LATEST"</defaultValue>
    <label>CDN PacketViewer Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_PBB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_PBB_Resource_URL__c</fullName>
    <defaultValue>"prod/pbb/LATEST"</defaultValue>
    <label>CDN Builder Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_QIB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_QIB_Resource_URL__c</fullName>
    <defaultValue>"prod/qib/LATEST"</defaultValue>
    <label>CDN Quote Item Builder Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_RV_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_RV_Resource_URL__c</fullName>
    <defaultValue>"prod/rv/LATEST"</defaultValue>
    <label>CDN Report Viewer Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CDN_TIB_Resource_URL__c.field-meta.xml
<CustomField>
    <fullName>CDN_TIB_Resource_URL__c</fullName>
    <defaultValue>"prod/tib/LATEST"</defaultValue>
    <label>CDN Ticket Item Builder Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/Job_Whiteboard_Role_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Job_Whiteboard_Role_Record_Types__c</fullName>
    <defaultValue>"Labor"</defaultValue>
    <label>Job Whiteboard Role Record Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/MixPanelSecurityToken__c.field-meta.xml
<CustomField>
    <fullName>MixPanelSecurityToken__c</fullName>
    <defaultValue>"dfe456579c77b0bd5fec94f106e0e094"</defaultValue>
    <label>MixPanelSecurityToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/PacketViewer_Instance_URL_Override__c.field-meta.xml
<CustomField>
    <fullName>PacketViewer_Instance_URL_Override__c</fullName>
    <label>PacketViewer Instance URL Override</label>
    <description>Provides an override property to set the appropriate base/instance url in the case the primary method isn't sufficient.  This should be set to the "domain name" of this page (e.g. https://&lt;host-name>.cloudforce.com ). Setting this is usually only necessary if the sub-domain is "cloudforce.com" and the Packet Viewer is having issues re-running packets.</description>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/UtilityCustomSettings.cls
public with sharing class UtilityCustomSettings
{
    public UtilityCustomSettings(ApexPages.StandardController controller) { }

    public string getCustomSettings() { return JSON.serialize(UtilityCustomSettings.CurrentCustomSettings()); }

    public string getMixPanelSecurityToken() { return UtilityCustomSettings.CurrentCustomSettings().MixPanelSecurityToken; }
    public string getCdnTibResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_TIB_Resource_URL; }
    public string getCdnPbbResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_PBB_Resource_URL; }
    public string getCdnRvResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_RV_Resource_URL; }
    public string getCdnJwbResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_JWB_Resource_URL; }
    public string getCdnJsdResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_JSD_Resource_URL; }
    public string getCdnQibResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_QIB_Resource_URL; }
    public string getCdnIibResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_IIB_Resource_URL; }
    public string getCdnCmbResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_CMB_Resource_URL; }
    public string getCdnPacketViewerResourceURL() { return UtilityCustomSettings.CurrentCustomSettings().CDN_PacketViewer_Resource_URL; }
    public string getJwbRoleRecordTypes() { return UtilityCustomSettings.CurrentCustomSettings().Job_Whiteboard_Role_Record_Types; }


    private static CustomSettings customSettings = null;

    public static CustomSettings CurrentCustomSettings()
    {
        if (customSettings == null)
        {

            customSettings = new CustomSettings();
            FX_Settings__c fxSettings = FX_Settings__c.getInstance(UserInfo.getUserId());

            customSettings.MixPanelSecurityToken = fxSettings.MixPanelSecurityToken__c;
            customSettings.Job_Whiteboard_Role_Record_Types = fxSettings.Job_Whiteboard_Role_Record_Types__c;

            String val = fxSettings.CDN_TIB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/tib/LATEST';
            }
            customSettings.CDN_TIB_Resource_URL = val;

            val = fxSettings.CDN_PBB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/pbb/LATEST';
            }
            customSettings.CDN_PBB_Resource_URL = val;

            val = fxSettings.CDN_RV_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/rv/LATEST';
            }
            customSettings.CDN_RV_Resource_URL = val;

            val = fxSettings.CDN_JWB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/jwb/LATEST';
            }
            customSettings.CDN_JWB_Resource_URL = val;

            val = fxSettings.CDN_JSD_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/jsd/LATEST';
            }
            customSettings.CDN_JSD_Resource_URL = val;

            val = fxSettings.CDN_QIB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/qib/LATEST';
            }
            customSettings.CDN_QIB_Resource_URL = val;

            val = fxSettings.CDN_IIB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'iib/LATEST';
            }
            customSettings.CDN_IIB_Resource_URL = val;

            val = fxSettings.CDN_CMB_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'cmb/LATEST';
            }
            customSettings.CDN_CMB_Resource_URL = val;

            val = fxSettings.CDN_PacketViewer_Resource_URL__c;
            if (String.isBlank(val)) {
                val = 'prod/pv/LATEST';
            }
            customSettings.CDN_PacketViewer_Resource_URL = val;

            // optional: no default value
            val = fxSettings.PacketViewer_Instance_URL_Override__c;
            customSettings.PacketViewer_Instance_URL_Override = val;

        }

        return customSettings;
    }

    public class CustomSettings {
        public string MixPanelSecurityToken { get; set; }
        public string CDN_TIB_Resource_URL { get; set; }
        public string CDN_PBB_Resource_URL { get; set; }
        public string CDN_RV_Resource_URL { get; set; }
        public string CDN_JWB_Resource_URL { get; set; }
        public string CDN_JSD_Resource_URL { get; set; }
        public string CDN_QIB_Resource_URL { get; set; }
        public string CDN_IIB_Resource_URL { get; set; }
        public string CDN_CMB_Resource_URL { get; set; }
        public string CDN_PacketViewer_Resource_URL { get; set; }
        public string Job_Whiteboard_Role_Record_Types { get; set; }
        public string PacketViewer_Instance_URL_Override {get;set;}
    }
}