src/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <description>Storage for sync (upload) errors and other similar data.</description>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>AL-{0}</displayFormat>
        <label>Audit Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Audit_Log__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <inlineHelpText>Date and time of the event recorded by the log entry. For sync upload errors, this is the date and time when the sync failed. For successful syncs, this is the date and time when the sync completed successfully.</inlineHelpText>
    <label>Event Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/Audit_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Log Entry</description>
    <inlineHelpText>Type of log entry.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>SyncComplete</fullName>
            </value>
            <value>
                <fullName>SyncDownloadComplete</fullName>
            </value>
            <value>
                <fullName>SyncUploadError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/AuditLogRetainingDays__c.field-meta.xml
<CustomField>
    <fullName>AuditLogRetainingDays__c</fullName>
    <defaultValue>30</defaultValue>
    <label>AuditLogRetainingDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/AuditLogTypeForTruncation__c.field-meta.xml
<CustomField>
    <fullName>AuditLogTypeForTruncation__c</fullName>
    <defaultValue>'SyncComplete,SyncDownloadComplete'</defaultValue>
    <label>AuditLogTypeForTruncation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/AuditLogTruncator_Test.cls
@isTest
private class AuditLogTruncator_Test
{
	static testmethod void Schedulable_Test()
    { 
        Test.startTest();

        // This test runs a scheduled job at midnight March 15, 2054
        String CRON_EXP = '0 0 0 15 3 ? 2054';

        // Schedule the test job
        String jobId = System.schedule('AuditLogTruncatorScheduler_Test',
                        CRON_EXP, 
                        new AuditLogTruncatorScheduler());
         
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);

        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        // Verify the next time the job will run
        System.assertEquals('2054-03-15 00:00:00', String.valueOf(ct.NextFireTime));      
        Test.stopTest();
    }

    static testMethod void Batchable_NoFX_Setting_Test()
    {        
        Test.startTest();
        
        AuditLogTruncator b = new AuditLogTruncator();
        Database.executeBatch(b);
        Test.stopTest();
    }

    static testMethod void Batchable_WithFX_Setting_Test()
    {        
    	Test.startTest();

    	FX_Settings__c setting = FX_Settings__c.getInstance(UserInfo.getUserId());    
    	setting.AuditLogTypeForTruncation__c = 'SyncComplete,SyncDownloadComplete';
    	setting.AuditLogRetainingDays__c =  -1;
    	upsert setting;

    	List<Audit_Log__c> items = new List<Audit_Log__c>();
    	for(Integer i=0; i<100; i++)
    	{
    		items.add( new Audit_Log__c(Type__c = 'SyncComplete', Event_Date__c = Datetime.now().addMinutes(-10)));
    	}
    	insert items;

    	List<Audit_Log__c> dbItems = [SELECT Id FROM Audit_Log__c WHERE IsDeleted=false];
    	System.assert(dbItems.size()==100, 'should have 100 items instead of ' + dbItems.size());
       
        AuditLogTruncator b = new AuditLogTruncator();
        Database.executeBatch(b);
        Test.stopTest();

        dbItems = [SELECT Id FROM Audit_Log__c WHERE IsDeleted=false];
    	System.assert(dbItems.isEmpty(), 'should have no item after deletion, instead of ' + dbItems.size());
    }

    static testMethod void Batchable_DryRun_Test()
    {        
        Test.startTest();
        AuditLogTruncator b = new AuditLogTruncator();
        b.DryRun();
        Test.stopTest();
    }

}