src/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer for which the checklist displays on tickets. If no customer is specified, the checklist displays on the tickets for every customer.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklists (Account)</relationshipLabel>
    <relationshipName>Ticket_Check_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Checklist__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office for which the checklist displays on tickets. If no office is specified, the checklist displays on tickets for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklists (Office)</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Checklist__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for which the checklist displays on tickets. If no segment is specified, the checklist displays on tickets for every segment.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Checklist__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <inlineHelpText>Ticket type for which the checklist displays on tickets. If no ticket type is specified, the checklist displays on tickets for every ticket type.</inlineHelpText>
    <label>Ticket Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Field Ticket</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Checklist_Step__c/Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Checklist Step</label>
    <nameField>
        <label>Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Checklist_Step__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <inlineHelpText>Checklist on which the step displays.</inlineHelpText>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Steps</relationshipLabel>
    <relationshipName>Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Checklist_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Text that displays for the step on a checklist.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Checklist_Step__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the position of the step on a checklist. For example, "5.0000" indicates the step is the fifth step on a checklist.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Notes recorded about the job.</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <inlineHelpText>Business segment for the job.</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Segment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the job.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the job.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment used on the job is stored. When you select a warehouse, the ticket items added to tickets for the job will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Notes recorded about the ticket.</inlineHelpText>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Job__r.Office__r.Name</formula>
    <inlineHelpText>Office responsible for performing the work listed on the ticket.</inlineHelpText>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Current status of the ticket.</inlineHelpText>
    <label>Status</label>
    <referenceTo>Status__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after adding the ticket.</inlineHelpText>
    <label>Tracking Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment included on the ticket is stored. When you select a warehouse, ticket items will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Text that displays for the step on a checklist.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the position of the step on a checklist. For example, "5.0000" indicates that the step is the fifth step on a checklist.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will insert a UUID only if it is not already there</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/TicketBuilder_Test.cls
@isTest
private class TicketBuilder_Test 
{    
    static testmethod void Initialize_Test()
    {
        Test.StartTest();
        Integer tktCount = 200;
        List<Ticket__c> tkts =  AlpineTestHelper.CreateTickets(tktCount, false);        
        string jobID = tkts.get(0).Job__c;

        string notes = StringUtility.newGuid();
        for(Integer i=0; i<tktCount; i++)
        {
            tkts.get(i).Notes__c = notes;
        }
        insert tkts;
        Test.StopTest();
        List<Ticket__c> dbTkts = [SELECT SyncID__c, Tracking_Number__c, Status__c FROM Ticket__c WHERE Job__c =:jobID];
        System.assertEquals(dbTkts.size(), tktCount);
        for(Ticket__c tkt : dbTkts)
        {
            System.debug(tkt);
            System.assert(StringUtility.isValidTrackingNumber(StringUtility.EntityObjectType.Ticket, tkt.Tracking_Number__c));          
            System.assert(tkt.SyncID__c != null);
            System.assert(tkt.Status__c != null);
        }
    }


    static testmethod void PopulateTicketWarehouse_Test()
    {
        Warehouse__c wh = new Warehouse__c(Name=StringUtility.newGuid());
        insert wh;
        Job__c job = AlpineTestHelper.CreateJobs(1, false).get(0);
        job.Warehouse__c = wh.Id;
        insert job;

        Test.StartTest();
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        Test.StopTest();

        Ticket__c dbTkt = [SELECT Id, Warehouse__c FROM Ticket__c WHERE Job__c =:job.Id LIMIT 1];
        System.assert(!String.isBlank(dbTkt.Warehouse__c));
        System.assertEquals(wh.Id, dbTkt.Warehouse__c);


    }
    static testmethod void CreateChecklistSteps_Test()
    {
        Test.StartTest();

        string newGuid = StringUtility.newGuid();
        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        j.Name = newGuid;
        insert j;    
        
        Job__c job = [SELECT Id, CustomerAccount__c, Office__c, RecordTypeId, RecordType.DeveloperName, Segment__c FROM Job__c WHERE Name=:newGuid LIMIT 1];

        Ticket__c t = AlpineTestHelper.CreateTickets(job, 1, false).get(0);
        
        RecordType rt = [SELECT DeveloperName FROM RecordType where IsActive=true AND  Id=:t.RecordTypeId];

        String checklistName = 'Checklist' + newGuid;
        Checklist__c cl = new Checklist__c(Account__c = job.CustomerAccount__c, Name=checklistName, Ticket_Type__c = rt.DeveloperName);
        insert cl;

        List<Checklist_Step__c> checklistSteps = new List<Checklist_Step__c>();
        Integer steps = 5;
        for(Integer i=0; i<steps; i++)
        { 
             Checklist_Step__c cli = new Checklist_Step__c(Checklist__c = cl.Id, Sequence_Number__c = i, Description__c = string.valueOf(i) + newGuid, Screen__c = 'Labor');
             checklistSteps.add(cli);
        }
        insert checklistSteps;   

        insert t;     

        Test.StopTest();

        Ticket__c dbTkt = [SELECT Checklist_Name__c FROM Ticket__c where Id =:t.Id];
        System.assertEquals(checklistName, dbTkt.Checklist_Name__c);

        List<Ticket_Checklist_Step__c> pis = [SELECT Screen__c, Sequence_Number__c, Name, Description__c, SyncID__c FROM Ticket_Checklist_Step__c WHERE Ticket__c = :t.Id ORDER BY Sequence_Number__c];     
        System.assertEquals(steps, pis.size());

        for(Integer i=0; i<steps; i++)
        {
            System.assertEquals(string.valueOf(i) + newGuid, pis.get(i).Description__c);
            System.assert(StringUtility.isValidGuid(pis.get(i).SyncID__c));
        }
       
    }


    
}