src/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Customer for which the checklist displays on tickets. If no customer is specified, the checklist displays on the tickets for every customer.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklists (Account)</relationshipLabel>
    <relationshipName>Ticket_Check_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Checklist_Step__c/Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Checklist Step</label>
    <nameField>
        <label>Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Checklist_Step__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <inlineHelpText>Checklist on which the step displays.</inlineHelpText>
    <label>Checklist</label>
    <referenceTo>Checklist__c</referenceTo>
    <relationshipLabel>Checklist Steps</relationshipLabel>
    <relationshipName>Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Checklist_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Text that displays for the step on a checklist.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Checklist_Step__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <inlineHelpText>Tab on the Tickets page in FieldFX Mobile that displays when a user selects the step on a checklist.</inlineHelpText>
    <label>Screen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ticket/{trackingNumber}?tab=details</fullName>
            </value>
            <value>
                <fullName>ticket/{trackingNumber}?tab=log</fullName>
            </value>
            <value>
                <fullName>ticket/{trackingNumber}?tab=items</fullName>
            </value>
            <value>
                <fullName>ticket/{trackingNumber}?tab=reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Checklist_Step__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the position of the step on a checklist. For example, "5.0000" indicates the step is the fifth step on a checklist.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Name__c</fullName>
    <description>The name of the checklist assigned to this ticket</description>
    <inlineHelpText>Name of the checklist used on the ticket.</inlineHelpText>
    <label>Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Text that displays for the step on a checklist.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <inlineHelpText>Page in FieldFX Mobile that displays when a user selects the step on a checklist.</inlineHelpText>
    <label>Screen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Sign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the position of the step on a checklist. For example, "5.0000" indicates that the step is the fifth step on a checklist.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will insert a UUID only if it is not already there</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/TestCreateChecklistTrigger.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
 * The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
private class TestCreateChecklistTrigger {

    static testMethod void myUnitTest() {
       
        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);

        string checkListName = StringUtility.newGuid();
        Checklist__c cl = new Checklist__c(Account__c = j.CustomerAccount__c, Name= checkListName);
        insert cl;
        Checklist_Step__c cli = new Checklist_Step__c(Checklist__c = cl.Id, Sequence_Number__c = 1, Description__c = 'test1', Screen__c = 'Labor');
        Checklist_Step__c cli2 = new Checklist_Step__c(Checklist__c = cl.Id, Sequence_Number__c = 2, Description__c = 'test2', Screen__c = 'Labor');
        insert cli;
        insert cli2;
        
        Ticket__c t = AlpineTestHelper.CreateTickets(j, 1, true).get(0);

            
        //Ticket_Checklist_Step__c secondpi = pis.get(1);
        
        Ticket__c tkt = [SELECT Checklist_Name__c FROM Ticket__c WHERE Id = :t.Id LIMIT 1];
        System.assertEquals(tkt.Checklist_Name__c,  checkListName);

        List<Ticket_Checklist_Step__c> pis = [SELECT Screen__c, Sequence_Number__c, Name, Description__c, SyncID__c FROM Ticket_Checklist_Step__c WHERE Ticket__c = :t.Id ORDER BY Sequence_Number__c];    

        System.assertEquals(pis.size(), 2);
        //System.assertEquals(secondpi.Sequence_Number__c, 2);
        //System.assertEquals(secondpi.Description__c, 'test2');
        //System.assert(StringUtility.isValidGuid(secondpi.SyncID__c));
    }
}