src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Classification to which the item belongs.</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Catalog Items</relationshipLabel>
    <relationshipName>Catalog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Cost of purchasing the item.</inlineHelpText>
    <label>Cost</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Name_Unique__c</fullName>
    <description>This is only used to guarantee uniqueness of the SFDC standard object field Name (Item Code).  It never needs to be shown to the user.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the item.</inlineHelpText>
    <label>Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Office responsible for completing the job.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Office)</relationshipLabel>
    <relationshipName>Jobs1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Office that uses the price book. If an office is not selected, the price book is available for every office.</inlineHelpText>
    <label>Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books (Office)</relationshipLabel>
    <relationshipName>Price_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Description_Override__c.field-meta.xml
<CustomField>
    <fullName>Description_Override__c</fullName>
    <description>Complete this field to override the catalog item description within this price book</description>
    <inlineHelpText>Catalog description for the price book item. This description overrides the catalog description inherited from the linked catalog item.</inlineHelpText>
    <label>Description Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Locked_Description__c.field-meta.xml
<CustomField>
    <fullName>Locked_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, the user cannot change the description when the price book item is used on a ticket.</description>
    <inlineHelpText>If selected, users cannot changed the description for the price book item when adding a ticket.</inlineHelpText>
    <label>Locked Description</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Locked_Discount__c.field-meta.xml
<CustomField>
    <fullName>Locked_Discount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users cannot change the discount granted on the price book item when adding a ticket.</inlineHelpText>
    <label>Locked Discount</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Locked_Price_Markup__c.field-meta.xml
<CustomField>
    <fullName>Locked_Price_Markup__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users cannot change the price charged for the price book item when adding a ticket.</inlineHelpText>
    <label>Locked Price/Markup</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Requires_Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Requires_Parent_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item and its parent price book item get added automatically to all new tickets.</inlineHelpText>
    <label>Requires Parent Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Job__r.Office__r.Name</formula>
    <inlineHelpText>Office responsible for performing the work listed on the ticket.</inlineHelpText>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Cost of purchasing the ticket item. The ticket item inherits this cost from the linked catalog item.</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <formula>Ticket__r.Job__r.CustomerAccount__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Ticket__r.Job__r.Office__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/TicketItemPreventChangingLockedDesc_Test.cls
@isTest
private class TicketItemPreventChangingLockedDesc_Test {

    static Price_Book__c SetupPriceBook() 
    {
        Classification__c classification = new Classification__c();
        classification.Name = 'Name';
        insert classification;
        
        Catalog_Item__c catalogItem = new Catalog_Item__c();
        catalogItem.Classification__c = classification.Id;
        catalogItem.Cost__c = 0.0;
        catalogItem.Description__c = 'Description';
        catalogItem.Name = 'Name';
        catalogItem.Name_Unique__c = 'Name Unique';
        insert catalogItem;
        
        Price_Book__c priceBook = new Price_Book__c();
        insert priceBook;
        
        Price_Book_Item__c pbi = new Price_Book_Item__c();
        pbi.Description_Override__c = 'locked desc';
        pbi.Catalog_Item__c = catalogItem.Id;
        pbi.Price_Book__c = priceBook.Id;
        pbi.Default_Quantity__c = 0;
        pbi.Price__c = 0;
        pbi.Locked_Description__c = true;
        insert pbi;
        
        pbi = new Price_Book_Item__c();
        pbi.Description_Override__c = 'unlocked';
        pbi.Catalog_Item__c = catalogItem.Id;
        pbi.Price_Book__c = priceBook.Id;
        pbi.Default_Quantity__c = 0;
        pbi.Price__c = 0;
        pbi.Locked_Description__c = false;
        pbi.Locked_Discount__c = false;
        pbi.Locked_Price_Markup__C = false;
        pbi.Parent_Price_Book_Item__c = pbi.Id;
        pbi.Requires_Parent_Item__c = true;

        insert pbi;

        pbi = new Price_Book_Item__c();
        pbi.Description_Override__c = 'locked discount';
        pbi.Catalog_Item__c = catalogItem.Id;
        pbi.Price_Book__c = priceBook.Id;
        pbi.Default_Quantity__c = 0;
        pbi.Price__c = 0;
        pbi.Locked_Description__c = false;
        pbi.Locked_Discount__c = true;
        pbi.Parent_Price_Book_Item__c = pbi.Id;
        pbi.Requires_Parent_Item__c = true;

        insert pbi;

        pbi = new Price_Book_Item__c();
        pbi.Description_Override__c = 'locked price markup';
        pbi.Catalog_Item__c = catalogItem.Id;
        pbi.Price_Book__c = priceBook.Id;
        pbi.Default_Quantity__c = 0;
        pbi.Price__c = 0;
        pbi.Locked_Description__c = false;
        pbi.Locked_Discount__c = false;
        pbi.Locked_Price_Markup__C = true;
        pbi.Parent_Price_Book_Item__c = pbi.Id;
        pbi.Requires_Parent_Item__c = true;

        insert pbi;
        
        return priceBook;
    }

    static Job__c SetupJob(Price_Book__c priceBook) 
    {
        Account account = new Account();
        account.Name = 'Account';
        insert account;
        
        Account office = new Account();
        office.Name = 'office';
        office.RecordTypeId = [select Id FROM RecordType where IsActive=true AND  Name = 'office' and SobjectType = 'Account'][0].Id;
        insert office;
        
        Job__c job = new Job__c();
        job.Name = 'jobname';
        job.Office__c = office.Id;
        job.CustomerAccount__c = account.Id;
        job.Price_Book__c = priceBook.Id;
        insert job;
        
        Ticket__c ticket = new Ticket__c();
        ticket.Job__c = job.Id;
        insert ticket;
        
        Ticket_Item__c ticketItem = new Ticket_Item__c();
        ticketItem.Price_Book_Item__c = [select Id from Price_Book_Item__c where Description_Override__c = 'locked desc'][0].Id;
        ticketItem.Ticket__c = ticket.Id;
        insert ticketItem;

        ticketItem = new Ticket_Item__c();
        ticketItem.Price_Book_Item__c = [select Id from Price_Book_Item__c where Description_Override__c = 'unlocked'][0].Id;
        ticketItem.Ticket__c = ticket.Id;
        insert ticketItem;

        ticketItem = new Ticket_Item__c();
        ticketItem.Price_Book_Item__c = [select Id from Price_Book_Item__c where Description_Override__c = 'locked discount'][0].Id;
        ticketItem.Ticket__c = ticket.Id;
        insert ticketItem;

        ticketItem = new Ticket_Item__c();
        ticketItem.Price_Book_Item__c = [select Id from Price_Book_Item__c where Description_Override__c = 'locked price markup'][0].Id;
        ticketItem.Ticket__c = ticket.Id;
        insert ticketItem;
        
        return Job;
    }    
    
    static testmethod void ChangeLockedDiscriptionTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
        Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'locked desc' ];
        ticketItem.Description__c = 'changed description';
        
        try {
            update ticketItem;
        } catch (exception e) {
            system.assert(e.getMessage().contains('Cannot change the description as it is locked.'));
        }
    }

    static testmethod void ChangeUnLockedDiscriptionTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
        Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'unlocked' ];
        
        ticketItem.Description__c = 'changed description';
        update ticketItem;
        
        List<Ticket_Item__c> verifyTicketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'changed description' ];

        system.assertEquals(1 , verifyTicketItems.size() );
    }
 
    static testmethod void ChangeLockedDiscountTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
        Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'locked discount' ];
        ticketItem.Discount_Percent__c  = 99;
        
        try {
            update ticketItem;
        } catch (exception e) {
            system.assert(e.getMessage().contains('Cannot change the discounted percent as the discount is locked.'));
        }
    }
 
     static testmethod void ChangeUnLockedDiscountTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
         Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'unlocked' ];
        
        ticketItem.Discount_Percent__c  = 99;
        update ticketItem;
        
        List<Ticket_Item__c> verifyTicketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id AND Discount_Percent__c = 99 ];

        system.assertEquals(1 , verifyTicketItems.size() );
   }
 
    static testmethod void ChangeLockedPriceMarkupTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
        Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'locked price markup' ];
        ticketItem.Price__c = 99;
        
        try {
            update ticketItem;
        } catch (exception e) {
            system.assert(e.getMessage().contains('Cannot change the price'));
        }
    }
 
     static testmethod void ChangeUnLockedPriceMarkupTest()
    {
        Test.StartTest();
        
        //setup test
        Price_Book__c priceBook = SetupPriceBook();
        Job__c job = SetupJob(pricebook);
        
        Test.StopTest();
        
        //test to see if passed
        
        Ticket__c ticket = [select Id from Ticket__c where Job__c = :job.Id];
        List<Ticket_Item__c> ticketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id];

        system.assertEquals(4 , ticketItems.size() ); 
        
         Ticket_Item__c ticketItem = [select Id, Price_Book_Item__c from Ticket_Item__c where Ticket__c = :ticket.Id AND Description__c = 'unlocked' ];
        
        ticketItem.Price__c = 99;
        update ticketItem;
        
        List<Ticket_Item__c> verifyTicketItems = [select Id from Ticket_Item__c where Ticket__c = :ticket.Id AND Price__c = 99 ];

        system.assertEquals(1 , verifyTicketItems.size() );
   }
 
}