src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/CreatePricebookItemsFromCatalogItemsTest.cls
@isTest
private class CreatePricebookItemsFromCatalogItemsTest 
{    
    static testmethod void Create4Items()
    {
        Test.StartTest();   
        
        String itemType = 'Labor';
        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        Catalog_Item__c cat1 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item1', 
                                    UOM__c='Gal', Sequence_Number__c=1,  Ticket_Item_Record_Type__c = itemType);
        insert cat1;

        Catalog_Item__c cat2 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item2', 
                                    UOM__c='Gal', Sequence_Number__c=2,  Ticket_Item_Record_Type__c = itemType);
        insert cat2;

        Catalog_Item__c cat3 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item3', 
                                    UOM__c='Gal', Sequence_Number__c=3,  Ticket_Item_Record_Type__c = itemType);
        insert cat3;

        Catalog_Item__c cat4 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item4', 
                                    UOM__c='Gal', Sequence_Number__c=4,  Ticket_Item_Record_Type__c = itemType);
        insert cat4;
        cat1 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item1' LIMIT 1];
        cat2 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item2' LIMIT 1];
        cat3 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item3' LIMIT 1];
        cat4 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item4' LIMIT 1];
        
        List<Id> catalogItemIds = new List<Id>();
        catalogItemIds.add(cat1.Id);
        catalogItemIds.add(cat2.Id);
        catalogItemIds.add(cat3.Id);
        catalogItemIds.add(cat4.Id);

        String parentId = '';

        CreatePricebookItemsFromCatalogItems.CreatePricebookItems(pb.Id, catalogItemIds, parentId);

        Test.StopTest();

        List<Price_Book_Item__c> dbItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id];
        System.assert(dbItems.size() == 4);
    }  

    static testmethod void Create1Item3Children()
    {
        Test.StartTest();   
        
        String itemType = 'Labor';
        Price_Book__c pb = AlpineTestHelper.CreatePriceBook(true, Date.today(), 'USD');

        Catalog_Item__c cat1 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item1', 
                                    UOM__c='Gal', Sequence_Number__c=1,  Ticket_Item_Record_Type__c = itemType);
        insert cat1;
        cat1 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item1' LIMIT 1];

        List<Id> catalogItemIds = new List<Id>();
        catalogItemIds.add(cat1.Id);
        CreatePricebookItemsFromCatalogItems.CreatePricebookItems(pb.Id, catalogItemIds, '');
        List<Price_Book_Item__c> dbItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id];
        Price_Book_Item__c parentPbi = dbItems[0];

        Catalog_Item__c cat2 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item2', 
                                    UOM__c='Gal', Sequence_Number__c=2,  Ticket_Item_Record_Type__c = itemType);
        insert cat2;
        Catalog_Item__c cat3 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item3', 
                                    UOM__c='Gal', Sequence_Number__c=3,  Ticket_Item_Record_Type__c = itemType);
        insert cat3;
        Catalog_Item__c cat4 = new Catalog_Item__c(Name= 'CI' +  StringUtility.newGuid(), Description__c = 'Test Catalog Item4', 
                                    UOM__c='Gal', Sequence_Number__c=4,  Ticket_Item_Record_Type__c = itemType);
        insert cat4;
        cat2 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item2' LIMIT 1];
        cat3 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item3' LIMIT 1];
        cat4 = [SELECT Id FROM Catalog_Item__c WHERE Description__c ='Test Catalog Item4' LIMIT 1];
        
        catalogItemIds = new List<Id>();
        catalogItemIds.add(cat2.Id);
        catalogItemIds.add(cat3.Id);
        catalogItemIds.add(cat4.Id);

        String parentId = parentPbi.Id;

        CreatePricebookItemsFromCatalogItems.CreatePricebookItems(pb.Id, catalogItemIds, parentId);

        Test.StopTest();

        dbItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id];
        System.assert(dbItems.size() == 4);

        dbItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id AND Id =:parentPbi.Id];
        System.assert(dbItems.size() == 1);

        dbItems = [SELECT Id FROM Price_Book_Item__c WHERE Price_Book__c =:pb.Id AND Parent_Price_Book_Item__c =:parentPbi.Id];
        System.assert(dbItems.size() == 3);
    }  

}