src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Included_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Included_Quantity__c</fullName>
    <inlineHelpText>Quantity of the price book item given to the customer at no charge.</inlineHelpText>
    <label>Included Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the ticket item. The ticket item inherits this discount from the linked price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/PBI_Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>PBI_Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket. The ticket item inherits this default quantity from the linked price book item.</inlineHelpText>
    <label>PBI Default Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/TicketItemManglerTest.cls
@isTest
private class TicketItemManglerTest{

    
    static testmethod void setupTicketItem(){
        
        Test.startTest();
      Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
       Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
       insert catalogItem;
              
       Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       insert pli;
       
        
      Ticket__c t= new Ticket__c(Job__c = job.Id);
      insert t;
       
      Ticket_Item__c tktItem  = new Ticket_Item__c(Ticket__c = t.Id, Price_Book_Item__c = pli.Id);
       
       insert tktItem;    
       Test.stopTest();

       Price_Book_Item__c dbPli = [SELECT Id, Default_Quantity__c FROM Price_Book_Item__c WHERE Id=:pli.Id];
       System.debug('dbPli=' + dbPli);

       Ticket_Item__c dbItem  = [SELECT Id, Price_Book_Item__c, PBI_Default_Quantity__c, SyncID__c FROM Ticket_Item__c WHERE Ticket__c= :t.Id AND Price_Book_Item__c =:pli.Id LIMIT 1];  
       System.debug('tktItem=' + dbItem);
       
       System.debug('Tkt Item SyncID__c *************************************************  AFTER insert ' + dbItem.SyncID__c);
       system.assert(StringUtility.isValidGuid(dbitem.SyncID__c)); 
       system.assertEquals(1096, dbItem.PBI_Default_Quantity__c); 
      
    }

    static testmethod void AddChild_Test()
    {
        Test.StartTest();        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c ticket = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        Id priceBookId = job.Price_Book__c;

        AlpineTestHelper.CreatePriceBookItems(5, priceBookId , 'Equipment', true);
        List<Price_Book_Item__c> dbItems = [SELECT Id, Price_Book__c,  Parent_Price_Book_Item__c FROM Price_Book_Item__c WHERE Price_Book__c =:priceBookId];

        Price_Book_Item__c p= dbItems.get(0);
        dbItems.get(1).Parent_Price_Book_Item__c = p.Id;
        dbItems.get(2).Parent_Price_Book_Item__c = p.Id;        
        update dbItems;

        Ticket_Item__c ti = new Ticket_Item__c();
        ti.Ticket__c = ticket.Id;
        ti.Price_Book_Item__c = p.Id;
        insert ti;
        Test.stopTest();

        List<Ticket_Item__c> tktItems = [SELECT Id, Auto_Added__c FROM Ticket_Item__c WHERE Ticket__c=:ticket.Id AND Auto_Added__c=false];
        System.assert(tktItems.size()==3, 'Ticket should have 3 items - 1 parent with two child items');

    }


    static testmethod void DeletePbRequiredItem_NoGo_Test()
    {
      Test.startTest();
      Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
      Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
      insert catalogItem;
              
      Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Price__c=125, Required_Item__c=true,
         Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
      insert pli;
       
        
      Ticket__c t= new Ticket__c(Job__c = job.Id);
      insert t;

      //Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = t.Id, Price_Book_Item__c = pli.Id, Auto_Added__c =true);
      //insert ti;

      Test.stopTest();

      List<Ticket_Item__c> tktItems = [SELECT Id, PBI_Required_Item__c, Price_Book_Item__r.Required_Item__c FROM Ticket_Item__c WHERE Ticket__c=:t.Id AND Price_Book_Item__c = :pli.Id];
      System.assert(tktItems.size()==1);
      System.assert(tktItems.get(0).PBI_Required_Item__c);
      System.assert(tktItems.get(0).Price_Book_Item__r.Required_Item__c);

      String errorMsg = '';
      try
      {
          delete tktItems;
      }
      catch(System.DMLException e) 
      {
          for (Integer i = 0; i < e.getNumDml(); i++)
          {
             errorMsg += e.getDmlMessage(i);
          }    
      }
      System.assert(errorMsg.contains('Cannot delete a required ticket item'));   
       
    }

    static testmethod void DeletePbRequiredItem_Go_Test()
    {
      Test.startTest();
      Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       
      Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
      insert catalogItem;
              
      Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Price__c=125, Required_Item__c=true,
         Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
      insert pli;
       
        
      Ticket__c t= new Ticket__c(Job__c = job.Id);
      insert t;

      //Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = t.Id, Price_Book_Item__c = pli.Id, Auto_Added__c =true);
      //insert ti;

      pli.Required_Item__c = false;
      update pli;
      Test.stopTest();

      List<Ticket_Item__c> tktItems = [SELECT Id, PBI_Required_Item__c, Price_Book_Item__r.Required_Item__c FROM Ticket_Item__c WHERE Ticket__c=:t.Id AND Price_Book_Item__c = :pli.Id];
      System.assertEquals(1, tktItems.size());
      System.assertEquals(true, tktItems.get(0).PBI_Required_Item__c);
      System.assertEquals(false, tktItems.get(0).Price_Book_Item__r.Required_Item__c);

      String errorMsg = '';
      try
      {
          delete tktItems;
      }
      catch(System.DMLException e) 
      {
          for (Integer i = 0; i < e.getNumDml(); i++)
          {
             errorMsg += e.getDmlMessage(i);
          }    
      }
      System.assertEquals('', errorMsg);  
       
    }
    
    static testmethod void TicketItemDiscountedPriceStandbyPrice(){
      
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
      
       Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210, Ticket_Item_Record_Type__c = 'Equipment');
       insert catalogItem;
       
       
       Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Price__c=100, Sequence_Number__c =1, Discount_Percent__c=10, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       insert pli;
       


        Ticket__c t= new Ticket__c(Job__c = job.Id);
        insert t;
      
       Ticket_Item__c tktItem1  = new Ticket_Item__c(Ticket__c = t.Id, Price_Book_Item__c = pli.Id);
       insert tktItem1;    
       //Ticket_Item__c dbItem1  = [SELECT Discounted_Price__c FROM Ticket_Item__c WHERE Id= :tktItem1.Id LIMIT 1];  

       //system.assertEquals(dbItem1.Discounted_Price__c , pli.Price__c * (1 - pli.Discount_Percent__c/100.0)); 

       Price_Book_Item__c pli2 = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Price__c=200, Sequence_Number__c =1, Discount_Percent__c=10, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       pli2.Standby_Price__c = 99;
       insert pli2;

       Ticket_Item__c tktItem2  = new Ticket_Item__c(Ticket__c = t.Id, Price_Book_Item__c = pli2.Id, On_Standby__c=true);
       insert tktItem2;    
       //Ticket_Item__c dbItem2  = [SELECT Standby_Price__c FROM Ticket_Item__c WHERE Id =:tktItem2.Id LIMIT 1];  

       //System.assertEquals(dbItem2.Standby_Price__c , pli2.Standby_Price__c); 
       
    }   
     static testmethod void TicketItemDiscountedPriceStraightPrice(){
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
       

       Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210, Ticket_Item_Record_Type__c = 'Equipment');
       insert catalogItem;
      

       Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Sequence_Number__c =1, Price__c=100, Discount_Percent__c=10, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       pli.Pricing_Method__c = 'Straight Price'; 
       insert pli;
        Price_Book_Item__c pbi = [SELECT Id, Pricing_Method__c, Price__c FROM Price_Book_Item__c WHERE Price_Book__c=:job.Price_Book__c LIMIT 1];       
        Ticket__c t= new Ticket__c(Job__c = job.Id);
        insert t;
        Ticket__c tkt =  [SELECT Id, Tracking_Number__c FROM Ticket__c WHERE Job__c= :job.Id LIMIT 1];  
        string rowID2 = StringUtility.newGuid();
        Ticket_Item__c tktItem2  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id, Description__c = rowID2);
        tktItem2.Price__c=100;
        insert tktItem2;    
        Ticket_Item__c dbItem = [SELECT Id, PBI_Pricing_Method__c, Price__c, Discount_Percent__c FROM Ticket_Item__c WHERE Ticket__c= :tkt.Id  AND Description__c=:rowID2 LIMIT 1];

        // Test Update
        dbItem.Price__c = 200;
        update dbItem;
        Ticket_Item__c dbItem2 = [SELECT Id, PBI_Pricing_Method__c, Price__c, Discount_Percent__c FROM Ticket_Item__c WHERE Ticket__c= :tkt.Id  AND Description__c=:rowID2 LIMIT 1];
        //system.assertEquals(dbItem2.Discounted_Price__c , 180);
    }
    static testmethod void TicketItemDiscountedPriceCostPlusMarkupPercent(){
         Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
 
       Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', Cost__c=100, UOM__c='Gal', Sequence_Number__c=210, Ticket_Item_Record_Type__c = 'Equipment');
       insert catalogItem;
    

       Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Sequence_Number__c =1, Price__c=100, Discount_Percent__c=10, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       pli.Pricing_Method__c = 'Cost Plus Markup Percent'; 
       pli.Cost_Plus_Markup_Percent__c = 20;
       pli.Discount_Percent__c=10;
       insert pli;
        Price_Book_Item__c pbi = [SELECT Id, Pricing_Method__c, Price__c FROM Price_Book_Item__c WHERE Price_Book__c=:job.Price_Book__c LIMIT 1];       
        Ticket__c t= new Ticket__c(Job__c = job.Id);
        insert t;
        Ticket__c tkt =  [SELECT Id, Tracking_Number__c FROM Ticket__c WHERE Job__c= :job.Id LIMIT 1];  
        string rowID2 = StringUtility.newGuid();
        Ticket_Item__c tktItem2  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id, Description__c = rowID2);
        tktItem2.Price__c=100;
        tktItem2.Cost__c = 100;
        tktItem2.Cost_Plus_Markup_Percent__c = 20;
        tktItem2.Discount_Percent__c = 10;
        insert tktItem2;    
        Ticket_Item__c dbItem= [SELECT Id, On_Standby__c, PBI_Pricing_Method__c, Cost_Plus_Markup_Percent__c , Price__c, Discount_Percent__c FROM Ticket_Item__c WHERE Ticket__c= :tkt.Id  AND Description__c=:rowID2 LIMIT 1];
        System.debug('Tkt Item On_Standby__c*************************************************  AFTER insert ' + dbItem.On_Standby__c);
        System.debug('Tkt Item PBI_Pricing_Method__c*************************************************  AFTER insert ' + dbItem.PBI_Pricing_Method__c);
        System.debug('Tkt Item Cost_Plus_Markup_Percent__c *************************************************  AFTER insert ' + dbItem.Cost_Plus_Markup_Percent__c );
        System.debug('Tkt Item Price__c*************************************************  AFTER insert ' + dbItem.Price__c);
        System.debug('Tkt Item Discount_Percent__c*************************************************  AFTER insert ' + dbItem.Discount_Percent__c);
    }
    static testmethod void TicketItemDiscountedPriceCostPlusMarkupAmount(){
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
 
       
       Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', Cost__c=100, UOM__c='Gal', Sequence_Number__c=210, Ticket_Item_Record_Type__c = 'Equipment');
       insert catalogItem;
        
       Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Sequence_Number__c =1, Price__c=100, Discount_Percent__c=10, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
       pli.Pricing_Method__c = 'Cost Plus Markup Amount'; 
       pli.Cost_Plus_Markup_Amount__c = 100;
       pli.Discount_Percent__c=10;
       insert pli;
        Price_Book_Item__c pbi = [SELECT Id, Pricing_Method__c, Price__c FROM Price_Book_Item__c WHERE Price_Book__c=:job.Price_Book__c LIMIT 1];       
        Ticket__c t= new Ticket__c(Job__c = job.Id);
        insert t;
        Ticket__c tkt =  [SELECT Id, Tracking_Number__c FROM Ticket__c WHERE Job__c= :job.Id LIMIT 1];  
        string rowID2 = StringUtility.newGuid();
        Ticket_Item__c tktItem2  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id, Description__c = rowID2);
        tktItem2.Price__c=100;
        tktItem2.Cost__c =100;
        tktItem2.Cost_Plus_Markup_Amount__c = 100;
        tktItem2.Discount_Percent__c = 10;
        insert tktItem2;    
        Ticket_Item__c dbItem= [SELECT Id, On_Standby__c, Cost__c, PBI_Pricing_Method__c, Cost_Plus_Markup_Amount__c, Price__c, Discount_Percent__c FROM Ticket_Item__c WHERE Ticket__c= :tkt.Id  AND Description__c=:rowID2 LIMIT 1];
    }        
    
}