src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/AddTktItemsByPBSeqNum__c.field-meta.xml
<CustomField>
    <fullName>AddTktItemsByPBSeqNum__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, price book items, when added to a ticket, should honor the sequence number.  Otherwise they will be inserted at the end of the ticket.</description>
    <inlineHelpText>Controls whether users can change sequence numbers for price book items to adjust the order of item lists. If selected, users cannot change sequence numbers. If deselected, users can change sequence numbers and new items get added at the end of a list.</inlineHelpText>
    <label>Honor Sequence Number</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/CreatePricebookItemsFromCatalogItems.cls
@RestResource(urlMapping='/CreatePricebookItemsFromCatalogItems/*')
global with sharing class CreatePricebookItemsFromCatalogItems
{       
    @HttpPost
    global static List<Price_Book_Item__c> CreatePricebookItems(Id newPricebookId, List<Id> catalogItemIds, String parentId)
    {
        String ns = UtilityGetNamespace.CurrentNamespace();

        Schema.DescribeSObjectResult rCatalogItem = Catalog_Item__c.sObjectType.getDescribe();
        List<SObjectField> catalogItemFields = rCatalogItem.fields.getMap().values();

        Set<String> pbItemFieldNames = new Set<String>();        
        for(Schema.SObjectField f: Schema.sObjectType.Price_Book_Item__c.fields.getMap().values())
        {
            Schema.DescribeFieldResult fd = f.getDescribe(); 

            if (!fd.isAccessible() || !fd.isCreateable() || fd.isCalculated() || fd.isAutoNumber()) 
            {
                continue;
            }

            pbItemFieldNames.add(fd.getName());
        }
        String fieldsStr = String.join(new List<String>(pbItemFieldNames), ',');

        String fields = '';
        String sep = '';
        for(SObjectField fCatalogItem: catalogItemFields)
        {
            DescribeFieldResult dfrCatalogItem = fCatalogItem.getDescribe();
            fields += sep + dfrCatalogItem.getName();
            sep = ',';
        }       

        String soql = 'SELECT ';
        soql += fields;
        soql += ' FROM '+rCatalogItem.getName();
        soql += ' WHERE Id IN :catalogItemIds ';

        List<Catalog_Item__c> sourceCatalogItems = Database.query(soql);
        if(sourceCatalogItems == null) return null;

        Map<String, Catalog_Item__c> sourceCatalogItemsIdLookup = new Map<String, Catalog_Item__c>();
        for(Catalog_Item__c ci : sourceCatalogItems)
        {
            sourceCatalogItemsIdLookup.put(ci.Id, ci);
        }

        Map<Id, Catalog_Item__c> sourceCiLookup = new Map<Id, Catalog_Item__c>(sourceCatalogItems);

        List<Price_Book_Item__c> newPriceBookItems = new List<Price_Book_Item__c>();
        List<Price_Book_Item__c> pbItems = CreatePriceBookItemsUsingCatalogItems(newPricebookId, catalogItemIds, sourceCiLookup, parentId);
        insert pbItems;

        Map<Integer, Id> newPbiLookup = new Map<Integer, Id>();
        //need to preserve order so we can lookup matching quoteItem and ticketItem
        for(Integer i=0; i<pbItems.size(); i++)
        {
            newPbiLookup.put(i, pbItems.get(i).Id);            
        }

        List<Price_Book_Item__c> dbItems = refreshPricebookItemsList(pbItems, fieldsStr);
        Map<Id, Price_Book_Item__c> dbItemLookup = new Map<Id, Price_Book_Item__c>(dbItems);

        pbItems = UpdatePricebookItemsUsingCatalogItems(dbItems, catalogItemIds, sourceCiLookup, 
                        pbItemFieldNames, catalogItemFields,
                        sourceCatalogItemsIdLookup);

        newPriceBookItems.addAll(pbItems);

        return newPriceBookItems;
    }

    public static List<Price_Book_Item__c> refreshPricebookItemsList(List<Price_Book_Item__c> pbItems, String fieldsStr) {
        String ns = UtilityGetNamespace.CurrentNamespace();
        Set<Id> pbItemIds = new Map<Id, Price_Book_Item__c>(pbItems).keySet();
        String pbiSoql = String.format('SELECT {0} FROM {1} WHERE Id IN :pbItemIds', new String[]{fieldsStr, ns+'Price_Book_Item__c'});
        return (List<Price_Book_Item__c>)Database.query(pbiSoql);
    }

    public static List<Price_Book_Item__c> UpdatePricebookItemsUsingCatalogItems(
            List<Price_Book_Item__c> pbItems, List<Id> catalogItemIds, Map<Id, Catalog_Item__c> sourceCiLookup,
            Set<String> pbItemFieldNames, List<SObjectField> catalogItemFields,
            Map<String, Catalog_Item__c> sourceCatalogItemsIdLookup
    ) {
        String ns = UtilityGetNamespace.CurrentNamespace();

        Integer m = 0;
        Map<String, String> newIdToOriginalIdLookup = new Map<String, String>();
        for(String origId : sourceCatalogItemsIdLookup.keySet())
        {
            Price_Book_Item__c newPbi = pbItems.get(m);
            newIdToOriginalIdLookup.put(origId, newPbi.Id);

            m++;
        }

        Map<String, Price_Book_Item__c> targetPbItemIdsIdLookup = new Map<String, Price_Book_Item__c>();
        for(Price_Book_Item__c dbpbi : pbItems)
        {
            targetPbItemIdsIdLookup.put(dbpbi.Id, dbpbi);
        }

        Map<Id, Price_Book_Item__c> pbiLookup = new Map<Id, Price_Book_Item__c>(pbItems);
        //Map<Id, Price_Book_Item__c> tiToPbiLookup = new Map<Id, Ticket_Item__c>();

        for(Id catalogItemId: catalogItemIds) {
            Catalog_Item__c sourceCatalogItem = sourceCiLookup.get(catalogItemId);
            String targetId = newIdToOriginalIdLookup.get(sourceCatalogItem.Id);
            Price_Book_Item__c targetPbItem = targetPbItemIdsIdLookup.get(targetId);

            //copy fields
            for(SObjectField fCatalogItem: catalogItemFields)
            {
                DescribeFieldResult dfrCatalogItem = fCatalogItem.getDescribe();
                String origf = dfrCatalogItem.getName();
                String f = ns + origf.replace(ns,''); //make sure fieldname has namespace
                String nf = origf.replace(ns,'');

                //skip system fields, and Sequence_Number__c. 
                //PriceBook has a flag AddTktItemsByPBSeqNum__c to control how the sequence number should be assigned 
                //and codes are down below to do that.
                if(!f.endsWith('__c')) continue;

                if(pbItemFieldNames.contains(f)) 
                {
                    targetPbItem.put(f, sourceCatalogItem.get(origf));
                } else if(pbItemFieldNames.contains(nf)) 
                {
                    targetPbItem.put(nf, sourceCatalogItem.get(origf));
                }
            }
        }

        update pbItems;

        return pbItems;
    }

    public static List<Price_Book_Item__c> CreatePriceBookItemsUsingCatalogItems(Id newPricebookId, List<Id> catalogItemIds, Map<Id, Catalog_Item__c> ciLookup, String parentId) {
        List<Price_Book_Item__c> pbItems = new List<Price_Book_Item__c>();

        for(Id catalogItemId: catalogItemIds) {
            Catalog_Item__c ci = ciLookup.get(catalogItemId);
            String recName = Schema.SObjectType.Catalog_Item__c.getRecordTypeInfosById().get(ci.RecordTypeId).getName();

            RecordTypeInfo recordInfo = Schema.SObjectType.Price_Book_Item__c.getRecordTypeInfosByName().get(recName);
            if (recordInfo != null) {
                ID recId = recordInfo.getRecordTypeId();
                Price_Book_Item__c pbItem  = (Price_Book_Item__c)Price_Book_Item__c.sObjectType.newSObject(recId, true);
                pbItem.Price_Book__c = newPricebookId;
                pbItem.Catalog_Item__c = catalogItemId;

                if (!String.isBlank(parentId)) {
                    //pbItem.Parent_Price_Book_Item__r = new Price_Book_Item__c(Id = parentId);
                    pbItem.Parent_Price_Book_Item__c = parentId;
                }

                pbItems.add(pbItem);
            }
        }

        return pbItems;
    }
}