src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the catalog item is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/AddTktItemsByPBSeqNum__c.field-meta.xml
<CustomField>
    <fullName>AddTktItemsByPBSeqNum__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, price book items, when added to a ticket, should honor the sequence number.  Otherwise they will be inserted at the end of the ticket.</description>
    <inlineHelpText>Controls whether users can change sequence numbers for price book items to adjust the order of item lists. If selected, users cannot change sequence numbers. If deselected, users can change sequence numbers and new items get added at the end of a list.</inlineHelpText>
    <label>Honor Sequence Number</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Date from which users can select the price book for jobs.</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Last date that users can select the price book for jobs. You cannot select the price book for a job after this date.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(!IsArchived__c &amp;&amp; Effective_Date__c &lt;=TODAY() &amp;&amp; (ISNULL(Expiration_Date__c) || (Expiration_Date__c >=TODAY())) &amp;&amp; (ISBLANK(Account__c) || !Account__r.IsArchived__c), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether users can select the price book for a job. Users cannot select a price book for a job if the current date is before the "Effective Date", the current date is after the "Expiration Date", or "Archived" is selected.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the price book is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Parent_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book for the price book. When a price book has a parent, you can select items from its parent price book when building tickets.</inlineHelpText>
    <label>Parent Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Description__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Description__c</fullName>
    <formula>Catalog_Item__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog description for the price book item. The price book item inherits this description from the linked catalog item by default. If the price book item has a description override, the price book item uses that description.</inlineHelpText>
    <label>Catalog Description</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item_Code__c</fullName>
    <formula>Catalog_Item__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog item code for the price book item. The price book item inherits this item code from the linked catalog item.</inlineHelpText>
    <label>Catalog Item Code</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Description_Override__c.field-meta.xml
<CustomField>
    <fullName>Description_Override__c</fullName>
    <description>Complete this field to override the catalog item description within this price book</description>
    <inlineHelpText>Catalog description for the price book item. This description overrides the catalog description inherited from the linked catalog item.</inlineHelpText>
    <label>Description Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/IsArchived__c.field-meta.xml
<CustomField>
    <fullName>IsArchived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the price book item is deactivated.</inlineHelpText>
    <label>Archived</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Requires_Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Requires_Parent_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item and its parent price book item get added automatically to all new tickets.</inlineHelpText>
    <label>Requires Parent Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Parent_Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent item for the quote item. When you add a parent item to a quote, any designated child items also get added. You cannot add child items to quotes individually without adding their parent first.</inlineHelpText>
    <label>Parent Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/ParentPricebookUtilities.cls
global with sharing class ParentPricebookUtilities {

    public static List<Price_Book__c> GetParentPricebooks(Id pricebookId) {

        Map<Id, Price_Book__c> pricebooksLookup = new Map<Id, Price_Book__c>([SELECT Id, Parent_Price_Book__c, IsArchived__c, Is_Active__c, Effective_Date__c, Expiration_Date__c, AddTktItemsByPBSeqNum__c
            FROM Price_Book__c WHERE IsDeleted=false AND Is_Active__c=true]);

        List<Price_Book__c> parentPricebooks = new List<Price_Book__c>();

        Id pbId = pricebooksLookup.containsKey(pricebookId)? pricebooksLookup.get(pricebookId).Parent_Price_Book__c : null;

        while(!String.isBlank(pbId) && pricebooksLookup.containsKey(pbId)) {
            Price_Book__c pb = pricebooksLookup.get(pbId);
            parentPricebooks.add(pb);
            pbId = pb.Parent_Price_Book__c;
        }
        return parentPricebooks;
    }

    public static String GetPriceBookItemsFromParentPricebook(String processStr) {
      JSONParser parser = JSON.createParser(processStr);
      Type resultType = Type.forName('ParentPricebookUtilities.GetPriceBookItemsFromParentPricebookRequest');
      ParentPricebookUtilities.GetPriceBookItemsFromParentPricebookRequest readValueAsResult = (ParentPricebookUtilities.GetPriceBookItemsFromParentPricebookRequest)parser.readValueAs(resultType);

      Result resultV1 = ParentPricebookUtilities.GetPricebookItemsFromParentPricebook(readValueAsResult.parentPricebookId, readValueAsResult.objectId,
                  readValueAsResult.showItemsAlreadyOnTheObject, readValueAsResult.keyword, readValueAsResult.classification,
                  readValueAsResult.itemType, readValueAsResult.itemLimit, readValueAsResult.itemOffset, readValueAsResult.sortby,
                  readValueAsResult.sortdir, readValueAsResult.fields, readValueAsResult.sobjectType);

      GetPriceBookItemsFromParentPricebookResult getPriceBookItemsFromParentPricebookResult = new GetPriceBookItemsFromParentPricebookResult();
      getPriceBookItemsFromParentPricebookResult.items = resultV1.items;
      getPriceBookItemsFromParentPricebookResult.soql = resultV1.soql;
      getPriceBookItemsFromParentPricebookResult.parentPricebooks = resultV1.parentPricebooks;

      getPriceBookItemsFromParentPricebookResult.itemPBIds = new Map<Id, Id>();
      getPriceBookItemsFromParentPricebookResult.qtItemOnObjPBIds = new Map<Id, Id>();
      String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
      if (readValueAsResult.sobjectType == fxNamespacePrefix+'Quote__c') {
        for(Quote_Item__c qi : [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Quote__c=:readValueAsResult.objectId]) {
          getPriceBookItemsFromParentPricebookResult.itemPBIds.put(qi.Price_Book_Item__c, qi.Id);
        }
      } else {
        for(Ticket_Item__c ti : [SELECT Id, Price_Book_Item__c, Quote_Item__c FROM Ticket_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Ticket__c=:readValueAsResult.objectId]) {
          getPriceBookItemsFromParentPricebookResult.itemPBIds.put(ti.Price_Book_Item__c, ti.Id);
          if (ti.Quote_Item__c != null) getPriceBookItemsFromParentPricebookResult.qtItemOnObjPBIds.put(ti.Price_Book_Item__c, ti.Quote_Item__c);
        }

        for(Quote_Item__c qi : [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Quote__c=:readValueAsResult.relatedObjectId]) {
          getPriceBookItemsFromParentPricebookResult.qtItemOnObjPBIds.put(qi.Price_Book_Item__c, qi.Id);
        }

      }

      return JSON.serializePretty(getPriceBookItemsFromParentPricebookResult, false);
    }

    public static String GetPriceBookItemsFromParentPricebooks(String processStr) {
      JSONParser parser = JSON.createParser(processStr);
      Type resultType = Type.forName('ParentPricebookUtilities.GetPriceBookItemsFromParentPricebooksRequest');
      ParentPricebookUtilities.GetPriceBookItemsFromParentPricebooksRequest readValueAsResult = (ParentPricebookUtilities.GetPriceBookItemsFromParentPricebooksRequest)parser.readValueAs(resultType);

      Result resultV1 = ParentPricebookUtilities.GetPriceBookItems(readValueAsResult.pricebookId, readValueAsResult.objectId,
                readValueAsResult.showItemsAlreadyOnTheObject, readValueAsResult.keyword, readValueAsResult.classification,
                readValueAsResult.itemType, readValueAsResult.itemLimit, readValueAsResult.itemOffset, readValueAsResult.sortby,
                readValueAsResult.sortdir, readValueAsResult.fields, readValueAsResult.sobjectType);

      GetPriceBookItemsFromParentPricebooksResult getPriceBookItemsFromParentPricebooksResult = new GetPriceBookItemsFromParentPricebooksResult();
      getPriceBookItemsFromParentPricebooksResult.items = resultV1.items;
      getPriceBookItemsFromParentPricebooksResult.soql = resultV1.soql;
      getPriceBookItemsFromParentPricebooksResult.parentPricebooks = resultV1.parentPricebooks;

      getPriceBookItemsFromParentPricebooksResult.itemPBIds = new Map<Id, Id>();
      getPriceBookItemsFromParentPricebooksResult.qtItemOnObjPBIds = new Map<Id, Id>();
      String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
      if (readValueAsResult.sobjectType == fxNamespacePrefix+'Quote__c') {
        for(Quote_Item__c qi : [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Quote__c=:readValueAsResult.objectId]) {
          getPriceBookItemsFromParentPricebooksResult.itemPBIds.put(qi.Price_Book_Item__c, qi.Id);
        }
      } else {
        for(Ticket_Item__c ti : [SELECT Id, Price_Book_Item__c, Quote_Item__c FROM Ticket_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Ticket__c=:readValueAsResult.objectId]) {
          getPriceBookItemsFromParentPricebooksResult.itemPBIds.put(ti.Price_Book_Item__c, ti.Id);
        }

System.debug(readValueAsResult.relatedObjectId);
        for(Quote_Item__c qi : [SELECT Id, Price_Book_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Price_Book_Item__c!=null AND Quote__c=:readValueAsResult.relatedObjectId]) {
System.debug(qi);
          getPriceBookItemsFromParentPricebooksResult.qtItemOnObjPBIds.put(qi.Price_Book_Item__c, qi.Id);
        }
      }

      return JSON.serializePretty(getPriceBookItemsFromParentPricebooksResult, false);
    }

    public static Result GetPriceBookItems(
            Id pricebookId,
            String objectId,
            String showItemsAlreadyOnTheObject,
            String keyword,
            String classification,
            String itemType,
            String itemLimit,
            String itemOffset,
            String sortby,
            String sortdir,
            String fields)
    {
        return ParentPricebookUtilities.GetPriceBookItems(pricebookId, objectId, showItemsAlreadyOnTheObject, keyword, classification,
            itemType, itemLimit, itemOffset, sortby, sortdir, fields, null);
    }

    public static Result GetPriceBookItems(
            Id pricebookId,
            String objectId,
            String showItemsAlreadyOnTheObject,
            String keyword,
            String classification,
            String itemType,
            String itemLimit,
            String itemOffset,
            String sortby,
            String sortdir,
            String fields,
            String sobjectType)
    {
        String pbIds = '';

        String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();
        Result result = new Result();

        //Datetime now = Datetime.now();
        Price_Book__c pricebook = [SELECT Id, Parent_Price_Book__c FROM Price_Book__c WHERE Id =: pricebookId LIMIT 1 ];

        Set<Id> catalogItemIdsSet = new Set<Id>();
        for(Price_Book_Item__c pbi : [SELECT Id, Catalog_Item__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Price_Book__c =: pricebookId
                                      AND (Parent_Price_Book_Item__c = null OR Requires_Parent_Item__c = false)])
        {
            catalogItemIdsSet.add(pbi.Catalog_Item__c);
        }

        List<Price_Book__c> parentPricebooks = ParentPricebookUtilities.GetParentPricebooks(pricebookId);
        result.parentPricebooks = parentPricebooks;

        if (parentPricebooks.isEmpty()) {
            result.items = new List<Price_Book_Item__c>();
            result.soql = '';
            return result;
        }

        Map<Id, Price_Book__c> parentPricebooksLookup = new Map<Id, Price_Book__c>(parentPricebooks);
        List<Id> parentIds = new List<Id>();
        Map<Id, Integer> parentGeneration = new Map<Id, Integer>();
        Integer generation = 0;
        for (Price_Book__c parent : parentPricebooks) {
            parentIds.add(parent.Id);
            parentGeneration.put(parent.Id, generation);
            generation++;
        }
        pbIds = GetIDsAsString(parentIds);

        Set<Id> ticketCatalogIdsSet = new Set<Id>();
        if (sobjectType == fxNamespacePrefix+'Quote__c') {
            for(Quote_Item__c qi : [SELECT Price_Book_Item__r.Catalog_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Quote__c =: objectId AND Parent_Quote_Item__c = null])
            {
                ticketCatalogIdsSet.add(qi.Price_Book_Item__r.Catalog_Item__c);
            }
        } else {
            for(Ticket_Item__c ti : [SELECT Catalog_Item__c FROM Ticket_Item__c WHERE IsDeleted=false AND Ticket__c =: objectId AND Parent_Ticket_Item__c = null])
            {
                ticketCatalogIdsSet.add(ti.Catalog_Item__c);
            }
        }

        //make sure Catalog_Item__c, Price_Book__c in fields
        if(!fields.contains('Catalog_Item__c'))
        {
            fields += ','+fxNamespacePrefix+'Catalog_Item__c';
        }
        if(!fields.contains('Price_Book__c'))
        {
            fields += ','+fxNamespacePrefix+'Price_Book__c';
        }

        String commandText = 'SELECT ' + fields + ' FROM {0}Price_Book_Item__c ';
        commandText += ' WHERE IsDeleted=false ';
        commandText += ' AND {0}IsArchived__c = false ';
        commandText += ' AND {0}Parent_Price_Book_Item__c = null ';

        commandText = String.format(commandText, new String[]{fxNamespacePrefix});

        if (!parentIds.isEmpty()) {
            commandText += ' AND '+fxNamespacePrefix+'Price_Book__c in (' + pbIds + ') ';
        }

        if(!catalogItemIdsSet.isEmpty())
        {
          commandText += String.format( ' AND {0}Catalog_Item__r.Id not in :catalogItemIdsSet ', new String[]{fxNamespacePrefix });
        }

        if(!catalogItemIdsSet.isEmpty())
        {
          commandText += String.format( ' AND {0}Catalog_Item__r.Id not in :catalogItemIdsSet ', new String[]{fxNamespacePrefix });
        }

        if (showItemsAlreadyOnTheObject == 'false' && ticketCatalogIdsSet.size() > 0) {
          commandText += String.format( ' AND {0}Catalog_Item__r.Id not in :ticketCatalogIdsSet ', new String[]{fxNamespacePrefix });
        }

        if (keyword != null && keyword != '') {
          String keywordSoql = ' AND ( ';
          List<String> keywords = keyword.split(' ');

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += 'Name LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Catalog_Description__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Description_Override__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') OR ';

          keywordSoql += ' ( ';
          for(String str : keywords) {
            keywordSoql += fxNamespacePrefix + 'Catalog_Item_Code__c LIKE \'%' + str + '%\' AND ';
          }
          keywordSoql = keywordSoql.substring(0,keywordSoql.length()-4);
          keywordSoql += ') ';

          keywordSoql += ' ) ';
          commandText += keywordSoql;
        }

        if (classification != null && classification != '') {
            commandText += ' AND '+fxNamespacePrefix+'Catalog_Classification__c in (' + classification + ') ';
        }

        if (itemType != null && itemType != '') {
            commandText += String.format(' AND {0}Ticket_Item_Record_Type__c = \'\'' + itemType + '\'\' ', new String[]{fxNamespacePrefix});
        }

        String sb = (sortby != '') ? ' ORDER BY ' + sortby : '';
        String sd = (sb != '') ? (sortdir != null) ? sortdir : '' : '';
        String nullsLast = (sb != '') ? 'NULLS LAST' : '';
        commandText += sb + ' ' + sd + ' ' + nullsLast;

        String lim = (itemLimit != '' ) ? (Integer.valueOf(itemLimit) > 2000) ? '2000' : itemLimit : '2000';
        String off = (itemOffset != '' ) ? (Integer.valueOf(itemOffset) > 2000) ? '2000' : itemOffset : '0';
        commandText += ' LIMIT ' + lim + ' OFFSET ' + off + ' ';

        result.soql = commandText;

        List<Price_Book_Item__c> items = Database.query(commandText);

        Map<Id, List<Price_Book_Item__c>> itemsOfInterest = new Map<Id, List<Price_Book_Item__c>>();
        Map<Id, Integer> catalogItemIdFromParent = new Map<Id, Integer>();

        for(Price_Book_Item__c item: items)
        {
          Id catalogItemId = item.Catalog_Item__c;
          Integer level = parentGeneration.get(item.Price_Book__c);

          if(catalogItemIdFromParent.containsKey(catalogItemId))
          {
            Integer prevLevel = catalogItemIdFromParent.get(catalogItemId);
            if(level<prevLevel)
            {
              catalogItemIdFromParent.put(catalogItemId, level); //overwrite old entry
              List<Price_Book_Item__c> itemList = new List<Price_Book_Item__c>();
              itemList.add(item);
              itemsOfInterest.put(catalogItemId, itemList); //overwrite old entry
            } else if (level==prevLevel) {
              if (itemsOfInterest.containsKey(catalogItemId)) {
                List<Price_Book_Item__c> itemList = itemsOfInterest.get(catalogItemId);
                itemList.add(item);
              } else {
                List<Price_Book_Item__c> itemList = new List<Price_Book_Item__c>();
                itemList.add(item);
                itemsOfInterest.put(catalogItemId, itemList);
              }
            }
          } else {
            catalogItemIdFromParent.put(catalogItemId, level);
            List<Price_Book_Item__c> itemList = new List<Price_Book_Item__c>();
            itemList.add(item);
            itemsOfInterest.put(catalogItemId, itemList);
          }
        }

        List<Price_Book_Item__c> allItems = new List<Price_Book_Item__c>();
        for (List<Price_Book_Item__c> itemList: itemsOfInterest.values()) {
          allItems.addAll(itemList);
        }

        result.items = allItems;
        return result;
    }


    public static Result GetPricebookItemsFromParentPricebook(
        String parentPricebookId,
        String objectId,
        String showItemsAlreadyOnTheObject,
        String keyword,
        String classification,
        String itemType,
        String itemLimit,
        String itemOffset,
        String sortby,
        String sortdir,
        String fields)
    {
        return ParentPricebookUtilities.GetPricebookItemsFromParentPricebook(parentPricebookId, objectId, showItemsAlreadyOnTheObject, keyword,
                     classification, itemType, itemLimit, itemOffset, sortby, sortdir, fields, null);
    }

    public static Result GetPricebookItemsFromParentPricebook(
        String parentPricebookId,
        String objectId,
        String showItemsAlreadyOnTheObject,
        String keyword,
        String classification,
        String itemType,
        String itemLimit,
        String itemOffset,
        String sortby,
        String sortdir,
        String fields,
        String sobjectType) {

        String fxNamespacePrefix = UtilityGetNamespace.CurrentNamespace();

        Result result = new Result();

        Set<Id> ticketCatalogIdsSet = new Set<Id>();
        if (sobjectType == fxNamespacePrefix+'Quote__c') {
            for(Quote_Item__c qi : [SELECT Price_Book_Item__r.Catalog_Item__c FROM Quote_Item__c WHERE IsDeleted=false AND Quote__c =: objectId AND Parent_Quote_Item__c = null])
            {
                ticketCatalogIdsSet.add(qi.Price_Book_Item__r.Catalog_Item__c);
            }
        } else {
            for(Ticket_Item__c ti : [SELECT Catalog_Item__c FROM Ticket_Item__c WHERE IsDeleted=false AND Ticket__c =: objectId AND Parent_Ticket_Item__c = null])
            {
                ticketCatalogIdsSet.add(ti.Catalog_Item__c);
            }
        }

        String commandText = 'SELECT ' + fields + ' FROM {0}Price_Book_Item__c ';
        commandText += ' WHERE Id != null ';
        commandText += ' AND {0}Price_Book__c = \'\'' + parentPricebookId + '\'\' ';
        commandText += ' AND {0}IsArchived__c = false ';
        commandText += ' AND {0}Parent_Price_Book_Item__c = null ';

        commandText = String.format(commandText, new String[]{fxNamespacePrefix});

        if (showItemsAlreadyOnTheObject == 'false' && ticketCatalogIdsSet.size() > 0) {
          commandText += String.format( ' AND {0}Catalog_Item__r.Id not in :ticketCatalogIdsSet ', new String[]{fxNamespacePrefix });
        }

        if (keyword != null && keyword != '') {
          commandText += String.format(' AND ({0}Catalog_Description__c LIKE \'\'%' + keyword + '%\'\' OR {0}Description_Override__c LIKE \'\'%' + keyword + '%\'\' OR {0}Catalog_Item_Code__c LIKE \'\'%' + keyword + '%\'\') ', new String[]{fxNamespacePrefix});
        }

        if (classification != null && classification != '') {
            commandText += ' AND '+fxNamespacePrefix+'Catalog_Classification__c in (' + classification + ') ';
        }

        if (itemType != null && itemType != '') {
            commandText += String.format(' AND {0}Ticket_Item_Record_Type__c = \'\'' + itemType + '\'\' ', new String[]{fxNamespacePrefix});
        }

        String sb = (sortby != '') ? ' ORDER BY ' + sortby : '';
        String sd = (sb != '') ? (sortdir != null) ? sortdir : '' : '';
        String nullsLast = (sb != '') ? 'NULLS LAST' : '';
        commandText += sb + ' ' + sd + ' ' + nullsLast;

        String lim = (itemLimit != '' ) ? (Integer.valueOf(itemLimit) > 2000) ? '2000' : itemLimit : '2000';
        String off = (itemOffset != '' ) ? (Integer.valueOf(itemOffset) > 2000) ? '2000' : itemOffset : '0';
        commandText += ' LIMIT ' + lim + ' OFFSET ' + off + ' ';

        result.soql = commandText;

        result.items = Database.query(commandText);

        return result;
    }

    static String GetIDsAsString(List<Id> ids) {
        String sep = '';
        String soql = '';
        for(Id id: ids)
        {
            soql += sep + '\'' + id + '\'';
            sep = ',';
        }

        return soql;
    }

    global class Result {
        public List<Price_Book_Item__c> items;
        public string soql;
        public List<Price_Book__c> parentPricebooks;
    }

    public class GetPriceBookItemsFromParentPricebooksResult {
        public List<Price_Book_Item__c> items;
        public string soql;
        public List<Price_Book__c> parentPricebooks;
        public Map<Id, Id> itemPBIds;
        public Map<Id, Id> qtItemOnObjPBIds;
    }

    public class GetPriceBookItemsFromParentPricebooksRequest {
        public Id pricebookId;
        public String objectId;
        public String relatedObjectId;
        public String showItemsAlreadyOnTheObject;
        public String keyword;
        public String classification;
        public String itemType;
        public String itemLimit;
        public String itemOffset;
        public String sortby;
        public String sortdir;
        public String fields;
        public String sobjectType;
    }

    public class GetPriceBookItemsFromParentPricebookResult {
        public List<Price_Book_Item__c> items;
        public string soql;
        public List<Price_Book__c> parentPricebooks;
        public Map<Id, Id> itemPBIds;
        public Map<Id, Id> qtItemOnObjPBIds;
    }

    public class GetPriceBookItemsFromParentPricebookRequest {
        public String parentPricebookId;
        public String objectId;
        public String relatedObjectId;
        public String showItemsAlreadyOnTheObject;
        public String keyword;
        public String classification;
        public String itemType;
        public String itemLimit;
        public String itemOffset;
        public String sortby;
        public String sortdir;
        public String fields;
        public String sobjectType;
    }

}