src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users can add the catalog item to a warehouse to track the item's inventory levels.</inlineHelpText>
    <label>Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/EnableInventoryTracking__c.field-meta.xml
<CustomField>
    <fullName>EnableInventoryTracking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set it to true to turn on Inventory Tracking. When it is set to false, the Inventory Tracking module won't run even the Catalog Items have Track Inventory checked.</description>
    <label>EnableInventoryTracking</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment used on the job is stored. When you select a warehouse, the ticket items added to tickets for the job will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment included on the ticket is stored. When you select a warehouse, ticket items will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where the ticket item is stored.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/objects/Warehouse_Item__c/Warehouse_Item__c.object-meta.xml
<CustomObject>
    <label>Warehouse Item</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Warehouse Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Warehouse_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the warehouse item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipName>Inventory_Location_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Warehouse_Item__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Quantity of the item currently on hand.</inlineHelpText>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Warehouse_Item__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <inlineHelpText>Warehouse where the item is stored.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Items</relationshipLabel>
    <relationshipName>Inventory_Location_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/InventoryManager_Test.cls
@isTest
private class InventoryManager_Test
{
	static Double w1QtyOnHand = 50000;
	static Double w2QtyOnHand = 40000;

	static Ticket_Item__c SetupTicketItem()
	{
        FX_Settings__c fs = FX_Settings__c.getOrgDefaults();
        fs.SetupOwnerId = UserInfo.getOrganizationId();
        fs.EnableInventoryTracking__c = true;
        insert fs;

		Warehouse__c w1 = new Warehouse__c(Name='w1');
		Warehouse__c w2 = new Warehouse__c(Name='w2');

		insert w1;
		insert w2;


		String guid = StringUtility.newGuid();
		Catalog_Item__c ci = new Catalog_Item__c(Name='InventoryUnitTestCatalogItem', Description__c='Test', Sequence_Number__c=99.1, Ticket_Item_Record_Type__c='Equipment', Track_Inventory__c=true);

		insert ci;

		Warehouse_Item__c wi1 = new Warehouse_Item__c(Warehouse__c = w1.Id, Catalog_Item__c = ci.Id, Quantity_On_Hand__c = w1QtyOnHand);
		Warehouse_Item__c wi2 = new Warehouse_Item__c(Warehouse__c = w2.Id, Catalog_Item__c = ci.Id, Quantity_On_Hand__c = w2QtyOnHand);

		insert wi1;
		insert wi2;

		Job__c job = AlpineTestHelper.CreateJobs(1, false).get(0);
		job.Warehouse__c = w1.Id;
		insert job;

		Price_Book_Item__c pbi = new Price_Book_Item__c(Price_Book__c = job.Price_Book__c, Catalog_Item__c = ci.Id, Default_Quantity__c=5, Sequence_Number__c=0, Discount_Percent__c=0);
		insert pbi;

		Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);

		Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id);
		insert ti;
		return ti;
	}


	static testmethod void InsertTicketItem_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem();
    	Test.StopTest();

    	String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();

    	String tktItemSoql = 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE Id=\'' + ti.Id + '\'';

    	String ns = UtilityGetNamespace.CurrentNamespace();

		tktItemSoql = tktItemSoql.replace('[ns]', ns);

		List<sObject> objs = Database.query(tktItemSoql);

		System.assertEquals(1, objs.size());

    	String wiSoql = 'SELECT [ns]Warehouse__c, [ns]Catalog_Item__c, [ns]Quantity_On_Hand__c FROM [ns]Warehouse_Item__c WHERE [ns]Warehouse__r.Name=\'W1\'';

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
    	System.assertEquals(1, wiItems.size());

    	Double qty = (Double)objs.get(0).get(warehouseQtyFieldName);

    	System.assertEquals(wiItems.get(0).Quantity_On_Hand__c, w1QtyOnHand - qty);

    }

    static testmethod void InsertSamePriceBookItem_Test()
    {
        Test.StartTest();
        Ticket_Item__c ti = SetupTicketItem();

        Ticket_Item__c ti2 = new Ticket_Item__c(Ticket__c = ti.Ticket__c, Price_Book_Item__c = ti.Price_Book_Item__c);
        insert ti2;

        Test.StopTest();

        String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();

        String tktItemSoql = 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE [ns]Ticket__c=\'' + ti.Ticket__c + '\'';

        String ns = UtilityGetNamespace.CurrentNamespace();

        tktItemSoql = tktItemSoql.replace('[ns]', ns);

        List<Ticket_Item__c> tktItems  = (List<Ticket_Item__c>)Database.query(tktItemSoql);

        
        Double totalQty = 0;
        for(Ticket_Item__c tktItem : tktItems)
        {
            totalQty += (double)tktItem.get(warehouseQtyFieldName);
        }

        String wiSoql = 'SELECT [ns]Warehouse__c, [ns]Catalog_Item__c, [ns]Quantity_On_Hand__c FROM [ns]Warehouse_Item__c WHERE [ns]Warehouse__r.Name=\'W1\'';

        List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
        System.assertEquals(1, wiItems.size());

        System.assertEquals(wiItems.get(0).Quantity_On_Hand__c, w1QtyOnHand - totalQty);

    }

    static testmethod void UpdateSamePriceBookItem_Test()
    {
        Ticket_Item__c ti = SetupTicketItem();

        List<Ticket_Item__c> items = new List<Ticket_Item__c>();
        for(Integer i =0; i<300; i++)
        {
            items.add(new Ticket_Item__c(Ticket__c = ti.Ticket__c, Price_Book_Item__c = ti.Price_Book_Item__c));
        }
        insert items;
        String ns = UtilityGetNamespace.CurrentNamespace();
        String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();
        String tktItemSoql = (warehouseQtyFieldName == ns + 'Input_Qty__c')? 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE [ns]Ticket__c=\'' + ti.Ticket__c + '\''
        : 'SELECT Id, [ns]Input_Qty__c, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE [ns]Ticket__c=\'' + ti.Ticket__c + '\'';
      
        tktItemSoql = tktItemSoql.replace('[ns]', ns);

        Test.StartTest();
        List<Ticket_Item__c> dbItems  = (List<Ticket_Item__c>)Database.query(tktItemSoql);
        for(Ticket_Item__c item : dbItems)
        {
            Double qty = item.Input_Qty__c;
            item.Input_Qty__c =  qty * 2;
        }
        update dbItems;

        Test.StopTest();  

        List<Ticket_Item__c> tktItems  = (List<Ticket_Item__c>)Database.query(tktItemSoql);

        Double totalQty = 0;
        for(Ticket_Item__c tktItem : tktItems)
        {
            totalQty += (double)tktItem.get(warehouseQtyFieldName);
        }

        String wiSoql = 'SELECT [ns]Warehouse__c, [ns]Catalog_Item__c, [ns]Quantity_On_Hand__c FROM [ns]Warehouse_Item__c WHERE [ns]Warehouse__r.Name=\'W1\'';

        List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
        System.assertEquals(1, wiItems.size());

        System.assertEquals(wiItems.get(0).Quantity_On_Hand__c, w1QtyOnHand - totalQty);

    }


    static testmethod void UpdateTicketItemQty_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem();    	
    	String ns = UtilityGetNamespace.CurrentNamespace();
    	String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();

    	String tktItemSoql = 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE Id=\'' + ti.Id + '\'';	

		tktItemSoql = tktItemSoql.replace('[ns]', ns);

		List<sObject> objs = Database.query(tktItemSoql);

		System.assertEquals(1, objs.size());
		Ticket_Item__c dbTktItem = (Ticket_Item__c)objs.get(0);
		Double newQty = 1;
		dbTktItem.Input_Qty__c = newQty;

		update dbTktItem;

    	Test.StopTest();

    

    	objs = Database.query(tktItemSoql);
		System.assertEquals(1, objs.size());


    	String wiSoql = 'SELECT [ns]Warehouse__c, [ns]Catalog_Item__c, [ns]Quantity_On_Hand__c FROM [ns]Warehouse_Item__c WHERE [ns]Warehouse__r.Name=\'W1\'';

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
    	System.assertEquals(1, wiItems.size());

    	Double qty = (Double)objs.get(0).get(warehouseQtyFieldName);

    	System.assertEquals(newQty, qty);

    	System.assertEquals(wiItems.get(0).Quantity_On_Hand__c, w1QtyOnHand - qty);

    }

    static testmethod void UpdateTicketItem_WarehouseAndQty_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem();    	
    	String ns = UtilityGetNamespace.CurrentNamespace();
    	String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();

    	String tktItemSoql = 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE Id=\'' + ti.Id + '\'';	

		tktItemSoql = tktItemSoql.replace('[ns]', ns);

		List<sObject> objs = Database.query(tktItemSoql);

		System.assertEquals(1, objs.size());
		Ticket_Item__c dbTktItem = (Ticket_Item__c)objs.get(0);
		Double newQty = 1;
		dbTktItem.Input_Qty__c = newQty;

		Warehouse__c w2 = [SELECT Id FROM Warehouse__c WHERE Name='W2' LIMIT 1];

		dbTktItem.Warehouse__c = w2.Id;
		update dbTktItem;

    	Test.StopTest();

    

    	objs = Database.query(tktItemSoql);
		System.assertEquals(1, objs.size());

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__r.Name, Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1' OR Warehouse__r.Name='W2'];
    	System.assertEquals(2, wiItems.size());

    	if(wiItems.get(0).Warehouse__r.Name == 'W1')
    	{
    		System.assertEquals(w1QtyOnHand, wiItems.get(0).Quantity_On_Hand__c);
    		System.assertEquals(w2QtyOnHand - newQty, wiItems.get(1).Quantity_On_Hand__c);
    	}
    	else
    	{
    		System.assertEquals(w1QtyOnHand, wiItems.get(1).Quantity_On_Hand__c);
    		System.assertEquals(w2QtyOnHand - newQty, wiItems.get(0).Quantity_On_Hand__c);

    	}   

    }


    static testmethod void DeleteTicketItem_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem(); 
    	delete ti;
    	Test.StopTest();    

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
    	System.assertEquals(1, wiItems.size());
    	System.assertEquals(w1QtyOnHand, wiItems.get(0).Quantity_On_Hand__c);
    }

    static testmethod void DeleteJob_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem();  
    	Ticket_Item__c dbTktItem = [SElECT Id, Ticket__c, Ticket__r.Id, Ticket__r.Job__c,  Ticket__r.Job__r.Id FROM Ticket_Item__c WHERE Id=:ti.Id];
    	delete dbTktItem.Ticket__r.Job__r;

    	Test.StopTest();    

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
    	System.assertEquals(1, wiItems.size());
    	System.assertEquals(w1QtyOnHand, wiItems.get(0).Quantity_On_Hand__c);
    }

    static testmethod void DeleteTicket_Test()
    {
    	Test.StartTest();
    	Ticket_Item__c ti = SetupTicketItem();  

    	Ticket_Item__c dbTktItem = [SElECT Id, Ticket__c, Ticket__r.Id, Ticket__r.Job__c,  Ticket__r.Job__r.Id FROM Ticket_Item__c WHERE Id=:ti.Id];

    
    	delete dbTktItem.Ticket__r;

    	Test.StopTest();    

    	List<Warehouse_Item__c> wiItems = [SELECT Warehouse__c, Catalog_Item__c, Quantity_On_Hand__c FROM Warehouse_Item__c WHERE Warehouse__r.Name='W1'];
    	System.assertEquals(1, wiItems.size());
    	System.assertEquals(w1QtyOnHand, wiItems.get(0).Quantity_On_Hand__c);
    }

}