src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Included_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Included_Quantity__c</fullName>
    <inlineHelpText>Quantity of the price book item given to the customer at no charge.</inlineHelpText>
    <label>Included Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the ticket item. The ticket item inherits this discount from the linked price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/CopyTicketItemsTest.cls
@isTest
private class CopyTicketItemsTest{
   
    static testmethod void CopySingleItem(){
        Test.startTest();

        List<Id> ticketItemIds = new List<Id>();
    
        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        insert j;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);
        insert tkt;

        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;

        Price_Book_Item__c pli1 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        insert pli1;

        Ticket_Item__c ptktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli1.Id);
        insert ptktItem;    
        ticketItemIds.add(ptktItem.Id);
        List<Ticket_Item__c> result = CopyTicketItems.CopyTicketItems(tkt.Id, ticketItemIds, true, 0);
        System.assert(result.size() == 1);

        Test.stopTest();

    }

    static testmethod void CopySingleItemWithAutoChildren(){
        Test.startTest();

        List<Id> ticketItemIds = new List<Id>();
    
        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        insert j;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);
        insert tkt;

        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;

        List<Price_Book_Item__c> pliItems = new List<Price_Book_Item__c>();

        Price_Book_Item__c pli1 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli1);
        Price_Book_Item__c pli2 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =2, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli2);
        Price_Book_Item__c pli3 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =3, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli3);
        Price_Book_Item__c pli4 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =4, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli4);
        insert pliItems;

        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();

        Ticket_Item__c ptktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli1.Id);
        insert ptktItem;     
        ticketItemIds.add(ptktItem.Id);      

        Ticket_Item__c ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli2.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        tktItems.add(ctktItem);    

        ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli3.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        tktItems.add(ctktItem);            

        ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli4.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        tktItems.add(ctktItem);     

        insert tktItems;       

        List<Ticket_Item__c> result = CopyTicketItems.CopyTicketItems(tkt.Id, ticketItemIds, true, 0);
        System.assert(result.size() == 4, 'should have 4 items, instead of ' + result.size());

        Test.stopTest();

    }    

    static testmethod void CopySingleItemWithSelectedChildren(){
        Test.startTest();

        List<Id> ticketItemIds = new List<Id>();
    
        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        insert j;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);
        insert tkt;

        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;

        List<Price_Book_Item__c> pliItems = new List<Price_Book_Item__c>();

        Price_Book_Item__c pli1 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli1);
        Price_Book_Item__c pli2 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =2, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli2);
        Price_Book_Item__c pli3 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =3, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli3);
        Price_Book_Item__c pli4 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =4, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli4);
        insert pliItems;

        Ticket_Item__c ptktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli1.Id);
        insert ptktItem;    
        ticketItemIds.add(ptktItem.Id);

        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();


        tktItems.add(new Ticket_Item__c(Parent_Ticket_Item__c = ptktItem.Id, Ticket__c = tkt.Id, Price_Book_Item__c = pli2.Id)); 
        tktItems.add(new Ticket_Item__c(Parent_Ticket_Item__c = ptktItem.Id, Ticket__c = tkt.Id, Price_Book_Item__c = pli3.Id));
        tktItems.add(new Ticket_Item__c(Parent_Ticket_Item__c = ptktItem.Id, Ticket__c = tkt.Id, Price_Book_Item__c = pli4.Id));
     
        insert tktItems;  
        for(Ticket_Item__c ti : tktItems)          
        {
            ticketItemIds.add(ti.Id);
        }

        List<Ticket_Item__c> result = CopyTicketItems.CopyTicketItems(tkt.Id, ticketItemIds, true, 0);
        System.assert(result.size() == 4);

        Test.stopTest();
    }    

    static testmethod void CopySingleChild(){
        Test.startTest();

        List<Id> ticketItemIds = new List<Id>();
    
        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        insert j;

        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);
        insert tkt;

        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;

        List<Price_Book_Item__c> pliItems = new List<Price_Book_Item__c>();

        Price_Book_Item__c pli1 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli1);
        Price_Book_Item__c pli2 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =2, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli2);
        Price_Book_Item__c pli3 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =3, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli3);
        Price_Book_Item__c pli4 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =4, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        pliItems.add(pli4);
        insert pliItems;

        Ticket_Item__c ptktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli1.Id);
        insert ptktItem;    

        Ticket_Item__c ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli2.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        insert ctktItem;    

        ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli3.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        insert ctktItem;            

        ctktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli4.Id);
        ctktItem.Parent_Ticket_Item__c = ptktItem.Id;
        insert ctktItem;            
        ticketItemIds.add(ctktItem.Id);

        List<Ticket_Item__c> result = CopyTicketItems.CopyTicketItems(tkt.Id, ticketItemIds, true, 0);
        System.assert(result.size() == 1);

        Test.stopTest();
    }    

}