src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/PriceBookItemLookupController_Test.cls
@isTest
private class PriceBookItemLookupController_Test {
   
    static testMethod void search_Test() 
    {

        Test.startTest();

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Integer laborItemCount = 21;
        List<Price_Book_Item__c> pliItems = AlpineTestHelper.CreatePriceBookItems(laborItemCount, job.Price_Book__c, 'Labor') ;
        AlpineTestHelper.CreatePriceBookItems(50, job.Price_Book__c, 'Equipment') ;          
        Test.stopTest();        
      
        PriceBookItemLookupController controller = new PriceBookItemLookupController();           
        System.debug(' search_Test: pbID=' + job.Price_Book__c + ', ItemType=Labor');
        List<Price_Book_Item__c> results =controller.performSearch(job.Price_Book__c, 'Labor', '');

        System.assertEquals(laborItemCount, results.size());
        
    }  


    

    static testMethod void search_GetAll_Test() 
    {

        Test.startTest();

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Integer laborItemCount = 21;
        Integer equipItemCount = 26;

        List<Price_Book_Item__c> pliItems = AlpineTestHelper.CreatePriceBookItems(laborItemCount, job.Price_Book__c, 'Labor') ;
        AlpineTestHelper.CreatePriceBookItems(equipItemCount, job.Price_Book__c, 'Equipment') ;   
        Test.stopTest();
     
  
        PriceBookItemLookupController controller = new PriceBookItemLookupController();           
        System.debug(' search_Test: pbID=' + job.Price_Book__c + ', ItemType=Labor');
        List<Price_Book_Item__c> results =controller.performSearch(job.Price_Book__c, 'Labor', '');      

        System.assertEquals(laborItemCount, results.size());
        
        results =controller.performSearch(job.Price_Book__c, 'Equipment', '');
        System.assertEquals(equipItemCount, results.size());
       
    }  

    static testMethod void searchKeywork_Test() 
    {

        Test.startTest();

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Integer itemCount = 21;
        Integer equipItemCount = 26;

        List<Price_Book_Item__c> pliItems = AlpineTestHelper.CreatePriceBookItems(itemCount, job.Price_Book__c, 'Labor') ;
        Set<Id> catalogItemIDs = new Set<Id>();

        string keyword = 'Test12345 Item';

        for(Integer i=0; i<6; i++)
        {
            catalogItemIDs.add(pliItems.get(i).Catalog_Item__c);
        }
        List<Catalog_Item__c> cItems = [SELECT Name, Description__c FROM Catalog_Item__c WHERE Id IN :catalogItemIDs];
        Boolean alter= true;
        for(Catalog_Item__c ci: cItems)
        {
            if(alter)
            {
                ci.Name = keyword + StringUtility.newGuid();                
            }
            else
            {
                ci.Description__c = StringUtility.newGuid() + keyword + StringUtility.newGuid();     
            }
            alter = !alter;
        }
        update cItems;            
       
       
        Test.stopTest();


        PriceBookItemLookupController controller = new PriceBookItemLookupController();   
        
        List<Price_Book_Item__c> results =controller.performSearch(job.Price_Book__c, 'Labor', keyword);      
        System.assertEquals(cItems.size(), results.size());       

    }  

    static testMethod void uiElement_Test() 
    {

        Test.startTest();

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Integer laborItemCount = 21;
        Integer equipItemCount = 26;

        List<Price_Book_Item__c> pliItems = AlpineTestHelper.CreatePriceBookItems(laborItemCount, job.Price_Book__c, 'Labor') ;
        AlpineTestHelper.CreatePriceBookItems(equipItemCount, job.Price_Book__c, 'Equipment') ;   
     

        PageReference page = new PageReference('PriceBookItemSearcher');
      
        Test.setCurrentPage(page);        
      
        PriceBookItemLookupController controller = new PriceBookItemLookupController();   
        controller.search();
        Test.stopTest();
        try
        {            
            controller.getFormTag();
            controller.getTextBox();
            System.assert(true);
        }
        catch(Exception ex)
        {
            System.assert(false);
        }       
    }  
}