src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/EnableInventoryTracking__c.field-meta.xml
<CustomField>
    <fullName>EnableInventoryTracking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set it to true to turn on Inventory Tracking. When it is set to false, the Inventory Tracking module won't run even the Catalog Items have Track Inventory checked.</description>
    <label>EnableInventoryTracking</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/TicketItemWarehouseQty__c.field-meta.xml
<CustomField>
    <fullName>TicketItemWarehouseQty__c</fullName>
    <defaultValue>'Qty__c'</defaultValue>
    <description>The API name of quantity field for WarehouseItem inventory update</description>
    <label>TicketItemWarehouseQty</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment used on the job is stored. When you select a warehouse, the ticket items added to tickets for the job will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where equipment included on the ticket is stored. When you select a warehouse, ticket items will be from the specified warehouse by default.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Track_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Track_Inventory__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, users can add the linked catalog item to a warehouse to track its inventory levels.</inlineHelpText>
    <label>Catalog Track Inventory</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Input_Qty__c.field-meta.xml
<CustomField>
    <fullName>Input_Qty__c</fullName>
    <inlineHelpText>Quantity of the ticket item added to the ticket.</inlineHelpText>
    <label>Input Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Warehouse where the ticket item is stored.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii0000001dLM7EAM_00Ni000000CaazdEAB</fullName>
        <active>true</active>
        <errorMessage>Archived Warehouse won't be available for new Job.</errorMessage>
        <field>Job__c.Warehouse__c</field>
        <filterItems>
            <field>Warehouse__c.IsArchived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Job_Warehouse</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000001dLMLEA2_00Ni000000Cab2SEAR</fullName>
        <active>true</active>
        <field>Ticket__c.Warehouse__c</field>
        <filterItems>
            <field>Warehouse__c.IsArchived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket_Warehouse</name>
    </namedFilters>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Warehouse_Item__c/Warehouse_Item__c.object-meta.xml
<CustomObject>
    <label>Warehouse Item</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Warehouse Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Warehouse_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the warehouse item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipName>Inventory_Location_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Warehouse_Item__c/fields/Quantity_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Quantity_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Quantity of the item currently on hand.</inlineHelpText>
    <label>Quantity On Hand</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Warehouse_Item__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <inlineHelpText>Warehouse where the item is stored.</inlineHelpText>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Warehouse Items</relationshipLabel>
    <relationshipName>Inventory_Location_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Warehouse_Item__c/fields/Warehouse_Item_Unique__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Item_Unique__c</fullName>
    <description>This field will hold the concatenation of the Warehouse ID + Catalog Item ID and this combo will be required to be unique.  This filed is autoupdated by a workflow rule and field update to ensure that you don't setup duplicate warehouse items.  This field never needs to be displayed to the user.</description>
    <inlineHelpText>Unique identifier for the warehouse item.</inlineHelpText>
    <label>Warehouse Item Unique</label>
    <length>160</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/InventoryManager.cls
public class InventoryManager
{   
    public static void OnTicketItemAfterInsert(List<Ticket_Item__c> items)
    {          
        if(FX_Settings__c.getOrgDefaults().EnableInventoryTracking__c != true) return;

        String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();
        List<InventoryManager.TicketItemInventoryInfo> inventoryTrackingItems = new List<InventoryManager.TicketItemInventoryInfo>();  

        for(Ticket_Item__c ti : items)
        {
            if(ti.Warehouse__c == null || !ti.Catalog_Track_Inventory__c) continue;
            inventoryTrackingItems.add(new InventoryManager.TicketItemInventoryInfo(ti, warehouseQtyFieldName, false));
        }
        InventoryManager.UpdateWarehouseInventory(inventoryTrackingItems);
    }   

    public static void OnTicketItemAfterUpdate(List<Ticket_Item__c> items, Map<Id, Ticket_Item__c> oldMap)
    {
        if(FX_Settings__c.getOrgDefaults().EnableInventoryTracking__c != true) return;

        String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();
        List<InventoryManager.TicketItemInventoryInfo> inventoryTrackingItems = new List<InventoryManager.TicketItemInventoryInfo>();  

        for(Ticket_Item__c ti: items)
        {
            if(!ti.Catalog_Track_Inventory__c) continue;

            Ticket_Item__c old = oldMap.get(ti.Id);
            Double newQty = (Double)ti.get(warehouseQtyFieldName);
            Double oldQty = TicketItemInventoryQtyLookup.containsKey(ti.Id)? TicketItemInventoryQtyLookup.get(ti.Id) : (Double)old.get(warehouseQtyFieldName);

            if(ti.Warehouse__c == old.Warehouse__c && newQty != oldQty && ti.Warehouse__c!=null)
            {
                inventoryTrackingItems.add(new InventoryManager.TicketItemInventoryInfo(ti, newQty - oldQty));
                TicketItemInventoryQtyLookup.put(ti.Id, newQty);
            } 
            else if(ti.Warehouse__c != old.Warehouse__c)
            {
                if(old.Warehouse__c!=null)
                {
                    inventoryTrackingItems.add(new InventoryManager.TicketItemInventoryInfo(old, warehouseQtyFieldName, true));
                }
                if(ti.Warehouse__c!=null)
                {
                    inventoryTrackingItems.add(new InventoryManager.TicketItemInventoryInfo(ti, warehouseQtyFieldName, false));
                    TicketItemInventoryQtyLookup.put(ti.Id, newQty);
                }
            }                
        }
        InventoryManager.UpdateWarehouseInventory(inventoryTrackingItems);

    }

    public static void OnTicketItemAfterDelete(List<Ticket_Item__c> items)
    {
        if(FX_Settings__c.getOrgDefaults().EnableInventoryTracking__c != true) return;
        
        String warehouseQtyFieldName = InventoryManager.GetTicketItemInventoryQtyFieldName();
        List<InventoryManager.TicketItemInventoryInfo> inventoryTrackingItems = new List<InventoryManager.TicketItemInventoryInfo>();  

        for(Ticket_Item__c ti : items)
        {
            if(ti.Warehouse__c == null || !ti.Catalog_Track_Inventory__c) continue;
            inventoryTrackingItems.add(new InventoryManager.TicketItemInventoryInfo(ti, warehouseQtyFieldName, true));
        }
        InventoryManager.UpdateWarehouseInventory(inventoryTrackingItems);
    }

    static Map<Id, Double> TicketItemInventoryQtyLookup 
    {
        get
        {
            if(TicketItemInventoryQtyLocal==null)
            {
                TicketItemInventoryQtyLocal = new Map<Id, Double>();
            }
            return TicketItemInventoryQtyLocal;
        }
    }
    static Map<Id, Double> TicketItemInventoryQtyLocal;

    public static String GetTicketItemInventoryQtyFieldName()
    {
        if(String.isBlank(TicketItemInventoryQtyFieldNameLocal))
        {
            String warehouseQtyFieldName = FX_Settings__c.getOrgDefaults().TicketItemWarehouseQty__c;
            warehouseQtyFieldName = String.isBlank(warehouseQtyFieldName) ? 'qty__c' : warehouseQtyFieldName.toLowercase();
               
            Set<String> fields = Ticket_Item__c.sObjectType.getDescribe().fields.getMap().keySet();
            if(fields.contains(warehouseQtyFieldName))
            {
                TicketItemInventoryQtyFieldNameLocal = warehouseQtyFieldName;
            }
            else
            {
                TicketItemInventoryQtyFieldNameLocal = UtilityGetNamespace.CurrentNamespace() +  'Input_Qty__c';
            }
        }
        return TicketItemInventoryQtyFieldNameLocal;
    }
    static String TicketItemInventoryQtyFieldNameLocal;

	public static void RestoreInventoryUponTicketDelete(Set<Id> tktIds)
	{
        if(FX_Settings__c.getOrgDefaults().EnableInventoryTracking__c != true) return;

		String warehouseQtyFieldName = GetTicketItemInventoryQtyFieldName();

		String soql = 'SELECT Id, [ns]Warehouse__c, [ns]Catalog_Item__c, ' + warehouseQtyFieldName + ' FROM [ns]Ticket_Item__c WHERE [ns]Ticket__c IN :tktIds AND [ns]Warehouse__c!=null AND  [ns]Catalog_Track_Inventory__c=true';
		soql = soql.replace('[ns]', UtilityGetNamespace.CurrentNamespace());

        //System.debug('RestoreInventoryUponTicketDelete soql: ' + soql);

		List<TicketItemInventoryInfo> items = new List<TicketItemInventoryInfo>();
		for(sObject o : Database.query(soql))
		{
			items.add(new TicketItemInventoryInfo((Ticket_Item__c)o, warehouseQtyFieldName, true));
		}
		if(!items.isEmpty())
		{
			UpdateWarehouseInventory(items);
		}
	}

	public static void RestoreInventoryUponJobDelete(Set<Id> jobIds)
	{
        if(FX_Settings__c.getOrgDefaults().EnableInventoryTracking__c != true) return;

		List<Ticket__c> tkts = [SELECT Id FROM Ticket__c WHERE Job__c IN :jobIds];
		RestoreInventoryUponTicketDelete((new Map<Id, Ticket__c>(tkts)).keySet());
	}

	static void UpdateWarehouseInventory(List<TicketItemInventoryInfo> items)
    {       
        Map<String, Double> wiQtyLookup = new Map<String, Double>();
        for(TicketItemInventoryInfo item : items)
        {
            String key = item.WarehouseItemUniqueID;
            Double prevQty = wiQtyLookup.containsKey(key)? wiQtyLookup.get(key) : 0;  
            wiQtyLookup.put(item.WarehouseItemUniqueID, prevQty + item.Qty);
        }
        
        Set<String> ids = wiQtyLookup.keySet();
        List<Warehouse_Item__c> warehouseItems = [SELECT Quantity_On_Hand__c, Warehouse_Item_Unique__c FROM Warehouse_Item__c WHERE Warehouse_Item_Unique__c IN :ids];
        for(Warehouse_Item__c wi: warehouseItems)
        {            
            wi.Quantity_On_Hand__c = wi.Quantity_On_Hand__c - wiQtyLookup.get(wi.Warehouse_Item_Unique__c);
        }
        Database.update(warehouseItems, false);        
    }
    public class TicketItemInventoryInfo
    {
        public TicketItemInventoryInfo(Ticket_Item__c ti, String qtyField, Boolean isRestock)
        {            
            Qty = (Double)ti.get(qtyField);            
            if(isRestock)
            {
                Qty *= -1;
            }
            WarehouseItemUniqueID = ti.Warehouse__c + ti.Catalog_Item__c;

            //System.debug('TicketItemInventoryInfo('+ti.Id+', '+qtyField+', '+isRestock+'): ' + Qty + ' : ' + WarehouseItemUniqueID);

        }

        public TicketItemInventoryInfo(Ticket_Item__c ti, Double qty0)
        {
            WarehouseItemUniqueID = ti.Warehouse__c + ti.Catalog_Item__c;
            Qty = qty0;
            
            //System.debug('TicketItemInventoryInfo('+ti.Id+', '+qty0+'): ' + Qty + ' : ' + WarehouseItemUniqueID);
        }

        public Double Qty {get; private set;}
        public String WarehouseItemUniqueID {get; private set;}
    }

}