src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Breadcrumb__c.field-meta.xml
<CustomField>
    <fullName>Breadcrumb__c</fullName>
    <inlineHelpText>Unique identifier used to categorize the item in catalog item lists.</inlineHelpText>
    <label>Breadcrumb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Classification to which the item belongs.</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Catalog Items</relationshipLabel>
    <relationshipName>Catalog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Name_Unique__c</fullName>
    <description>This is only used to guarantee uniqueness of the SFDC standard object field Name (Item Code).  It never needs to be shown to the user.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the item.</inlineHelpText>
    <label>Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Classification__c/fields/Breadcrumb__c.field-meta.xml
<CustomField>
    <fullName>Breadcrumb__c</fullName>
    <formula>SUBSTITUTE(
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__c, NULL, "", P__r.P__r.Name + " : ") + 
CASE(P__c, NULL, "", P__r.Name + " : ") + Name, 
"ItemClassification : ", "")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique identifier used to categorize the classification in lists.</inlineHelpText>
    <label>Breadcrumb</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/CatalogItemBuilder.cls
public class CatalogItemBuilder
{
	public static void OnBeforeInsert(List<Catalog_Item__c> items)
	{
		CopyClassificationBreadcrumb(items);
        for(Catalog_Item__c ci : items)
        {
            ci.Name_Unique__c = ci.Name;
        }
	}

	public static void OnBeforeUpdate(List<Catalog_Item__c> items, Map<Id, Catalog_Item__c> oldMap)
	{
		List<Catalog_Item__c> actionItems = new List<Catalog_Item__c>();
		for(Catalog_Item__c ci : items)
		{
			if(ci.Classification__c != oldMap.get(ci.Id).Classification__c)
			{
				if(ci.Classification__c == null)
				{
					ci.Breadcrumb__c = null;
				}
				else
				{
					actionItems.add(ci);
				}
			}
			ci.Name_Unique__c = ci.Name;
		}
		if(!actionItems.isEmpty()) CopyClassificationBreadcrumb(actionItems);
	}

	public static void OnAfterUpdate(List<Catalog_Item__c> items, Map<Id, Catalog_Item__c> oldMap)
	{
		TaintPriceBookItems(items);
	}	

	public static void CopyClassificationBreadcrumb(List<Catalog_Item__c> items)
	{
		Set<Id> classificationIDs = new Set<Id>();
		List<Catalog_Item__c> actionItems = new List<Catalog_Item__c>();
		for(Catalog_Item__c ci : items)
		{
			if(ci.Classification__c != null)
			{
				classificationIDs.add(ci.Classification__c);
				actionItems.add(ci);
			}
		}
		if(!actionItems.isEmpty())
		{
			Map<Id, Classification__c> classificationLookup = new Map<Id, Classification__c>([SELECT Id, Breadcrumb__c FROM Classification__c  WHERE Id IN :classificationIDs]);
			for(Catalog_Item__c ci : actionItems)
			{
				ci.Breadcrumb__c = classificationLookup.get(ci.Classification__c).Breadcrumb__c;
			}
		}
	}

	public static void TaintPriceBookItems(List<Catalog_Item__c> items)
	{
		Set<Id> catalogItemIDs = new Map<Id, Catalog_Item__c>(items).keySet();
		PriceBookItemTainter.TaintPriceBookItems(catalogItemIDs);
		//PriceBookItemBulkTainting b= new PriceBookItemBulkTainting(catalogItemIDs);
		//Database.executeBatch(b, 200);	

	}
}