src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/Ticket_Checklist_Step__c.object-meta.xml
<CustomObject>
    <label>Ticket Checklist Step</label>
    <nameField>
        <label>Ticket Checklist Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Text that displays for the step on a checklist.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the position of the step on a checklist. For example, "5.0000" indicates that the step is the fifth step on a checklist.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Checklist_Step__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Checklist Steps</relationshipLabel>
    <relationshipName>Ticket_Checklist_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the ticket item. The ticket item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the ticket item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/objects/Ticket_Log__c/Ticket_Log__c.object-meta.xml
<CustomObject>
    <label>Ticket Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Ticket Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Log__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Log__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket for which the log entry was recorded.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Logs</relationshipLabel>
    <relationshipName>Ticket_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/JobPropagator_Test.cls
@isTest
private class JobPropagator_Test
{
    static testmethod void RunForCodeCoverage()
    {
        Map<String, String> formKeySObjs = new Map<String, String>();
        String ns = StringUtility.FXNamespace();
        JobPropagator.GetPathsToJob(Ticket__c.sObjectType.getDescribe());
        formKeySObjs.put(ns + 'Ticket__c', ns + 'Job__c');
        JobPropagator.formKeySObjs = formKeySObjs;
        JobPropagator.GetPathsToJob(Ticket__c.sObjectType.getDescribe());

        Job__c j = AlpineTestHelper.CreateJobs(1, false).get(0);
        insert j;
        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, false).get(0);
        insert tkt;
        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= '12000', Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210,  Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;
        Price_Book_Item__c pli1 = new Price_Book_Item__c(Price_Book__c = j.Price_Book__c, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);
        insert pli1;
        Ticket_Item__c tktItem  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pli1.Id);
        insert tktItem;   
        JobPropagator.GetJobID(tktItem, ns + 'Ticket__r.' + ns + 'Job__c');


    }
    static testmethod void TicketLog_TurnOffJobPropagator_Test()
    {
        Test.startTest();
        FX_Settings__c setting = FXSettingHelper.FXSettings; 
        setting.TurnOffJobPropagator__c =  true;
        upsert setting;

        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Ticket_Log__c> objs = new List<Ticket_Log__c>();
        insert new Ticket_Log__c(Ticket__c = tkt.Id, Start_Time__c = Datetime.now());
        Test.stopTest();
        List<Ticket_Log__c> dbItems = [SELECT Id FROM Ticket_Log__c WHERE Ticket__c =:tkt.Id AND Job__c = null];
        System.assert(dbItems.size() == 1, 'should NOT have value for Job__c');
    
    }

    static testmethod void TicketItem_Test()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(10, job.Price_Book__c, 'Equipment');
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : pbiItems)
        {
            tktItems.add(new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt.Id));
        }
        insert tktItems;
        Test.stopTest();
        List<Ticket_Item__c> dbItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 10, 'should have 10 entries with jobId, instead of ' + dbItems.size());
    }


    static testmethod void TicketItem_ReparentTest()
    {
        Test.startTest();
        List<Job__c> jobs = AlpineTestHelper.CreateJobs(2, false);
        jobs.get(1).Price_Book__c = jobs.get(0).Price_Book__c;
        insert jobs;
        Job__c j1 = jobs.get(0);
        Job__c j2 = jobs.get(1);


        Ticket__c tkt1 = AlpineTestHelper.CreateTickets(j1, 1, true).get(0);
        Ticket__c tkt2 = AlpineTestHelper.CreateTickets(j2, 1, true).get(0);
        Price_Book_Item__c pbi = AlpineTestHelper.CreatePriceBookItems(1, j1.Price_Book__c, 'Equipment').get(0);
        
        Ticket_Item__c ti1 = new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt1.Id);
        insert ti1;

        Ticket_Item__c dbTktItem = [SELECT Id, Job__c, Ticket__c FROM Ticket_Item__c WHERE Id=:ti1.Id];
        System.assert(dbTktItem.Job__c == j1.Id, 'Job__c should be ' + j1.Id + ', instead of ' + dbTktItem.Job__c);

        dbTktItem.Ticket__c = tkt2.Id;
        update dbTktItem;

        dbTktItem = [SELECT Id, Job__c, Ticket__c FROM Ticket_Item__c WHERE Id=:ti1.Id];
        System.assert(dbTktItem.Job__c == j2.Id, 'Job__c should be ' + j2.Id + ', instead of ' + dbTktItem.Job__c);


    }


    static testmethod void TicketLog_Test()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Ticket_Log__c> objs = new List<Ticket_Log__c>();
        insert new Ticket_Log__c(Ticket__c = tkt.Id, Start_Time__c = Datetime.now());
        Test.stopTest();
        List<Ticket_Log__c> dbItems = [SELECT Id FROM Ticket_Log__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
    
    }
    
    static testmethod void TicketLog_Update_Test()
    {
       
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Ticket_Log__c> objs = new List<Ticket_Log__c>();
        insert new Ticket_Log__c(Ticket__c = tkt.Id, Start_Time__c = Datetime.now());
        Test.startTest();
        List<Ticket_Log__c> dbItems = [SELECT Id, Job__c FROM Ticket_Log__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
        
        Ticket_Log__c log = dbItems.get(0);
        log.Job__c = null;
        update log;
        Test.stopTest();
        dbItems = [SELECT Id FROM Ticket_Log__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
    
    }
    
    static testmethod void TicketChecklistStep_Test()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Ticket_Checklist_Step__c> objs = new List<Ticket_Checklist_Step__c>();
        insert new Ticket_Checklist_Step__c(Ticket__c = tkt.Id, Name = StringUtility.newGuid(), Description__c='Unit Test');
        Test.stopTest();
        List<Ticket_Checklist_Step__c> dbItems = [SELECT Id FROM Ticket_Checklist_Step__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
    }
    
    static testmethod void TicketChecklistStep_Update_Test()
    {       
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Ticket_Checklist_Step__c> objs = new List<Ticket_Checklist_Step__c>();
        insert new Ticket_Checklist_Step__c(Ticket__c = tkt.Id, Name = StringUtility.newGuid(), Description__c='Unit Test');
        Test.startTest();        
         List<Ticket_Checklist_Step__c> dbItems = [SELECT Id FROM Ticket_Checklist_Step__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
        Ticket_Checklist_Step__c obj = dbItems.get(0);
        obj.Job__c = null;
        update obj;
        Test.stopTest();
        dbItems = [SELECT Id FROM Ticket_Checklist_Step__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 1, 'should have value for Job__c');
    }

    static testmethod void sObject_Test()
    {
        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(1, job.Price_Book__c, 'Equipment');
        List<sObject> tktItems = new List<sObject>();
        for(Price_Book_Item__c pbi : pbiItems)
        {
            tktItems.add(new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt.Id));
        }
        insert tktItems;
        Test.startTest();
        String ns = StringUtility.FXNamespace();
        tktItems = Database.query('SELECT Id FROM ' + ns + 'Ticket_Item__c');
        JobPropagator.SetJobId(tktItems);        
        Test.stopTest();

        tktItems = Database.query('SELECT Id, ' + ns + 'Job__c FROM ' + ns + 'Ticket_Item__c');

        for(Ticket_Item__c ti: (List<Ticket_Item__c> )tktItems)
        {
            System.assert(ti.Job__c == job.Id, 'Job__c should be ' + job.Id + ', instead of ' + ti.Job__c);
        }
    }

    static testmethod void PropagatorBatchTest()
    {
        
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(10, job.Price_Book__c, 'Equipment');
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : pbiItems)
        {
            tktItems.add(new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt.Id));
        }
        insert tktItems;
        Test.startTest();
        Database.executeBatch(new JobPropagatorBatchable(StringUtility.FXNamespace() + 'Ticket_Item__c'));
        Test.stopTest();
        List<Ticket_Item__c> dbItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 10, 'should have 10 entries with jobId, instead of ' + dbItems.size());
    }

    static testmethod void RunPostInstall_Test()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(10, job.Price_Book__c, 'Equipment');
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : pbiItems)
        {
            tktItems.add(new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt.Id));
        }
        insert tktItems;
        JobPropagatorBatchable.RunPostInstall();
        Test.stopTest();
        List<Ticket_Item__c> dbItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 10, 'should have 10 entries with jobId, instead of ' + dbItems.size()); 
    }  
    

    static testmethod void JobPropagatorExt_Test()
    {
        Test.startTest();
        Job__c job = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(job, 1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(10, job.Price_Book__c, 'Equipment');
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : pbiItems)
        {
            tktItems.add(new Ticket_Item__c(Price_Book_Item__c = pbi.Id, Ticket__c = tkt.Id));
        }
        insert tktItems;
        JobPropagatorExt.Run(tktItems);
        Test.stopTest();
        List<Ticket_Item__c> dbItems = [SELECT Id FROM Ticket_Item__c WHERE Ticket__c =:tkt.Id AND Job__c = :job.Id];
        System.assert(dbItems.size() == 10, 'should have 10 entries with jobId, instead of ' + dbItems.size()); 
    }  
}