src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/CatalogItemPriceBook__c.object-meta.xml
<CustomObject>
    <description>Track the Price Books where Catalog Item is used</description>
    <label>CatalogItemPriceBook</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>CatalogItemPriceBook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CatalogItemPriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/IsDirty__c.field-meta.xml
<CustomField>
    <fullName>IsDirty__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag item for processing</description>
    <label>IsDirty</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/JointKey__c.field-meta.xml
<CustomField>
    <fullName>JointKey__c</fullName>
    <externalId>true</externalId>
    <label>JointKey</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/CatalogItemPriceBook__c.field-meta.xml
<CustomField>
    <fullName>CatalogItemPriceBook__c</fullName>
    <formula>CASESAFEID( Catalog_Item__c) + CASESAFEID(Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CatalogItemPriceBook</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/CatalogItemPriceBookHandler.cls
public class CatalogItemPriceBookHandler
{       
    public static void SetDirtyFlagJointKey(List<CatalogItemPriceBook__c> items)
    {
        for(CatalogItemPriceBook__c o : items)
        {
            String key = GetJointKey(o);
            if(o.JointKey__c != key)
            {
                o.JointKey__c = key;
            }
            o.IsDirty__c = true;
        }
    }
    public static void CreateCatalogItemPriceBook(List<Price_Book_Item__c> items)
    {           
        List<CatalogItemPriceBook__c> objs = new List<CatalogItemPriceBook__c>();
        Set<String> keys = new Set<String>();
        for(Price_Book_Item__c pbi : items)
        {
            String key = GetJointKey(pbi);
            if(keys.contains(key)) continue;
            objs.add(new CatalogItemPriceBook__c(Catalog_Item__c = pbi.Catalog_Item__c, Price_Book__c = pbi.Price_Book__c, JointKey__c=key));
            keys.add(key);
        }
        if(!objs.isEmpty()){
            upsert objs JointKey__c;
        }
    }      

    public static void RefreshCatalogItemPriceBook(List<Price_Book_Item__c> items)
    {
        Set<String> jointKeys = new Set<String>();
        Set<Id> catalogItemIds = new Set<Id>();
        Set<Id> priceBookIds = new Set<Id>();

        for(Price_Book_Item__c pbi: items)
        {
            priceBookIds.add(pbi.Price_Book__c);            
            catalogItemIds.add(pbi.Catalog_Item__c);
            jointKeys.add(GetJointKey(pbi));
        }
        for(Price_Book_Item__c pbi: [SELECT Id, CatalogItemPriceBook__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Price_Book__c IN :priceBookIds AND Catalog_Item__c IN :catalogItemIds])
        {
            jointKeys.remove(pbi.CatalogItemPriceBook__c);
        }
        if(!jointKeys.isEmpty())
        {
            delete [SELECT Id FROM CatalogItemPriceBook__c WHERE JointKey__c IN :jointKeys];
        }
    }

    public static String GetJointKey(Price_Book_Item__c o)
    {
        return String.valueOf(o.Catalog_Item__c) + String.valueOf(o.Price_Book__c);
    }

    public static String GetJointKey(CatalogItemPriceBook__c o)
    {
        return String.valueOf(o.Catalog_Item__c) + String.valueOf(o.Price_Book__c);
    }

}