src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/AddTktItemsByPBSeqNum__c.field-meta.xml
<CustomField>
    <fullName>AddTktItemsByPBSeqNum__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, price book items, when added to a ticket, should honor the sequence number.  Otherwise they will be inserted at the end of the ticket.</description>
    <inlineHelpText>Controls whether users can change sequence numbers for price book items to adjust the order of item lists. If selected, users cannot change sequence numbers. If deselected, users can change sequence numbers and new items get added at the end of a list.</inlineHelpText>
    <label>Honor Sequence Number</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Description__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Description__c</fullName>
    <formula>Catalog_Item__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Catalog description for the price book item. The price book item inherits this description from the linked catalog item by default. If the price book item has a description override, the price book item uses that description.</inlineHelpText>
    <label>Catalog Description</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_UOM__c.field-meta.xml
<CustomField>
    <fullName>Catalog_UOM__c</fullName>
    <formula>TEXT(Catalog_Item__r.UOM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unit of measurement used for the price book item. The price book item inherits this unit of measurement from the linked catalog item.</inlineHelpText>
    <label>Catalog UOM</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Description_Override__c.field-meta.xml
<CustomField>
    <fullName>Description_Override__c</fullName>
    <description>Complete this field to override the catalog item description within this price book</description>
    <inlineHelpText>Catalog description for the price book item. This description overrides the catalog description inherited from the linked catalog item.</inlineHelpText>
    <label>Description Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Auto_Added__c.field-meta.xml
<CustomField>
    <fullName>Auto_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item was added to the quote automatically. An item gets added to a quote automatically if the linked price book item has a default quantity or the linked price book item has a parent price book item.</inlineHelpText>
    <label>Auto Added</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Catalog_UOM__c.field-meta.xml
<CustomField>
    <fullName>Catalog_UOM__c</fullName>
    <description>The Unit of Measure copied from the corresponding catalog item.</description>
    <inlineHelpText>Unit of measurement used for the quote item. The quote item inherits this unit of measurement from the linked catalog item.</inlineHelpText>
    <label>Catalog UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Created_in_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Created_in_Mobile__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item was added to the quote in FieldFX Mobile. If unselected, the item was added to the quote in FieldFX Back office.</inlineHelpText>
    <label>Created in Mobile</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the quote item. The quote item inherits this description from the linked catalog item by default. If the linked price book item has a description override, the quote item inherits that description.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/PBI_Maximum_Quantity__c.field-meta.xml
<CustomField>
    <fullName>PBI_Maximum_Quantity__c</fullName>
    <inlineHelpText>Maximum quantity of the item that users can add to a quote. The quote item inherits this quantity from the linked price book item.</inlineHelpText>
    <label>PBI Maximum Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <inlineHelpText>Quantity of the item added to the quote.</inlineHelpText>
    <label>Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the quote item displays in lists. The quote item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/QuoteItemHandler.cls
public class QuoteItemHandler
{
	public static void InitQuoteItems(List<Quote_Item__c> items)
	{
		Set<Id> pbiIds = new Set<Id>();
		Set<Id> quoteIds = new Set<Id>();
		for(Quote_Item__c obj: items)
		{
			pbiIds.add(obj.Price_Book_Item__c);
			quoteIds.add(obj.Quote__c);
		}
		String ns = StringUtility.FXNamespace();	

		List<String> soqlFields = new List<String>();
		String[] params = new String[]{ns};
		
		soqlFields.add(String.format('{0}Price_Book__r.{0}AddTktItemsByPBSeqNum__c', params));
		soqlFields.add(String.format('{0}Catalog_Item__r.{0}Description__c', params));
        soqlFields.add(String.format('{0}Catalog_Item__r.{0}Ticket_Item_Record_Type__c', params));
        soqlFields.add(String.format('{0}Catalog_Item__r.{0}UOM__c', params));

		Set<String> priceBookItemFields = new Set<String>();

		for(Schema.SObjectField f: Schema.sObjectType.Price_Book_Item__c.fields.getMap().values())
        {
            Schema.DescribeFieldResult fd = f.getDescribe();    
            String fName = fd.getName();         
            soqlFields.add(fName);
            if(fd.isNameField() || fd.isCustom() || fName == 'CurrencyIsoCode')
            {
            	priceBookItemFields.add(fName);
            }
        }

        String soql = String.format('SELECT {1} FROM {0}Price_Book_Item__c WHERE Id IN :pbiIds AND IsDeleted=false', new String[]{ns, String.join(soqlFields, ',')});

        Map<Id, Price_Book_Item__c> pbiItems = new Map<Id, Price_Book_Item__c>((List<Price_Book_Item__c>)Database.query(soql));

        
        Map<Id, Decimal> quoteItemMaxSequenceNumber = new Map<Id, Decimal>();
        
        String quoteFieldName = ns + 'Quote__c';

        for(AggregateResult ar : [SELECT Quote__c, max(Sequence_Number__c) maxseq FROM Quote_Item__c WHERE IsDeleted=false AND Quote__c in :quoteIds GROUP BY Quote__c])
        {
        	quoteItemMaxSequenceNumber.put((Id)ar.get(quoteFieldName), (Decimal)ar.get('maxseq'));
        }	

        Map<String, String> fieldMapping = GetQuoteItemFieldMapping(ns, priceBookItemFields);
        Set<String> qiFields = fieldMapping.keySet();

        String objType = ns  + 'Quote_Item__c';
        
        Map<string, Id> recordTypeLookup = new Map<string, Id>();           
        for(RecordType rt : [SELECT Id, Name, DeveloperName FROM RecordType where IsActive=true AND  SobjectType=:objType])
        {   
            recordTypeLookup.put(rt.Name, rt.Id);
            recordTypeLookup.put(rt.DeveloperName, rt.Id);
        }


        for(Quote_Item__c qi : items)
        {  
        	if(String.isBlank(qi.SyncID__c))  
            {      
                qi.SyncID__c = StringUtility.newGuid();
            }

        	if(pbiItems.containsKey(qi.Price_Book_Item__c)) 
        	{
	            Price_Book_Item__c pli = pbiItems.get(qi.Price_Book_Item__c);
	            for(String f: qiFields)
	            {
	            	qi.put(f, pli.get(fieldMapping.get(f)));                
	            }
	            if(qi.Description__c == NULL) 
	            {
	            	qi.Description__c = String.isBlank(pli.Description_Override__c)? pli.Catalog_Description__c : pli.Description_Override__c;               
	            } 

	            if ((qi.Sequence_Number__c == NULL || qi.Sequence_Number__c == 0) && pli.Price_Book__r.AddTktItemsByPBSeqNum__c == true) 
                {
                    qi.Sequence_Number__c = pli.Sequence_Number__c; 
                } 

                if( qi.Qty__c == null)
                {
                    qi.Qty__c = (pli.Default_Quantity__c != null) ? pli.Default_Quantity__c : 1;
                }
                if (qi.PBI_Maximum_Quantity__c == 0) 
                {
                    qi.PBI_Maximum_Quantity__c = 1;
                }
                qi.Catalog_UOM__c = pli.Catalog_Item__r.UOM__c;

                if(recordTypeLookup.containsKey(pli.Catalog_Item__r.Ticket_Item_Record_Type__c)) 
                {      
                    qi.RecordTypeId = recordTypeLookup.get(pli.Catalog_Item__r.Ticket_Item_Record_Type__c);
                }
            }     


            if(qi.Sequence_Number__c == NULL || qi.Sequence_Number__c == 0) 
            {                
                if(quoteItemMaxSequenceNumber.containsKey(qi.Quote__c))
                {
                    qi.Sequence_Number__c = quoteItemMaxSequenceNumber.get(qi.Quote__c) + 1;
                }
                else
                {
                	qi.Sequence_Number__c = 1;
                }               
            }
            quoteItemMaxSequenceNumber.put(qi.Quote__c, qi.Sequence_Number__c);
        }
	}

	public static void AddChildren(List<Quote_Item__c> items) 
    {
        Set<Id> pliIds = new Set<Id>();
        Set<Id> quoteIds = new Set<Id>();

        List<Quote_Item__c> itemsOfInterest = new List<Quote_Item__c>();

        String ns = StringUtility.FXNamespace();

        

        for(Quote_Item__c obj : items)
        {
            if(obj.Auto_Added__c == true || obj.Created_in_Mobile__c == true) continue;

            pliIds.add(obj.Price_Book_Item__c);
            quoteIds.add(obj.Quote__c);              
            itemsOfInterest.add(obj);            
        }
        if(itemsOfInterest.isEmpty()) return;       

        String quoteItemTypeName = ns + 'Quote_Item__c';
        Map<String, Id> quoteItemRecordTypeLookup = new Map<String, Id>();
        for(RecordType rt: [SELECT Id, Name, DeveloperName FROM RecordType WHERE IsActive=true AND  SobjectType=:quoteItemTypeName])
        {
        	quoteItemRecordTypeLookup.put(rt.Name, rt.Id);
        	quoteItemRecordTypeLookup.put(rt.DeveloperName, rt.Id);
        }


        List<Price_Book_Item__c> childPriceBookItems = [SELECT Id, Price_Book__c, Catalog_Item__r.Ticket_Item_Record_Type__c, Parent_Price_Book_Item__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Parent_Price_Book_Item__c IN :pliIds];
        
        Map<Id, Price_Book_Item__c> pbiLookup = new Map<Id, Price_Book_Item__c>(childPriceBookItems);

        Map<Id, Set<Id>> childItems = new Map<Id, Set<Id>>();
        Set<Id> pbiItemIds = new Set<Id>();
        Map<String, Id> quoteItemRecordType = new Map<String, Id>();
        for(Price_Book_Item__c pbi : childPriceBookItems)
        {
            if(!childItems.containsKey(pbi.Parent_Price_Book_Item__c))
            {
                childItems.put(pbi.Parent_Price_Book_Item__c, new Set<Id>());
            }
            childItems.get(pbi.Parent_Price_Book_Item__c).add(pbi.Id);
            pbiItemIds.add(pbi.Id);

            String rt = pbi.Catalog_Item__r.Ticket_Item_Record_Type__c;
            if(String.isBlank(rt) || !quoteItemRecordTypeLookup.containsKey(rt)) continue;

            quoteItemRecordType.put(pbi.Id, quoteItemRecordTypeLookup.get(rt));
        }

        List<Quote_Item__c> newQuoteItems = new List<Quote_Item__c>();

       
        SobjectType quoteItemSObjectType = Quote_Item__c.sObjectType;


        for(Quote_Item__c qi : itemsOfInterest)
        {
            if(!childItems.containsKey(qi.Price_Book_Item__c)) continue;

            for(Id pbi : childItems.get(qi.Price_Book_Item__c))
            {
            	Quote_Item__c newItem = (Quote_Item__c)quoteItemSObjectType.newSObject(quoteItemRecordType.containsKey(pbi)? quoteItemRecordType.get(pbi) : null, true);

                newItem.Price_Book_Item__c = pbi;
                newItem.Quote__c = qi.Quote__c;
                newItem.Parent_Quote_Item__c = qi.Id;
                newItem.SyncID__c = StringUtility.newGuid();
                newQuoteItems.add(newItem);
            }
        }
        insert newQuoteItems;
    }

    public static void DeleteChildItems(List<Quote_Item__c> items)
    {
    	Set<Id> itemIds = new Map<Id, Quote_Item__c>(items).keySet();
        Map<Id, Quote_Item__c> dbTktItems = new Map<Id, Quote_Item__c>([SELECT Id, (SELECT Id FROM Quote_Items__r WHERE IsDeleted=false AND Id NOT IN :itemIds) FROM Quote_Item__c WHERE IsDeleted=false AND Id IN :itemIds]);
        
        List<Quote_Item__c> childItemsToDelete = new List<Quote_Item__c>();
        for(Quote_Item__c ti: items)
        {  
            if (RuleEngineCore.RuleEngineInProgress!=true && ti.Auto_Added__c == true 
                && ti.Rule_Required_Item__c ==true) 
            {                
                ti.addError('Cannot delete a required quote item.');
                continue;
            }            
            
            if(!dbTktItems.get(ti.Id).Quote_Items__r.isEmpty())
            {
                childItemsToDelete.addAll(dbTktItems.get(ti.Id).Quote_Items__r);
            }
        }
      
        if(!childItemsToDelete.isEmpty())
        {
            Boolean flag = RuleEngineCore.RuleEngineInProgress;
            try
            {
               
                RuleEngineCore.RuleEngineInProgress = true;
                delete childItemsToDelete;
            }
            catch(Exception ex)
            {
                throw ex;
            }
            finally
            {
                RuleEngineCore.RuleEngineInProgress = flag;
            }
        }
    }

	static Map<String, String> GetQuoteItemFieldMapping(String ns, Set<String> priceBookItemFields)
	{
		Boolean isDevOrg = String.isBlank(ns);

        Set<String> quoteItemFields = new Set<String>();        
        Map<String, String> quoteItemToPriceBookItemMapping = new Map<String, String>();

        for(Schema.SObjectField f: Schema.sObjectType.Quote_Item__c.fields.getMap().values())
        {
            Schema.DescribeFieldResult fd = f.getDescribe(); 
            String qiFieldName = fd.getName();

            if(!fd.isAccessible() 
            	|| !fd.isCreateable() || fd.isCalculated() 
            	|| fd.isAutoNumber() || fd.isExternalId() || fd.isUnique()
            	|| (!fd.isNameField() && !fd.isCustom() && qiFieldName != 'CurrencyIsoCode'))
            {
                continue;
            }            
            
            quoteItemFields.add(qiFieldName);

            String mappingField = '';

            if(priceBookItemFields.contains(qiFieldName))
            {
            	mappingField = qiFieldName;
            }
            else
            {
            	String qiFieldNameVaried = qiFieldName.replace(ns, '').replace('PBI_', '');
            	if(priceBookItemFields.contains(qiFieldNameVaried))
            	{	
            		mappingField = qiFieldNameVaried;
            	}
            	else if(priceBookItemFields.contains(ns + qiFieldNameVaried))
            	{
            		mappingField = ns + qiFieldNameVaried;
            	} 
            }
            if(!String.isBlank(mappingField))
            {
            	quoteItemToPriceBookItemMapping.put(qiFieldName, mappingField);
            }
            
        }
        quoteItemToPriceBookItemMapping.remove(ns + 'Sequence_Number__c');

        quoteItemToPriceBookItemMapping.put(ns + 'Item_Code__c', ns + 'Catalog_Item_Code__c');
        if (quoteItemFields.contains('Cost__c')) {
            quoteItemToPriceBookItemMapping.put('Cost__c', ns + 'Catalog_Cost__c');
        }


        return quoteItemToPriceBookItemMapping;
	}
}