src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Breadcrumb__c.field-meta.xml
<CustomField>
    <fullName>Breadcrumb__c</fullName>
    <inlineHelpText>Unique identifier used to categorize the item in catalog item lists.</inlineHelpText>
    <label>Breadcrumb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Classification to which the item belongs.</inlineHelpText>
    <label>Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Catalog Items</relationshipLabel>
    <relationshipName>Catalog_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>Cost of purchasing the item.</inlineHelpText>
    <label>Cost</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Catalog description for the item.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Name_Unique__c.field-meta.xml
<CustomField>
    <fullName>Name_Unique__c</fullName>
    <description>This is only used to guarantee uniqueness of the SFDC standard object field Name (Item Code).  It never needs to be shown to the user.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the item.</inlineHelpText>
    <label>Name Unique</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <description>This is the record type that will be used when a user creates a ticket item from this catalog item.</description>
    <inlineHelpText>Record type used for the item when added to a ticket.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equipment</fullName>
                <default>true</default>
                <label>Equipment</label>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Supplies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Catalog_Item__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <inlineHelpText>Unit of measurement used for the item.</inlineHelpText>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EA</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>DAY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Classification__c/Classification__c.object-meta.xml
<CustomObject>
    <label>Classification</label>
    <nameField>
        <label>Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Classification__c/fields/Breadcrumb__c.field-meta.xml
<CustomField>
    <fullName>Breadcrumb__c</fullName>
    <formula>SUBSTITUTE(
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__r.P__c, NULL, "", P__r.P__r.P__r.Name + " : ") + 
CASE(P__r.P__c, NULL, "", P__r.P__r.Name + " : ") + 
CASE(P__c, NULL, "", P__r.Name + " : ") + Name, 
"ItemClassification : ", "")</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique identifier used to categorize the classification in lists.</inlineHelpText>
    <label>Breadcrumb</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Classification__c/fields/P__c.field-meta.xml
<CustomField>
    <fullName>P__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent of the classification. If a classification has a parent, it is a subclassification of another classification.</inlineHelpText>
    <label>Parent Classification</label>
    <referenceTo>Classification__c</referenceTo>
    <relationshipLabel>Classifications</relationshipLabel>
    <relationshipName>Classifications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Items_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Items_Last_Modified__c</fullName>
    <inlineHelpText>Date and time the price book was last updated.</inlineHelpText>
    <label>Items Last Modified</label>
    <summarizedField>Price_Book_Item__c.LastModifiedDate</summarizedField>
    <summaryForeignKey>Price_Book_Item__c.Price_Book__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Breadcrumb__c.field-meta.xml
<CustomField>
    <fullName>Breadcrumb__c</fullName>
    <formula>Catalog_Item__r.Breadcrumb__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Unique identifier used to categorize the item in price book item lists.</inlineHelpText>
    <label>Breadcrumb</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Included_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Included_Quantity__c</fullName>
    <inlineHelpText>Quantity of the price book item given to the customer at no charge.</inlineHelpText>
    <label>Included Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Ticket_Item_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item_Record_Type__c</fullName>
    <formula>TEXT( Catalog_Item__r.Ticket_Item_Record_Type__c )</formula>
    <inlineHelpText>Ticket item record type for the price book item. The price book item inherits this record type from the linked catalog item.</inlineHelpText>
    <label>Ticket Item Record Type</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/CatalogItemBuilder_Test.cls
@isTest
private class CatalogItemBuilder_Test 
{    
    static testmethod void CopyClassificationBreadcrumb_Insert()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   

        Classification__c cParent = new Classification__c(Name='p' + newGuid);
        insert cParent;

        Classification__c cChild = new Classification__c(Name='c' + newGuid, P__c = cParent.Id);
        insert cChild;


        Catalog_Item__c catalogItem = new Catalog_Item__c();
        catalogItem.Classification__c = cChild.Id;
        catalogItem.Cost__c = 10;
        catalogItem.Description__c = newGuid;
        catalogItem.Name = newGuid;
        catalogItem.Name_Unique__c = newGuid;

        insert catalogItem;

        Test.StopTest();

        string cName='c' + newGuid;
        Classification__c c = [SELECT Breadcrumb__c FROM Classification__c WHERE Name=:cName LIMIT 1];

        List<Catalog_Item__c> dbItems = [SELECT Breadcrumb__c FROM Catalog_Item__c WHERE Name =:newGuid];
        for(Catalog_Item__c ci : dbItems)
        {
            System.assertEquals(c.Breadcrumb__c, ci.Breadcrumb__c);
        }       
    }  

    static testmethod void CopyClassificationBreadcrumb_Update()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   

        Classification__c cParent = new Classification__c(Name='p' + newGuid);
        insert cParent;

        Classification__c cChild1 = new Classification__c(Name='c1' + newGuid, P__c = cParent.Id);
        insert cChild1;

        Classification__c cChild2 = new Classification__c(Name='c2' + newGuid, P__c = cParent.Id);
        insert cChild2;

        Catalog_Item__c catalogItem = new Catalog_Item__c();
        catalogItem.Classification__c = cChild1.Id;
        catalogItem.Cost__c = 10;
        catalogItem.Description__c = newGuid;
        catalogItem.Name = newGuid;
        catalogItem.Name_Unique__c = newGuid;

        insert catalogItem;

        Catalog_Item__c ci = [SELECT Classification__c FROM Catalog_Item__c WHERE Name =:newGuid LIMIT 1];
        ci.Classification__c = cChild2.Id;

        update ci;

        Test.StopTest();

        string cName='c2' + newGuid;
        Classification__c c = [SELECT Breadcrumb__c FROM Classification__c WHERE Name=:cName LIMIT 1];

        Catalog_Item__c dbItem= [SELECT Breadcrumb__c FROM Catalog_Item__c WHERE Name =:newGuid LIMIT 1];
        System.assertEquals(c.Breadcrumb__c, dbItem.Breadcrumb__c);   
    }  


    static testmethod void CopyClassificationBreadcrumb_UpdateClassificationToNull()
    {
        Test.StartTest();   
        String newGuid = StringUtility.newGuid();   

        Classification__c cParent = new Classification__c(Name='p' + newGuid);
        insert cParent;

        Classification__c cChild1 = new Classification__c(Name='c1' + newGuid, P__c = cParent.Id);
        insert cChild1;

        Classification__c cChild2 = new Classification__c(Name='c2' + newGuid, P__c = cParent.Id);
        insert cChild2;

        Catalog_Item__c catalogItem = new Catalog_Item__c();
        catalogItem.Classification__c = cChild1.Id;
        catalogItem.Cost__c = 10;
        catalogItem.Description__c = newGuid;
        catalogItem.Name = newGuid;
        catalogItem.Name_Unique__c = newGuid;

        insert catalogItem;

        Catalog_Item__c ci = [SELECT Classification__c FROM Catalog_Item__c WHERE Name =:newGuid LIMIT 1];
        ci.Classification__c = null;

        update ci;

        Test.StopTest();

        string cName='c2' + newGuid;
        Classification__c c = [SELECT Breadcrumb__c FROM Classification__c WHERE Name=:cName LIMIT 1];

        Catalog_Item__c dbItem= [SELECT Breadcrumb__c FROM Catalog_Item__c WHERE Name =:newGuid LIMIT 1];
        System.assert(dbItem.Breadcrumb__c==null);
    }  


    static testmethod void TaintPriceBookItems_Test()
    {
          
        String newGuid = StringUtility.newGuid();   

        Price_Book__c priceBook = new Price_Book__c(Name = 'PriceBook ' + newGuid);
        insert priceBook;


        Catalog_Item__c catalogItem = new Catalog_Item__c(Name= newGuid, Description__c = 'Test Catalog Item', UOM__c='Gal', Sequence_Number__c=210, Ticket_Item_Record_Type__c = 'Equipment');
        insert catalogItem;       
        
        Price_Book_Item__c pli = new Price_Book_Item__c(Price_Book__c = priceBook.Id, Price__c=125, Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, Included_Quantity__c=0, Catalog_Item__c=catalogItem.Id);

        insert pli;

        Price_Book__c pb1 = [SELECT Name, Items_Last_Modified__c FROM Price_Book__c WHERE Id=:priceBook.Id];
        
        Datetime lastTime = pb1.Items_Last_Modified__c;

        Test.StartTest();

       
        Catalog_Item__c ci = [SELECT Id, Name, Sequence_Number__c FROM Catalog_Item__c WHERE Name = :newGuid LIMIT 1];

        ci.Sequence_Number__c = 500;

        update ci;      

        Test.StopTest();

        Price_Book__c pb2 = [SELECT Name, Items_Last_Modified__c FROM Price_Book__c WHERE Id=:priceBook.Id];

        //System.debug('before:' + pb1);
        //System.debug('after: ' + pb2);
        System.assert(pb2.Items_Last_Modified__c >= lastTime);
    }      
}