src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Contact/fields/Available_for_Field_Work__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Field_Work__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this field to indicate that the person is available to work in the field. This typically means that they can be assigned to a job or ticket.</description>
    <inlineHelpText>If selected, the user is selectable when adding a job or ticket in FieldFX Mobile. You must select this option if the user needs to use FieldFX Mobile.</inlineHelpText>
    <label>Available for Field Work</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Contact/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the person to a specific catalog item so that this person can be added to a field ticket and the app will automatically lookup the person's catalog item in the ticket's job's price book in order to automatically select the correct price book item to add to the ticket.</description>
    <inlineHelpText>Labor catalog item for the user's job title.</inlineHelpText>
    <label>Job Title from Catalog</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/Crew_Planning__c.object-meta.xml
<CustomObject>
    <label>Crew Planning</label>
    <nameField>
        <displayFormat>JC-{0}</displayFormat>
        <label>Job Crew Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Crew_Planning__c/fields/Crew_Member__c.field-meta.xml
<CustomField>
    <fullName>Crew_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Employee scheduled to work on the job.</inlineHelpText>
    <label>Crew Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the employee is scheduled to work.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Crew_Planning__c/fields/Role_on_Job__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Labor catalog item for the employee's role on the job.</inlineHelpText>
    <label>Role on Job</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Crew Planning</relationshipLabel>
    <relationshipName>Crew_Planning_Role</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Catalog item for the equipment. You must link an equipment record to a catalog item. Equipment records inherit the catalog description and ticket item record type for their linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Equipment2__c.field-meta.xml
<CustomField>
    <fullName>Equipment2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Equipment Planning (Equipment)</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the equipment is scheduled for use.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Job_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Price book item for the equipment.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/FX_Settings__c/FX_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FX Settings</label>
</CustomObject>

src/main/default/objects/FX_Settings__c/fields/AutoAddJobCreatorToCrew__c.field-meta.xml
<CustomField>
    <fullName>AutoAddJobCreatorToCrew__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</description>
    <inlineHelpText>Automatically create a Crew Planning entry for Job creator if this flag is set to true.</inlineHelpText>
    <label>AutoAddJobCreatorToCrew</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/CrewPlanningSkipAssignPriceBookItem__c.field-meta.xml
<CustomField>
    <fullName>CrewPlanningSkipAssignPriceBookItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, skip auto assigning Role_on_Job using Crew Member's (Contact) 'Job Title from Catalog' (Catalog_Item__c) to find related Price Book Item from the Job's Price Book.</description>
    <label>CrewPlanningSkipAssignPriceBookItem</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/FX_Settings__c/fields/EquipmentPlanningSkipAssignPriceBookItem__c.field-meta.xml
<CustomField>
    <fullName>EquipmentPlanningSkipAssignPriceBookItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, skip auto assigning Price Book Item using Equipment's Catalog Item value to find related Price Book Item from the Job's Price Book.</description>
    <label>EquipmentPlanningSkipAssignPriceBookItem</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/JobResourcePlanning_Test.cls
@isTest
private class JobResourcePlanning_Test
{
    static void SetupCrewPlanning(Boolean skipTrigger)
    {
        FX_Settings__c s = FX_Settings__c.getInstance(UserInfo.getUserId());
        s.CrewPlanningSkipAssignPriceBookItem__c = skipTrigger;
        s.AutoAddJobCreatorToCrew__c = false;
        upsert s;

        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        
        List<Price_Book_Item__c> pbiItems =  AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Labor', true);        
        Price_Book_Item__c pbi = pbiItems.get(0); 

        Contact c = AlpineTestHelper.CreateContactWithStandardUser(false);
        c.Available_for_Field_Work__c = true;
        c.Catalog_Item__c = pbi.Catalog_Item__c;
        insert c;

        Contact c2 = AlpineTestHelper.CreateContactWithStandardUser(false);
        c2.Available_for_Field_Work__c = true;
        c2.Catalog_Item__c = pbiItems.get(1).Catalog_Item__c;
        insert c2;


    }

    static void SetupEquipmentPlanning(Boolean skipTrigger)
    {
        FX_Settings__c s = FX_Settings__c.getInstance(UserInfo.getUserId());
        s.EquipmentPlanningSkipAssignPriceBookItem__c = skipTrigger;
        s.AutoAddJobCreatorToCrew__c = false;
        upsert s;

        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        List<Price_Book_Item__c> pbiItems = AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Equipment', true);
        Price_Book_Item__c pbi = pbiItems.get(0);

        Equipment__c e = AlpineTestHelper.CreateEquipment(false);
        e.Catalog_Item__c = pbi.Catalog_Item__c;
        insert e;

        Equipment__c e2 = AlpineTestHelper.CreateEquipment(false);
        e2.Catalog_Item__c = pbiItems.get(1).Catalog_Item__c;
        insert e2;

    }
    static testmethod void CrewPlanningSkipTriggerTest()
    {
        Test.startTest();
        SetupCrewPlanning(true);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        Crew_Planning__c cp = new Crew_Planning__c(Job__c = j.Id, Crew_Member__c = c.Id);
        insert cp;

        Test.stopTest();

        Crew_Planning__c dbItem =  [SELECT Id, Role_on_Job__c FROM Crew_Planning__c WHERE Id =:cp.Id];
        System.assert(String.isBlank(dbItem.Role_on_Job__c), 'Role_on_Job__c should be null instead of ' + dbItem.Role_on_Job__c);

    }

    static testmethod void CrewPlanningSwitchContact_Test()
    {
       
        SetupCrewPlanning(false);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        List<Contact> contacts =  [SELECT Id, Catalog_Item__c FROM Contact];        
        Crew_Planning__c cp = new Crew_Planning__c(Job__c = j.Id, Crew_Member__c = contacts.get(0).Id);
        insert cp;

        Test.startTest();
        Crew_Planning__c dbItem = [SELECT Id, Role_on_Job__c, Crew_Member__c FROM Crew_Planning__c WHERE Id=:cp.Id];
        System.assert(!String.isBlank(dbItem.Role_on_Job__c), 'Role_on_Job__c should not be null');
        dbItem.Crew_Member__c = contacts.get(1).Id;
        update dbItem;
        Test.stopTest();

        Crew_Planning__c dbItem2 = [SELECT Id, Role_on_Job__c, Crew_Member__c FROM Crew_Planning__c WHERE Id=:cp.Id];

        System.debug('before :' + dbItem.Role_on_Job__c);
        System.debug('after :' + dbItem2.Role_on_Job__c);

        System.assert(!String.isBlank(dbItem2.Role_on_Job__c) && dbItem.Role_on_Job__c!=dbItem2.Role_on_Job__c,
            'Role_on_Job__c should have been updated using the new Crew Member\'s Catalog Item ');

    }

    static testmethod void EquipmentPlanningSwitchEquipment_Test()
    {
       
        SetupEquipmentPlanning(false);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        List<Equipment__c> equipItems = [SELECT Id FROM Equipment__c];
        Equipment__c e = equipItems.get(0);
        Equipment_Planning__c ep = new Equipment_Planning__c(Job__c = j.Id, Equipment2__c = e.Id);
        insert ep;

        Test.startTest();

        Equipment_Planning__c dbItem =  [SELECT Id, Equipment2__c, Price_Book_Item__c FROM Equipment_Planning__c WHERE Id =:ep.Id];
        
        System.assert(!String.isBlank(dbItem.Equipment2__c), 'Equipment2__c should not be null');
        dbItem.Equipment2__c = equipItems.get(1).Id;
        update dbItem;
        Test.stopTest();

        Equipment_Planning__c dbItem2 = [SELECT Id, Equipment2__c, Price_Book_Item__c FROM Equipment_Planning__c WHERE Id =:ep.Id];
       
        System.assert(!String.isBlank(dbItem2.Equipment2__c) && dbItem.Price_Book_Item__c!=dbItem2.Price_Book_Item__c,
            'Price_Book_Item__c should have been updated using the new Equipment\'s Catalog Item ');

    }


    static testmethod void CrewPlanningAssignRole_on_JobTest()
    {
        Test.startTest();
        SetupCrewPlanning(false);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        Crew_Planning__c cp = new Crew_Planning__c(Job__c = j.Id, Crew_Member__c = c.Id);
        insert cp;

        Test.stopTest();

        Crew_Planning__c dbItem =  [SELECT Id, Role_on_Job__c FROM Crew_Planning__c WHERE Id =:cp.Id];
        System.assert(!String.isBlank(dbItem.Role_on_Job__c), 'Role_on_Job__c should have value instead of null ');

    }

    static testmethod void EquipmentPlanningSkipTriggerTest()
    {
        Test.startTest();
        SetupEquipmentPlanning(true);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        Equipment__c e = [SELECT Id FROM Equipment__c LIMIT 1];
        Equipment_Planning__c ep = new Equipment_Planning__c(Job__c = j.Id, Equipment2__c = e.Id);
        insert ep;

        Test.stopTest();

        Equipment_Planning__c dbItem =  [SELECT Id, Price_Book_Item__c FROM Equipment_Planning__c WHERE Id =:ep.Id];
        System.assert(String.isBlank(dbItem.Price_Book_Item__c), 'Price_Book_Item__c should be null instead of ' + dbItem.Price_Book_Item__c);

    }

    static testmethod void EquipmentPlanningAssignRole_on_JobTest()
    {
        Test.startTest();
        SetupEquipmentPlanning(false);

        Job__c j = [SELECT Id FROM Job__c LIMIT 1];
        Equipment__c e = [SELECT Id FROM Equipment__c LIMIT 1];
        Equipment_Planning__c ep = new Equipment_Planning__c(Job__c = j.Id, Equipment2__c = e.Id);
        insert ep;

        Test.stopTest();

        Equipment_Planning__c dbItem =  [SELECT Id, Price_Book_Item__c FROM Equipment_Planning__c WHERE Id =:ep.Id];
        System.assert(!String.isBlank(dbItem.Price_Book_Item__c), 'Price_Book_Item__c should have value instead of null ');

    }

   
}