src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Catalog item for the equipment. You must link an equipment record to a catalog item. Equipment records inherit the catalog description and ticket item record type for their linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Parent_Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book item for the price book item. When a price book item has a parent, the parent gets added automatically to every ticket where the price book item is added.</inlineHelpText>
    <label>Parent Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Child Price Book Items</relationshipLabel>
    <relationshipName>Child_Price_Book_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Requires_Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Requires_Parent_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If selected, the item and its parent price book item get added automatically to all new tickets.</inlineHelpText>
    <label>Requires Parent Item</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Quote__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote__c/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Parent_Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent item for the quote item. When you add a parent item to a quote, any designated child items also get added. You cannot add child items to quotes individually without adding their parent first.</inlineHelpText>
    <label>Parent Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>Quote on which the item was added.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Equipment record linked to the ticket item.</inlineHelpText>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/classes/ItemHandler.cls
public class ItemHandler
{
  public static String CreateItemUsingExactMatch(String processStr) {
    JSONParser parser = JSON.createParser(processStr);
    Type resultType = Type.forName('ItemHandler.CreateItemUsingExactMatchRequest');
    ItemHandler.CreateItemUsingExactMatchRequest readValueAsResults = (ItemHandler.CreateItemUsingExactMatchRequest)parser.readValueAs(resultType);

    CreateItemUsingExactMatchResult result = CreateItemUsingExactMatch(readValueAsResults);

    return JSON.serializePretty(result, false);
  }

  private static string GetTicketItemsFilterSoql(SiblingFilter siblingFilter) {
    TicketItemsFetch.TktItemsFilterResponse tktItemFilter = new TicketItemsFetch.TktItemsFilterResponse();

    tktItemFilter.keyword = siblingFilter.keyword;
    tktItemFilter.itemType = siblingFilter.itemType;
    tktItemFilter.classification = siblingFilter.classification;
    tktItemFilter.itemLimit = siblingFilter.itemLimit;
    tktItemFilter.itemOffset = siblingFilter.itemOffset;
    tktItemFilter.sortby = siblingFilter.sortby;
    tktItemFilter.sortdir = siblingFilter.sortdir;

    return TicketItemsFetch.GetFilterSoql(tktItemFilter);
  }

  private static string GetQuoteItemsFilterSoql(SiblingFilter siblingFilter) {
    QuoteItemsFetch.QtItemsFilterResponse qtItemFilter = new QuoteItemsFetch.QtItemsFilterResponse();

    qtItemFilter.keyword = siblingFilter.keyword;
    qtItemFilter.itemType = siblingFilter.itemType;
    qtItemFilter.classification = siblingFilter.classification;
    qtItemFilter.itemLimit = siblingFilter.itemLimit;
    qtItemFilter.itemOffset = siblingFilter.itemOffset;
    qtItemFilter.sortby = siblingFilter.sortby;
    qtItemFilter.sortdir = siblingFilter.sortdir;

    return QuoteItemsFetch.GetFilterSoql(qtItemFilter);
  }

  public static CreateItemUsingExactMatchResult CreateItemUsingExactMatch(CreateItemUsingExactMatchRequest request) {
    String pricebookId = request.pricebookId;
    String fieldPbi = request.fieldPbi;
    String fieldEq = request.fieldEq;
    String fieldValue = request.fieldValue;
    Decimal nextSeqNumber = request.nextSeqNumber;
    String objType = request.objType;
    String picklistFields = request.picklistFields;

    if (!picklistFields.contains('LastModifiedDate')) {
        picklistFields += ', LastModifiedDate';
    }

    String ns = StringUtility.FXNamespace();

    List<Price_Book_Item__c> sourcePBIs = new List<Price_Book_Item__c>();
    CreateItemUsingExactMatchResult result = new CreateItemUsingExactMatchResult();
    result.errorMessage = '';
    result.error = false;

    List<Price_Book_Item__c> pbis = new List<Price_Book_Item__c>();
    List<Equipment__c> eqs = new List<Equipment__c>();

    if (fieldPbi!='') {
      String pbiSoql = 'SELECT Id, Requires_Parent_Item__c, Parent_Price_Book_Item__c FROM '+ns+'Price_Book_Item__c WHERE isDeleted=false AND Price_Book__c=:pricebookId AND ' +fieldPbi+ ' = ' + '\'' +fieldValue+'\' LIMIT 2';
      pbis = (List<Price_Book_Item__c>)Database.query(pbiSoql);
    }

    if(pbis.IsEmpty()) {
      if (fieldEq!='') {
        String eqSoql = 'SELECT Id, Catalog_Item__c FROM '+ns+'Equipment__c WHERE isDeleted=false AND ' +fieldEq+ ' = ' + '\'' +fieldValue+'\' LIMIT 2';
        eqs = (List<Equipment__c>)Database.query(eqSoql);

        if(eqs.IsEmpty()) {
          if (fieldPbi!='') {
            result.errorMessage = 'Item not found: [Price_Book_Item__c.'+fieldPbi+']: '+fieldValue+', [Equipment__c.'+fieldEq+']: '+fieldValue;
            result.error = true;
          } else {
            result.errorMessage = 'Item not found: [Equipment__c.'+fieldEq+']: '+fieldValue;
            result.error = true;
          }
        } else if(eqs.size()>1) {
          result.errorMessage = 'Too many Equipment items found: [Equipment__c.'+fieldEq+']: '+fieldValue;
          result.error = true;
        } else {
          System.debug(eqs);
          System.debug(eqs.size());

          if (eqs[0].Catalog_Item__c==null) {
            result.errorMessage = 'Item found: [Equipment__c.'+fieldEq+']: '+fieldValue+'. Catalog_Item__c not set.';
            result.error = true;
          } else {
            List<Catalog_Item__c> catalogItem = [SELECT Name FROM Catalog_Item__c WHERE Id=:eqs[0].Catalog_Item__c LIMIT 1];

            List<Price_Book_item__c> eqpbis = [SELECT Id FROM Price_Book_item__c WHERE IsDeleted=false AND Price_Book__c=:pricebookId AND Catalog_Item__c=:eqs[0].Catalog_Item__c LIMIT 1];

            if (eqpbis.isEmpty()) {
              result.errorMessage = 'Item found: [Equipment__c.'+fieldEq+']: '+fieldValue+'. Catalog_Item__c not valid for this Job\'s Pricebook: ['+eqs[0].Catalog_Item__c+' - '+catalogItem[0].Name+']';
              result.error = true;
            } else if (eqpbis.size()>1) {
              result.errorMessage = 'Item found: [Equipment__c.'+fieldEq+']: '+fieldValue+'. Too many matching Catalog_Item__c in this Job\'s Pricebook: ['+eqs[0].Catalog_Item__c+' - '+catalogItem[0].Name+']';
              result.error = true;
            } else {
              sourcePBIs.add(eqpbis[0]);

              for(Price_Book_item__c pbiChild : [SELECT Id, Parent_Price_Book_Item__c FROM Price_Book_item__c WHERE IsDeleted=false AND Parent_Price_Book_Item__c=:eqpbis[0].Id]) {
                sourcePBIs.add(pbiChild);
              }

              if (objType == 'Ticket_Item__c') {
                result = CreateNewTktItems(request, sourcePBIs, nextSeqNumber, eqs[0].Id);
              } else if (objType == 'Quote_Item__c') {
                result = CreateNewQtItems(request, sourcePBIs, nextSeqNumber, eqs[0].Id);
              }
            }
          }
        }
      } else {
        result.errorMessage = 'Item not found: [Price_Book_Item__c.'+fieldPbi+']: '+fieldValue;
        result.error = true;
      }
    } else if(pbis.size()>1) {
      result.errorMessage = 'Too many Price Book Items found: [Price_Book_Item__c.'+fieldPbi+']: '+fieldValue;
      result.error = true;
    } else {
      Price_Book_Item__c pbi = pbis[0];
      if (pbi.Requires_Parent_Item__c || pbi.Parent_Price_Book_Item__c != null) {
        result.errorMessage = 'Price Book Item is configured as a child item: [Price_Book_Item__c.'+fieldPbi+']: '+fieldValue;
        result.error = true;
      }
      else {
        sourcePBIs.add(pbi);

        for(Price_Book_item__c pbiChild : [SELECT Id, Parent_Price_Book_Item__c FROM Price_Book_item__c WHERE IsDeleted=false AND Parent_Price_Book_Item__c=:pbi.Id]) {
          sourcePBIs.add(pbiChild);
        }

        System.debug(sourcePBIs);

        if (objType == 'Ticket_Item__c') {
          result = CreateNewTktItems(request, sourcePBIs, nextSeqNumber, null);
        } else if (objType == 'Quote_Item__c') {
          result = CreateNewQtItems(request, sourcePBIs, nextSeqNumber, null);
        }
      }
    }

    return result;
  }

  public static CreateItemUsingExactMatchResult CreateNewTktItems(CreateItemUsingExactMatchRequest request, List<Price_Book_Item__c> sourcePBIs, Decimal nextSeqNumber, Id eqId) {
    String ns = StringUtility.FXNamespace();

    String ticketId = request.tktId;
    String parentFields = request.parentFields;
    String siblingFields = request.siblingFields;
    if (!parentFields.contains('LastModifiedDate')) {
        parentFields += ', LastModifiedDate';
    }
    if (!siblingFields.contains('LastModifiedDate')) {
        siblingFields += ', LastModifiedDate';
    }

    CreateItemUsingExactMatchResult result = new CreateItemUsingExactMatchResult();
    result.errorMessage = '';
    result.error = false;

    List<Id> sourceIds = new List<Id>();
    sourceIds.add(sourcePBIs[0].Id);
    List<sObject> newItems = (List<sObject>) TicketItemHandler.CreateTicketItems(ticketId, sourceIds, nextSeqNumber, null);
    List<Ticket_Item__c> newTktItems = [SELECT Id, Equipment__c FROM Ticket_Item__c WHERE Id=:newItems[0].Id];

    if (eqId != null) {
      newTktItems[0].Equipment__c = eqId;
      Database.update(newTktItems);
    }

    newTktItems = [SELECT Id, Equipment__c FROM Ticket_Item__c WHERE Id=:newItems[0].Id];
    result.newItems = newTktItems;

    sourceIds = new List<Id>();
    for(Price_Book_Item__c pbi : sourcePBIs) {
      if (pbi.Parent_Price_Book_Item__c!=null) {
        sourceIds.add(pbi.Id);
      }
    }

    if (sourceIds.size()>0) {
      newItems = (List<sObject>) TicketItemHandler.CreateTicketItems(ticketId, sourceIds, nextSeqNumber, newTktItems[0].Id);
      newTktItems = [SELECT Id, Equipment__c FROM Ticket_Item__c WHERE Id in :newItems];
      result.newItems.addAll((List<SObject>)newTktItems);
    }

    String siblingFilterSoql = GetTicketItemsFilterSoql(request.siblingFilter);

    String soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Parent_Ticket_Item__c = NULL AND Ticket__c=:ticketId {2}',
      new String[]{siblingFields, ns+'Ticket_Item__c', siblingFilterSoql});
    result.rootItems = Database.query(soql);
    soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Parent_Ticket_Item__c != NULL AND Ticket__c=:ticketId {2}',
      new String[]{siblingFields, ns+'Ticket_Item__c', siblingFilterSoql});
    result.childItems = Database.query(soql);
    soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Id=:ticketId', new String[]{parentFields, ns+'Ticket__c'});
    result.parent = Database.query(soql);

    return result;
  }

  public static CreateItemUsingExactMatchResult CreateNewQtItems(CreateItemUsingExactMatchRequest request, List<Price_Book_Item__c> sourcePBIs, Decimal nextSeqNumber, Id eqId) {
    String ns = StringUtility.FXNamespace();

    String quoteId = request.qtId;
    String parentFields = request.parentFields;
    String siblingFields = request.siblingFields;
    if (!parentFields.contains('LastModifiedDate')) {
        parentFields += ', LastModifiedDate';
    }
    if (!siblingFields.contains('LastModifiedDate')) {
        siblingFields += ', LastModifiedDate';
    }

    CreateItemUsingExactMatchResult result = new CreateItemUsingExactMatchResult();
    result.errorMessage = '';
    result.error = false;

    Quote_Item__c newQt = new Quote_Item__c(Quote__c = quoteId, Price_Book_Item__c = sourcePBIs[0].Id); //create parent quote item
    insert newQt;

    List<Quote_Item__c> newQtItems = [SELECT Id FROM Quote_Item__c WHERE Id=:newQt.Id LIMIT 1];

    Boolean quoteHasEqField = CheckQuoteHasEqField();
    System.debug(quoteHasEqField);
    if (quoteHasEqField && eqId != null) {
      newQtItems[0].put('Equipment__c', eqId);
      Database.update(newQtItems);
    }

    newQtItems = [SELECT Id FROM Quote_Item__c WHERE Id=:newQt.Id LIMIT 1];
    result.newItems = newQtItems;

    String siblingFilterSoql = GetQuoteItemsFilterSoql(request.siblingFilter);

    String soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Parent_Quote_Item__c = NULL AND Quote__c=:quoteId {2}',
      new String[]{siblingFields, ns+'Quote_Item__c', siblingFilterSoql});
    result.rootItems = Database.query(soql);
    soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Parent_Quote_Item__c != NULL AND Quote__c=:quoteId {2}',
      new String[]{siblingFields, ns+'Quote_Item__c', siblingFilterSoql});
    result.childItems = Database.query(soql);

    soql = String.format('SELECT {0} FROM {1} WHERE IsDeleted=false AND Id=:quoteId', new String[]{parentFields, ns+'Quote__c'});
    result.parent = Database.query(soql);

    return result;
  }

  public static Boolean CheckQuoteHasEqField() {
  System.debug(JSON.serializePretty(Quote_Item__c.getSobjectType().getDescribe().fields.getMap().keySet(), false));
    return Quote_Item__c.getSobjectType().getDescribe().fields.getMap().keySet().contains('Equipment__c') ||
            Quote_Item__c.getSobjectType().getDescribe().fields.getMap().keySet().contains('equipment__c');
  }

  public class CreateItemUsingExactMatchRequest {
    public Id tktId;
    public Id qtId;
    public String pricebookId;
    public String fieldPbi;
    public String fieldEq;
    public String fieldValue;
    public Decimal nextSeqNumber;
    public String objType;
    public String parentFields;
    public String siblingFields;
    public String picklistFields;
    public SiblingFilter siblingFilter;
  }

  public class SiblingFilter {
    public string keyword;
    public string itemType;
    public string classification;
    public string itemLimit;
    public string itemOffset;
    public string sortby;
    public string sortdir;
  }

  public class CreateItemUsingExactMatchResult {
    public String errorMessage;
    public Boolean error;
    public List<sObject> newItems;
    public List<sObject> rootItems;
    public List<sObject> childItems;
    public List<sObject> parent;
  }

}