src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/CatalogItemPriceBook__c.object-meta.xml
<CustomObject>
    <description>Track the Price Books where Catalog Item is used</description>
    <label>CatalogItemPriceBook</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>CatalogItemPriceBook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CatalogItemPriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/IsDirty__c.field-meta.xml
<CustomField>
    <fullName>IsDirty__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag item for processing</description>
    <label>IsDirty</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/PriceBookIsActive__c.field-meta.xml
<CustomField>
    <fullName>PriceBookIsActive__c</fullName>
    <formula>Price_Book__r.Is_Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PriceBookIsActive</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(!IsArchived__c &amp;&amp; Effective_Date__c &lt;=TODAY() &amp;&amp; (ISNULL(Expiration_Date__c) || (Expiration_Date__c >=TODAY())) &amp;&amp; (ISBLANK(Account__c) || !Account__r.IsArchived__c), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether users can select the price book for a job. Users cannot select a price book for a job if the current date is before the "Effective Date", the current date is after the "Expiration Date", or "Archived" is selected.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Price_Book_Index__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Price_Book_Index__c</fullName>
    <label>Catalog Price Book Index</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/CatalogItemPriceBook__c.field-meta.xml
<CustomField>
    <fullName>CatalogItemPriceBook__c</fullName>
    <formula>CASESAFEID( Catalog_Item__c) + CASESAFEID(Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CatalogItemPriceBook</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/CatalogItemPriceBookBatcher.cls
public class CatalogItemPriceBookBatcher extends FXBatchableBase implements Database.Stateful
{    
    Set<Id> priceBookIds { get; set; }   
    Set<Id> catalogItemIds {get;set;}
    
    Map<Id, String> catalogItemPriceBookIndex {get;set;}

    List<CatalogItemPriceBook__c> catalogItemPriceBookEntries {get;set;}

    Set<Id> dirtyCatalogItemIds {get;set;}

    @TestVisible
    enum OperType {  
        ProcessCatalogItemPriceBook,
        FlagIsDirty
    }

    OperType opType { get; set; }

    static Integer catalogItemBatchSize = 1000;         
    
    public static void FlagIsDirty(Set<Id> priceBookIds)
    { 
        String soql = String.format('SELECT Id, {0}IsDirty__c, {0}Catalog_Item__c, {0}Price_Book__c FROM {0}CatalogItemPriceBook__c WHERE IsDeleted=false AND {0}Price_Book__c IN :priceBookIds AND {0}IsDirty__c=false',
                    new String[]{StringUtility.FXNamespace()});

        Integer rowCountLimit = Limits.getLimitDMLRows() - Limits.getDMLRows();
        String soqlQuery = soql + ' LIMIT ' + rowCountLimit;

        System.debug('FlagIsDirty soql=' + soqlQuery);

        List<CatalogItemPriceBook__c> items = (List<CatalogItemPriceBook__c>)Database.query(soqlQuery);

        System.debug('soql results count: ' + items.size());
        Set<Id> dirtyIds = new Set<Id>();
        List<CatalogItemPriceBook__c> itemsToUpdate = new List<CatalogItemPriceBook__c>();
        for(CatalogItemPriceBook__c o : items)
        {   
            if(dirtyIds.contains(o.Catalog_Item__c)) continue;
            o.IsDirty__c = true;            
            itemsToUpdate.add(o);
            dirtyIds.add(o.Catalog_Item__c);
        }
        if(!itemsToUpdate.isEmpty())
        {
            update itemsToUpdate;
        }

        if(items.size() == rowCountLimit)
        {
            CatalogItemPriceBookBatcher b = new CatalogItemPriceBookBatcher(soql, OperType.FlagIsDirty);
            b.priceBookIds = priceBookIds;
            Database.executeBatch(b); 
        }
        else
        {
            ScheduleRefreshPriceBookIndex(0);
        }
    }

    @TestVisible
    private CatalogItemPriceBookBatcher(String soql, OperType opt)
    {
        soqlQuery = soql;   
        opType = opt; 
        
        catalogItemPriceBookIndex = new Map<Id, String>();
        if(opt == OperType.FlagIsDirty)
        {
            dirtyCatalogItemIds = new Set<Id>();
        }
    }

    public static void ProcessCatalogItemPriceBook()
    {
        Database.executeBatch(new CatalogItemPriceBookBatcher());
    }

    public static void ScheduleRefreshPriceBookIndex(Integer delayInMintues)
    {
        Integer count = [SELECT COUNT() FROM CronTrigger WHERE CronJobDetail.Name LIKE 'Refresh CatalogItem PriceBook Index%'];
        if(count==0)
        {
            count = [SELECT COUNT() FROM AsyncApexJob WHERE ApexClass.Name='CatalogItemPriceBookBatcher' AND Status IN ('Holding', 'Queued', 'Preparing', 'Processing')];
        }
        if(count !=0) 
        {
            System.debug('Either CatalogItemPriceBookBatcher is running or a Refresh CatalogItem PriceBook Index job has been scheduled.');
            return;
        }
        if(delayInMintues<=0)
        {
            Database.executeBatch(new CatalogItemPriceBookBatcher());
        }
        else
        {
           String jobName = 'Refresh CatalogItem PriceBook Index - ' + Datetime.now().getTime();
           System.scheduleBatch(new CatalogItemPriceBookBatcher(), jobName, delayInMintues); 
        }
    }
    
    public CatalogItemPriceBookBatcher()
    {
        opType = OperType.ProcessCatalogItemPriceBook;

        catalogItemPriceBookEntries = [SELECT Catalog_Item__c FROM CatalogItemPriceBook__c WHERE IsDeleted=false AND IsDirty__c = true ORDER BY Catalog_Item__c LIMIT :catalogItemBatchSize];

        catalogItemPriceBookIndex = new Map<Id, String>();
         
        catalogItemIds = new Set<Id>();
        for(CatalogItemPriceBook__c o : catalogItemPriceBookEntries)
        {
            catalogItemIds.add(o.Catalog_Item__c);
        }
        String ns = StringUtility.FXNamespace(); 

        String catalogItemFilter = String.format(' AND {0}Catalog_Item__c IN :catalogItemIds', new String[]{ns});

        soqlQuery =  String.format('SELECT {0}Price_Book__c, {0}Catalog_Item__c FROM {0}Price_Book_Item__c WHERE IsDeleted=false AND {0}Price_Book__r.{0}Is_Active__c=true {1} ORDER BY {0}Catalog_Item__c', 
                new String[]{ns, catalogItemFilter});        
    }
    

    public override Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(soqlQuery);
    }

    public override void execute(Database.BatchableContext BC, List<sObject> scope)
    {   
        if(opType == OperType.ProcessCatalogItemPriceBook)      
        {           
            List<Price_Book_Item__c> items = (List<Price_Book_Item__c>)scope;
            Set<Id> catalogItemIds = new Set<Id>();
            if(catalogItemPriceBookIndex == null)
            {
                catalogItemPriceBookIndex = new Map<Id, String>();

            }
            for(Price_Book_Item__c pbi : items)
            {
                if(catalogItemPriceBookIndex.containsKey(pbi.Catalog_Item__c)) continue;
                catalogItemIds.add(pbi.Catalog_Item__c);
            }
            
            for(Catalog_Item__c ci : [SELECT Id, (SELECT Price_Book__c FROM CatalogItemPriceBooks__r WHERE IsDeleted=false AND PriceBookIsActive__c=true) FROM Catalog_Item__c WHERE IsDeleted=false AND Id IN :catalogItemIds])
            {
                Set<Id> priceBookIds = new Set<Id>();
                for(CatalogItemPriceBook__c o : ci.CatalogItemPriceBooks__r)
                {
                    priceBookIds.add(o.Price_Book__c);
                }
                catalogItemPriceBookIndex.put(ci.Id, String.join(new List<Id>(priceBookIds), ','));
            }
            for(Price_Book_Item__c pbi : items)
            {
                pbi.Catalog_Price_Book_Index__c = catalogItemPriceBookIndex.get(pbi.Catalog_Item__c);
            }
            update items;
        }
        else if(opType == OperType.FlagIsDirty)
        {
            List<CatalogItemPriceBook__c> items = (List<CatalogItemPriceBook__c>)scope;
            List<CatalogItemPriceBook__c> dirtyItems = new List<CatalogItemPriceBook__c>();
            for(CatalogItemPriceBook__c o : items)
            {
                if(dirtyCatalogItemIds.contains(o.Catalog_Item__c)) continue;
                o.IsDirty__c = true;
                dirtyCatalogItemIds.add(o.Catalog_Item__c);
                dirtyItems.add(o);
            }
            if(!dirtyItems.isEmpty())
            {
                update dirtyItems;
            }
        }
    } 
    
    public override void finish(Database.BatchableContext BC)
    {       
        if(opType == OperType.FlagIsDirty)     
        {
            ScheduleRefreshPriceBookIndex(0);
        }            
        else if(opType == OperType.ProcessCatalogItemPriceBook)
        {
            for(CatalogItemPriceBook__c o: catalogItemPriceBookEntries)
            {
                o.IsDirty__c = false;
            }
            Database.update(catalogItemPriceBookEntries, false);
            if(catalogItemPriceBookEntries.size() == CatalogItemBatchSize)
            {
                Database.executeBatch(new CatalogItemPriceBookBatcher());
            }
        }      
    }     
}