src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Catalog_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is used to order the items in the catalog in something other than alphabetical order.</description>
    <inlineHelpText>Number used to determine the order in which the item displays in catalog item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Catalog item for the equipment. You must link an equipment record to a catalog item. Equipment records inherit the catalog description and ticket item record type for their linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Equipment2__c.field-meta.xml
<CustomField>
    <fullName>Equipment2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Equipment Planning (Equipment)</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the equipment is scheduled for use.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Job_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Price book item for the equipment.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Parent_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book for the price book. When a price book has a parent, you can select items from its parent price book when building tickets.</inlineHelpText>
    <label>Parent Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Default quantity added when adding the item to a ticket.</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Included_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Included_Quantity__c</fullName>
    <inlineHelpText>Quantity of the price book item given to the customer at no charge.</inlineHelpText>
    <label>Included Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/EquipmentPlanning_Test.cls
@isTest
private class EquipmentPlanning_Test
{
    static TestMethod void InsertWithValidPriceBookItem_Test()
    {
        Test.startTest();
        Job__c j1 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j2 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j3 = AlpineTestHelper.CreateJobs(1, true).get(0);

        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);
        Price_Book_Item__c pbi = AlpineTestHelper.CreatePriceBookItems(1, j1.Price_Book__c, 'Equipment').get(0);

        Equipment_Planning__c ep = new Equipment_Planning__c(Equipment2__c = equip.Id, Job__c = j1.Id, Price_Book_Item__c = pbi.Id);
        insert ep;
        Test.stopTest();
        List<Equipment_Planning__c> items = [SELECT Id FROM Equipment_Planning__c WHERE Equipment2__c =: equip.Id];
        System.assert(items.size()==1, 'Should have one Equipment_Planning__c entry');
    }


    static TestMethod void DifferentPriceBookPriceBookItem_Test()
    {
        Test.startTest();
        Job__c j1 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j2 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j3 = AlpineTestHelper.CreateJobs(1, true).get(0);

        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);
        Price_Book_Item__c pbi = AlpineTestHelper.CreatePriceBookItems(1, j2.Price_Book__c, 'Equipment').get(0);

        Equipment_Planning__c ep = new Equipment_Planning__c(Equipment2__c = equip.Id, Job__c = j1.Id, Price_Book_Item__c = pbi.Id);

        String msg= '';
        try
        {
            Database.insert(ep);
        }
        catch(System.DmlException e)
        {
            
            for (Integer i = 0; i < e.getNumDml(); i++) {
                msg += ' | ' + e.getDmlMessage(i); 
            }
            
        }
        
        Test.stopTest();
        
        System.debug(msg);

        System.assert(msg.indexOf('Price Book Item must be from the Job\'s Price Book')>=0, 'Should error out with msg: "Price Book Item must be from the Job\'s Price Book", instead of "' + msg + '"');

        List<Equipment_Planning__c> items = [SELECT Id FROM Equipment_Planning__c WHERE Equipment2__c =: equip.Id];
        System.assert(items.size()==0, 'Should have one Equipment_Planning__c entry');
    }

    static TestMethod void SkipJobPriceBookPriceBookItem_Test()
    {
        Test.startTest();
        Job__c j1 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j2 = AlpineTestHelper.CreateJobs(1, false).get(0);

        if(EquipmentPlanningHandler.HasColumnEnableExtendedPricing)
        {
            j2.put(EquipmentPlanningHandler.EnableExtendedPricingColumnName, true);
        }
        insert j2;

        Map<Id, Price_Book__c> pbMap = new Map<Id, Price_Book__c>([SELECT Id FROM Price_Book__c]);

        Price_Book__c pbChild = pbMap.get(j2.Price_Book__c);
        pbChild.Parent_Price_Book__c = j1.Price_Book__c;
        update pbChild;

        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);
        Price_Book_Item__c pbiOnChildPriceBook = AlpineTestHelper.CreatePriceBookItems(1, j2.Price_Book__c, 'Equipment').get(0);


        Price_Book_Item__c pbiOnParentPriceBook = new Price_Book_Item__c(Price_Book__c = j1.Price_Book__c, Price__c=500, 
            Sequence_Number__c =1, Discount_Percent__c=0.123, Default_Quantity__c=1096, 
            Included_Quantity__c=0, Catalog_Item__c=pbiOnChildPriceBook.Catalog_Item__c);
        
        insert pbiOnParentPriceBook;

        Equipment_Planning__c ep = new Equipment_Planning__c(Equipment2__c = equip.Id, Job__c = j2.Id, 
            Price_Book_Item__c = pbiOnParentPriceBook.Id);

        String msg= '';
        try
        {
            Database.insert(ep);
        }
        catch(System.DmlException e)
        {
            
            for (Integer i = 0; i < e.getNumDml(); i++) {
                msg += ' | ' + e.getDmlMessage(i); 
            }
            
        }
        
        Test.stopTest();

        if(!EquipmentPlanningHandler.HasColumnEnableExtendedPricing)
        {
            System.assert(msg.indexOf('Price Book Item must be from the Job\'s Price Book')>=0, 'Should error out with msg: "Price Book Item must be from the Job\'s Price Book", instead of "' + msg + '"');
        }
        else
        {
            System.assert(msg.indexOf('Price Book Item must be from the Job\'s or the nearest upper level Price Book')>=0, 
                    'Should error out with msg: Price Book Item must be from the Job\'s or the nearest upper level Price Book');
        }
        List<Equipment_Planning__c> items = [SELECT Id FROM Equipment_Planning__c WHERE Equipment2__c =: equip.Id];
        System.assert(items.size()==0, 'Should have no Equipment_Planning__c entry');
    }


    static TestMethod void ParentPriceBookPriceBookItem_Test()
    {
        Test.startTest();
        Job__c j1 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j2 = AlpineTestHelper.CreateJobs(1, false).get(0);

        if(EquipmentPlanningHandler.HasColumnEnableExtendedPricing)
        {
            j2.put(EquipmentPlanningHandler.EnableExtendedPricingColumnName, true);
        }
        insert j2;

        Map<Id, Price_Book__c> pbMap = new Map<Id, Price_Book__c>([SELECT Id FROM Price_Book__c]);

        Price_Book__c pbChild = pbMap.get(j2.Price_Book__c);
        pbChild.Parent_Price_Book__c = j1.Price_Book__c;
        update pbChild;

        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);

        Price_Book_Item__c pbi = AlpineTestHelper.CreatePriceBookItems(1, j1.Price_Book__c, 'Equipment').get(0);

        Equipment_Planning__c ep = new Equipment_Planning__c(Equipment2__c = equip.Id, Job__c = j2.Id, 
            Price_Book_Item__c = pbi.Id);

        String msg= '';
        try
        {
            Database.insert(ep);
        }
        catch(System.DmlException e)
        {
            
            for (Integer i = 0; i < e.getNumDml(); i++) {
                msg += ' | ' + e.getDmlMessage(i); 
            }               
        }
        
        Test.stopTest();

        List<Equipment_Planning__c> items = [SELECT Id FROM Equipment_Planning__c WHERE Equipment2__c =: equip.Id];
        if(!EquipmentPlanningHandler.HasColumnEnableExtendedPricing)
        {
            System.assert(msg.indexOf('Price Book Item must be from the Job\'s Price Book')>=0, 'Should error out with msg: "Price Book Item must be from the Job\'s Price Book", instead of "' + msg + '"');

        }
        else
        {
            System.assert(msg.indexOf('Price Book Item must be from the Job\'s Price Book')>=0, 'Should error out with msg: "Price Book Item must be from the Job\'s Price Book", instead of "' + msg + '"');

        }
    }


    static TestMethod void UpdatePriceBookItem_Test()
    {
        Test.startTest();
        Job__c j1 = AlpineTestHelper.CreateJobs(1, true).get(0);
        Job__c j2 = AlpineTestHelper.CreateJobs(1, false).get(0);

        if(EquipmentPlanningHandler.HasColumnEnableExtendedPricing)
        {
            j2.put(EquipmentPlanningHandler.EnableExtendedPricingColumnName, true);
        }
        insert j2;

        Map<Id, Price_Book__c> pbMap = new Map<Id, Price_Book__c>([SELECT Id FROM Price_Book__c]);

        Price_Book__c pbChild = pbMap.get(j2.Price_Book__c);
        pbChild.Parent_Price_Book__c = j1.Price_Book__c;
        update pbChild;

        Equipment__c equip = AlpineTestHelper.CreateEquipment(true);

        Price_Book_Item__c pbi1 = AlpineTestHelper.CreatePriceBookItems(1, j1.Price_Book__c, 'Equipment').get(0);
        Price_Book_Item__c pbi2 = AlpineTestHelper.CreatePriceBookItems(1, j2.Price_Book__c, 'Equipment').get(0);

        Equipment_Planning__c ep = new Equipment_Planning__c(Equipment2__c = equip.Id, Job__c = j1.Id, 
            Price_Book_Item__c = pbi1.Id);

        String msg= '';
        try
        {
            Database.insert(ep);
        }
        catch(System.DmlException e)
        {
            
            for (Integer i = 0; i < e.getNumDml(); i++) {
                msg += ' | ' + e.getDmlMessage(i); 
            }               
        }

        Equipment_Planning__c dbItem = [SELECT Id FROM Equipment_Planning__c WHERE Id=:ep.Id];
        dbItem.Job__c = j2.Id;
        dbItem.Price_Book_Item__c = pbi2.Id;
        update dbItem;
        
        Test.stopTest();

        List<Equipment_Planning__c> items = [SELECT Id FROM Equipment_Planning__c WHERE Equipment2__c =: equip.Id];
        System.assert(items.size()==1, 'Should have one Equipment_Planning__c entry, instead of ' + items.size());
    }


}