src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/CatalogItemPriceBook__c.object-meta.xml
<CustomObject>
    <description>Track the Price Books where Catalog Item is used</description>
    <label>CatalogItemPriceBook</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>CatalogItemPriceBook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CatalogItemPriceBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/CatalogItemPriceBook__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/CatalogItemPriceBook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>CatalogItemPriceBooks</relationshipLabel>
    <relationshipName>CatalogItemPriceBooks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/Equipment_Planning__c.object-meta.xml
<CustomObject>
    <description>This object tracks the actual equipment that is scheduled on the job.  It will eventually be used to track non-job locations for equipment as well such as repair shops or inspection facilities.</description>
    <label>Equipment Planning</label>
    <nameField>
        <displayFormat>JE-{0}</displayFormat>
        <label>Equipment Planning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Equipment_Planning__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Job on which the equipment is scheduled for use.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Job_Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Equipment_Planning__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Price book item for the equipment.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Equipment Planning</relationshipLabel>
    <relationshipName>Equipment_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(!IsArchived__c &amp;&amp; Effective_Date__c &lt;=TODAY() &amp;&amp; (ISNULL(Expiration_Date__c) || (Expiration_Date__c >=TODAY())) &amp;&amp; (ISBLANK(Account__c) || !Account__r.IsArchived__c), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates whether users can select the price book for a job. Users cannot select a price book for a job if the current date is before the "Effective Date", the current date is after the "Expiration Date", or "Archived" is selected.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book__c/fields/Parent_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Parent_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent price book for the price book. When a price book has a parent, you can select items from its parent price book when building tickets.</inlineHelpText>
    <label>Parent Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/CatalogItemPriceBook__c.field-meta.xml
<CustomField>
    <fullName>CatalogItemPriceBook__c</fullName>
    <formula>CASESAFEID( Catalog_Item__c) + CASESAFEID(Price_Book__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CatalogItemPriceBook</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/EquipmentPlanningHandler.cls
public class EquipmentPlanningHandler 
{
    public static String EnableExtendedPricingColumnName
    {
        get { return 'Enable_Extended_Pricing__c';}
    }

    public static String EnableExtendedPricingColumnNameLowercase
    {
        get { return 'enable_extended_pricing__c';}
    }

    public static Boolean HasColumnEnableExtendedPricing
    {
        get
        {
            if(EnableExtendedPricingFlag<0)
            {
                EnableExtendedPricingFlag = Job__c.sObjectType.getDescribe().fields.getMap().keySet().contains(EnableExtendedPricingColumnNameLowercase)? 1 : 0;
            }
            return EnableExtendedPricingFlag==1;
        }
    }
    Static Integer EnableExtendedPricingFlag = -1;

    public static void ValidateSourcePriceBook(List<Equipment_Planning__c> items, Map<Id, Equipment_Planning__c> oldmap)
    {
        Set<Id> jobIds = new Set<Id>();
        Set<Id> priceBookItemIds = new Set<Id>();

        List<Equipment_Planning__c> itemsOfInterest = new List<Equipment_Planning__c>();
        for(Equipment_Planning__c o : items)
        {
            if(String.isBlank(o.Job__c) || String.isBlank(o.Price_Book_Item__c)) continue;
            
            if(oldmap!=null)
            {
                Equipment_Planning__c prev = oldmap.get(o.Id);
                if(o.Job__c == prev.Job__c && o.Price_Book_Item__c == prev.Price_Book_Item__c) continue;
            }
            itemsOfInterest.add(o);    
            jobIds.add(o.Job__c);
            priceBookItemIds.add(o.Price_Book_Item__c);
        }
        if(itemsOfInterest.isEmpty()) return;
        
        //System.debug('itemsOfInterest size='+ itemsOfInterest.size());

        String extendedPricingCol = HasColumnEnableExtendedPricing? (', ' + EnableExtendedPricingColumnName): '';
        String soql = String.format('SELECT Id, {0}Price_Book__c {1} FROM {0}Job__c WHERE IsDeleted=false', 
            new String[]{StringUtility.FXNamespace(), extendedPricingCol });

        Map<Id, Job__c> jobMap = new Map<Id, Job__c>((List<Job__c>)Database.query(soql));      

        Map<Id, Id> parentPriceBookMap = new Map<Id, Id>();
        if(HasColumnEnableExtendedPricing)
        {
            for(Price_Book__c p : [SELECT Id, Parent_Price_Book__c FROM Price_Book__c WHERE IsDeleted=false AND Is_Active__c=true])
            {
                if(String.isBlank(p.Parent_Price_Book__c)) continue;
                parentPriceBookMap.put(p.Id, p.Parent_Price_Book__c);
            }
        }

        List<Price_Book_Item__c> pbItems = [SELECT Id, Catalog_Item__c, Price_Book__c, CatalogItemPriceBook__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Price_Book__r.Is_Active__c=true AND Id IN :priceBookItemIds];
        Set<Id> catalogItemIds = new Set<Id>();
        for(Price_Book_Item__c o : pbItems)
        {
            catalogItemIds.add(o.Catalog_Item__c);
        }
        Map<Id, Price_Book_Item__c> equipPlanningPriceBookItemMap = new Map<Id, Price_Book_Item__c>(pbItems);

        Map<String, Set<Id>> catalogItemPriceBookItemMap = new Map<String, Set<Id>>();
        for(Price_Book_Item__c o : [SELECT Id, Catalog_Item__c, Price_Book__c, CatalogItemPriceBook__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Price_Book__r.Is_Active__c=true  AND Catalog_Item__c IN : catalogItemIds])
        {
            if(!catalogItemPriceBookItemMap.containsKey(o.CatalogItemPriceBook__c))
            {
                catalogItemPriceBookItemMap.put(o.CatalogItemPriceBook__c, new Set<Id>());
            }
            catalogItemPriceBookItemMap.get(o.CatalogItemPriceBook__c).add(o.Id);

        }


        Map<Id, Price_Book_Item__c> pbiMap = new Map<Id, Price_Book_Item__c> ([SELECT Id, Catalog_Item__c, Price_Book__c, Price_Book__r.Parent_Price_Book__c FROM Price_Book_Item__c WHERE IsDeleted=false AND Id IN :priceBookItemIds]);

        for(Equipment_Planning__c o : itemsOfInterest)
        {
            
            Job__c job = jobMap.get(o.Job__c);
            if(job.Price_Book__c == pbiMap.get(o.Price_Book_Item__c).Price_Book__c) continue;

            Id jobId = o.Job__c;
           
            //System.debug('extendedPricing='+ extendedPricing);
            if(!HasColumnEnableExtendedPricing || !Boolean.valueOf(job.get(EnableExtendedPricingColumnName)))
            {
                o.addError('Price Book Item must be from the Job\'s Price Book.');             
            }
            else
            {                  
                Price_Book_Item__c pbi = equipPlanningPriceBookItemMap.get(o.Price_Book_Item__c);
                String key = pbi.CatalogItemPriceBook__c;
                Id priceBookId = jobMap.get(jobId).Price_Book__c;
                Boolean isGood = false;

                while(!String.isBlank(priceBookId))
                {
                    String catalogItemPriceBookIndex = String.valueOf(pbi.Catalog_Item__c) + String.valueOf(priceBookId);
                    if(catalogItemPriceBookItemMap.containsKey(catalogItemPriceBookIndex))                      
                    {
                        isGood = catalogItemPriceBookItemMap.get(catalogItemPriceBookIndex).contains(pbi.Id);
                        break;
                    }   
                    priceBookId = parentPriceBookMap.containsKey(priceBookId)? parentPriceBookMap.get(priceBookId) : null;
                }

                if(!isGood)
                {
                    o.addError('Price Book Item must be from the Job\'s Price Book or the nearest active upper level Price Book.');
                }               
            }
        }
        
    }
    
}