src/main/default/objects/Catalog_Item__c/Catalog_Item__c.object-meta.xml
<CustomObject>
    <description>A master catalog item</description>
    <label>Catalog Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>Contact_00Ni0000007nL5vEAE</fullName>
        <active>true</active>
        <field>Contact.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Contact_Job Title from Catalog</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii0000000wFirEAE_00Ni000000ApFj5EAF</fullName>
        <active>true</active>
        <field>Equipment__c.Catalog_Item__c</field>
        <filterItems>
            <field>Catalog_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Equipment_Catalog Item</name>
    </namedFilters>
    <pluralLabel>Catalog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Customer for the job.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs (Customer)</relationshipLabel>
    <relationshipName>JobsCustomer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Override__c/Override__c.object-meta.xml
<CustomObject>
    <label>Override</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Override__c/fields/Applies_to_SObject__c.field-meta.xml
<CustomField>
    <fullName>Applies_to_SObject__c</fullName>
    <label>Applies to SObject</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OverrideSObject</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Override__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Overrides</relationshipLabel>
    <relationshipName>Overrides</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Override__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>notEqual</operation>
            <value>Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Overrides</relationshipLabel>
    <relationshipName>Overrides</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Override_Config__c/Override_Config__c.object-meta.xml
<CustomObject>
    <label>Override Config</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Override Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Override_Config__c/fields/Applies_to_SObject__c.field-meta.xml
<CustomField>
    <fullName>Applies_to_SObject__c</fullName>
    <label>Applies to SObject</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OverrideSObject</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Override_Config__c/fields/Filter_Clause__c.field-meta.xml
<CustomField>
    <fullName>Filter_Clause__c</fullName>
    <label>Filter Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/Override_Config__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Override_Config__c/fields/Override_Fields__c.field-meta.xml
<CustomField>
    <fullName>Override_Fields__c</fullName>
    <label>Override Fields</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <inlineHelpText>Catalog item linked to the price book item. The price book item inherits information such as unit of measurement and cost from the linked catalog item.</inlineHelpText>
    <label>Catalog Item</label>
    <referenceTo>Catalog_Item__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Override_Price_Method__c.field-meta.xml
<CustomField>
    <fullName>Override_Price_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Override Price Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Override_Config__c.Override_Type__c</field>
            <operation>equals</operation>
            <value>Price</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Override_Config__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items_OverridePrice</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Price charged for the price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Catalog_Item__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Item__c</fullName>
    <formula>CASESAFEID(Price_Book_Item__r.Catalog_Item__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Catalog Item</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/CustomerAccount__c.field-meta.xml
<CustomField>
    <fullName>CustomerAccount__c</fullName>
    <formula>Ticket__r.Job__r.CustomerAccount__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Account</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Percentage discount granted on the ticket item. The ticket item inherits this discount from the linked price book item. Users can change the discount when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Discount Percent</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Override</label>
    <referenceTo>Override__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>Price charged for the ticket item. The ticket item inherits this price from the linked price book item. Users can change the price when adding a ticket if granted sufficient permissions.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/globalValueSets/OverrideSObject.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ticket</fullName>
    </customValue>
    <customValue>
        <fullName>Quote</fullName>
    </customValue>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <masterLabel>OverrideSObject</masterLabel>
</GlobalValueSet>

src/main/default/classes/OverrideHandler_Test.cls
@isTest
private class OverrideHandler_Test
{
    @testSetup
    static void Setup()
    {
        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        
        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, true).get(0);
                
        String ns = StringUtility.FXNamespace();
        Override_Config__c config = new Override_Config__c(
            Applies_to_SObject__c = 'Ticket',
            Override_Fields__c = ns + 'Price__c',
            Filter_Clause__c= ns + 'CustomerAccount__c=$CustomerAccount__c AND ' + ns + 'Catalog_Item__c=$Catalog_Item__c',
            Limit__c=1);        
        insert config;
        
        Id pbId = j.Price_Book__c;
        
        List<Override__c> overrides = new List<Override__c>();
        
        List<Price_Book_Item__c> pbItems = AlpineTestHelper.CreatePriceBookItems(10, pbId, 'Equipment', false);
        for(Price_Book_Item__c pbi: pbItems)
        {
            pbi.Override_Price_Method__c = config.Id;
            pbi.Discount_Percent__c = 0;
            
            overrides.add(new Override__c(Catalog_Item__c = pbi.Catalog_Item__c, 
                Price__c = pbi.Price__c * 2,
                Applies_to_SObject__c = 'Ticket',
                CustomerAccount__c = j.CustomerAccount__c));
                
        }
        insert pbItems;
        insert overrides;

    }    

     static testmethod void RunOnTicketUpdate()
    {        
        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c LIMIT 2])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;

        tktItems = [SELECT Id, Price__c, Price_Book_Item__r.Price__c, Override__c, Override__r.Price__c FROM Ticket_Item__c];
        for(Ticket_Item__c ti: tktItems)
        {
            System.assert(ti.Price__c == ti.Override__r.Price__c && ti.Price__c != ti.Price_Book_Item__r.Price__c, 
                'Price not overridden: ' + JSON.serializePretty(ti));
        }
        List<Override__c> overrides = [SELECT Id, Price__c FROM Override__c];
        for(Override__c o: overrides)
        {
            o.Price__c += 210;
        }
        update overrides;

        Test.startTest();
        update tkt;
        Test.stopTest();
        tktItems = [SELECT Id, Price__c, Price_Book_Item__r.Price__c, Override__c, Override__r.Price__c FROM Ticket_Item__c];
        for(Ticket_Item__c ti: tktItems)
        {
            System.assert(ti.Price__c == ti.Override__r.Price__c && ti.Price__c != ti.Price_Book_Item__r.Price__c, 
                'Price not overridden: ' + JSON.serializePretty(ti));
        }
    }

     static testmethod void RunOnJobUpdate()
    {        
        Job__c job = [SELECT Id  FROM Job__c LIMIT 1];

        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c LIMIT 2])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;

        tktItems = [SELECT Id, Price__c, Price_Book_Item__r.Price__c, Override__c, Override__r.Price__c FROM Ticket_Item__c];
        for(Ticket_Item__c ti: tktItems)
        {
            System.assert(ti.Price__c == ti.Override__r.Price__c && ti.Price__c != ti.Price_Book_Item__r.Price__c, 
                'Price not overridden: ' + JSON.serializePretty(ti));
        }
        List<Override__c> overrides = [SELECT Id, Price__c FROM Override__c];
        for(Override__c o: overrides)
        {
            o.Price__c += 210;
        }
        update overrides;

        Test.startTest();
        update job;
        Test.stopTest();
        tktItems = [SELECT Id, Price__c, Price_Book_Item__r.Price__c, Override__c, Override__r.Price__c FROM Ticket_Item__c];
        for(Ticket_Item__c ti: tktItems)
        {
            System.assert(ti.Price__c == ti.Override__r.Price__c && ti.Price__c != ti.Price_Book_Item__r.Price__c, 
                'Price not overridden: ' + JSON.serializePretty(ti));
        }
    }

    
    static testmethod void RunOnTicket_Batch()
    {        
        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;
        Test.startTest();
        Set<Id> ids = new Set<Id>();
        ids.add(tkt.Id);
        OverrideBatcher.RunBatch(OverrideBatcher.TicketItemCountSoql_Tickets, ids, tktItems.size()+1);
        Test.stopTest();
    }

    static testmethod void RunOnTicket_NoBatch()
    {
        
        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c LIMIT 2])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;
        Test.startTest();
        Set<Id> ids = new Set<Id>();
        ids.add(tkt.Id);
        OverrideBatcher.RunOnTickets(ids);
        Test.stopTest();
    }
    

    static testmethod void RunOnJob_Batch()
    {       
        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;
        Test.startTest();
        Set<Id> ids = new Set<Id>();
        ids.add(tkt.Job__c);
        OverrideBatcher.RunBatch(OverrideBatcher.TicketItemCountSoql_Jobs, ids, tktItems.size()+1);
        Test.stopTest();
    }

    static testmethod void RunOnJob_NoBatch()
    {
        
        Ticket__c tkt = [SELECT Id, Job__c FROM Ticket__c LIMIT 1];
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : [SELECT Id FROM Price_Book_Item__c LIMIT 2])
        {
            tktItems.add(new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id));
        }
        insert tktItems;
        Test.startTest();
        Set<Id> ids = new Set<Id>();
        ids.add(tkt.Job__c);
        OverrideBatcher.RunOnJobs(ids);
        Test.stopTest();
    }

    static testmethod void OverridePrice_Test()
    {
       
        Ticket__c tkt = [SELECT Id FROM Ticket__c LIMIT 1];
        Price_Book_Item__c pbi = [SELECT Id, Price__c, Catalog_Item__c FROM Price_Book_Item__c LIMIT 1];
        Override__c overrideObj = [SELECT Id, Price__c, Catalog_Item__c FROM Override__c WHERE Catalog_Item__c =:pbi.Catalog_Item__c LIMIT 1];
        Test.startTest();
        Ticket_Item__c ti = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id);
        insert ti;
        Test.stopTest();
        Ticket_Item__c dbItem = [SELECT Id, Price__c, Override__c FROM Ticket_Item__c WHERE Id=:ti.Id];
        
        System.assert(dbItem.Price__c == overrideObj.Price__c, 'Price should be ' + overrideObj.Price__c + ', instead of ' + dbItem.Price__c);
        System.assert(dbItem.Override__c == overrideObj.Id, 'Override Id should be ' + overrideObj.Id + ', instead of ' + dbItem.Override__c);
        
    }

    static testmethod void OverrideConfigValidation_Test()
    {
       
        Test.startTest();
        String ns = StringUtility.FXNamespace();
        Override_Config__c config = new Override_Config__c(
            Applies_to_SObject__c = 'Ticket',
            Override_Fields__c = ns + 'Price123__c',
            Filter_Clause__c= ns + 'CustomerAccount__c=$' + ns + 'CustomerAccount__c AND ' + ns + 'Catalog_Item__c=$' + ns + 'Catalog_Item__c',
            Limit__c=1);        
        try {
            insert config;
        }
        catch (Exception ex) {
            System.debug(ex.getMessage());
        }   
        Test.stopTest();    

    }

    static testmethod void OverrideConfigUpdate_Validation_Test()
    {
       
        Test.startTest();
        Override_Config__c config = [SELECT Id, Override_Fields__c, Filter_Clause__c FROM Override_Config__c LIMIT 1];
        try {
            String ns = StringUtility.FXNamespace();
            config.Filter_Clause__c = ns + 'FieldNotExisted__c=$' + ns + 'CustomerAccount__c';
            update config;
        }
        catch (Exception ex) {
            System.debug(ex.getMessage());
        }   
        Test.stopTest();    

    }
    
}