src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0}</displayFormat>
        <label>Quote Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Quote_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book item linked to the quote item. The quote item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Quote_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid.</description>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Parent_Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Parent ticket item for the ticket item. When a ticket item has a parent, the parent gets added automatically to every ticket where the ticket item is added.</inlineHelpText>
    <label>Parent Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/SyncID__c.field-meta.xml
<CustomField>
    <fullName>SyncID__c</fullName>
    <description>Trigger will populate this property when it is null. It should populate with a guid if possible.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier assigned automatically after syncing.</inlineHelpText>
    <label>SyncID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/CreateTicketItemsFromQuoteItems.cls
@RestResource(urlMapping='/CreateTicketItemsFromQuoteItems/*')
global with sharing class CreateTicketItemsFromQuoteItems
{       
    @HttpPost
    global static List<Ticket_Item__c> CreateTicketItems(Id tktId, List<Id> quoteItemIds, 
        Boolean honorSequenceNumber, Decimal nextSequenceNumber)
    {        
        return TicketItemHandler.CreateTicketItems(tktId, quoteItemIds, honorSequenceNumber? null : nextSequenceNumber);         
    }

    public static List<Ticket_Item__c> refreshTktItemsList(List<Ticket_Item__c> tktItems, String fieldsStr) {
        String ns = UtilityGetNamespace.CurrentNamespace();
        Set<Id> tktItemIds = new Map<Id, Ticket_Item__c>(tktItems).keySet();
        String tiSoql = String.format('SELECT {0} FROM {1} WHERE Id IN :tktItemIds', new String[]{fieldsStr, ns+'Ticket_Item__c'});
        return (List<Ticket_Item__c>)Database.query(tiSoql);
    }

    public static List<Ticket_Item__c> CreateTicketItemsUsingPriceBookItems(Id newTicketId, List<Id> quoteItemIds, Map<Id, Quote_Item__c> qiLookup, String parentSyncId) {
        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();

        for(Id quoteItemId: quoteItemIds) {
            Quote_Item__c qi = qiLookup.get(quoteItemId);
            String recName = Schema.SObjectType.Quote_Item__c.getRecordTypeInfosById().get(qi.RecordTypeId).getName();

            RecordTypeInfo recordInfo = Schema.SObjectType.Ticket_Item__c.getRecordTypeInfosByName().get(recName);
            if (recordInfo != null) {
                ID recId = recordInfo.getRecordTypeId();
                Ticket_Item__c tktItem  = (Ticket_Item__c)Ticket_Item__c.sObjectType.newSObject(recId, true);
                tktItem.Ticket__c = newTicketId;
                tktItem.Price_Book_Item__c = qi.Price_Book_Item__c;
                tktItem.SyncID__c = StringUtility.newGuid();

                if (!String.isBlank(parentSyncId)) {
                    tktItem.Parent_Ticket_Item__r = new Ticket_Item__c(SyncID__c = parentSyncId);
                }

                tktItems.add(tktItem);
            }
        }

        return tktItems;
    }

    global static Ticket_Item__c CreateTicketItem(Id newTicketId, Id quoteItemId, Boolean honorSequenceNumber, Decimal nextSequenceNumber, 
        List<SObjectField> tktItemFields, List<SObjectField> quoteItemFields)
    {
        return null;
    }    
}