src/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Invoice__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Invoice_Item__c/fields/Ticket_Item__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket Item</label>
    <referenceTo>Ticket_Item__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/main/default/objects/Job__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Price book used for the job.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Price_Book__c/Price_Book__c.object-meta.xml
<CustomObject>
    <description>Items from the catalog are priced zero or one time in zero or more price books.</description>
    <label>Price Book</label>
    <nameField>
        <label>Price Book Name</label>
        <type>Text</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01Ii00000005Z90EAE_00Ni0000001Yv2dEAC</fullName>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND (5 OR 6)</booleanFilter>
        <errorMessage>The Price Book does not match the Job information. Check the Account, Segment and Office on the Price Book.</errorMessage>
        <field>Job__c.Price_Book__c</field>
        <filterItems>
            <field>$Source.CustomerAccount__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Account__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Account__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Office__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Office__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Office__r.Id</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>$Source.Segment__c</field>
            <operation>equals</operation>
            <valueField>Price_Book__c.Segment__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book__c.Segment__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <infoMessage>When selecting a Price Book to use for this job, the system restricts your selections to only Price Books where the Price Book's office, segment and customer match those of this Job or where the respective price book's attribute is null.</infoMessage>
        <isOptional>false</isOptional>
        <name>Job_Price Book</name>
        <sourceObject>Job__c</sourceObject>
    </namedFilters>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book__c/fields/AddTktItemsByPBSeqNum__c.field-meta.xml
<CustomField>
    <fullName>AddTktItemsByPBSeqNum__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, price book items, when added to a ticket, should honor the sequence number.  Otherwise they will be inserted at the end of the ticket.</description>
    <inlineHelpText>Controls whether users can change sequence numbers for price book items to adjust the order of item lists. If selected, users cannot change sequence numbers. If deselected, users can change sequence numbers and new items get added at the end of a list.</inlineHelpText>
    <label>Honor Sequence Number</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/Price_Book_Item__c.object-meta.xml
<CustomObject>
    <label>Price Book Item</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <namedFilters>
        <fullName>nf_01IF0000002KqRcMAK_00NF000000D7FdUMAV</fullName>
        <active>true</active>
        <field>Price_Book_Rule__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Price_Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Rule_Price Book Item</name>
        <sourceObject>Price_Book_Rule__c</sourceObject>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000004oehEAA_00Ni0000000LddCEAS</fullName>
        <active>true</active>
        <field>Crew_Planning__c.Role_on_Job__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Ticket_Item_Record_Type__c</field>
            <operation>contains</operation>
            <value>Labor</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
        <name>Job Crew_Role on Job</name>
    </namedFilters>
    <namedFilters>
        <fullName>nf_01Ii00000005Z99EAE_00Ni0000001Ytl2EAC</fullName>
        <active>true</active>
        <field>Ticket_Item__c.Price_Book_Item__c</field>
        <filterItems>
            <field>Price_Book_Item__c.Price_Book_Catalog_Item_Unique__c</field>
            <operation>equals</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Price_Book_Catalog_Item_Unique__c</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Id</field>
            <operation>notEqual</operation>
            <valueField>Price_Book_Item__c.Parent_Price_Book_Item__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.Parent_Price_Book_Item__r.Requires_Parent_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Price_Book_Item__c.IsArchived__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
        <name>Ticket Item_Price Book Item</name>
    </namedFilters>
    <pluralLabel>Price Book Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Price_Book_Item__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <inlineHelpText>Price book in which the price book item is included.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Price_Book__c</referenceTo>
    <relationshipLabel>Price Book Items</relationshipLabel>
    <relationshipName>Price_Book_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Price_Book_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in price book item lists.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Ticket ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <inlineHelpText>Job for which the ticket was added.</inlineHelpText>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/Ticket_Item__c.object-meta.xml
<CustomObject>
    <label>Ticket Item</label>
    <nameField>
        <displayFormat>TI-{0}</displayFormat>
        <label>Ticket Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Ticket_Item__c/fields/Invoice_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Item</label>
    <referenceTo>Invoice_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Price_Book_Item__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The price book item on which this ticket item was created.</description>
    <inlineHelpText>Price book item linked to the ticket item. The ticket item inherits pricing information from the linked price book item.</inlineHelpText>
    <label>Price Book Item</label>
    <referenceTo>Price_Book_Item__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number used to determine the order in which the item displays in ticket item lists. The ticket item inherits this number from the linked price book item.</inlineHelpText>
    <label>Sequence Number</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <inlineHelpText>Ticket on which the ticket item was added.</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Ticket Items</relationshipLabel>
    <relationshipName>Ticket_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/Ticket_Item__c/recordTypes/Equipment.recordType-meta.xml
<RecordType>
    <fullName>Equipment</fullName>
    <active>true</active>
    <label>Equipment</label>
</RecordType>

src/main/default/objects/Ticket_Item__c/recordTypes/Labor.recordType-meta.xml
<RecordType>
    <fullName>Labor</fullName>
    <active>true</active>
    <label>Labor</label>
</RecordType>

src/main/default/classes/InvoiceItemHandler_Test.cls
@isTest
private class InvoiceItemHandler_Test
{

    @testSetup
    static void setup()
    {
        Job__c j = AlpineTestHelper.CreateJobs(1, true).get(0);
        Ticket__c tkt = AlpineTestHelper.CreateTickets(j, 1, true).get(0);

        Price_Book__c pb = [SELECT Id, AddTktItemsByPBSeqNum__c FROM Price_Book__c WHERE Id=:j.Price_Book__c ];
        pb.AddTktItemsByPBSeqNum__c = false;
        update pb;

        List<Price_Book_Item__c> pbiEquip = AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Equipment', true);
        List<Price_Book_Item__c> pbiLabor = AlpineTestHelper.CreatePriceBookItems(5, j.Price_Book__c, 'Labor', true);

        List<Ticket_Item__c> tktItems = new List<Ticket_Item__c>();
        for(Price_Book_Item__c pbi : pbiEquip)
        {
            Ticket_Item__c ti  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id);
            tktItems.add(ti);
        }
        for(Price_Book_Item__c pbi : pbiLabor)
        {
            Ticket_Item__c ti  = new Ticket_Item__c(Ticket__c = tkt.Id, Price_Book_Item__c = pbi.Id);
            tktItems.add(ti);
        }
        insert tktItems;

        List<Invoice__c> invs = AlpineTestHelper.CreateInvoices(1, true, j.Price_Book__c);
    }

    static testmethod void GetAvailableTicketsForInvoiceTest() {
        Test.startTest();

        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        InvoiceItemHandler.GetAvailableTicketsForInvoiceRequest data = new InvoiceItemHandler.GetAvailableTicketsForInvoiceRequest();
        data.invoiceId = inv.Id;
        data.showItemsAlreadyOnTheInvoice = 'false';
        data.itemLimit = '400';
        data.itemOffset = '0';
        data.sortby = 'Name';
        data.sortdir = 'DESC';
        data.tktFields = 'Id';
        data.tktItemFields = 'Id';

        InvoiceItemHandler.GetAvailableTicketsForInvoiceResult res = InvoiceItemHandler.GetAvailableTicketsForInvoice(data);
        System.debug(res);

        System.assert(res.availableTickets.size() > 0, 'should have some availableTickets');

        Test.stopTest();
    }

    static testmethod void createInvItemsWithTicketItem_Test()
    {
        Test.startTest();
        List<Ticket_Item__c> sources  = [SELECT Id FROM Ticket_Item__c];

        System.assert(sources!=null && sources.size() == 10, 'should have 10 Ticket_Book_Item__c items');
        List<Id> sourceIds = new List<Id>(new Map<Id, Ticket_Item__c>(sources).keySet());

        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];

        Decimal nextSeqNumber = 200;
        List<Invoice_Item__c> invItems = InvoiceItemHandler.CreateInvoiceItems(inv.Id, sourceIds, nextSeqNumber, null);

        Test.stopTest();

        Integer count = invItems!=null? invItems.size() : 0;

        System.assert(count == sources.size(), 'should have 10 items, instead having ' + count);

        //check sequence numbers
        Map<Id, Decimal> expectedResults = new Map<Id, Decimal>();
        for(Integer i=0; i<sourceIds.size(); i++)
        {
            expectedResults.put(sourceIds.get(i), nextSeqNumber + i);
        }
        for(Invoice_Item__c invi: invItems)
        {
            System.assert(invi.Sequence_Number__c == expectedResults.get(invi.Ticket_Item__c), 'Sequence_Number__c should be sequential starting with the provided nextSeqNumber');
        }
    }

    static testmethod void createInvoiceItemWithPBItem_Test()
    {
      Test.startTest();
      List<Price_book_Item__c> sources  = [SELECT Id FROM Price_book_Item__c];

      System.assert(sources!=null && sources.size() == 10, 'should have 10 Price_book_Item__c items');
      List<Id> sourceIds = new List<Id>(new Map<Id, Price_book_Item__c>(sources).keySet());

      Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];

      Decimal nextSeqNumber = 200;

      List<Invoice_Item__c> invItems = InvoiceItemHandler.CreateInvoiceItems(inv.Id, sourceIds, nextSeqNumber, null);

      Test.stopTest();

      Integer count = invItems!=null? invItems.size() : 0;

      System.assert(count == sources.size(), 'should have 10 items, instead having ' + count);

      //check sequence numbers
      Map<Id, Decimal> expectedResults = new Map<Id, Decimal>();
      for(Integer i=0; i<sourceIds.size(); i++)
      {
          expectedResults.put(sourceIds.get(i), nextSeqNumber + i);
      }
      for(Invoice_Item__c invi: invItems)
      {
          System.assert(invi.Sequence_Number__c == expectedResults.get(invi.Price_book_Item__c), 'Sequence_Number__c should be sequential starting with the provided nextSeqNumber');
      }
    }

    static testmethod void invoiceItemsFetch_Test()
    {
      Test.startTest();

      Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];

      String invItemId = null;
      String invId = inv.Id;
      string invFields = 'Name,Id';
      string invItemFields = 'Name,Id';
      InvoiceItemHandler.InvItemsFilterResponse filter = new InvoiceItemHandler.InvItemsFilterResponse();
      filter.keyword = '';
      filter.itemType = '';
      filter.classification = '';
      filter.itemLimit = '';
      filter.itemOffset = '';
      filter.sortby = '';
      filter.sortdir = '';

      InvoiceItemHandler.InvoiceItemsFetchResult res = InvoiceItemHandler.InvoiceItemsFetch(invItemId, invId, invFields, invItemFields, filter);

      Test.stopTest();
    }


}